import { text, type TemplateFile } from "../utils"
import cardWorldArchitectAgentConfig from "../../../../../../cards/沉浸阅读器.tsian-card/workspace/agents/world-architect/agent.json?raw"
import cardWorldArchitectAgentInstructions from "../../../../../../cards/沉浸阅读器.tsian-card/workspace/agents/world-architect/AGENT.md?raw"
import cardOpeningSkill from "../../../../../../cards/沉浸阅读器.tsian-card/workspace/agents/world-architect/skills/开局建模/SKILL.md?raw"
import cardOpeningCommon from "../../../../../../cards/沉浸阅读器.tsian-card/workspace/agents/world-architect/skills/开局建模/scripts/_common.js?raw"
import cardOpeningValidation from "../../../../../../cards/沉浸阅读器.tsian-card/workspace/agents/world-architect/skills/开局建模/scripts/_validation.js?raw"
import cardOpeningProgress from "../../../../../../cards/沉浸阅读器.tsian-card/workspace/agents/world-architect/skills/开局建模/scripts/_progress.js?raw"
import cardOpeningReadProgress from "../../../../../../cards/沉浸阅读器.tsian-card/workspace/agents/world-architect/skills/开局建模/scripts/read-opening-progress.js?raw"
import cardOpeningAdvanceProgress from "../../../../../../cards/沉浸阅读器.tsian-card/workspace/agents/world-architect/skills/开局建模/scripts/advance-opening-progress.js?raw"
import cardOpeningInspectSource from "../../../../../../cards/沉浸阅读器.tsian-card/workspace/agents/world-architect/skills/开局建模/scripts/inspect-source-opening.js?raw"
import cardOpeningReadSlice from "../../../../../../cards/沉浸阅读器.tsian-card/workspace/agents/world-architect/skills/开局建模/scripts/read-opening-slice.js?raw"
import cardOpeningCommit from "../../../../../../cards/沉浸阅读器.tsian-card/workspace/agents/world-architect/skills/开局建模/scripts/commit-opening.js?raw"
import {
  COMMIT_PLAY_SETUP_SCRIPT_JS,
  OPENING_COMMON_JS,
  OPENING_VALIDATION_JS,
} from "../scripts/opening"
import {
  COMMIT_FRONTIER_MATERIALS_SCRIPT_JS,
  COMMIT_FRONTIER_STATE_SCRIPT_JS,
  READ_FRONTIER_WINDOW_SCRIPT_JS,
} from "../scripts/frontier"

const PLAY_SETUP_SKILL_MD = text([
  "---",
  "name: 游玩设定",
  "title: 游玩设定",
  "description: 引导玩家补充本局特别设定（特殊体质、天赋、系统等），确认后落盘并生成开局正文。",
  "triggers:",
  "  - 玩家完成角色设定后进入游玩设定对话",
  "appliesTo:",
  "  - world-architect",
  "---",
  "",
  "# 游玩设定",
  "",
  "本 Skill 引导玩家补充本局特别设定，确认后落盘并生成开局正文。",
  "",
  "## 访谈",
  "",
  "逐轮提问，每次最多 1～2 个问题。每个问题附带默认前端识别的 `[[选项]]` 模板，允许自由输入。",
  "",
  "### 问题 1：特别设定",
  "",
  "> 这局你想给主角加点什么特别设定吗？可以直接选一个模板，也可以自己说。没有的话我们直接开始。",
  "",
  "[[选项]]",
  "- 不加特殊设定，直接开始",
  "- 给主角一个特殊体质/天赋（如天生剑骨、明镜心、不灭血脉）",
  "- 给主角一个系统/外挂（如签到系统、模拟器、面板提示）",
  "- 改变主角处境（如多一个隐藏身份、被宗门误会、其实是某位大能转世）",
  "- 我自己描述",
  "[[/选项]]",
  "",
  "### 问题 2：能力详情（仅当玩家选了特殊体质/天赋/系统）",
  "",
  "> 好。请说说它是什么、能做什么。可以选快捷模板，也可以自己填。",
  "",
  "快捷模板：",
  "[[选项]]",
  "- 偏修炼：提升某方面修炼速度/亲和/悟性",
  "- 偏战斗：更强感知、爆发、恢复或防御",
  "- 偏探索：看破幻象、发现隐藏线索、感知危险",
  "- 偏系统：签到/任务/模拟/提示/面板",
  "[[/选项]]",
  "",
  "如果玩家选了快捷模板，追问名称和具体效果描述。",
  "",
  "### 问题 3：处境详情（仅当玩家选了改变处境）",
  "",
  "> 你想怎么改变主角的处境？",
  "",
  "[[选项]]",
  "- 开局多一个隐藏身份",
  "- 被宗门/势力误会或针对",
  "- 其实是某位大能转世",
  "- 与原著某角色有额外关系",
  "[[/选项]]",
  "",
  "### 收尾确认",
  "",
  "信息收集齐后：",
  "",
  "> 设定已收集齐。你还有想补充或修改的吗？",
  "",
  "[[选项]]",
  "- 还有补充",
  "- 想修改前面的设定",
  "- 直接开始",
  "[[/选项]]",
  "",
  "## 开局钩子",
  "",
  "不由玩家决定切入点。根据玩家设定和已读开局素材安排：",
  "- 原著角色：默认沿用原著开局。",
  "- 原创角色：根据角色设定合理嵌入世界。",
  "- 特殊能力（traits）可影响开局呈现。",
  "",
  "## 落盘",
  "",
  "玩家选择「直接开始」后：",
  "",
  "1. 整理给 storyteller 的上下文：主角信息、traits、已读开局素材边界、本局设定摘要。",
  "2. `agent_call` storyteller，在 request 中补一句“生成开局正文前请先按 Skill《文风学习》结合已读开局素材学习一次原著相近场景文风”，`expectedOutput` 要求返回【开局正文】+【初始选项】3～5 个。",
  "3. storyteller 返回后，调 `commit_play_setup` 一次写入：",
  "   - 主角 entity 的 `traits[]`（每项 `{ id, name, description?, effects? }`，`id` 用 `trait:<localId>` 格式）",
  "   - `setup-summary.json`（小说简介式 summary）",
  "   - `save/history/turns/turn-000000.json`（开局 assistant 回复，包含正文与内嵌 `[[选项]]`）",
  "   - `save/agents/<playerTurnAgent>/context.json`（玩家正式回合入口 Agent 的 turn 0 上下文种子）",
  "4. 最终回复玩家：「开局已准备好，进入故事即可开始。」",
  "5. 不在回复中展示开局正文全文。",
  "",
  "## 可用 action",
  "",
  "```json tsian-actions",
  "[",
  "  {",
  "    \"name\": \"commit_play_setup\",",
  "    \"description\": \"Step 4 收尾单一 action：校验 protagonistRef 指向已存在 character entity、summary 非空（≤2000）、openingReply 非空、traits[] 每项 id（trait:<localId>）+ name 必填，read-modify-write 主角 entity 合并 traits（按 id 去重覆盖），并一次写入 setup-summary.json、turn 0 history 与玩家回合入口 Agent context。返回 {status, writes}，不含 openingReply 正文（避免 Step 4 UI 提前展示）。\",",
  "    \"inputSchema\": { \"type\": \"object\", \"required\": [\"protagonistRef\", \"summary\", \"openingReply\"], \"properties\": { \"protagonistRef\": { \"type\": \"string\" }, \"traits\": { \"type\": \"array\", \"items\": { \"type\": \"object\", \"required\": [\"id\", \"name\"], \"properties\": { \"id\": { \"type\": \"string\" }, \"name\": { \"type\": \"string\" }, \"description\": { \"type\": \"string\" }, \"effects\": { \"type\": \"array\", \"items\": { \"type\": \"string\" } } } } }, \"summary\": { \"type\": \"string\" }, \"openingReply\": { \"type\": \"string\", \"description\": \"开局 assistant 回复整体，包含开局正文与可选的内嵌 [[选项]] 块。\" } } },",
  "    \"outputSchema\": { \"type\": \"object\" },",
  "    \"executor\": { \"type\": \"browser_script\", \"path\": \"scripts/commit-play-setup.js\", \"timeoutMs\": 10000, \"helpers\": [\"_common.js\", \"_validation.js\"] }",
  "  }",
  "]",
  "```",
  "",
  "## spoiler-safe",
  "",
  "只使用开局窗口中读到的内容。不推断、不剧透未来剧情。",
])

const WORLD_ARCHITECT_FRONTIER_ADVANCE_SKILL_MD = text([
  "---",
  "name: frontier推进",
  "title: frontier推进",
  "description: 推进 source frontier，读取下一段源章节窗口，识别剧情节点建立 source 锚点，抽取最小素材增量。",
  "triggers:",
  "  - 前端基于 plotOrder 客观计算触发 frontier 推进时",
  "appliesTo:",
  "  - world-architect",
  "---",
  "",
  "# frontier推进",
  "",
  "被前端触发时推进 source frontier：读下一段源章节窗口，识别剧情节点建立 source 锚点，抽取最小素材增量。推进只扩展素材边界，不产生剧情方向指导。",
  "",
  "## 推进流程",
  "",
  "1. `read_frontier_window` → 读当前 frontier.json 的 sourceWindow，计算下一段最多 15 章窗口，通过 source reader 读取对应章节，返回章节文本 + frontier 状态。",
  "2. 识别剧情节点 + 抽取最小素材增量。",
  "3. `commit_frontier_materials` → 校验并写入 entities/relationships/schema patches 增量。",
  "4. `commit_frontier_state` → 校验 order 递增、sourceWindow 顺序推进、timeline 锚点 chapter 在窗口内，写入 frontier.json（合并新 source 锚点到 timeline 数组）。",
  "",
  "素材增量提交成功后才推进 frontier 状态。若素材提交失败，不推进 sourceWindow/extractedThrough/timeline。无可抽取素材时也需通过空 materials 提交明确完成后再推进 frontier。",
  "",
  "## 抽取什么",
  "",
  "- 新登场角色（entity）：identity/appearance/attributes（按境界参照 schema guide 示例刻度尺填写），不抽 sourceRefs/origin。",
  "- 角色关系（relationship）：仅 character↔character，不抽地点/组织/物品关联。",
  "- schema 增量：仅在发现需要新字段/结构时写 pending patch。",
  "",
  "## 不抽取什么",
  "",
  "- 不抽场景（scene 由 stage-manager 维护）。",
  "- 不抽 player 锚点（stage-manager 维护）。",
  "- 不抽剧情摘要/阶段目标/创作指导。",
  "- 不全量提取窗口内所有内容——只抽\"与当前阶段可能相关的最小增量\"。",
  "",
  "## source 锚点建立规范",
  "",
  "- 识别剧情节点（不是每章都建，只在有显著事件变化的节点建）。",
  "- 原文有明确时间词 → 直接用。",
  "- 原文无时间词 → 从剧情推断估计时间（如\"赶路翻三座山\"→ 估\"数周后\"→ 按当前时间线推算）。不允许因\"读不到时间词\"而跳过锚点建立——time 可为估计值，order 照常递增。",
  "- label 一句话客观标签，不是剧情摘要。",
  "- order 赋值：严格大于现有最后一个 source 锚点的 order，连续递增。",
  "- 锚点的 chapter 必须落在你提交的 sourceWindow 范围内（脚本会校验）。",
  "",
"## 窗口与节点",
"",
"- 单次推进最多读 15 章（硬上限，防止大节点一次吞太多章节）。",
"- 语义目标：覆盖至少 1-2 个剧情节点后即可提交 sourceWindow.end，不必读到上限。",
"- 上限内读不到 2 个完整节点时，提交到上限章节，就已有显著变化点建锚点，剩余节点延续到下次推进。",
"- sourceWindow.end 由你语义决定，可小于实际读到的最后一章。",
"- 只对不超出 sourceWindow.end 的章节建 source 锚点和抽取实体；超出 end 的章节仅供判断\"是否还有下一个剧情节点\"，不从中抽实体、不建锚点（spoiler-safe）。",
"- 窗口还受总字符数兜底（约 12 万字），长章节小说实际读到的章数可能少于 15——以 read_frontier_window 返回的 window.end 为准。",
"- 过去章节不倒回搜索。窗口外不读。",
  "",
  "## 可用脚本（tsian-actions）",
  "",
  "用 `run_script` 执行下列 browser_script action；脚本校验输入并写入对应落点，失败时返回 code/message 供你修正重试。",
  "",
  "```json tsian-actions",
  "[",
  "  {",
  "    \"name\": \"read_frontier_window\",",
  "    \"description\": \"读 frontier.json 当前 sourceWindow，计算下一段最多 15 章窗口，通过 source reader 读取对应章节文本，返回章节文本与 frontier 状态。只读不写。\",",
  "    \"inputSchema\": { \"type\": \"object\", \"properties\": {} },",
  "    \"outputSchema\": { \"type\": \"object\" },",
  "    \"executor\": { \"type\": \"browser_script\", \"path\": \"scripts/read-frontier-window.js\", \"timeoutMs\": 15000, \"helpers\": [\"_common.js\"] }",
  "  },",
  "  {",
  "    \"name\": \"commit_frontier_materials\",",
  "    \"description\": \"校验 entities/relationships/schemaPatches 增量并写入 save/entities/、save/relationships/、save/schema/patches/pending/。校验 entity ref 格式、relationship subject/to 为 character:<localId>。\",",
  "    \"inputSchema\": { \"type\": \"object\", \"properties\": { \"entities\": { \"type\": \"array\" }, \"relationships\": { \"type\": \"array\" }, \"schemaPatches\": { \"type\": \"array\" } } },",
  "    \"outputSchema\": { \"type\": \"object\" },",
  "    \"executor\": { \"type\": \"browser_script\", \"path\": \"scripts/commit-frontier-materials.js\", \"timeoutMs\": 15000, \"helpers\": [\"_common.js\", \"_validation.js\"] }",
  "  },",
  "  {",
  "    \"name\": \"commit_frontier_state\",",
  "    \"description\": \"校验 order 严格大于现有最后 source 锚点 order、sourceWindow 顺序推进、timeline 锚点 chapter 在新窗口内，写入 frontier.json（合并新 source 锚点到 timeline 数组）。\",",
  "    \"inputSchema\": { \"type\": \"object\", \"required\": [\"sourceWindow\", \"timelineAnchors\"], \"properties\": { \"sourceWindow\": { \"type\": \"object\" }, \"extractedThrough\": { \"type\": \"string\" }, \"timelineAnchors\": { \"type\": \"array\" } } },",
  "    \"outputSchema\": { \"type\": \"object\" },",
  "    \"executor\": { \"type\": \"browser_script\", \"path\": \"scripts/commit-frontier-state.js\", \"timeoutMs\": 10000, \"helpers\": [\"_common.js\", \"_validation.js\"] }",
  "  }",
  "]",
  "```",
  "",
  "## 重试策略",
  "",
  "脚本返回校验错误时按 code/message 修正后重试，不放弃。",
  "",
  "## spoiler-safe",
  "",
  "只使用窗口中读到的内容。不推断、不剧透窗口外的未来剧情。",
])

export const WORLD_ARCHITECT_AGENT_FILES: TemplateFile[] = [
  {
    path: "agents/world-architect/agent.json",
    content: cardWorldArchitectAgentConfig,
  },
  {
    path: "agents/world-architect/AGENT.md",
    content: cardWorldArchitectAgentInstructions,
  },
  {
    path: "agents/world-architect/SOUL.md",
    content: text(["# 世界架构师灵魂", "", "你像一位负责小说改编项目的世界观架构师：先理解故事真正需要什么，再决定如何落成资料。", "你不追求万能本体论；你偏好小而稳定、可读、可演进的结构。", "你尊重已读内容的边界：只把读到的落成资料，不推断未读的未来。", "你忠实于原作：读到的设定照实落成资料，不替原文净化或删减——成人、暴力、暗黑和温柔一样是该记的设定。", "脚本返回错误时你不放弃——你把它当成建模对话，按错误修正后重试。"]),
  },
]

export const WORLD_ARCHITECT_SKILL_FILES: TemplateFile[] = [
  { path: "agents/world-architect/skills/开局建模/SKILL.md", content: cardOpeningSkill },
  { path: "agents/world-architect/skills/开局建模/scripts/_common.js", content: cardOpeningCommon },
  { path: "agents/world-architect/skills/开局建模/scripts/_validation.js", content: cardOpeningValidation },
  { path: "agents/world-architect/skills/开局建模/scripts/_progress.js", content: cardOpeningProgress },
  { path: "agents/world-architect/skills/开局建模/scripts/read-opening-progress.js", content: cardOpeningReadProgress },
  { path: "agents/world-architect/skills/开局建模/scripts/advance-opening-progress.js", content: cardOpeningAdvanceProgress },
  { path: "agents/world-architect/skills/开局建模/scripts/inspect-source-opening.js", content: cardOpeningInspectSource },
  { path: "agents/world-architect/skills/开局建模/scripts/read-opening-slice.js", content: cardOpeningReadSlice },
  { path: "agents/world-architect/skills/开局建模/scripts/commit-opening.js", content: cardOpeningCommit },
  { path: "agents/world-architect/skills/游玩设定/SKILL.md", content: PLAY_SETUP_SKILL_MD },
  { path: "agents/world-architect/skills/游玩设定/scripts/_common.js", content: OPENING_COMMON_JS },
  { path: "agents/world-architect/skills/游玩设定/scripts/_validation.js", content: OPENING_VALIDATION_JS },
  { path: "agents/world-architect/skills/游玩设定/scripts/commit-play-setup.js", content: COMMIT_PLAY_SETUP_SCRIPT_JS },
  { path: "agents/world-architect/skills/frontier推进/SKILL.md", content: WORLD_ARCHITECT_FRONTIER_ADVANCE_SKILL_MD },
  { path: "agents/world-architect/skills/frontier推进/scripts/_common.js", content: OPENING_COMMON_JS },
  { path: "agents/world-architect/skills/frontier推进/scripts/_validation.js", content: OPENING_VALIDATION_JS },
  { path: "agents/world-architect/skills/frontier推进/scripts/read-frontier-window.js", content: READ_FRONTIER_WINDOW_SCRIPT_JS },
  { path: "agents/world-architect/skills/frontier推进/scripts/commit-frontier-materials.js", content: COMMIT_FRONTIER_MATERIALS_SCRIPT_JS },
  { path: "agents/world-architect/skills/frontier推进/scripts/commit-frontier-state.js", content: COMMIT_FRONTIER_STATE_SCRIPT_JS },
]
