import { agentConfigContent, text, type TemplateFile } from "../utils"
import {
  COMMIT_ENTITIES_SCRIPT_JS,
  COMMIT_PLAY_SETUP_SCRIPT_JS,
  COMMIT_RUNTIME_AND_FRONTIER_SCRIPT_JS,
  COMMIT_SCENES_AND_RELATIONSHIPS_SCRIPT_JS,
  COMMIT_UNDERSTANDING_SUMMARY_SCRIPT_JS,
  INSPECT_SOURCE_OPENING_SCRIPT_JS,
  OPENING_COMMON_JS,
  OPENING_VALIDATION_JS,
  READ_OPENING_SLICE_SCRIPT_JS,
} from "../scripts/opening"
import {
  COMMIT_FRONTIER_MATERIALS_SCRIPT_JS,
  COMMIT_FRONTIER_STATE_SCRIPT_JS,
  READ_FRONTIER_WINDOW_SCRIPT_JS,
} from "../scripts/frontier"

const PLAY_SETUP_SKILL_MD = text([
  "---",
  "name: 游玩设定",
  "title: 游玩设定",
  "description: 引导玩家补充本局特别设定（特殊体质、天赋、系统等），确认后落盘并生成开局正文。",
  "triggers:",
  "  - 玩家完成角色设定后进入游玩设定对话",
  "appliesTo:",
  "  - world-architect",
  "---",
  "",
  "# 游玩设定",
  "",
  "本 Skill 引导玩家补充本局特别设定，确认后落盘并生成开局正文。",
  "",
  "## 访谈",
  "",
  "逐轮提问，每次最多 1～2 个问题。每个问题附带默认前端识别的 `[[选项]]` 模板，允许自由输入。",
  "",
  "### 问题 1：特别设定",
  "",
  "> 这局你想给主角加点什么特别设定吗？可以直接选一个模板，也可以自己说。没有的话我们直接开始。",
  "",
  "[[选项]]",
  "- 不加特殊设定，直接开始",
  "- 给主角一个特殊体质/天赋（如天生剑骨、明镜心、不灭血脉）",
  "- 给主角一个系统/外挂（如签到系统、模拟器、面板提示）",
  "- 改变主角处境（如多一个隐藏身份、被宗门误会、其实是某位大能转世）",
  "- 我自己描述",
  "[[/选项]]",
  "",
  "### 问题 2：能力详情（仅当玩家选了特殊体质/天赋/系统）",
  "",
  "> 好。请说说它是什么、能做什么。可以选快捷模板，也可以自己填。",
  "",
  "快捷模板：",
  "[[选项]]",
  "- 偏修炼：提升某方面修炼速度/亲和/悟性",
  "- 偏战斗：更强感知、爆发、恢复或防御",
  "- 偏探索：看破幻象、发现隐藏线索、感知危险",
  "- 偏系统：签到/任务/模拟/提示/面板",
  "[[/选项]]",
  "",
  "如果玩家选了快捷模板，追问名称和具体效果描述。",
  "",
  "### 问题 3：处境详情（仅当玩家选了改变处境）",
  "",
  "> 你想怎么改变主角的处境？",
  "",
  "[[选项]]",
  "- 开局多一个隐藏身份",
  "- 被宗门/势力误会或针对",
  "- 其实是某位大能转世",
  "- 与原著某角色有额外关系",
  "[[/选项]]",
  "",
  "### 收尾确认",
  "",
  "信息收集齐后：",
  "",
  "> 设定已收集齐。你还有想补充或修改的吗？",
  "",
  "[[选项]]",
  "- 还有补充",
  "- 想修改前面的设定",
  "- 直接开始",
  "[[/选项]]",
  "",
  "## 开局钩子",
  "",
  "不由玩家决定切入点。根据玩家设定和已读开局素材安排：",
  "- 原著角色：默认沿用原著开局。",
  "- 原创角色：根据角色设定合理嵌入世界。",
  "- 特殊能力（traits）可影响开局呈现。",
  "",
  "## 落盘",
  "",
  "玩家选择「直接开始」后：",
  "",
  "1. 整理给 storyteller 的上下文：主角信息、traits、已读开局素材边界、本局设定摘要。",
  "2. `agent_call` storyteller，在 request 中补一句“生成开局正文前请先按 Skill《文风学习》学习一次原著相近场景文风；原著正文由资料员按 `save/playthrough/frontier.json` 的 `sourceWindow.chapters[*].path`（`save/source/chapters/...`）检索提供”，`expectedOutput` 要求返回【开局正文】+【初始选项】3～5 个。",
  "3. storyteller 返回后，调 `commit_play_setup` 一次写入：",
  "   - 主角 entity 的 `traits[]`（每项 `{ id, name, description?, effects? }`，`id` 用 `trait:<localId>` 格式）",
  "   - `setup-summary.json`（小说简介式 summary）",
  "   - `save/history/turns/turn-000000.json`（开局 assistant 回复，包含正文与内嵌 `[[选项]]`）",
  "   - `save/agents/<playerTurnAgent>/context.json`（玩家正式回合入口 Agent 的 turn 0 上下文种子）",
  "4. 最终回复玩家：「开局已准备好，进入故事即可开始。」",
  "5. 不在回复中展示开局正文全文。",
  "",
  "## 可用 action",
  "",
  "```json tsian-actions",
  "[",
  "  {",
  "    \"name\": \"commit_play_setup\",",
  "    \"description\": \"Step 4 收尾单一 action：校验 protagonistRef 指向已存在 character entity、summary 非空（≤2000）、openingReply 非空、traits[] 每项 id（trait:<localId>）+ name 必填，read-modify-write 主角 entity 合并 traits（按 id 去重覆盖），并一次写入 setup-summary.json、turn 0 history 与玩家回合入口 Agent context。返回 {status, writes}，不含 openingReply 正文（避免 Step 4 UI 提前展示）。\",",
  "    \"inputSchema\": { \"type\": \"object\", \"required\": [\"protagonistRef\", \"summary\", \"openingReply\"], \"properties\": { \"protagonistRef\": { \"type\": \"string\" }, \"traits\": { \"type\": \"array\", \"items\": { \"type\": \"object\", \"required\": [\"id\", \"name\"], \"properties\": { \"id\": { \"type\": \"string\" }, \"name\": { \"type\": \"string\" }, \"description\": { \"type\": \"string\" }, \"effects\": { \"type\": \"array\", \"items\": { \"type\": \"string\" } } } } }, \"summary\": { \"type\": \"string\" }, \"openingReply\": { \"type\": \"string\", \"description\": \"开局 assistant 回复整体，包含开局正文与可选的内嵌 [[选项]] 块。\" } } },",
  "    \"outputSchema\": { \"type\": \"object\" },",
  "    \"executor\": { \"type\": \"browser_script\", \"path\": \"scripts/commit-play-setup.js\", \"timeoutMs\": 10000, \"helpers\": [\"_common.js\", \"_validation.js\"] }",
  "  }",
  "]",
  "```",
  "",
  "## spoiler-safe",
  "",
  "只使用开局窗口中读到的内容。不推断、不剧透未来剧情。",
])

const WORLD_ARCHITECT_OPENING_SKILL_MD = text([
  "---",
  "name: 开局建模",
  "title: 开局建模",
  "description: 为刚导入的小说建立开局世界资料（实体、场景、关系、runtime、frontier、understanding-summary）。",
  "triggers:",
  "  - 小说导入后建立开局世界资料",
  "appliesTo:",
  "  - world-architect",
  "---",
  "",
  "# 开局建模",
  "",
  "目标是建立后续常态流程能读到的正式路径。所有开局产物通过脚本校验写入——脚本返回错误时按错误修正后重试。",
  "",
  "## 可用脚本（tsian-actions）",
  "",
  "用 `run_script` 执行下列 browser_script action；脚本校验输入并写入对应落点，失败时返回 code/message 供你修正重试。",
  "",
  "```json tsian-actions",
  "[",
  "  {",
  "    \"name\": \"inspect_source_opening\",",
  "    \"description\": \"观察导入源 manifest 与开头章节预览，选择开局阅读窗口。\",",
  "    \"inputSchema\": { \"type\": \"object\", \"properties\": { \"previewCount\": { \"type\": \"number\" }, \"previewCharacters\": { \"type\": \"number\" } } },",
  "    \"outputSchema\": { \"type\": \"object\" },",
  "    \"executor\": { \"type\": \"browser_script\", \"path\": \"scripts/inspect-source-opening.js\", \"timeoutMs\": 10000, \"helpers\": [\"_common.js\"] }",
  "  },",
  "  {",
  "    \"name\": \"read_opening_slice\",",
  "    \"description\": \"连续读开头章节正文，返回拼接文本与窗口元信息。可多次调用。\",",
  "    \"inputSchema\": { \"type\": \"object\", \"properties\": { \"startIndex\": { \"type\": \"number\" }, \"endIndex\": { \"type\": \"number\" }, \"maxCharacters\": { \"type\": \"number\" } } },",
  "    \"outputSchema\": { \"type\": \"object\" },",
  "    \"executor\": { \"type\": \"browser_script\", \"path\": \"scripts/read-opening-slice.js\", \"timeoutMs\": 10000, \"helpers\": [\"_common.js\"] }",
  "  },",
  "  {",
  "    \"name\": \"commit_entities\",",
  "    \"description\": \"校验实体 id/必填字段并写入 save/entities/<type>/<localId>.json。先于 scenes/relationships/runtime 提交。\",",
  "    \"inputSchema\": {",
  "      \"type\": \"object\",",
  "      \"required\": [\"entities\"],",
  "      \"properties\": {",
  "        \"entities\": {",
  "          \"type\": \"array\",",
  "          \"items\": {",
  "            \"type\": \"object\",",
  "            \"required\": [\"id\", \"name\", \"brief\"],",
  "            \"properties\": {",
  "              \"id\": { \"type\": \"string\" },",
  "              \"name\": { \"type\": \"string\" },",
  "              \"brief\": { \"type\": \"string\" },",
  "              \"type\": { \"type\": \"string\" },",
  "              \"gender\": { \"type\": \"string\" },",
  "              \"tags\": { \"type\": \"array\" },",
  "              \"aliases\": { \"type\": \"array\" },",
  "              \"identity\": { \"type\": \"string\" },",
  "              \"appearance\": { \"type\": \"string\" },",
  "              \"attributes\": { \"type\": \"object\" }",
  "            }",
  "          }",
  "        }",
  "      }",
  "    },",
  "    \"outputSchema\": { \"type\": \"object\" },",
  "    \"executor\": { \"type\": \"browser_script\", \"path\": \"scripts/commit-entities.js\", \"timeoutMs\": 10000, \"helpers\": [\"_common.js\", \"_validation.js\"] }",
  "  },",
  "  {",
  "    \"name\": \"commit_scenes_and_relationships\",",
  "    \"description\": \"校验场景与人物关系 ref；场景写入 save/scenes/<localId>.json，人物关系写入 save/relationships/<scope>.json（subject/to 均必须是 character:<localId>）。共享一次 entity id 加载。\",",
  "    \"inputSchema\": {",
  "      \"type\": \"object\",",
  "      \"required\": [\"scenes\", \"relationships\"],",
  "      \"properties\": {",
  "        \"scenes\": {",
  "          \"type\": \"array\",",
  "          \"items\": {",
  "            \"type\": \"object\",",
  "            \"required\": [\"id\", \"name\", \"location\", \"present\"],",
  "            \"properties\": {",
  "              \"id\": { \"type\": \"string\" },",
  "              \"name\": { \"type\": \"string\" },",
  "              \"location\": { \"type\": \"object\", \"required\": [\"ref\", \"name\"], \"properties\": { \"ref\": { \"type\": \"string\" }, \"name\": { \"type\": \"string\" } } },",
  "              \"present\": { \"type\": \"array\", \"items\": { \"type\": \"object\", \"required\": [\"ref\"], \"properties\": { \"ref\": { \"type\": \"string\" } } } }",
  "            }",
  "          }",
  "        },",
  "        \"relationships\": {",
  "          \"type\": \"array\",",
  "          \"items\": {",
  "            \"type\": \"object\",",
  "            \"required\": [\"subject\", \"edges\"],",
  "            \"properties\": {",
  "              \"subject\": { \"type\": \"string\" },",
  "              \"edges\": {",
  "                \"type\": \"array\",",
  "                \"items\": {",
  "                  \"type\": \"object\",",
  "                  \"required\": [\"to\", \"type\"],",
  "                  \"properties\": {",
  "                    \"to\": { \"type\": \"string\" },",
  "                    \"type\": { \"type\": \"string\" },",
  "                    \"since\": { \"type\": \"number\" },",
  "                    \"until\": { \"type\": \"number\" },",
  "                    \"note\": { \"type\": \"string\" }",
  "                  }",
  "                }",
  "              }",
  "            }",
  "          }",
  "        }",
  "      }",
  "    },",
  "    \"outputSchema\": { \"type\": \"object\" },",
  "    \"executor\": { \"type\": \"browser_script\", \"path\": \"scripts/commit-scenes-and-relationships.js\", \"timeoutMs\": 10000, \"helpers\": [\"_common.js\", \"_validation.js\"] }",
  "  },",
  "  {",
  "    \"name\": \"commit_runtime_and_frontier\",",
  "    \"description\": \"校验 runtime.activeSceneRefs 指向已写 scene、protagonistRef/location 指向已写 entity，接受 runtime.worldTime/weather 字符串（缺省为空），校验 frontier.sourceWindow 章节路径存在与 frontier.timeline 锚点格式，一次写入 runtime.json 与 frontier.json。\",",
  "    \"inputSchema\": {",
  "      \"type\": \"object\",",
  "      \"required\": [\"runtime\", \"frontier\"],",
  "      \"properties\": {",
  "        \"runtime\": {",
  "          \"type\": \"object\",",
  "          \"required\": [\"activeSceneRefs\"],",
  "          \"properties\": {",
  "            \"turn\": { \"type\": \"number\" },",
  "            \"worldTime\": { \"type\": \"string\" },",
  "            \"weather\": { \"type\": \"string\" },",
  "            \"activeSceneRefs\": {",
  "              \"type\": \"array\",",
  "              \"items\": {",
  "                \"type\": \"object\",",
  "                \"required\": [\"ref\", \"name\"],",
  "                \"properties\": { \"ref\": { \"type\": \"string\" }, \"name\": { \"type\": \"string\" } }",
  "              }",
  "            },",
  "            \"protagonistRef\": { \"type\": \"object\", \"required\": [\"ref\", \"name\"], \"properties\": { \"ref\": { \"type\": \"string\" }, \"name\": { \"type\": \"string\" } } },",
  "            \"location\": { \"type\": \"object\", \"required\": [\"ref\", \"name\"], \"properties\": { \"ref\": { \"type\": \"string\" }, \"name\": { \"type\": \"string\" } } },",
  "            \"extensions\": { \"type\": \"object\" }",
  "          }",
  "        },",
  "        \"frontier\": {",
  "          \"type\": \"object\",",
  "          \"required\": [\"sourceWindow\", \"timeline\"],",
  "          \"properties\": {",
  "            \"sourceWindow\": {",
  "              \"type\": \"object\",",
  "              \"required\": [\"startIndex\", \"endIndex\", \"reason\", \"chapters\"],",
  "              \"properties\": {",
  "                \"startIndex\": { \"type\": \"number\" },",
  "                \"endIndex\": { \"type\": \"number\" },",
  "                \"reason\": { \"type\": \"string\" },",
  "                \"chapters\": {",
  "                  \"type\": \"array\",",
  "                  \"items\": {",
  "                    \"type\": \"object\",",
  "                    \"required\": [\"index\", \"title\", \"path\"],",
  "                    \"properties\": { \"index\": { \"type\": \"number\" }, \"title\": { \"type\": \"string\" }, \"path\": { \"type\": \"string\" } }",
  "                  }",
  "                }",
  "              }",
  "            },",
  "            \"timeline\": {",
  "              \"type\": \"array\",",
  "              \"items\": {",
  "                \"type\": \"object\",",
  "                \"required\": [\"chapter\", \"time\", \"label\"],",
  "                \"properties\": { \"chapter\": { \"type\": \"number\" }, \"time\": { \"type\": \"string\" }, \"label\": { \"type\": \"string\" } }",
  "              }",
  "            },",
  "            \"extractedThrough\": { \"type\": \"string\" },",
  "            \"notes\": { \"type\": \"string\" }",
  "          }",
  "        }",
  "      }",
  "    },",
  "    \"outputSchema\": { \"type\": \"object\" },",
  "    \"executor\": { \"type\": \"browser_script\", \"path\": \"scripts/commit-runtime-and-frontier.js\", \"timeoutMs\": 10000, \"helpers\": [\"_common.js\", \"_validation.js\"] }",
  "  },",
  "  {",
  "    \"name\": \"commit_understanding_summary\",",
  "    \"description\": \"校验 title 与 candidateCharacters 并写入 save/playthrough/understanding-summary.json 为 {status, title, candidateCharacters}。\",",
  "    \"inputSchema\": {",
  "      \"type\": \"object\",",
  "      \"required\": [\"title\", \"candidateCharacters\"],",
  "      \"properties\": {",
  "        \"title\": { \"type\": \"string\" },",
  "        \"candidateCharacters\": {",
  "          \"type\": \"array\",",
  "          \"items\": {",
  "            \"type\": \"object\",",
  "            \"required\": [\"id\", \"name\", \"brief\"],",
  "            \"properties\": {",
  "              \"id\": { \"type\": \"string\" },",
  "              \"name\": { \"type\": \"string\" },",
  "              \"brief\": { \"type\": \"string\" },",
  "              \"gender\": { \"type\": \"string\" }",
  "            }",
  "          }",
  "        }",
  "      }",
  "    },",
  "    \"outputSchema\": { \"type\": \"object\" },",
  "    \"executor\": { \"type\": \"browser_script\", \"path\": \"scripts/commit-understanding-summary.js\", \"timeoutMs\": 10000, \"helpers\": [\"_common.js\", \"_validation.js\"] }",
  "  }",
  "]",
  "```",
  "",
  "## 执行步骤",
  "",
  "1. `inspect_source_opening` → 观察导入源结构和章节预览。",
  "2. `read_opening_slice` → 连续阅读开头剧情（可多次调用）。读够的判据：主要角色登场、冲突建立、开局场景可定。",
  "3. `commit_entities` → 写入实体（先写，后续 ref 依赖）。每实体至少 `id` / `name` / `brief`，按需加 `gender` / `tags` / `aliases` / `identity` / `appearance` / `attributes`。character 的 `attributes` 按境界参照 schema guide 的示例刻度尺填写；没有剧情佐证时也要估算，不要全填基线或留空。",
  "  示例：",
  "  ```json",
  "  {\"entities\":[{\"id\":\"character:飞星\",\"name\":\"飞星\",\"brief\":\"乘星而落的失忆少年，体内潜伏醉仙情花\",\"gender\":\"男\"},{\"id\":\"location:逍遥海岸\",\"name\":\"逍遥海岸\",\"brief\":\"大陆南方之海\"}]}",
  "  ```",
  "4. `commit_scenes_and_relationships` → 写入场景与人物关系（校验 present/location ref 指向已写实体；relationship subject/to 均必须是 `character:<localId>`；双向角色关系两边各写一条；非角色关联不要写入 relationships）。",
  "  示例：",
  "  ```json",
  "  {\"scenes\":[{\"id\":\"scene:逍遥海岸飞星落\",\"name\":\"逍遥海岸飞星落\",\"location\":{\"ref\":\"location:逍遥海岸\",\"name\":\"逍遥海岸\"},\"present\":[{\"ref\":\"character:飞星\"},{\"ref\":\"character:恶欲邪魔\"}]}],\"relationships\":[{\"subject\":\"character:飞星\",\"edges\":[{\"to\":\"character:玉霜\",\"type\":\"师徒\",\"note\":\"玉霜收飞星上岛\"}]}]}",
  "  ```",
  "5. `commit_runtime_and_frontier` → 写入 runtime（校验 activeSceneRefs 指向已写 scene、protagonistRef/location 指向已写 entity；`worldTime` 传 `\"元年\"`，`weather` 写当前天气字符串，未知则留空）与 frontier（`sourceWindow` 传 `{ startIndex, endIndex, reason, chapters }`：`startIndex`/`endIndex`/`chapters` 复用 `read_opening_slice` 返回的窗口字段，`reason` 写一句话说明为何选此窗口；`timeline` 传第一个锚点 `[{ kind: \"source\", order: 1, chapter: <开局起始章>, time: \"元年\", label: \"开局\" }]`，`chapter` 用 `sourceWindow.startIndex` 的值。脚本会自动按数组顺序赋 `order`（从 1 递增），`kind` 固定为 `\"source\"`）。",
  "  示例：",
  "  ```json",
  "  {\"runtime\":{\"worldTime\":\"元年\",\"weather\":\"雪\",\"activeSceneRefs\":[{\"ref\":\"scene:逍遥海岸飞星落\",\"name\":\"逍遥海岸飞星落\"}],\"protagonistRef\":{\"ref\":\"character:飞星\",\"name\":\"飞星\"},\"location\":{\"ref\":\"location:玉霜独居之岛\",\"name\":\"玉霜独居之岛\"}},\"frontier\":{\"sourceWindow\":{\"startIndex\":1,\"endIndex\":4,\"reason\":\"前四章建立主角登场、师徒关系与情花冲突\",\"chapters\":[{\"index\":1,\"title\":\"第一章 逍遥海岸飞星落\",\"path\":\"save/source/chapters/chapter-0001.md\"}]},\"timeline\":[{\"chapter\":1,\"time\":\"元年\",\"label\":\"开局\"}]}}",
  "  ```",
  "6. `commit_understanding_summary` → 写入理解摘要。`candidateCharacters` 从已写 character 类型 entity 提取 `{id, name, brief, gender?}`；无合适原著角色时给空数组。",
  "  示例：",
  "  ```json",
  "  {\"title\":\"情花孽1-297\",\"candidateCharacters\":[{\"id\":\"character:飞星\",\"name\":\"飞星\",\"brief\":\"乘星而落的失忆少年，体内潜伏醉仙情花\",\"gender\":\"男\"}]}",
  "  ```",
  "",
  "无依赖的 commit 脚本可在一轮内同时调用。例如 `commit_understanding_summary` 与 `commit_runtime_and_frontier` 互不依赖，可并行发出工具调用，框架串行执行后一并返回。并行返回混合结果时，只重发失败的那一个，不要全量重发。",
  "",
  "## 产物落点（直接 workspace_write，不走脚本）",
  "",
  "- `save/schema/current.md` 与 `save/schema/changelog.md`：当前 schema 草案与变更理由。",
  "",
  "## 重试策略",
  "",
  "脚本返回校验错误时按 code/message 修正后重试，不放弃。常见错误：",
  "",
  "- `OPENING_SOURCE_REF_UNKNOWN` — 窗口章节 path 指向不存在章节 → 检查 path 是否来自 `read_opening_slice` 结果。",
  "- `OPENING_WINDOW_REASON_REQUIRED` — `frontier.sourceWindow.reason` 缺失 → 补一句话窗口选择理由。",
  "- `OPENING_ENTITY_ID_INVALID` — id 格式错 → 改成 `<type>:<localId>`。",
  "- `OPENING_ENTITY_TYPE_INVALID` — `container` 实体需 `type=\"container\"`；`item` 实体 `type` 需为 equipment/material/consumable/special/other 之一 → 补/改正 `type` 字段。",
  "- `OPENING_CANDIDATE_TYPE_INVALID` — 理解摘要候选角色 id 必须用 `character:<localId>` → 改成 character 类型。",
  "- `OPENING_REF_UNKNOWN` / `OPENING_RELATIONSHIP_SUBJECT_UNKNOWN` / `OPENING_RELATIONSHIP_TO_UNKNOWN` / `OPENING_RUNTIME_SCENE_UNKNOWN` / `OPENING_RUNTIME_PROTAGONIST_UNKNOWN` / `OPENING_RUNTIME_LOCATION_UNKNOWN` — ref 指向不存在的实体/场景 → 确认目标已在之前 commit 中写入或已存在。",
  "- `OPENING_RELATIONSHIP_SUBJECT_TYPE_INVALID` / `OPENING_RELATIONSHIP_TO_TYPE_INVALID` — relationships 只记录角色/人物关系，subject/to 必须是 `character:<localId>`；地点、组织、物品、事件、尸体/线索等非角色关联放到对应字段、已有 ref 结构或 `extensions.render=\"ref\"`，不要写入 relationships。",
  "- `OPENING_SCENE_PRESENT_REQUIRED` — 场景 present 不能为空。",
  "- `OPENING_TIMELINE_ANCHOR_INVALID` / `OPENING_TIMELINE_TIME_REQUIRED` / `OPENING_TIMELINE_LABEL_REQUIRED` — frontier.timeline 锚点格式错 → 每项需为 `{ chapter: number, time: string, label: string }`（脚本自动补 `kind: \"source\"` 和 `order`），`chapter` 用 `sourceWindow.start`。",
  "- 缺必填 → 补齐。",
  "",
  "## spoiler-safe",
  "",
  "只使用开头窗口中读到的内容。不推断、不剧透未来剧情。实体都只反映开局已知事实。",
])

// ── world-architect ongoing frontier 推进 Skill ──
// 被前端触发时读下一段源章节窗口，识别剧情节点建 source 锚点，抽最小素材增量。
const WORLD_ARCHITECT_FRONTIER_ADVANCE_SKILL_MD = text([
  "---",
  "name: frontier推进",
  "title: frontier推进",
  "description: 推进 source frontier，读取下一段源章节窗口，识别剧情节点建立 source 锚点，抽取最小素材增量。",
  "triggers:",
  "  - 前端基于 plotOrder 客观计算触发 frontier 推进时",
  "appliesTo:",
  "  - world-architect",
  "---",
  "",
  "# frontier推进",
  "",
  "被前端触发时推进 source frontier：读下一段源章节窗口，识别剧情节点建立 source 锚点，抽取最小素材增量。推进只扩展素材边界，不产生剧情方向指导。",
  "",
  "## 推进流程",
  "",
  "1. `read_frontier_window` → 读当前 frontier.json 的 sourceWindow，计算下一段最多 15 章窗口，读 `save/source/chapters/` 下对应章节，返回章节文本 + frontier 状态。",
  "2. 识别剧情节点 + 抽取最小素材增量。",
  "3. `commit_frontier_materials` → 校验并写入 entities/relationships/schema patches 增量。",
  "4. `commit_frontier_state` → 校验 order 递增、sourceWindow 顺序推进、timeline 锚点 chapter 在窗口内，写入 frontier.json（合并新 source 锚点到 timeline 数组）。",
  "",
  "素材增量提交成功后才推进 frontier 状态。若素材提交失败，不推进 sourceWindow/extractedThrough/timeline。无可抽取素材时也需通过空 materials 提交明确完成后再推进 frontier。",
  "",
  "## 抽取什么",
  "",
  "- 新登场角色（entity）：identity/appearance/attributes（按境界参照 schema guide 示例刻度尺填写），不抽 sourceRefs/origin。",
  "- 角色关系（relationship）：仅 character↔character，不抽地点/组织/物品关联。",
  "- schema 增量：仅在发现需要新字段/结构时写 pending patch。",
  "",
  "## 不抽取什么",
  "",
  "- 不抽场景（scene 由 stage-manager 维护）。",
  "- 不抽 player 锚点（stage-manager 维护）。",
  "- 不抽剧情摘要/阶段目标/创作指导。",
  "- 不全量提取窗口内所有内容——只抽\"与当前阶段可能相关的最小增量\"。",
  "",
  "## source 锚点建立规范",
  "",
  "- 识别剧情节点（不是每章都建，只在有显著事件变化的节点建）。",
  "- 原文有明确时间词 → 直接用。",
  "- 原文无时间词 → 从剧情推断估计时间（如\"赶路翻三座山\"→ 估\"数周后\"→ 按当前时间线推算）。不允许因\"读不到时间词\"而跳过锚点建立——time 可为估计值，order 照常递增。",
  "- label 一句话客观标签，不是剧情摘要。",
  "- order 赋值：严格大于现有最后一个 source 锚点的 order，连续递增。",
  "- 锚点的 chapter 必须落在你提交的 sourceWindow 范围内（脚本会校验）。",
  "",
"## 窗口与节点",
"",
"- 单次推进最多读 15 章（硬上限，防止大节点一次吞太多章节）。",
"- 语义目标：覆盖至少 1-2 个剧情节点后即可提交 sourceWindow.end，不必读到上限。",
"- 上限内读不到 2 个完整节点时，提交到上限章节，就已有显著变化点建锚点，剩余节点延续到下次推进。",
"- sourceWindow.end 由你语义决定，可小于实际读到的最后一章。",
"- 只对不超出 sourceWindow.end 的章节建 source 锚点和抽取实体；超出 end 的章节仅供判断\"是否还有下一个剧情节点\"，不从中抽实体、不建锚点（spoiler-safe）。",
"- 窗口还受总字符数兜底（约 12 万字），长章节小说实际读到的章数可能少于 15——以 read_frontier_window 返回的 window.end 为准。",
"- 过去章节不倒回搜索。窗口外不读。",
  "",
  "## 可用脚本（tsian-actions）",
  "",
  "用 `run_script` 执行下列 browser_script action；脚本校验输入并写入对应落点，失败时返回 code/message 供你修正重试。",
  "",
  "```json tsian-actions",
  "[",
  "  {",
  "    \"name\": \"read_frontier_window\",",
  "    \"description\": \"读 frontier.json 当前 sourceWindow，计算下一段最多 15 章窗口，读 save/source/chapters/ 下对应章节文本，返回章节文本与 frontier 状态。只读不写。\",",
  "    \"inputSchema\": { \"type\": \"object\", \"properties\": {} },",
  "    \"outputSchema\": { \"type\": \"object\" },",
  "    \"executor\": { \"type\": \"browser_script\", \"path\": \"scripts/read-frontier-window.js\", \"timeoutMs\": 15000, \"helpers\": [\"_common.js\"] }",
  "  },",
  "  {",
  "    \"name\": \"commit_frontier_materials\",",
  "    \"description\": \"校验 entities/relationships/schemaPatches 增量并写入 save/entities/、save/relationships/、save/schema/patches/pending/。校验 entity ref 格式、relationship subject/to 为 character:<localId>。\",",
  "    \"inputSchema\": { \"type\": \"object\", \"properties\": { \"entities\": { \"type\": \"array\" }, \"relationships\": { \"type\": \"array\" }, \"schemaPatches\": { \"type\": \"array\" } } },",
  "    \"outputSchema\": { \"type\": \"object\" },",
  "    \"executor\": { \"type\": \"browser_script\", \"path\": \"scripts/commit-frontier-materials.js\", \"timeoutMs\": 15000, \"helpers\": [\"_common.js\", \"_validation.js\"] }",
  "  },",
  "  {",
  "    \"name\": \"commit_frontier_state\",",
  "    \"description\": \"校验 order 严格大于现有最后 source 锚点 order、sourceWindow 顺序推进、timeline 锚点 chapter 在新窗口内，写入 frontier.json（合并新 source 锚点到 timeline 数组）。\",",
  "    \"inputSchema\": { \"type\": \"object\", \"required\": [\"sourceWindow\", \"timelineAnchors\"], \"properties\": { \"sourceWindow\": { \"type\": \"object\" }, \"extractedThrough\": { \"type\": \"string\" }, \"timelineAnchors\": { \"type\": \"array\" } } },",
  "    \"outputSchema\": { \"type\": \"object\" },",
  "    \"executor\": { \"type\": \"browser_script\", \"path\": \"scripts/commit-frontier-state.js\", \"timeoutMs\": 10000, \"helpers\": [\"_common.js\", \"_validation.js\"] }",
  "  }",
  "]",
  "```",
  "",
  "## 重试策略",
  "",
  "脚本返回校验错误时按 code/message 修正后重试，不放弃。",
  "",
  "## spoiler-safe",
  "",
  "只使用窗口中读到的内容。不推断、不剧透窗口外的未来剧情。",
])

export const WORLD_ARCHITECT_AGENT_FILES: TemplateFile[] = [
  {
    path: "agents/world-architect/agent.json",
    content: agentConfigContent({
      id: "world-architect",
      title: "世界架构师",
      summary: "开局建模、schema/world model 设计与 pending patch；不维护每回合 runtime。",
      contacts: ["researcher", "stage-manager", "storyteller"],
      contextPaths: [
        { path: "docs/novel-airp-schema-guide.md", role: "user", position: "prelude" },
        { path: "save/source/README.md", role: "user", position: "prelude" },
        { path: "save/source/manifest.json", role: "user", position: "prelude" },
        { path: "save/schema/current.md", role: "user", position: "prelude" },
        { path: "save/schema/changelog.md", role: "user", position: "prelude" },
        { path: "save/playthrough/frontier.json", role: "user", position: "runtime" },
        { path: "save/scenes/README.md", role: "user", position: "prelude" },
        { path: "save/relationships/README.md", role: "user", position: "prelude" },
      ],
      skills: { enabled: ["agents/world-architect/skills/开局建模/SKILL.md", "agents/world-architect/skills/游玩设定/SKILL.md", "agents/world-architect/skills/frontier推进/SKILL.md"], disabled: [] },
      tools: { enabled: [], disabled: ["roll_dice"] },
      platformTools: { enabled: ["workspace_read", "workspace_write", "workspace_semantic_search", "agent_call"], disabled: [] },
      workspaceAccess: { level: 1 },
    }),
  },
  {
    path: "agents/world-architect/AGENT.md",
    content: text([
      "# 世界架构师",
      "",
      "你负责为当前小说和本次游玩设计世界资料结构：schema、实体、场景、关系、runtime 指针。",
      "",
      "常驻原则：",
      "",
      "- 你不直接面对玩家；你的输出会作为结果返回给调用方，由调用方决定如何使用。",
      "- 从最小可用模型开始，只在当前游玩确实需要时增加字段或结构。relationships 只建模角色/人物关系；非角色关联不要塞入关系分片。",
      "- 安全小改可直接维护；有风险或需要决策的变更写 pending patch。",
      "- 需要源文本或实体事实时 call 资料员。",
      "- 不维护每回合 runtime，不写玩家正文。",
      "- 脚本返回错误时按错误修正后重试，不放弃。",
      "- 忠实落成读到的设定，不替原文净化：原作的成人、暴力、暗黑内容照实写进 entity/relationship/schema，不因审查跳过或删减。",
      "- 只使用已读到的内容，不推断未读的未来剧情。",
      "",
      "## ongoing frontier 推进",
      "",
      "- 被前端触发时读下一段源章节，建 source 锚点，抽最小素材增量。",
      "- 推进流程：read_frontier_window → 识别剧情节点 + 抽取素材 → commit_frontier_materials → commit_frontier_state。",
      "- 不写 runtime，不写 player 锚点，不写 scene。",
    ]),
  },
  {
    path: "agents/world-architect/SOUL.md",
    content: text(["# 世界架构师灵魂", "", "你像一位负责小说改编项目的世界观架构师：先理解故事真正需要什么，再决定如何落成资料。", "你不追求万能本体论；你偏好小而稳定、可读、可演进的结构。", "你尊重已读内容的边界：只把读到的落成资料，不推断未读的未来。", "你忠实于原作：读到的设定照实落成资料，不替原文净化或删减——成人、暴力、暗黑和温柔一样是该记的设定。", "脚本返回错误时你不放弃——你把它当成建模对话，按错误修正后重试。"]),
  },
]

export const WORLD_ARCHITECT_SKILL_FILES: TemplateFile[] = [
  { path: "agents/world-architect/skills/开局建模/SKILL.md", content: WORLD_ARCHITECT_OPENING_SKILL_MD },
  { path: "agents/world-architect/skills/开局建模/scripts/_common.js", content: OPENING_COMMON_JS },
  { path: "agents/world-architect/skills/开局建模/scripts/_validation.js", content: OPENING_VALIDATION_JS },
  { path: "agents/world-architect/skills/开局建模/scripts/inspect-source-opening.js", content: INSPECT_SOURCE_OPENING_SCRIPT_JS },
  { path: "agents/world-architect/skills/开局建模/scripts/read-opening-slice.js", content: READ_OPENING_SLICE_SCRIPT_JS },
  { path: "agents/world-architect/skills/开局建模/scripts/commit-entities.js", content: COMMIT_ENTITIES_SCRIPT_JS },
  { path: "agents/world-architect/skills/开局建模/scripts/commit-scenes-and-relationships.js", content: COMMIT_SCENES_AND_RELATIONSHIPS_SCRIPT_JS },
  { path: "agents/world-architect/skills/开局建模/scripts/commit-runtime-and-frontier.js", content: COMMIT_RUNTIME_AND_FRONTIER_SCRIPT_JS },
  { path: "agents/world-architect/skills/开局建模/scripts/commit-understanding-summary.js", content: COMMIT_UNDERSTANDING_SUMMARY_SCRIPT_JS },
  { path: "agents/world-architect/skills/游玩设定/SKILL.md", content: PLAY_SETUP_SKILL_MD },
  { path: "agents/world-architect/skills/游玩设定/scripts/_common.js", content: OPENING_COMMON_JS },
  { path: "agents/world-architect/skills/游玩设定/scripts/_validation.js", content: OPENING_VALIDATION_JS },
  { path: "agents/world-architect/skills/游玩设定/scripts/commit-play-setup.js", content: COMMIT_PLAY_SETUP_SCRIPT_JS },
  { path: "agents/world-architect/skills/frontier推进/SKILL.md", content: WORLD_ARCHITECT_FRONTIER_ADVANCE_SKILL_MD },
  { path: "agents/world-architect/skills/frontier推进/scripts/_common.js", content: OPENING_COMMON_JS },
  { path: "agents/world-architect/skills/frontier推进/scripts/_validation.js", content: OPENING_VALIDATION_JS },
  { path: "agents/world-architect/skills/frontier推进/scripts/read-frontier-window.js", content: READ_FRONTIER_WINDOW_SCRIPT_JS },
  { path: "agents/world-architect/skills/frontier推进/scripts/commit-frontier-materials.js", content: COMMIT_FRONTIER_MATERIALS_SCRIPT_JS },
  { path: "agents/world-architect/skills/frontier推进/scripts/commit-frontier-state.js", content: COMMIT_FRONTIER_STATE_SCRIPT_JS },
]
