import { json, text, type TemplateFile } from "../utils"

export const ROLL_DICE_FILES: TemplateFile[] = [
  // ---- Reference Tool: roll_dice ----
  // Task 07-05 seeded a single reference Tool at the shared `tools/` scope so
  // authors have a working `tool.json` + browser_script example. Task 07-07
  // extended it: count===1 大成功/大失败 + modifier 接受纯数字算术表达式
  // (白名单 + Function 严格模式求值). tsian.config is empty for Tools by design.
  //
  // Belongs in DEFAULT_WORKSPACE_FILES (card-content scope): `tools/**` is
  // reusable card content, not save-runtime data.
  {
    path: "tools/README.md",
    content: text([
      "# Tools",
      "",
      "本目录存放自定义 Tool。每个 Tool 是一个独立目录，含 `tool.json` 声明和一份 `browser_script` 实现（默认 `run.js`）。",
      "",
      "Tool 与 Skill 的区别：",
      "",
      "- Tool 是**能力**（LLM 原生函数调用直接可见），一次调用 = 一次输入 → 一次输出，无需 `use_skill` 激活。",
      "- Skill 是**知识 + 一组 action**，需要 `use_skill` 先激活，再 `run_script` 触发脚本。",
      "",
      "作用域：",
      "",
      "- `tools/<id>/` 共享 Tool，所有 Agent 可见（除非 `agent.json.tools.disabled` 屏蔽）。",
      "- `agents/<agent>/tools/<id>/` Agent 私有 Tool，只对该 Agent 可见；同名可覆盖共享 Tool。",
      "- `.tsian/local/<agent>/tools/<id>/` 机器私有 Tool，不入 checkpoint，不随卡包分发；可显式上传为独立 Tool 资源包。",
      "",
      "`tool.json` 必填字段：`name`（小写下划线，长度 ≤ 64）、`description`、`parameters`（JSON Schema）、`executor.type=\"browser_script\"`、`executor.path`。可选：`timeoutMs`、`helpers`、`outputSchema`。",
      "",
      "Tool 脚本内可用 `tsian.workspace.*`（受 Agent 的 workspaceAccess 约束）、`tsian.log`、`tsian.trace`、`tsian.lib.random.nextInt/dice`。**不提供** `tsian.config`（永远是 `{}`）、`tsian.lib.math`。平台不内置表达式求值器；个别 Tool（如 `roll_dice`）可在脚本内自实现受限求值。",
      "",
      "衍生数值（伤害、消耗、总分）一般由前端在状态变更点算好写回 workspace，LLM 直接读终值。需要 Tool 内精确算术时（如掷骰 modifier 差值），由 Tool 脚本自行实现受限求值，不依赖平台内置数学库。",
    ]),
  },
  {
    path: "tools/roll_dice/tool.json",
    content: json({
      name: "roll_dice",
      title: "掷骰",
      description: "掷骰用于不确定性建模，支持单方 DC 检定与双方对抗；`dc` 与 `opposed` 互斥。`count === 1` 时自然 1 为大失败（`criticalFailure`）、自然最大值为大成功（`criticalSuccess`），优先于常规 `success`/`winner` 判定；`count > 1` 时不判定大成功/大失败。`modifier` 可传数值或纯数字算术表达式字符串（支持 + - * / ^ 和 sqrt()），例如 \"15-12\" 表示双方属性差值；求值失败返回错误。可选 `advantage`/`disadvantage` 在 count === 1 时生效。",
      parameters: {
        type: "object",
        additionalProperties: false,
        properties: {
          sides: { type: "integer", minimum: 2, description: "骰面数，例如 20 表示 d20。" },
          count: { type: "integer", minimum: 1, default: 1, description: "投掷次数，默认 1。" },
          modifier: { type: ["number", "string"], default: 0, description: "加在总和上的数值调整。可传数字或纯数字算术表达式字符串（支持 + - * / ^ 和 sqrt()），例如 \"15-12\" 表示双方属性差值。不接受变量名、实体路径或除 sqrt 外的函数名。" },
          dc: { type: "number", description: "单方成功阈值（Difficulty Class）。给出时结果里会带 success 布尔；不可与 opposed 同时使用。" },
          advantage: { type: "boolean", default: false, description: "优势：仅在 count === 1 时生效，滚两次取高。" },
          disadvantage: { type: "boolean", default: false, description: "劣势：仅在 count === 1 时生效，滚两次取低。" },
          opposed: {
            type: "object",
            additionalProperties: false,
            description: "对抗方的一次掷骰；用于双方对抗，不可与 dc 同时使用。未提供 sides/count 时继承顶层值，modifier 默认 0。",
            properties: {
              sides: { type: "integer", minimum: 2, description: "对抗方骰面数；默认继承顶层 sides。" },
              count: { type: "integer", minimum: 1, description: "对抗方投掷次数；默认继承顶层 count。" },
              modifier: { type: ["number", "string"], default: 0, description: "对抗方加在总和上的数值调整。可传数字或纯数字算术表达式字符串（支持 + - * / ^ 和 sqrt()）。" },
              advantage: { type: "boolean", default: false, description: "对抗方优势：仅在 count === 1 时生效，滚两次取高。" },
              disadvantage: { type: "boolean", default: false, description: "对抗方劣势：仅在 count === 1 时生效，滚两次取低。" },
            },
          },
          reason: { type: "string", maxLength: 200, description: "触发掷骰的叙事原因（供日志阅读，不影响结果）。" },
        },
        required: ["sides"],
      },
      executor: {
        type: "browser_script",
        path: "run.js",
        timeoutMs: 3000,
      },
    }),
  },
  {
    path: "tools/roll_dice/run.js",
    content: text([
      "// roll_dice：参考 Tool 实现。使用 tsian.lib.random.dice 做骰，返回结构化结果。",
      "// modifier 可传数值或纯数字算术表达式字符串（支持 + - * / ^ 和 sqrt()）。",
      "// 表达式经白名单校验 + Function 构造器严格模式求值，不接受变量名/实体路径/eval。",
      "// count === 1 时判定大成功（自然最大值）/大失败（自然 1），优先于常规 success/winner。",
      "function isRecord(value) {",
      "  return typeof value === 'object' && value !== null && !Array.isArray(value);",
      "}",
      "function invalidArgs(message, details) {",
      "  const error = new Error('roll_dice: ' + message);",
      "  error.code = 'ROLL_DICE_INVALID_ARGS';",
      "  error.details = details;",
      "  throw error;",
      "}",
      "function hasOwn(value, key) {",
      "  return Object.prototype.hasOwnProperty.call(value, key);",
      "}",
      "// 受限表达式求值：白名单只允许数字、+ - * / ^ () . 和 sqrt 关键字与空格。",
      "// ^ → ** (JS 幂运算)，sqrt → Math.sqrt；Function 构造器严格模式无作用域访问，不用 eval。",
      "function evalExpr(expr) {",
      "  if (typeof expr !== 'string') {",
      "    invalidArgs('expression must be a string.', { expr: expr });",
      "  }",
      "  const cleaned = expr.replace(/\\s+/g, '');",
      "  if (!cleaned) {",
      "    invalidArgs('expression must not be empty.', { expr: expr });",
      "  }",
      "  if (!/^[\\d+\\-*/^().sqrt]+$/.test(cleaned)) {",
      "    invalidArgs('expression contains invalid characters (only digits, + - * / ^ ( ) . sqrt and spaces allowed).', { expr: expr });",
      "  }",
      "  const jsExpr = cleaned.replace(/\\^/g, '**').replace(/sqrt/g, 'Math.sqrt');",
      "  try {",
      "    const result = Function('\"use strict\"; return (' + jsExpr + ')')();",
      "    if (typeof result !== 'number' || !Number.isFinite(result)) {",
      "      invalidArgs('expression did not evaluate to a finite number.', { expr: expr, result: result });",
      "    }",
      "    return result;",
      "  } catch (e) {",
      "    invalidArgs('expression evaluation failed: ' + (e && e.message || e), { expr: expr });",
      "  }",
      "}",
      "function normalizeModifier(value, fallback, name) {",
      "  if (value === undefined) return fallback;",
      "  if (typeof value === 'number') {",
      "    if (!Number.isFinite(value)) {",
      "      invalidArgs(name + ' must be a finite number.', { modifier: value });",
      "    }",
      "    return value;",
      "  }",
      "  if (typeof value === 'string') {",
      "    if (!value.trim()) {",
      "      invalidArgs(name + ' expression must not be empty.', { modifier: value });",
      "    }",
      "    return evalExpr(value);",
      "  }",
      "  invalidArgs(name + ' must be a number or expression string.', { modifier: value });",
      "}",
      "function rollOnce(config, tsian) {",
      "  const roll = tsian.lib.random.dice({ sides: config.sides, count: config.count, modifier: config.modifier, advantage: config.advantage, disadvantage: config.disadvantage });",
      "  const output = {",
      "    sides: config.sides,",
      "    count: config.count,",
      "    modifier: config.modifier,",
      "    rolls: roll.rolls,",
      "    kept: roll.kept,",
      "    total: roll.total,",
      "  };",
      "  if (config.advantage && !config.disadvantage) output.advantage = true;",
      "  if (config.disadvantage && !config.advantage) output.disadvantage = true;",
      "  // 大成功/大失败：仅 count === 1 时判定，基于 kept[0] 自然骰值（advantage/disadvantage 时 kept 是选中那次）。",
      "  if (config.count === 1 && Array.isArray(roll.kept) && roll.kept.length > 0) {",
      "    const natural = roll.kept[0];",
      "    output.criticalSuccess = natural === config.sides;",
      "    output.criticalFailure = natural === 1;",
      "  }",
      "  return output;",
      "}",
      "async function rollDice(input, tsian) {",
      "  if (!isRecord(input)) {",
      "    invalidArgs('input must be an object.', { input: input });",
      "  }",
      "  const hasDc = hasOwn(input, 'dc') && input.dc !== undefined && input.dc !== null;",
      "  const hasOpposed = hasOwn(input, 'opposed') && input.opposed !== undefined;",
      "  if (hasDc && hasOpposed) {",
      "    invalidArgs('dc and opposed cannot be used together.', { dc: input.dc, opposed: true });",
      "  }",
      "  const sides = Number(input.sides);",
      "  if (!Number.isFinite(sides) || sides < 2) {",
      "    invalidArgs('sides must be an integer >= 2.', { sides: input.sides });",
      "  }",
      "  const count = input.count !== undefined ? Number(input.count) : 1;",
      "  const modifier = normalizeModifier(input.modifier, 0, 'modifier');",
      "  const advantage = Boolean(input.advantage);",
      "  const disadvantage = Boolean(input.disadvantage);",
      "  // advantage + disadvantage 同时为 true 时相互抵消（tsian.lib.random.dice 会忽略两者）。",
      "  const topConfig = { sides: sides, count: count, modifier: modifier, advantage: advantage, disadvantage: disadvantage };",
      "  let opposedConfig = null;",
      "  if (hasOpposed) {",
      "    if (!isRecord(input.opposed)) {",
      "      invalidArgs('opposed must be an object.', { opposed: input.opposed });",
      "    }",
      "    opposedConfig = {",
      "      sides: input.opposed.sides !== undefined ? Number(input.opposed.sides) : sides,",
      "      count: input.opposed.count !== undefined ? Number(input.opposed.count) : count,",
      "      modifier: normalizeModifier(input.opposed.modifier, 0, 'opposed.modifier'),",
      "      advantage: Boolean(input.opposed.advantage),",
      "      disadvantage: Boolean(input.opposed.disadvantage),",
      "    };",
      "  }",
      "  const output = rollOnce(topConfig, tsian);",
      "  if (hasDc) {",
      "    const dc = Number(input.dc);",
      "    if (Number.isFinite(dc)) {",
      "      output.dc = dc;",
      "      // 大成功/大失败优先于常规 dc 判定（仅在 count === 1 时 output 上有这两个字段）。",
      "      if (output.criticalSuccess) output.success = true;",
      "      else if (output.criticalFailure) output.success = false;",
      "      else output.success = output.total >= dc;",
      "    }",
      "  }",
      "  if (opposedConfig) {",
      "    output.opposed = rollOnce(opposedConfig, tsian);",
      "    output.margin = output.total - output.opposed.total;",
      "    // 大成功 vs 大失败 优先于常规 margin 判定；双方同为 crit 或均非 crit 时走常规 margin。",
      "    if (output.criticalSuccess && output.opposed.criticalFailure) {",
      "      output.winner = 'self';",
      "    } else if (output.criticalFailure && output.opposed.criticalSuccess) {",
      "      output.winner = 'opposed';",
      "    } else {",
      "      output.winner = output.margin > 0 ? 'self' : output.margin < 0 ? 'opposed' : 'tie';",
      "    }",
      "  }",
      "  if (typeof input.reason === 'string' && input.reason.trim()) {",
      "    output.reason = input.reason.trim().slice(0, 200);",
      "  }",
      "  const traceData = { sides: sides, count: count, modifier: modifier, total: output.total, kept: output.kept };",
      "  if (output.criticalSuccess !== undefined) traceData.criticalSuccess = output.criticalSuccess;",
      "  if (output.criticalFailure !== undefined) traceData.criticalFailure = output.criticalFailure;",
      "  if (opposedConfig) {",
      "    traceData.opposedTotal = output.opposed.total;",
      "    traceData.margin = output.margin;",
      "    traceData.winner = output.winner;",
      "    if (output.opposed.criticalSuccess !== undefined) traceData.opposedCriticalSuccess = output.opposed.criticalSuccess;",
      "    if (output.opposed.criticalFailure !== undefined) traceData.opposedCriticalFailure = output.opposed.criticalFailure;",
      "  }",
      "  tsian.trace('roll_dice', traceData);",
      "  return output;",
      "}",
      "return rollDice(input, tsian);",
    ]),
  },
]
