import { text } from "../utils"

// read-frontier-window — 读 frontier.json 当前 sourceWindow，计算下一段最多 15 章，读对应章节文本。
// 只读不写。复用 _common.js（isRecord/fail/parseJson/readJson/readText/cleanText/clipText/loadSource/normalizePositiveInt）。
export const READ_FRONTIER_WINDOW_SCRIPT_JS = `${text([
  "async function readFrontierWindow(input, tsian, signal) {",
  "  try {",
  "    signal.throwIfAborted();",
  "    // 1. 读当前 frontier.json",
  "    const frontier = await readJson(tsian, 'save/playthrough/frontier.json');",
  "    if (!isRecord(frontier)) fail('FRONTIER_INVALID', 'frontier.json must be a JSON object.', { path: 'save/playthrough/frontier.json' });",
  "    const sourceWindow = isRecord(frontier.sourceWindow) ? frontier.sourceWindow : { start: null, end: null };",
  "    const currentEnd = typeof sourceWindow.end === 'number' ? sourceWindow.end : 0;",
  "    // 2. 加载 source chapter index",
  "    const source = await loadSource(tsian);",
  "    const totalChapters = source.chapters.length;",
  "    const nextStart = currentEnd + 1;",
  "    if (nextStart > totalChapters) fail('FRONTIER_NO_MORE_CHAPTERS', 'No more chapters to read.', { currentEnd, totalChapters });",
  "    const windowSize = 15;",
  "    const nextEnd = Math.min(totalChapters, nextStart + windowSize - 1);",
  "    // 3. 读窗口内章节文本",
  "    const chapters = [];",
  "    const parts = [];",
  "    let totalCharacters = 0;",
  "    const maxCharacters = 120000;",
  "    for (const chapter of source.chapters.slice(nextStart - 1, nextEnd)) {",
  "      signal.throwIfAborted();",
  "      const content = await readText(tsian, chapter.path);",
  "      const cleaned = cleanText(content);",
  "      const remaining = maxCharacters - totalCharacters;",
  "      if (remaining <= 0) break;",
  "      const used = cleaned.length > remaining ? cleaned.slice(0, remaining) : cleaned;",
  "      totalCharacters += used.length;",
  "      chapters.push({ ...chapter, charactersRead: used.length, truncated: used.length < cleaned.length });",
  "      var body = used;",
  "      var nl = body.indexOf('\\n');",
  "      var firstLine = (nl === -1 ? body : body.slice(0, nl)).trim();",
  "      if (firstLine === chapter.title) { body = nl === -1 ? '' : body.slice(nl + 1).replace(/^\\s+/, ''); }",
  "      parts.push('# ' + chapter.title + '\\n\\n' + body);",
  "      if (totalCharacters >= maxCharacters) break;",
  "    }",
  "    // 4. 提取现有 timeline source 锚点（供 order 赋值参考）",
  "    const timeline = Array.isArray(frontier.timeline) ? frontier.timeline : [];",
  "    const sourceAnchors = timeline.filter(function (a) { return isRecord(a) && a.kind === 'source'; });",
  "    const lastSourceOrder = sourceAnchors.length > 0 ? Math.max.apply(null, sourceAnchors.map(function (a) { return typeof a.order === 'number' ? a.order : 0; })) : 0;",
  "    const result = {",
  "      window: { start: nextStart, end: chapters.length ? chapters[chapters.length - 1].index : nextStart, totalChapters: totalChapters, chapters: chapters },",
  "      text: parts.join('\\n\\n'),",
  "      frontierState: { sourceWindow: sourceWindow, lastSourceOrder: lastSourceOrder, timeline: timeline }",
  "    };",
  "    tsian.trace('frontier_window_read', { start: result.window.start, end: result.window.end, totalCharacters: totalCharacters, chapterCount: chapters.length, lastSourceOrder: lastSourceOrder });",
  "    return result;",
  "  } catch (error) {",
  "    tsian.trace('frontier_window_read_failed', { code: error && error.code || 'FRONTIER_READ_FAILED', message: error && error.message || String(error), details: error && error.details });",
  "    throw error;",
  "  }",
  "}",
  "return readFrontierWindow(input, tsian, signal);",
])}`

// commit-frontier-materials — 校验 entities/relationships/schemaPatches 增量，写入对应目录。
// 复用 _common.js + _validation.js（isRecord/fail/normalizeEntity/normalizeRelationships/loadExistingEntityIds/normalizeString）。
export const COMMIT_FRONTIER_MATERIALS_SCRIPT_JS = `${text([
  "async function commitFrontierMaterials(input, tsian, signal) {",
  "  try {",
  "    signal.throwIfAborted();",
  "    if (!isRecord(input)) fail('FRONTIER_MATERIALS_INVALID', 'Commit input must be an object.');",
  "    const writes = [];",
  "    // 1. entities（可选，可为空数组）",
  "    const entitiesRaw = Array.isArray(input.entities) ? input.entities : [];",
  "    const entities = entitiesRaw.map(normalizeEntity);",
  "    // 2. relationships（可选，可为空数组）",
  "    const relationshipsRaw = Array.isArray(input.relationships) ? input.relationships : [];",
  "    const knownEntityIds = await loadExistingEntityIds(tsian);",
  "    for (const item of entities) { knownEntityIds.add(item.entity.id); }",
  "    const relationships = normalizeRelationships(relationshipsRaw, knownEntityIds);",
  "    // 3. schemaPatches（可选，可为空数组）— 写入 save/schema/patches/pending/ 下",
  "    const schemaPatchesRaw = Array.isArray(input.schemaPatches) ? input.schemaPatches : [];",
  "    // 全部校验通过，统一写入",
  "    for (const item of entities) {",
  "      signal.throwIfAborted();",
  "      const file = await tsian.workspace.write({ scope: 'save-runtime', path: item.path, content: JSON.stringify(item.entity, null, 2) + '\\n', mediaType: 'application/json' });",
  "      writes.push({ path: file.path, size: file.content.length, kind: 'entity' });",
  "    }",
  "    for (const rel of relationships) {",
  "      signal.throwIfAborted();",
  "      const file = await tsian.workspace.write({ scope: 'save-runtime', path: 'save/relationships/' + rel.scope + '.json', content: JSON.stringify({ subject: rel.subject, edges: rel.edges, updatedTurn: 0, updatedBy: 'world-architect' }, null, 2) + '\\n', mediaType: 'application/json' });",
  "      writes.push({ path: file.path, size: file.content.length, kind: 'relationship' });",
  "    }",
  "    for (let i = 0; i < schemaPatchesRaw.length; i++) {",
  "      signal.throwIfAborted();",
  "      const patch = schemaPatchesRaw[i];",
  "      if (!isRecord(patch) || typeof patch.content !== 'string' || !patch.content.trim()) fail('FRONTIER_SCHEMA_PATCH_INVALID', 'Each schemaPatch must be an object with non-empty content string.', { index: i });",
  "      const patchName = typeof patch.name === 'string' && patch.name.trim() ? patch.name.trim().replace(/[^a-zA-Z0-9\\u4e00-\\u9fff_-]/g, '-') : 'patch-' + (i + 1);",
  "      const patchPath = 'save/schema/patches/pending/' + patchName + '.md';",
  "      const file = await tsian.workspace.write({ scope: 'save-runtime', path: patchPath, content: patch.content, mediaType: 'text/markdown' });",
  "      writes.push({ path: file.path, size: file.content.length, kind: 'schema-patch' });",
  "    }",
  "    tsian.trace('frontier_materials_committed', { entityCount: entities.length, relationshipCount: relationships.length, schemaPatchCount: schemaPatchesRaw.length, writes: writes.map((w) => w.path) });",
  "    return { status: 'ready', writes, entityCount: entities.length, relationshipCount: relationships.length, schemaPatchCount: schemaPatchesRaw.length };",
  "  } catch (error) {",
  "    tsian.trace('frontier_materials_commit_failed', { code: error && error.code || 'FRONTIER_COMMIT_FAILED', message: error && error.message || String(error), details: error && error.details });",
  "    throw error;",
  "  }",
  "}",
  "return commitFrontierMaterials(input, tsian, signal);",
])}`

// commit-frontier-state — 校验 order 递增、sourceWindow 顺序推进、timeline 锚点 chapter 在窗口内，写入 frontier.json。
// 复用 _common.js + _validation.js（isRecord/fail/normalizeString/normalizePositiveInt/normalizeEntityId/loadSource）。
export const COMMIT_FRONTIER_STATE_SCRIPT_JS = `${text([
  "async function commitFrontierState(input, tsian, signal) {",
  "  try {",
  "    signal.throwIfAborted();",
  "    if (!isRecord(input)) fail('FRONTIER_STATE_INVALID', 'Commit input must be an object.');",
  "    // 1. 读当前 frontier.json",
  "    const frontier = await readJson(tsian, 'save/playthrough/frontier.json');",
  "    if (!isRecord(frontier)) fail('FRONTIER_INVALID', 'frontier.json must be a JSON object.', { path: 'save/playthrough/frontier.json' });",
  "    const currentSourceWindow = isRecord(frontier.sourceWindow) ? frontier.sourceWindow : { start: null, end: null };",
  "    const currentEnd = typeof currentSourceWindow.end === 'number' ? currentSourceWindow.end : 0;",
  "    // 2. 校验 sourceWindow 顺序推进",
  "    if (!isRecord(input.sourceWindow)) fail('FRONTIER_WINDOW_INVALID', 'sourceWindow must be an object.');",
  "    const newStart = normalizePositiveInt(input.sourceWindow.start, currentEnd + 1, currentEnd + 1, 999999);",
  "    if (newStart !== currentEnd + 1) fail('FRONTIER_WINDOW_NOT_SEQUENTIAL', 'sourceWindow.start must equal current sourceWindow.end + 1.', { expected: currentEnd + 1, got: newStart });",
  "    const newEnd = normalizePositiveInt(input.sourceWindow.end, newStart, newStart, 999999);",
  "    // 3. 加载 source 校验章节路径",
  "    const source = await loadSource(tsian);",
  "    const knownPaths = new Set(source.chapters.map((chapter) => chapter.path));",
  "    const chaptersRaw = Array.isArray(input.sourceWindow.chapters) ? input.sourceWindow.chapters : [];",
  "    const chapters = chaptersRaw.map((chapter, index) => {",
  "      if (!isRecord(chapter)) fail('FRONTIER_WINDOW_CHAPTER_INVALID', 'Window chapters must be objects.', { index });",
  "      const path = normalizeString(chapter.path, 'FRONTIER_WINDOW_CHAPTER_PATH_REQUIRED', 'Window chapter path', 240);",
  "      if (!knownPaths.has(path)) fail('FRONTIER_SOURCE_REF_UNKNOWN', 'Window chapter path is not in imported chapter index.', { path });",
  "      return { index: normalizePositiveInt(chapter.index, index + 1, 1, 999999), title: typeof chapter.title === 'string' ? chapter.title.trim() : '', path };",
  "    });",
  "    // 4. 校验 timeline source 锚点",
  "    const timelineRaw = Array.isArray(input.timelineAnchors) ? input.timelineAnchors : [];",
  "    if (timelineRaw.length === 0) fail('FRONTIER_TIMELINE_ANCHORS_REQUIRED', 'At least one source anchor is required.');",
  "    const existingTimeline = Array.isArray(frontier.timeline) ? frontier.timeline : [];",
  "    const existingSourceAnchors = existingTimeline.filter(function (a) { return isRecord(a) && a.kind === 'source'; });",
  "    const lastSourceOrder = existingSourceAnchors.length > 0 ? Math.max.apply(null, existingSourceAnchors.map(function (a) { return typeof a.order === 'number' ? a.order : 0; })) : 0;",
  "    const newAnchors = [];",
  "    let expectedOrder = lastSourceOrder;",
  "    for (let i = 0; i < timelineRaw.length; i++) {",
  "      const anchor = timelineRaw[i];",
  "      if (!isRecord(anchor)) fail('FRONTIER_TIMELINE_ANCHOR_INVALID', 'Each timeline anchor must be an object.', { index: i });",
  "      if (anchor.kind !== 'source') fail('FRONTIER_TIMELINE_ANCHOR_KIND_INVALID', 'commit_frontier_state only accepts source anchors.', { index: i, kind: anchor.kind });",
  "      const order = normalizePositiveInt(anchor.order, expectedOrder + 1, 1, 999999);",
  "      if (order <= lastSourceOrder) fail('FRONTIER_ORDER_NOT_INCREASING', 'Source anchor order must be strictly greater than last existing source anchor order.', { order: order, lastSourceOrder: lastSourceOrder });",
  "      if (order <= expectedOrder) fail('FRONTIER_ORDER_NOT_SEQUENTIAL', 'Source anchor order must be strictly increasing within this commit.', { order: order, expected: expectedOrder + 1 });",
  "      expectedOrder = order;",
  "      const chapter = normalizePositiveInt(anchor.chapter, newStart, 1, 999999);",
  "      if (chapter < newStart || chapter > newEnd) fail('FRONTIER_TIMELINE_CHAPTER_OUT_OF_WINDOW', 'Timeline anchor chapter must be within the new sourceWindow range.', { chapter: chapter, windowStart: newStart, windowEnd: newEnd });",
  "      const time = normalizeString(anchor.time, 'FRONTIER_TIMELINE_TIME_REQUIRED', 'Timeline anchor time', 120);",
  "      const label = normalizeString(anchor.label, 'FRONTIER_TIMELINE_LABEL_REQUIRED', 'Timeline anchor label', 120);",
  "      newAnchors.push({ kind: 'source', order: order, chapter: chapter, time: time, label: label });",
  "    }",
  "    // 5. 校验 extractedThrough",
  "    const extractedThrough = typeof input.extractedThrough === 'string' && input.extractedThrough.trim() ? input.extractedThrough.trim() : (chapters.length ? chapters[chapters.length - 1].path : null);",
  "    if (extractedThrough && !knownPaths.has(extractedThrough)) fail('FRONTIER_SOURCE_REF_UNKNOWN', 'extractedThrough must point to an imported chapter file.', { extractedThrough });",
  "    // 6. 合并 timeline（追加新 source 锚点到现有数组）",
  "    const mergedTimeline = existingTimeline.concat(newAnchors);",
  "    const notes = typeof frontier.notes === 'string' ? frontier.notes : '';",
  "    const frontierFile = { sourceWindow: { start: newStart, end: newEnd, chapters: chapters }, extractedThrough: extractedThrough, timeline: mergedTimeline, notes: notes, updatedAt: new Date().toISOString(), updatedBy: 'world-architect' };",
  "    const file = await tsian.workspace.write({ scope: 'save-runtime', path: 'save/playthrough/frontier.json', content: JSON.stringify(frontierFile, null, 2) + '\\n', mediaType: 'application/json' });",
  "    tsian.trace('frontier_state_committed', { windowStart: newStart, windowEnd: newEnd, extractedThrough: extractedThrough, newAnchors: newAnchors.length, lastSourceOrder: lastSourceOrder, maxSourceOrder: expectedOrder, write: file.path });",
  "    return { status: 'ready', write: { path: file.path, size: file.content.length }, window: { start: newStart, end: newEnd }, newAnchors: newAnchors.length, lastSourceOrder: lastSourceOrder };",
  "  } catch (error) {",
  "    tsian.trace('frontier_state_commit_failed', { code: error && error.code || 'FRONTIER_COMMIT_FAILED', message: error && error.message || String(error), details: error && error.details });",
  "    throw error;",
  "  }",
  "}",
  "return commitFrontierState(input, tsian, signal);",
])}`
