import { text } from "../utils"

export const OPENING_COMMON_JS = text([
  "const OPENING_SCHEMA = 'tsian.opening.initial-understanding.v1';",
  "const MANIFEST_PATH = 'save/source/manifest.json';",
  "const CHAPTER_INDEX_PATH = 'save/source/chapters.index.json';",
  "function isRecord(value) { return typeof value === 'object' && value !== null && !Array.isArray(value); }",
  "function fail(code, message, details) { const error = new Error(message); error.code = code; if (details !== undefined) error.details = details; throw error; }",
  "function parseJson(content, path) { try { return JSON.parse(content); } catch (error) { fail('OPENING_JSON_INVALID', path + ' is not valid JSON: ' + (error && error.message || error), { path }); } }",
  "async function readJson(tsian, path) { const file = await tsian.workspace.read({ scope: 'effective', path }); if (!file || typeof file.content !== 'string') fail('OPENING_FILE_MISSING', 'Required file is missing.', { path }); return parseJson(file.content, path); }",
  "async function readText(tsian, path) { const file = await tsian.workspace.read({ scope: 'effective', path }); if (!file || typeof file.content !== 'string') fail('OPENING_FILE_MISSING', 'Required file is missing.', { path }); return file.content; }",
  "function cleanText(text) { return String(text || '').replace(/^#\\s+.*\\n+/, '').replace(/\\n{3,}/g, '\\n\\n').trim(); }",
  "function clipText(text, limit) { const cleaned = cleanText(text); return cleaned.length <= limit ? cleaned : cleaned.slice(0, limit).trimEnd() + '……'; }",
  "function normalizePositiveInt(value, fallback, min, max) { const number = Number(value); if (!Number.isFinite(number)) return fallback; return Math.max(min, Math.min(max, Math.floor(number))); }",
  "async function loadSource(tsian) {",
  "  const manifest = await readJson(tsian, MANIFEST_PATH);",
  "  const index = await readJson(tsian, CHAPTER_INDEX_PATH);",
  "  if (!isRecord(manifest) || manifest.status !== 'ready') fail('OPENING_SOURCE_NOT_READY', 'Imported source manifest is not ready.', { path: MANIFEST_PATH });",
  "  if (!isRecord(index) || !Array.isArray(index.chapters)) fail('OPENING_CHAPTER_INDEX_INVALID', 'Chapter index must contain chapters array.', { path: CHAPTER_INDEX_PATH });",
  "  const chapters = index.chapters.map((chapter, index) => {",
  "    if (!isRecord(chapter) || typeof chapter.path !== 'string') fail('OPENING_CHAPTER_INVALID', 'Each chapter must include a path.', { index });",
  "    return { index: index + 1, title: typeof chapter.title === 'string' && chapter.title.trim() ? chapter.title.trim() : '第 ' + (index + 1) + ' 章', path: chapter.path, characters: typeof chapter.characters === 'number' ? chapter.characters : null };",
  "  });",
  "  return { manifest, chapters };",
  "}",
])

// 校验 helper JS。作为独立 _validation.js 文件内容，由 executor.helpers 声明拼接。
// 仅含 commit_* 脚本需要的校验工具；inspect/read 脚本不依赖此常量。
export const OPENING_VALIDATION_JS = text([
  "function normalizeString(value, code, label, maxLength) {",
  "  if (typeof value !== 'string' || !value.trim()) fail(code, label + ' must be a non-empty string.');",
  "  const normalized = value.trim();",
  "  if (maxLength && normalized.length > maxLength) fail(code + '_TOO_LONG', label + ' is too long.', { maxLength, length: normalized.length });",
  "  return normalized;",
  "}",
  "function normalizeSegment(value, label) {",
  "  const segment = normalizeString(value, 'OPENING_ENTITY_ID_INVALID', label, 80);",
  "  if (segment === '.' || segment === '..' || /[\\/:\\0]/.test(segment)) fail('OPENING_ENTITY_ID_INVALID', label + ' must not contain path separators, colon, NUL, . or ...', { value });",
  "  return segment;",
  "}",
  "function normalizeEntityId(rawId, label) {",
  "  const id = normalizeString(rawId, 'OPENING_ENTITY_ID_REQUIRED', label, 120);",
  "  const parts = id.split(':');",
  "  if (parts.length !== 2) fail('OPENING_ENTITY_ID_INVALID', label + ' must use <type>:<localId>.', { id });",
  "  const type = normalizeSegment(parts[0], 'Entity type');",
  "  const localId = normalizeSegment(parts[1], 'Entity localId');",
  "  return { id: type + ':' + localId, type, localId };",
  "}",
  "function normalizeEntity(rawEntity, index) {",
  "  if (!isRecord(rawEntity)) fail('OPENING_ENTITY_INVALID', 'Each entity must be an object.', { index });",
  "  const parsed = normalizeEntityId(rawEntity.id, 'Entity id');",
  "  const entity = { ...rawEntity, id: parsed.id, name: normalizeString(rawEntity.name, 'OPENING_ENTITY_NAME_REQUIRED', 'Entity name', 120), brief: normalizeString(rawEntity.brief, 'OPENING_ENTITY_BRIEF_REQUIRED', 'Entity brief', 1000) };",
  "  if (parsed.type === 'container') { if (entity.type !== 'container') fail('OPENING_ENTITY_TYPE_INVALID', 'container entity must have type=\"container\".', { id: parsed.id, type: entity.type }); }",
  "  else if (parsed.type === 'item') { const t = typeof entity.type === 'string' ? entity.type.trim() : ''; if (!['equipment', 'material', 'consumable', 'special', 'other'].includes(t)) fail('OPENING_ENTITY_TYPE_INVALID', 'item entity type must be one of equipment/material/consumable/special/other.', { id: parsed.id, type: entity.type }); entity.type = t; }",
  "  return { path: 'save/entities/' + parsed.type + '/' + parsed.localId + '.json', entity };",
  "}",
  "function normalizeRef(rawRef, label, knownEntityIds, context) {",
  "  if (!isRecord(rawRef)) fail('OPENING_REF_INVALID', label + ' must be an object { ref, name }.', context);",
  "  const parsed = normalizeEntityId(rawRef.ref, label + ' ref');",
  "  if (knownEntityIds && !knownEntityIds.has(parsed.id)) fail('OPENING_REF_UNKNOWN', label + ' ref must point to an entity in this commit or an existing entity.', { ...context, ref: parsed.id });",
  "  return { ref: parsed.id, name: normalizeString(rawRef.name, 'OPENING_REF_NAME_REQUIRED', label + ' name', 120) };",
  "}",
  "function normalizeScene(rawScene, knownEntityIds) {",
  "  if (!isRecord(rawScene)) fail('OPENING_SCENE_INVALID', 'Opening scene must be an object.');",
  "  const parsed = normalizeEntityId(rawScene.id, 'Scene id');",
  "  if (parsed.type !== 'scene') fail('OPENING_SCENE_TYPE_INVALID', 'Scene id must use scene:<localId>.', { id: parsed.id });",
  "  const name = normalizeString(rawScene.name, 'OPENING_SCENE_NAME_REQUIRED', 'Scene name', 120);",
  "  const location = normalizeRef(rawScene.location, 'Scene location', knownEntityIds, { scene: parsed.id });",
  "  const presentRaw = Array.isArray(rawScene.present) ? rawScene.present : [];",
  "  if (presentRaw.length === 0) fail('OPENING_SCENE_PRESENT_REQUIRED', 'Scene present must list at least one entity.', { scene: parsed.id });",
  "  const present = presentRaw.map((item, index) => {",
  "    if (!isRecord(item)) fail('OPENING_SCENE_PRESENT_INVALID', 'Scene present entry must be an object { ref }.', { scene: parsed.id, index });",
  "    const refParsed = normalizeEntityId(item.ref, 'Scene present[' + index + '] ref');",
  "    if (knownEntityIds && !knownEntityIds.has(refParsed.id)) fail('OPENING_REF_UNKNOWN', 'Scene present ref must point to an entity in this commit or an existing entity.', { scene: parsed.id, index, ref: refParsed.id });",
  "    return { ref: refParsed.id };",
  "  });",
  "  return { id: parsed.id, name, location, present };",
  "}",
  "function scopeFromSubject(subjectId) {",
  "  const parsed = normalizeEntityId(subjectId, 'Relationship subject');",
  "  return parsed.type + '-' + parsed.localId;",
  "}",
  "function normalizeRelationships(rawRelationships, knownEntityIds) {",
  "  if (!Array.isArray(rawRelationships)) return [];",
  "  const seen = new Set();",
  "  const result = [];",
  "  for (const raw of rawRelationships) {",
  "    if (!isRecord(raw)) fail('OPENING_RELATIONSHIP_INVALID', 'Each relationship must be an object { subject, edges }.');",
  "    const subjectParsed = normalizeEntityId(raw.subject, 'Relationship subject');",
  "    if (subjectParsed.type !== 'character') fail('OPENING_RELATIONSHIP_SUBJECT_TYPE_INVALID', 'Relationship subject must use character:<localId>; relationships are character/person social edges, not a generic entity graph.', { subject: subjectParsed.id, type: subjectParsed.type });",
  "    if (knownEntityIds && !knownEntityIds.has(subjectParsed.id)) fail('OPENING_RELATIONSHIP_SUBJECT_UNKNOWN', 'Relationship subject must point to an entity in this commit or an existing entity.', { subject: subjectParsed.id });",
  "    const scope = scopeFromSubject(raw.subject);",
  "    if (seen.has(scope)) fail('OPENING_RELATIONSHIP_DUPLICATE_SUBJECT', 'Duplicate relationship subject in this commit.', { subject: subjectParsed.id });",
  "    seen.add(scope);",
  "    const edgesRaw = Array.isArray(raw.edges) ? raw.edges : [];",
  "    if (edgesRaw.length === 0) fail('OPENING_RELATIONSHIP_EDGES_REQUIRED', 'Relationship must have at least one edge.', { subject: subjectParsed.id });",
  "    const edges = edgesRaw.map((edge, index) => {",
  "      if (!isRecord(edge)) fail('OPENING_RELATIONSHIP_EDGE_INVALID', 'Each edge must be an object.', { subject: subjectParsed.id, index });",
  "      const toParsed = normalizeEntityId(edge.to, 'Edge to');",
  "      if (toParsed.type !== 'character') fail('OPENING_RELATIONSHIP_TO_TYPE_INVALID', 'Relationship edge.to must use character:<localId>; put non-character associations in fixed fields, existing ref structures, or extensions.render=\"ref\".', { subject: subjectParsed.id, to: toParsed.id, type: toParsed.type });",
  "      if (knownEntityIds && !knownEntityIds.has(toParsed.id)) fail('OPENING_RELATIONSHIP_TO_UNKNOWN', 'Edge to must point to an entity in this commit or an existing entity.', { subject: subjectParsed.id, to: toParsed.id });",
  "      return { to: toParsed.id, type: normalizeString(edge.type, 'OPENING_RELATIONSHIP_TYPE_REQUIRED', 'Edge type', 60), since: typeof edge.since === 'number' ? edge.since : 0, until: typeof edge.until === 'number' ? edge.until : undefined, note: typeof edge.note === 'string' && edge.note.trim() ? edge.note.trim() : undefined };",
  "    });",
  "    result.push({ subject: subjectParsed.id, edges, scope });",
  "  }",
  "  return result;",
  "}",
  "function normalizeCandidate(rawCandidate, index) {",
  "  if (!isRecord(rawCandidate)) fail('OPENING_CANDIDATE_INVALID', 'Each candidate character must be an object.', { index });",
  "  var errors = [];",
  "  var parsed;",
  "  try { parsed = normalizeEntityId(rawCandidate.id, 'Candidate id'); } catch (e) { errors.push({ field: 'id', code: e.code, message: e.message, details: e.details }); parsed = { id: '', type: '' }; }",
  "  if (parsed && parsed.type !== 'character') errors.push({ field: 'id', code: 'OPENING_CANDIDATE_TYPE_INVALID', message: 'Candidate id must use character:<localId>.', details: { id: parsed.id, type: parsed.type } });",
  "  var name, brief;",
  "  try { name = normalizeString(rawCandidate.name, 'OPENING_CANDIDATE_NAME_REQUIRED', 'Candidate name', 120); } catch (e) { errors.push({ field: 'name', code: e.code, message: e.message, details: e.details }); }",
  "  try { brief = normalizeString(rawCandidate.brief, 'OPENING_CANDIDATE_BRIEF_REQUIRED', 'Candidate brief', 500); } catch (e) { errors.push({ field: 'brief', code: e.code, message: e.message, details: e.details }); }",
  "  if (errors.length > 0) fail(errors[0].code, errors.length + ' field(s) failed; fix all and retry.', { fieldErrors: errors });",
  "  var candidate = { id: parsed.id, name: name, brief: brief };",
  "  if (typeof rawCandidate.gender === 'string' && rawCandidate.gender.trim()) candidate.gender = rawCandidate.gender.trim();",
  "  return candidate;",
  "}",
  "function normalizeWindow(rawWindow, knownPaths) {",
  "  if (!isRecord(rawWindow)) fail('OPENING_WINDOW_INVALID', 'Window must be an object.');",
  "  var startIndex = normalizePositiveInt(rawWindow.startIndex, 1, 1, 999999);",
  "  var endIndex = normalizePositiveInt(rawWindow.endIndex, startIndex, startIndex, 999999);",
  "  var errors = [];",
  "  var reason;",
  "  try { reason = normalizeString(rawWindow.reason, 'OPENING_WINDOW_REASON_REQUIRED', 'Window reason', 1000); } catch (e) { errors.push({ field: 'reason', code: e.code, message: e.message, details: e.details }); }",
  "  var chapters = Array.isArray(rawWindow.chapters) ? rawWindow.chapters : [];",
  "  var normalizedChapters = chapters.map(function (chapter, index) {",
  "    if (!isRecord(chapter)) { errors.push({ field: 'chapters[' + index + ']', code: 'OPENING_WINDOW_CHAPTER_INVALID', message: 'Window chapters must be objects.', details: { index: index } }); return null; }",
  "    var path, hadError = false;",
  "    try { path = normalizeString(chapter.path, 'OPENING_WINDOW_CHAPTER_PATH_REQUIRED', 'Window chapter path', 240); } catch (e) { errors.push({ field: 'chapters[' + index + '].path', code: e.code, message: e.message, details: e.details }); hadError = true; }",
  "    if (path && !knownPaths.has(path)) { errors.push({ field: 'chapters[' + index + '].path', code: 'OPENING_SOURCE_REF_UNKNOWN', message: 'Window chapter path is not in imported chapter index.', details: { path: path } }); hadError = true; }",
  "    if (hadError) return null;",
  "    return { index: normalizePositiveInt(chapter.index, index + 1, 1, 999999), title: typeof chapter.title === 'string' ? chapter.title.trim() : '', path: path };",
  "  }).filter(function (c) { return c !== null; });",
  "  if (errors.length > 0) fail(errors[0].code, errors.length + ' field(s) failed; fix all and retry.', { fieldErrors: errors });",
  "  return { startIndex: startIndex, endIndex: endIndex, reason: reason, chapters: normalizedChapters };",
  "}",
  "async function loadExistingEntityIds(tsian) {",
  "  const result = await tsian.workspace.glob({ scope: 'effective', pattern: 'save/entities/*/*.json', limit: 10000 });",
  "  const globResult = result || {};",
  "  const matches = Array.isArray(globResult.matches) ? globResult.matches : [];",
  "  if (globResult.truncated) fail('OPENING_ENTITY_GLOB_TRUNCATED', 'Entity count exceeds workspace.glob limit; resolve existing refs explicitly or narrow the pattern.', { limit: matches.length });",
  "  return new Set(matches.map((p) => { const seg = p.slice('save/entities/'.length).replace(/\\.json$/, '').split('/'); return seg[0] + ':' + seg[1]; }));",
  "}",
])

// inspect_source_opening — 直接复用旧 OPENING_INSPECT_SOURCE_SCRIPT_JS。
export const INSPECT_SOURCE_OPENING_SCRIPT_JS = `${text([
  "async function inspectSourceOpening(input, tsian, signal) {",
  "  try {",
  "    signal.throwIfAborted();",
  "    const previewCount = normalizePositiveInt(input && input.previewCount, 8, 1, 20);",
  "    const previewCharacters = normalizePositiveInt(input && input.previewCharacters, 700, 120, 2000);",
  "    const source = await loadSource(tsian);",
  "    const earlyChapters = [];",
  "    for (const chapter of source.chapters.slice(0, previewCount)) {",
  "      signal.throwIfAborted();",
  "      const content = await readText(tsian, chapter.path);",
  "      earlyChapters.push({ ...chapter, preview: clipText(content, previewCharacters) });",
  "    }",
  "    const result = { schema: OPENING_SCHEMA, title: source.manifest.title || '导入小说', totalCharacters: source.manifest.totalCharacters || 0, chapterCount: source.chapters.length, earlyChapters };",
  "    tsian.trace('opening_source_inspected', { title: result.title, chapterCount: result.chapterCount, previewCount: earlyChapters.length });",
  "    return result;",
  "  } catch (error) {",
  "    tsian.trace('opening_source_inspect_failed', { code: error && error.code || 'OPENING_INSPECT_FAILED', message: error && error.message || String(error), details: error && error.details });",
  "    throw error;",
  "  }",
  "}",
  "return inspectSourceOpening(input, tsian, signal);",
])}`

// read_opening_slice — 直接复用旧 OPENING_READ_SLICE_SCRIPT_JS。
export const READ_OPENING_SLICE_SCRIPT_JS = `${text([
  "async function readOpeningSlice(input, tsian, signal) {",
  "  try {",
  "    signal.throwIfAborted();",
  "    const source = await loadSource(tsian);",
  "    const startIndex = normalizePositiveInt(input && input.startIndex, 1, 1, Math.max(1, source.chapters.length));",
  "    const defaultEnd = Math.min(source.chapters.length, startIndex + 2);",
  "    const endIndex = normalizePositiveInt(input && input.endIndex, defaultEnd, startIndex, source.chapters.length);",
  "    const maxCharacters = normalizePositiveInt(input && input.maxCharacters, 60000, 4000, 120000);",
  "    let totalCharacters = 0;",
  "    const selectedChapters = [];",
  "    const parts = [];",
  "    for (const chapter of source.chapters.slice(startIndex - 1, endIndex)) {",
  "      signal.throwIfAborted();",
  "      const content = await readText(tsian, chapter.path);",
  "      const cleaned = cleanText(content);",
  "      const remaining = maxCharacters - totalCharacters;",
  "      if (remaining <= 0) break;",
  "      const used = cleaned.length > remaining ? cleaned.slice(0, remaining) : cleaned;",
  "      totalCharacters += used.length;",
  "      selectedChapters.push({ ...chapter, charactersRead: used.length, truncated: used.length < cleaned.length });",
  "      var body = used;",
  "      var nl = body.indexOf('\\n');",
  "      var firstLine = (nl === -1 ? body : body.slice(0, nl)).trim();",
  "      if (firstLine === chapter.title) { body = nl === -1 ? '' : body.slice(nl + 1).replace(/^\\s+/, ''); }",
  "      parts.push('# ' + chapter.title + '\\n\\n' + body);",
  "      if (totalCharacters >= maxCharacters) break;",
  "    }",
  "    const result = { schema: OPENING_SCHEMA, window: { startIndex, endIndex: selectedChapters.length ? selectedChapters[selectedChapters.length - 1].index : startIndex, maxCharacters, totalCharacters, chapters: selectedChapters }, text: parts.join('\\n\\n') };",
  "    tsian.trace('opening_slice_read', { startIndex: result.window.startIndex, endIndex: result.window.endIndex, totalCharacters, chapterCount: selectedChapters.length });",
  "    return result;",
  "  } catch (error) {",
  "    tsian.trace('opening_slice_read_failed', { code: error && error.code || 'OPENING_SLICE_FAILED', message: error && error.message || String(error), details: error && error.details });",
  "    throw error;",
  "  }",
  "}",
  "return readOpeningSlice(input, tsian, signal);",
])}`

// commit_entities — normalizeEntity 校验 + 逐个写入 save/entities/<type>/<localId>.json。
export const COMMIT_ENTITIES_SCRIPT_JS = `${text([
  "async function commitEntities(input, tsian, signal) {",
  "  try {",
  "    signal.throwIfAborted();",
  "    if (!isRecord(input)) fail('OPENING_COMMIT_INVALID', 'Commit input must be an object.');",
  "    if (!Array.isArray(input.entities) || input.entities.length === 0) fail('OPENING_ENTITIES_REQUIRED', 'At least one opening entity is required.');",
  "    const entities = input.entities.map(normalizeEntity);",
  "    const writes = [];",
  "    for (const item of entities) {",
  "      signal.throwIfAborted();",
  "      const file = await tsian.workspace.write({ scope: 'save-runtime', path: item.path, content: JSON.stringify(item.entity, null, 2) + '\\n', mediaType: 'application/json' });",
  "      writes.push({ path: file.path, size: file.content.length });",
  "    }",
  "    const entityIds = entities.map((item) => item.entity.id);",
  "    tsian.trace('opening_entities_committed', { entityCount: entities.length, writes: writes.map((w) => w.path) });",
  "    return { status: 'ready', writes, entityCount: entities.length, entityIds };",
  "  } catch (error) {",
  "    tsian.trace('opening_entities_commit_failed', { code: error && error.code || 'OPENING_COMMIT_FAILED', message: error && error.message || String(error), details: error && error.details });",
  "    throw error;",
  "  }",
  "}",
  "return commitEntities(input, tsian, signal);",
])}`

// commit_scenes_and_relationships — 合并 scenes + relationships，共享一次 loadExistingEntityIds 调用。
// input: { scenes: [...], relationships: [...] }。output: { writes, sceneCount, relationshipCount }。
export const COMMIT_SCENES_AND_RELATIONSHIPS_SCRIPT_JS = `${text([
  "async function commitScenesAndRelationships(input, tsian, signal) {",
  "  try {",
  "    signal.throwIfAborted();",
  "    if (!isRecord(input)) fail('OPENING_COMMIT_INVALID', 'Commit input must be an object.');",
  "    if (!Array.isArray(input.scenes) || input.scenes.length === 0) fail('OPENING_SCENES_REQUIRED', 'At least one opening scene is required.');",
  "    if (!Array.isArray(input.relationships)) fail('OPENING_RELATIONSHIPS_REQUIRED', 'relationships must be an array.');",
  "    const knownEntityIds = await loadExistingEntityIds(tsian);",
  "    const committedAt = new Date().toISOString();",
  "    // 先全部校验，再统一写入，避免 scenes 已落盘而 relationships 校验失败造成半成品",
  "    const normalizedScenes = input.scenes.map((rawScene) => normalizeScene(rawScene, knownEntityIds));",
  "    const relationships = normalizeRelationships(input.relationships, knownEntityIds);",
  "    const writes = [];",
  "    const sceneIds = [];",
  "    for (const scene of normalizedScenes) {",
  "      signal.throwIfAborted();",
  "      const sceneLocalId = scene.id.split(':')[1];",
  "      const sceneFile = { id: scene.id, name: scene.name, location: scene.location, present: scene.present, status: 'active', updatedTurn: 0, updatedBy: 'world-architect', updatedAt: committedAt };",
  "      const file = await tsian.workspace.write({ scope: 'save-runtime', path: 'save/scenes/' + sceneLocalId + '.json', content: JSON.stringify(sceneFile, null, 2) + '\\n', mediaType: 'application/json' });",
  "      writes.push({ path: file.path, size: file.content.length });",
  "      sceneIds.push(scene.id);",
  "    }",
  "    for (const rel of relationships) {",
  "      signal.throwIfAborted();",
  "      const file = await tsian.workspace.write({ scope: 'save-runtime', path: 'save/relationships/' + rel.scope + '.json', content: JSON.stringify({ subject: rel.subject, edges: rel.edges, updatedTurn: 0, updatedBy: 'world-architect' }, null, 2) + '\\n', mediaType: 'application/json' });",
  "      writes.push({ path: file.path, size: file.content.length });",
  "    }",
  "    tsian.trace('opening_scenes_and_relationships_committed', { sceneCount: sceneIds.length, relationshipCount: relationships.length, writes: writes.map((w) => w.path) });",
  "    return { status: 'ready', writes, sceneCount: sceneIds.length, sceneIds, relationshipCount: relationships.length };",
  "  } catch (error) {",
  "    tsian.trace('opening_scenes_and_relationships_commit_failed', { code: error && error.code || 'OPENING_COMMIT_FAILED', message: error && error.message || String(error), details: error && error.details });",
  "    throw error;",
  "  }",
  "}",
  "return commitScenesAndRelationships(input, tsian, signal);",
])}`

// commit_runtime_and_frontier — 合并 runtime + frontier，一次写入开局状态。
// input: { runtime: {turn, worldTime?, weather?, location?, activeSceneRefs, protagonistRef?, extensions?}, frontier: {sourceWindow, extractedThrough?, notes?} }。
// output: { writes }。
export const COMMIT_RUNTIME_AND_FRONTIER_SCRIPT_JS = `${text([
  "async function commitRuntimeAndFrontier(input, tsian, signal) {",
  "  try {",
  "    signal.throwIfAborted();",
  "    if (!isRecord(input)) fail('OPENING_COMMIT_INVALID', 'Commit input must be an object.');",
  "    if (!isRecord(input.runtime)) fail('OPENING_RUNTIME_INVALID', 'runtime must be an object.');",
  "    if (!isRecord(input.frontier)) fail('OPENING_FRONTIER_INVALID', 'frontier must be an object.');",
  "    const writes = [];",
  "    // runtime 校验：activeSceneRefs → glob(save/scenes) + protagonistRef/location → loadExistingEntityIds",
  "    const turn = normalizePositiveInt(input.runtime.turn, 0, 0, 999999);",
  "    const worldTime = typeof input.runtime.worldTime === 'string' ? input.runtime.worldTime.trim() : '';",
  "    const weather = typeof input.runtime.weather === 'string' ? input.runtime.weather.trim() : '';",
  "    const activeSceneRefsRaw = Array.isArray(input.runtime.activeSceneRefs) ? input.runtime.activeSceneRefs : [];",
  "    if (activeSceneRefsRaw.length === 0) fail('OPENING_RUNTIME_ACTIVE_SCENES_REQUIRED', 'runtime.activeSceneRefs must list at least one scene ref.');",
  "    const sceneGlob = await tsian.workspace.glob({ scope: 'effective', pattern: 'save/scenes/*.json', limit: 10000 });",
  "    const sceneMatches = Array.isArray(sceneGlob && sceneGlob.matches) ? sceneGlob.matches : [];",
  "    const knownSceneLocalIds = new Set(sceneMatches.map((p) => p.slice('save/scenes/'.length).replace(/\\.json$/, '')));",
  "    const activeSceneRefs = [];",
  "    for (const raw of activeSceneRefsRaw) {",
  "      if (!isRecord(raw)) fail('OPENING_RUNTIME_SCENE_INVALID', 'activeSceneRefs entry must be an object { ref, name }.');",
  "      const parsed = normalizeEntityId(raw.ref, 'Active scene ref');",
  "      if (parsed.type !== 'scene') fail('OPENING_RUNTIME_SCENE_TYPE_INVALID', 'activeSceneRefs entry must use scene:<localId>.', { id: parsed.id });",
  "      if (!knownSceneLocalIds.has(parsed.localId)) fail('OPENING_RUNTIME_SCENE_UNKNOWN', 'activeSceneRefs entry must point to an existing scene file.', { id: parsed.id });",
  "      const name = normalizeString(raw.name, 'OPENING_RUNTIME_SCENE_NAME_REQUIRED', 'Active scene name', 120);",
  "      activeSceneRefs.push({ ref: parsed.id, name });",
  "    }",
  "    const knownEntityIds = await loadExistingEntityIds(tsian);",
  "    let protagonistRef = null;",
  "    if (input.runtime.protagonistRef) {",
  "      if (!isRecord(input.runtime.protagonistRef)) fail('OPENING_RUNTIME_PROTAGONIST_INVALID', 'runtime.protagonistRef must be an object { ref, name }.');",
  "      const parsed = normalizeEntityId(input.runtime.protagonistRef.ref, 'Protagonist ref');",
  "      if (!knownEntityIds.has(parsed.id)) fail('OPENING_RUNTIME_PROTAGONIST_UNKNOWN', 'protagonistRef must point to an existing entity.', { ref: parsed.id });",
  "      const name = normalizeString(input.runtime.protagonistRef.name, 'OPENING_RUNTIME_PROTAGONIST_NAME_REQUIRED', 'Protagonist name', 120);",
  "      protagonistRef = { ref: parsed.id, name };",
  "    }",
  "    let location = null;",
  "    if (input.runtime.location) {",
  "      if (!isRecord(input.runtime.location)) fail('OPENING_RUNTIME_LOCATION_INVALID', 'runtime.location must be an object { ref, name }.');",
  "      const parsed = normalizeEntityId(input.runtime.location.ref, 'Runtime location ref');",
  "      if (!knownEntityIds.has(parsed.id)) fail('OPENING_RUNTIME_LOCATION_UNKNOWN', 'runtime.location must point to an existing entity.', { ref: parsed.id });",
  "      const name = normalizeString(input.runtime.location.name, 'OPENING_RUNTIME_LOCATION_NAME_REQUIRED', 'Runtime location name', 120);",
  "      location = { ref: parsed.id, name };",
  "    }",
  "    const rawExtensions = isRecord(input.runtime.extensions) ? input.runtime.extensions : {};",
  "    const extensions = {};",
  "    for (const key of Object.keys(rawExtensions)) { if (key.trim()) extensions[key] = rawExtensions[key]; }",
  "    const runtimeFile = { turn, worldTime, plotOrder: 1, location, weather, activeSceneRefs, protagonistRef, extensions, updatedAtTurn: turn, updatedBy: 'world-architect' };",
  "    // frontier 校验（先校验再写，避免 runtime 半成品落盘）：sourceWindow.chapters path → loadSource knownPaths",
  "    if (!isRecord(input.frontier.sourceWindow)) fail('OPENING_WINDOW_INVALID', 'frontier.sourceWindow must be an object.');",
  "    const source = await loadSource(tsian);",
  "    const knownPaths = new Set(source.chapters.map((chapter) => chapter.path));",
  "    const window = normalizeWindow(input.frontier.sourceWindow, knownPaths);",
  "    const extractedThrough = typeof input.frontier.extractedThrough === 'string' && input.frontier.extractedThrough.trim() ? input.frontier.extractedThrough.trim() : (window.chapters[window.chapters.length - 1] && window.chapters[window.chapters.length - 1].path) || null;",
  "    if (extractedThrough && !knownPaths.has(extractedThrough)) fail('OPENING_SOURCE_REF_UNKNOWN', 'frontier.extractedThrough must point to an imported chapter file.', { extractedThrough });",
  "    const notes = typeof input.frontier.notes === 'string' && input.frontier.notes.trim() ? input.frontier.notes.trim() : window.reason;",
  "    const timelineRaw = Array.isArray(input.frontier.timeline) ? input.frontier.timeline : [];",
  "    const timeline = timelineRaw.map(function (anchor, index) {",
  "      if (!isRecord(anchor)) fail('OPENING_TIMELINE_ANCHOR_INVALID', 'Each timeline anchor must be an object.', { index });",
  "      const chapter = normalizePositiveInt(anchor.chapter, 1, 1, 999999);",
  "      const time = normalizeString(anchor.time, 'OPENING_TIMELINE_TIME_REQUIRED', 'Timeline anchor time', 120);",
  "      const label = normalizeString(anchor.label, 'OPENING_TIMELINE_LABEL_REQUIRED', 'Timeline anchor label', 120);",
  "      return { kind: 'source', order: index + 1, chapter: chapter, time: time, label: label };",
  "    });",
  "    const frontierFile = { sourceWindow: { start: window.startIndex, end: window.endIndex, chapters: window.chapters }, extractedThrough, timeline, notes, updatedAt: new Date().toISOString(), updatedBy: 'world-architect' };",
  "    // 全部校验通过，统一写入 runtime 与 frontier",
  "    const runtimeWrite = await tsian.workspace.write({ scope: 'save-runtime', path: 'save/playthrough/runtime.json', content: JSON.stringify(runtimeFile, null, 2) + '\\n', mediaType: 'application/json' });",
  "    writes.push({ path: runtimeWrite.path, size: runtimeWrite.content.length });",
  "    const frontierWrite = await tsian.workspace.write({ scope: 'save-runtime', path: 'save/playthrough/frontier.json', content: JSON.stringify(frontierFile, null, 2) + '\\n', mediaType: 'application/json' });",
  "    writes.push({ path: frontierWrite.path, size: frontierWrite.content.length });",
  "    tsian.trace('opening_runtime_and_frontier_committed', { turn, activeSceneRefs: activeSceneRefs.map((r) => r.ref), protagonistRef: protagonistRef && protagonistRef.ref, location: location && location.ref, frontierStart: window.startIndex, frontierEnd: window.endIndex, extractedThrough, timelineAnchors: timeline.length, writes: writes.map((w) => w.path) });",
  "    return { status: 'ready', writes };",
  "  } catch (error) {",
  "    tsian.trace('opening_runtime_and_frontier_commit_failed', { code: error && error.code || 'OPENING_COMMIT_FAILED', message: error && error.message || String(error), details: error && error.details });",
  "    throw error;",
  "  }",
  "}",
  "return commitRuntimeAndFrontier(input, tsian, signal);",
])}`

// commit_understanding_summary — normalizeCandidate 校验 + 写 understanding-summary.json 为 {status:"ready", title, candidateCharacters}。
export const COMMIT_UNDERSTANDING_SUMMARY_SCRIPT_JS = `${text([
  "async function commitUnderstandingSummary(input, tsian, signal) {",
  "  try {",
  "    signal.throwIfAborted();",
  "    if (!isRecord(input)) fail('OPENING_COMMIT_INVALID', 'Commit input must be an object.');",
  "    const title = normalizeString(input.title, 'OPENING_SUMMARY_TITLE_REQUIRED', 'Summary title', 120);",
  "    const candidatesRaw = Array.isArray(input.candidateCharacters) ? input.candidateCharacters : null;",
  "    if (candidatesRaw === null) fail('OPENING_CANDIDATES_REQUIRED', 'candidateCharacters field is required (may be empty array).');",
  "    const candidateCharacters = candidatesRaw.map(normalizeCandidate);",
  "    const summaryFile = { status: 'ready', title, candidateCharacters };",
  "    const file = await tsian.workspace.write({ scope: 'save-runtime', path: 'save/playthrough/understanding-summary.json', content: JSON.stringify(summaryFile, null, 2) + '\\n', mediaType: 'application/json' });",
  "    tsian.trace('opening_understanding_summary_committed', { title, candidateCount: candidateCharacters.length, write: file.path });",
  "    return { status: 'ready', write: { path: file.path, size: file.content.length } };",
  "  } catch (error) {",
  "    tsian.trace('opening_understanding_summary_commit_failed', { code: error && error.code || 'OPENING_COMMIT_FAILED', message: error && error.message || String(error), details: error && error.details });",
  "    throw error;",
  "  }",
  "}",
  "return commitUnderstandingSummary(input, tsian, signal);",
])}`

// commit_play_setup — Step 4 收尾单一 action（task 07-15）。
// 一次校验并写入主角 traits[]、setup-summary.json、turn 0 history 与玩家回合 Agent context seed。
// 返回值不含 opening reply 正文，避免 Step 4 UI 提前展示。
// 复用 _common.js（isRecord/fail/parseJson/readJson）与 _validation.js（normalizeString/normalizeEntityId）。
export const COMMIT_PLAY_SETUP_SCRIPT_JS = `${text([
  "function normalizePlayerTurnAgentId(value) {",
  "  const agentId = normalizeString(value, 'OPENING_PLAYER_TURN_AGENT_REQUIRED', 'playerTurn agent id', 120);",
  "  if (agentId === '.' || agentId === '..' || agentId.includes('/') || agentId.includes('\\\\') || agentId.includes('\\0')) fail('OPENING_PLAYER_TURN_AGENT_INVALID', 'playerTurn agent id must be a safe path segment.', { agentId });",
  "  return agentId;",
  "}",
  "async function resolvePlayerTurnAgentId(tsian) {",
  "  const manifest = await readJson(tsian, 'game-card.json');",
  "  const runtime = isRecord(manifest.runtime) ? manifest.runtime : null;",
  "  const entrypoints = runtime && isRecord(runtime.entrypoints) ? runtime.entrypoints : null;",
  "  return normalizePlayerTurnAgentId(entrypoints && entrypoints.playerTurn);",
  "}",
  "function formatTurn0Path() { return 'save/history/turns/turn-000000.json'; }",
  "function formatAgentContextPath(agentId) { return 'save/agents/' + agentId + '/context.json'; }",
  "async function commitPlaySetup(input, tsian, signal) {",
  "  try {",
  "    signal.throwIfAborted();",
  "    if (!isRecord(input)) fail('OPENING_COMMIT_INVALID', 'Commit input must be an object.');",
  "    // 1. 校验 protagonistRef 指向已存在 character entity",
  "    const protagonistRef = normalizeString(input.protagonistRef, 'OPENING_PROTAGONIST_REF_REQUIRED', 'protagonistRef', 120);",
  "    const parsedRef = normalizeEntityId(protagonistRef, 'protagonistRef');",
  "    if (parsedRef.type !== 'character') fail('OPENING_PROTAGONIST_REF_INVALID', 'protagonistRef must use character:<localId>.', { ref: parsedRef.id });",
  "    const entityPath = 'save/entities/character/' + parsedRef.localId + '.json';",
  "    const entityFile = await tsian.workspace.read({ scope: 'effective', path: entityPath });",
  "    if (!entityFile || typeof entityFile.content !== 'string') fail('OPENING_PROTAGONIST_ENTITY_MISSING', 'protagonistRef must point to an existing character entity.', { ref: parsedRef.id, path: entityPath });",
  "    let protagonist = parseJson(entityFile.content, entityPath);",
  "    if (!isRecord(protagonist)) fail('OPENING_PROTAGONIST_ENTITY_INVALID', 'Protagonist entity must be a JSON object.', { ref: parsedRef.id });",
  "    // 2. 校验 summary 非空 ≤2000",
  "    const summary = normalizeString(input.summary, 'OPENING_SETUP_SUMMARY_REQUIRED', 'summary', 2000);",
  "    // 3. 校验 openingReply 非空（开局正文；投影后作为 assistant 回复落盘）",
  "    const openingReply = normalizeString(input.openingReply, 'OPENING_REPLY_REQUIRED', 'openingReply', 24000);",
  "    // 4. 解析玩家正式回合入口 Agent id；必须在任何写入前 fail loud。",
  "    const playerTurnAgentId = await resolvePlayerTurnAgentId(tsian);",
  "    const turn0Path = formatTurn0Path();",
  "    const contextPath = formatAgentContextPath(playerTurnAgentId);",
  "    // 5. 校验 traits[] 每项 id（trait:<localId>）+ name 必填，description/effects 可选",
  "    const rawTraits = Array.isArray(input.traits) ? input.traits : [];",
  "    const normalizedTraits = [];",
  "    const traitIds = new Set();",
  "    for (let i = 0; i < rawTraits.length; i++) {",
  "      const raw = rawTraits[i];",
  "      if (!isRecord(raw)) fail('PLAY_SETUP_TRAIT_INVALID', 'Each trait must be an object.', { index: i });",
  "      const traitId = normalizeString(raw.id, 'PLAY_SETUP_TRAIT_ID_REQUIRED', 'trait id', 120);",
  "      const traitName = normalizeString(raw.name, 'PLAY_SETUP_TRAIT_NAME_REQUIRED', 'trait name', 120);",
  "      if (!traitId.startsWith('trait:')) fail('PLAY_SETUP_TRAIT_ID_INVALID', 'trait id must use trait:<localId>.', { id: traitId, index: i });",
  "      if (traitIds.has(traitId)) fail('PLAY_SETUP_TRAIT_ID_DUPLICATE', 'Duplicate trait id in this commit.', { id: traitId, index: i });",
  "      traitIds.add(traitId);",
  "      const trait = { id: traitId, name: traitName };",
  "      if (typeof raw.description === 'string' && raw.description.trim()) trait.description = raw.description.trim();",
  "      if (Array.isArray(raw.effects)) {",
  "        const effects = [];",
  "        for (const e of raw.effects) { if (typeof e === 'string' && e.trim()) effects.push(e.trim()); }",
  "        if (effects.length > 0) trait.effects = effects;",
  "      }",
  "      normalizedTraits.push(trait);",
  "    }",
  "    // 6. read-modify-write 主角 entity：合并 traits（按 id 去重覆盖，保留其他字段）",
  "    const existingTraits = Array.isArray(protagonist.traits) ? protagonist.traits.filter((t) => isRecord(t) && typeof t.id === 'string') : [];",
  "    const mergedById = new Map();",
  "    for (const t of existingTraits) { mergedById.set(t.id, t); }",
  "    for (const t of normalizedTraits) { mergedById.set(t.id, t); }",
  "    const mergedTraits = Array.from(mergedById.values());",
  "    const updatedEntity = { ...protagonist, traits: mergedTraits };",
  "    const now = new Date().toISOString();",
  "    const projectedAssistant = await tsian.reply.project(openingReply);",
  "    const assistantContent = projectedAssistant && typeof projectedAssistant.content === 'string' ? projectedAssistant.content : openingReply;",
  "    const assistantItem = { kind: 'assistant', content: assistantContent };",
  "    if (projectedAssistant && typeof projectedAssistant.displayContent === 'string') assistantItem.displayContent = projectedAssistant.displayContent;",
  "    if (projectedAssistant && isRecord(projectedAssistant.projections)) assistantItem.projections = projectedAssistant.projections;",
  "    const turn0Record = { schema: 'tsian.airp.history.turn.v2', turn: 0, createdAt: now, source: { kind: 'agent-runtime', entryAgentId: playerTurnAgentId }, timeline: [assistantItem] };",
  "    const contextFile = { schema: 'tsian.agent.context.v1', saveId: '', agentId: playerTurnAgentId, summary: null, recentTurns: [{ turn: 0, role: 'assistant', content: assistantContent }], lastCompressedTurn: null, updatedAt: now };",
  "    const entityWrite = await tsian.workspace.write({ scope: 'save-runtime', path: entityPath, content: JSON.stringify(updatedEntity, null, 2) + '\\n', mediaType: 'application/json' });",
  "    // 7. 写 setup-summary.json = { status: 'complete', summary, committedAt, enteredPlay:false }",
  "    const summaryFile = { status: 'complete', summary, committedAt: now, enteredPlay: false };",
  "    const summaryWrite = await tsian.workspace.write({ scope: 'save-runtime', path: 'save/playthrough/setup-summary.json', content: JSON.stringify(summaryFile, null, 2) + '\\n', mediaType: 'application/json' });",
  "    // 8. 写 turn 0 history 与玩家回合 Agent context seed",
  "    const turn0Write = await tsian.workspace.write({ scope: 'save-runtime', path: turn0Path, content: JSON.stringify(turn0Record, null, 2) + '\\n', mediaType: 'application/json' });",
  "    const contextWrite = await tsian.workspace.write({ scope: 'save-runtime', path: contextPath, content: JSON.stringify(contextFile, null, 2) + '\\n', mediaType: 'application/json' });",
  "    const writes = [",
  "      { path: entityWrite.path, size: entityWrite.content.length, kind: 'traits' },",
  "      { path: summaryWrite.path, size: summaryWrite.content.length, kind: 'setup-summary' },",
  "      { path: turn0Write.path, size: turn0Write.content.length, kind: 'history-turn' },",
  "      { path: contextWrite.path, size: contextWrite.content.length, kind: 'agent-context' },",
  "    ];",
  "    tsian.trace('play_setup_committed', { protagonistRef: parsedRef.id, playerTurnAgentId, traitCount: normalizedTraits.length, writes: writes.map((w) => w.path) });",
  "    // 9. 返回 { status: 'ready', writes }，不含 opening reply 正文，避免 Step 4 UI 提前展示",
  "    return { status: 'ready', writes };",
  "  } catch (error) {",
  "    tsian.trace('play_setup_commit_failed', { code: error && error.code || 'OPENING_COMMIT_FAILED', message: error && error.message || String(error), details: error && error.details });",
  "    throw error;",
  "  }",
  "}",
  "return commitPlaySetup(input, tsian, signal);",
])}`
