export const DEFAULT_WORKSPACE_VERSION = 17
export const WORKSPACE_MANIFEST_PATH = ".tsian/manifest.json"

export const DEFAULT_SAVE_RUNTIME_UPGRADE_FILE_PATHS = new Set([
  "save/README.md",
  "save/agents/storyteller/notes.md",
  "save/agents/storyteller/writing-styles.md",
  "save/agents/storyteller/writing-rules.md",
  "save/agents/stage-manager/notes.md",
  "save/agents/world-architect/notes.md",
  "save/history/README.md",
  "save/history/turns/README.md",
  "save/memory/README.md",
  "save/memory/seeds.md",
  "save/source/README.md",
  "save/source/manifest.json",
  "save/schema/README.md",
  "save/schema/current.md",
  "save/schema/changelog.md",
  "save/schema/deprecated.md",
  "save/schema/patches/pending/README.md",
  "save/schema/patches/applied/README.md",
  "save/entities/README.md",
  "save/scenes/README.md",
  "save/relationships/README.md",
  "save/playthrough/README.md",
  "save/playthrough/runtime.json",
  "save/playthrough/player.json",
  "save/playthrough/frontier.json",
  "save/playthrough/understanding-summary.json",
  "save/playthrough/setup-summary.json",
  "save/playthrough/branch.json",
])
