import type { GameCardFrontendBinding } from "@tsian/contracts"
import type { PutLocalGameCardFrontendFileInput } from "./game-cards"
// Vendor 机制：第三方库源码通过 Vite ?raw 内联为字符串，作为额外 packaged 文件。
// index.html 用 <script src="vendor/xxx.js" defer> 加载，app.js 用 window.xxx 访问。
// 这是 packaged 前端引入第三方库的标准范式——玩家自定义前端可同样 vendor
// Three.js/PixiJS/Chart.js 等实现任意前端效果。助手 fork 时一并带走。
import markedUmdSource from "marked/marked.min.js?raw"

/**
 * Packaged frontend binding for the default lightweight AIRP frontend.
 * Bound to template cards created via `createDefaultPlatformGameCard`.
 */
export const DEFAULT_FRONTEND_BINDING: GameCardFrontendBinding = {
  kind: "packaged",
  entry: "frontend/index.html",
  bridgeVersion: "tsian.play-bridge.v1",
}

// ════════════════════════════════════════════════════════════════
// index.html — 骨架
// 结构：header(标题+状态栏+操作区占位) + main(正文区+过程区) + footer(输入区)
// 过程节点(thought/tool/interim)由 app.js 动态生成在 #story 内按发生顺序。
// ════════════════════════════════════════════════════════════════

const FRONTEND_INDEX_HTML = [
  "<!DOCTYPE html>",
  '<html lang="zh-CN">',
  "<head>",
  '  <meta charset="UTF-8" />',
  '  <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
  "  <title>Tsian 游戏前端</title>",
  '  <link rel="stylesheet" href="style.css" />',
  "  <!-- vendor 库：marked UMD，<script defer> 在 app.js 之前加载，app.js 用 window.marked -->",
  '  <script src="vendor/marked.umd.js" defer></script>',
  '  <script src="app.js" defer></script>',
  "</head>",
  "<body>",
  '  <div id="app" class="app">',
  "    <header class=\"app-header\">",
  "      <div class=\"header-left\">",
  "        <span class=\"app-title\">Tsian</span>",
  "        <span id=\"status\" class=\"app-status\" data-state=\"loading\">连接中…</span>",
  "      </div>",
  "      <div class=\"header-right\">",
  "        <span id=\"turn-badge\" class=\"turn-badge\" hidden>第 <b id=\"turn-num\">0</b> 回</span>",
  "        <!-- UI 操作区占位：检查点回溯等功能后续接线，本任务只留位置 -->",
  "        <button id=\"btn-checkpoint\" class=\"header-btn\" type=\"button\" disabled title=\"功能开发中\">回溯</button>",
  "      </div>",
  "    </header>",
  "    <main id=\"story\" class=\"story\" aria-live=\"polite\">",
  '      <div class="empty-state" id="empty-state">',
  "        <p class=\"empty-title\">故事尚未开始</p>",
  "        <p class=\"empty-hint\">在下方输入你的行动，开启冒险。</p>",
  "      </div>",
  "    </main>",
  "    <footer class=\"composer\">",
  "      <textarea id=\"input\" class=\"input\" rows=\"1\" placeholder=\"输入你的行动…（Enter 发送，Shift+Enter 换行）\" disabled></textarea>",
  "      <button id=\"send\" class=\"send\" type=\"button\" disabled>讲述</button>",
  "      <button id=\"stop\" class=\"stop\" type=\"button\" hidden>停止</button>",
  "    </footer>",
  "  </div>",
  "</body>",
  "</html>",
  "",
].join("\n")

// ════════════════════════════════════════════════════════════════
// style.css — 视觉风格：烛火书卷（Lamplight Codex）
// 调性：深褐黑底 + 烛光暖金强调 + 衬线正文字体 + 旧书阅读氛围。
// 与平台 retro OS（霓虹黄/CRT/等宽）区隔——游戏前端是独立"应用"。
// 记忆点：正文区羊皮纸纹理感（CSS gradient 模拟，无图片）+ 烛光暖金强调。
// ════════════════════════════════════════════════════════════════

const FRONTEND_STYLE_CSS = [
  "/* Tsian AIRP frontend — Lamplight Codex: 烛火书卷 */",
  ":root {",
  "  --ink: #14110d;            /* 深褐黑底 */",
  "  --parchment: #1c1812;       /* 羊皮纸深色 */",
  "  --parchment-elev: #252017;  /* 羊皮纸提升 */",
  "  --ember: #d4a24c;           /* 烛光暖金 */",
  "  --ember-deep: #8a6628;      /* 暖金深 */",
  "  --ember-dim: #6b5a3e;       /* 暖金暗 */",
  "  --prose: #e8dcc4;           /* 正文色（羊皮纸上的字） */",
  "  --prose-dim: #a89a7e;       /* 正文暗 */",
  "  --whisper: #6f6553;         /* 低语灰褐 */",
  "  --blood: #a64942;           /* 危险/错误 */",
  "  --gold-glow: rgba(212, 162, 76, 0.12);",
  "  --serif: \"Noto Serif SC\", \"Source Han Serif SC\", \"Songti SC\", Georgia, \"Times New Roman\", serif;",
  "  --mono: \"JetBrains Mono\", \"SF Mono\", Consolas, monospace;",
  "}",
  "",
  "* { box-sizing: border-box; }",
  "html, body { margin: 0; padding: 0; height: 100%; }",
  "body {",
  "  background: var(--ink);",
  "  color: var(--prose);",
  "  font-family: var(--serif);",
  "  font-size: 16px;",
  "  line-height: 1.8;",
  "  -webkit-font-smoothing: antialiased;",
  "}",
  "",
  "/* ── 布局 ── */",
  ".app { display: flex; flex-direction: column; height: 100vh; min-height: 0; }",
  "",
  "/* ── Header ── */",
  ".app-header {",
  "  display: flex; align-items: center; justify-content: space-between;",
  "  padding: 10px 20px; border-bottom: 1px solid var(--ember-deep);",
  "  background: var(--parchment); flex: 0 0 auto;",
  "}",
  ".header-left { display: flex; align-items: baseline; gap: 14px; }",
  ".app-title {",
  "  font-family: var(--serif); font-weight: 700; font-size: 18px;",
  "  color: var(--ember); letter-spacing: 0.08em;",
  "}",
  ".app-status {",
  "  font-family: var(--mono); font-size: 11px; color: var(--whisper);",
  "  letter-spacing: 0.1em; text-transform: uppercase;",
  "}",
  ".app-status[data-state=\"ready\"] { color: var(--ember); }",
  ".app-status[data-state=\"busy\"] { color: var(--ember-deep); }",
  ".app-status[data-state=\"error\"] { color: var(--blood); }",
  ".header-right { display: flex; align-items: center; gap: 10px; }",
  ".turn-badge {",
  "  font-family: var(--mono); font-size: 11px; color: var(--ember-deep);",
  "  border: 1px solid var(--ember-deep); padding: 2px 8px;",
  "}",
  ".turn-badge b { color: var(--ember); font-weight: 700; }",
  ".header-btn {",
  "  font-family: var(--mono); font-size: 11px; color: var(--whisper);",
  "  border: 1px solid var(--ember-deep); background: transparent;",
  "  padding: 3px 10px; cursor: pointer; letter-spacing: 0.08em;",
  "}",
  ".header-btn:hover:not(:disabled) { color: var(--ember); border-color: var(--ember); }",
  ".header-btn:disabled { opacity: 0.35; cursor: not-allowed; }",
  "",
  "/* ── Story 正文区 ── */",
  ".story {",
  "  flex: 1 1 auto; min-height: 0; overflow-y: auto; padding: 28px 20px;",
  "  scrollbar-width: thin; scrollbar-color: var(--ember-deep) var(--parchment);",
  "}",
  ".story::-webkit-scrollbar { width: 8px; }",
  ".story::-webkit-scrollbar-track { background: var(--parchment); }",
  ".story::-webkit-scrollbar-thumb { background: var(--ember-deep); }",
  "",
  "/* 正文容器：居中限宽，小说阅读感 */",
  ".story-inner { max-width: 42em; margin: 0 auto; }",
  "",
  "/* ── 消息渲染 ── */",
  "/* 剧情正文（AI 回复）：无气泡无强边框，小说式排版 */",
  ".msg-role {",
  "  font-family: var(--mono); font-size: 10px; color: var(--whisper);",
  "  letter-spacing: 0.2em; text-transform: uppercase; margin-bottom: 4px;",
  "}",
  ".narrative {",
  "  margin: 0 0 1.6em; padding: 0;",
  "}",
  ".narrative .msg-role { color: var(--ember-deep); }",
  "",
  "/* 用户消息：左竖线 + 淡背景，轻量区分非气泡 */",
  ".user-msg {",
  "  margin: 1.4em 0; padding: 10px 16px;",
  "  border-left: 3px solid var(--ember-deep);",
  "  background: var(--parchment-elev);",
  "}",
  ".user-msg .msg-role { color: var(--ember); }",
  ".user-msg .msg-body { white-space: pre-wrap; color: var(--prose); }",
  "",
  "/* ── 过程节点（thought/tool/interim）── */",
  "/* 过程元信息：左竖线 + 淡背景 + 小字号，与正文视觉分离 */",
  ".process-node {",
  "  margin: 0.5em 0; padding: 8px 14px;",
  "  border-left: 2px solid var(--ember-deep);",
  "  background: rgba(212, 162, 76, 0.04);",
  "  font-size: 13px; line-height: 1.6;",
  "}",
  ".process-node.interim { border-left-color: var(--whisper); background: transparent; }",
  ".process-node.thought { border-left-color: var(--ember-dim); }",
  ".process-node.tool { border-left-color: var(--ember-deep); }",
  ".process-node.tool.failed { border-left-color: var(--blood); }",
  "",
  ".process-head {",
  "  display: flex; align-items: center; gap: 8px; cursor: pointer;",
  "  font-family: var(--mono); font-size: 11px; color: var(--whisper);",
  "  letter-spacing: 0.06em; user-select: none;",
  "}",
  ".process-head:hover { color: var(--ember); }",
  ".process-head .agent-tag { color: var(--ember-deep); font-weight: 700; }",
  ".process-head .glyph { color: var(--ember); font-size: 10px; }",
  ".process-head .toggle { color: var(--whisper); font-size: 9px; transition: transform 0.15s; }",
  ".process-head .status-icon { margin-left: auto; }",
  ".process-head .status-icon.running { color: var(--ember-deep); }",
  ".process-head .status-icon.success { color: var(--ember); }",
  ".process-head .status-icon.failed { color: var(--blood); }",
  ".process-node.expanded .toggle { transform: rotate(90deg); }",
  ".process-body {",
  "  margin-top: 6px; padding-left: 4px;",
  "  color: var(--prose-dim); font-size: 12px; line-height: 1.5;",
  "  white-space: pre-wrap; word-wrap: break-word;",
  "}",
  ".process-node.collapsed .process-body { display: none; }",
  "",
  "/* ── markdown 渲染（prose）── */",
  ".prose p { margin: 0 0 0.8em; }",
  ".prose p:last-child { margin-bottom: 0; }",
  ".prose h1, .prose h2, .prose h3, .prose h4 {",
  "  margin: 1.2em 0 0.4em; color: var(--ember); font-weight: 700; line-height: 1.3;",
  "}",
  ".prose h1 { font-size: 1.3em; } .prose h2 { font-size: 1.15em; }",
  ".prose h3 { font-size: 1.05em; } .prose h4 { font-size: 0.95em; color: var(--ember-deep); }",
  ".prose h1:first-child, .prose h2:first-child, .prose h3:first-child, .prose h4:first-child { margin-top: 0; }",
  ".prose ul, .prose ol { margin: 0.5em 0 0.8em; padding-left: 1.6em; }",
  ".prose li { margin: 0.2em 0; }",
  ".prose ul { list-style: disc; } .prose ol { list-style: decimal; }",
  ".prose a { color: var(--ember); text-decoration: underline; text-underline-offset: 2px; }",
  ".prose a:hover { filter: brightness(1.2); }",
  ".prose strong { color: var(--ember); font-weight: 700; }",
  ".prose em { font-style: italic; color: var(--prose); }",
  ".prose blockquote {",
  "  margin: 0.8em 0; padding: 0.2em 1em; border-left: 2px solid var(--ember-deep);",
  "  color: var(--prose-dim); font-style: italic;",
  "}",
  ".prose blockquote p { margin: 0.3em 0; }",
  ".prose hr { margin: 1.2em 0; border: 0; border-top: 1px solid var(--ember-deep); }",
  ".prose code {",
  "  font-family: var(--mono); font-size: 0.85em; padding: 0.1em 0.35em;",
  "  background: var(--parchment-elev); color: var(--ember);",
  "}",
  ".prose pre {",
  "  margin: 0.8em 0; padding: 0.8em 1em; overflow-x: auto;",
  "  background: var(--ink); border: 1px solid var(--ember-deep);",
  "}",
  ".prose pre code { padding: 0; background: transparent; color: var(--prose); font-size: 0.85em; }",
  ".prose table { width: 100%; margin: 0.8em 0; border-collapse: collapse; font-size: 0.9em; }",
  ".prose th, .prose td { padding: 0.4em 0.7em; border: 1px solid var(--ember-deep); text-align: left; }",
  ".prose th { background: var(--gold-glow); color: var(--ember); font-weight: 700; }",
  "",
  "/* ── 流式 ── */",
  ".streaming-msg { color: var(--prose); }",
  ".streaming-msg::after {",
  "  content: '▌'; color: var(--ember); animation: cursor-blink 1s step-start infinite;",
  "  margin-left: 2px; font-size: 0.8em;",
  "}",
  "@keyframes cursor-blink { 50% { opacity: 0; } }",
  "",
  "/* ── 空状态 ── */",
  ".empty-state { text-align: center; padding: 60px 20px; color: var(--whisper); }",
  ".empty-title {",
  "  font-family: var(--serif); font-size: 1.1em; color: var(--ember-deep);",
  "  margin: 0 0 0.5em; letter-spacing: 0.1em;",
  "}",
  ".empty-hint { font-size: 0.9em; margin: 0; }",
  "",
  "/* ── Composer 输入区 ── */",
  ".composer {",
  "  flex: 0 0 auto; display: flex; gap: 10px; padding: 14px 20px;",
  "  border-top: 1px solid var(--ember-deep); background: var(--parchment);",
  "}",
  ".input {",
  "  flex: 1 1 auto; resize: none; min-height: 44px; max-height: 160px;",
  "  background: var(--parchment-elev); color: var(--prose);",
  "  border: 1px solid var(--ember-deep); padding: 10px 14px;",
  "  font-family: var(--serif); font-size: 15px; line-height: 1.6; outline: none;",
  "}",
  ".input:focus { border-color: var(--ember); box-shadow: 0 0 0 1px var(--gold-glow); }",
  ".input::placeholder { color: var(--whisper); font-style: italic; }",
  ".input:disabled { opacity: 0.5; }",
  ".send, .stop {",
  "  flex: 0 0 auto; padding: 0 22px; background: var(--ember-deep); color: var(--ink);",
  "  border: 1px solid var(--ember); cursor: pointer;",
  "  font-family: var(--serif); font-size: 14px; font-weight: 700; letter-spacing: 0.08em;",
  "}",
  ".send:hover:not(:disabled), .stop:hover:not(:disabled) { background: var(--ember); }",
  ".send:disabled, .stop:disabled { opacity: 0.35; cursor: not-allowed; }",
  ".stop { background: var(--blood); border-color: var(--blood); color: var(--prose); }",
  ".stop:hover:not(:disabled) { filter: brightness(1.15); }",
  "",
  "/* ── 响应式 ── */",
  "@media (max-width: 640px) {",
  "  .app-header { padding: 8px 14px; }",
  "  .header-left { gap: 8px; }",
  "  .app-title { font-size: 16px; }",
  "  .story { padding: 20px 14px; }",
  "  .story-inner { max-width: 100%; }",
  "  .composer { padding: 10px 14px; gap: 8px; }",
  "  .send, .stop { padding: 0 16px; }",
  "  .turn-badge { display: none; }",
  "}",
  "",
].join("\n")

// ════════════════════════════════════════════════════════════════
// app.js — 协议层 + 表现层（清晰隔离）
// ════════════════════════════════════════════════════════════════

const FRONTEND_APP_JS = [
  '"use strict";',
  "",
  "// ════════════════════════════════════════════════════════════════",
  "// 协议层（Bridge Layer）",
  "// 桥协议握手 / RPC 传输 / 事件订阅 / 状态暴露。",
  "// 未来抽为 packages/play-bridge 的 useBridge。助手 fork 时",
  "// 这块原样保留，只改表现层。表现层不碰 postMessage / RPC id。",
  "// ════════════════════════════════════════════════════════════════",
  "",
  'const CHANNEL = "tsian.play-bridge.v1";',
  "let sessionId = null;",
  "let nextReqId = 1;",
  "const pending = new Map();",
  "let bridgeReady = false;",
  "",
  "// 协议层对外回调（表现层通过 setEventHandlers 注册）",
  "const handlers = { onReady: null, onEvent: null, onSnapshot: null };",
  "",
  "function setEventHandlers(h) {",
  "  handlers.onReady = h.onReady || null;",
  "  handlers.onEvent = h.onEvent || null;",
  "  handlers.onSnapshot = h.onSnapshot || null;",
  "}",
  "",
  "// RPC: call(method, params) → Promise。表现层只用这个调平台能力。",
  "function call(method, params) {",
  "  const id = String(nextReqId++);",
  "  return new Promise(function (resolve, reject) {",
  "    pending.set(id, { resolve: resolve, reject: reject });",
  "    window.parent.postMessage({",
  "      channel: CHANNEL, kind: \"request\", sessionId: sessionId,",
  "      id: id, method: method, params: params,",
  "    }, \"*\");",
  "  });",
  "}",
  "",
  "// message 路由：按 kind 分发（协议层独占 addEventListener message）",
  "window.addEventListener(\"message\", function (e) {",
  "  const msg = e.data;",
  "  if (!msg || msg.channel !== CHANNEL) return;",
  "  if (msg.kind === \"ready\") {",
  "    sessionId = msg.sessionId;",
  "    bridgeReady = true;",
  "    handlers.onReady && handlers.onReady(sessionId);",
  "    return;",
  "  }",
  "  if (msg.kind === \"response\") {",
  "    const cb = pending.get(msg.id);",
  "    if (!cb) return;",
  "    pending.delete(msg.id);",
  "    if (msg.ok) cb.resolve(msg.result); else cb.reject(msg.error);",
  "    return;",
  "  }",
  "  if (msg.kind === \"event\") {",
  "    // turn-completed 的 payload.snapshot 触发覆盖渲染（§4 红线）",
  "    if (msg.event === \"turn-completed\" && msg.payload && msg.payload.snapshot) {",
  "      handlers.onSnapshot && handlers.onSnapshot(msg.payload.snapshot);",
  "    }",
  "    handlers.onEvent && handlers.onEvent(msg.event, msg.payload);",
  "    return;",
  "  }",
  "});",
  "",
  "// 启动握手：发 hello 给父窗口",
  "window.parent.postMessage({ channel: CHANNEL, kind: \"hello\" }, \"*\");",
  "",
  "// ════════════════════════════════════════════════════════════════",
  "// 表现层（Presentation Layer）",
  "// 消息渲染 / 流式 / 过程节点 / 状态栏 / 输入。助手地盘，自由改。",
  "// 只通过协议层 call() 和 setEventHandlers 与平台交互。",
  "// ════════════════════════════════════════════════════════════════",
  "",
  "// ── DOM 引用 ──",
  'const $status = document.getElementById("status");',
  'const $story = document.getElementById("story");',
  'const $input = document.getElementById("input");',
  'const $send = document.getElementById("send");',
  'const $stop = document.getElementById("stop");',
  'const $turnBadge = document.getElementById("turn-badge");',
  'const $turnNum = document.getElementById("turn-num");',
  'const $emptyState = document.getElementById("empty-state");',
  "",
  "// ── 回合状态机（移植自 useAssistantTimeline，原生 JS 版）──",
  "// timeline: 过程节点（thought/tool/interim），按发生顺序，带 agentId。",
  "let turnActive = false;",
  "let currentTurnEls = null;   // 当前回合的 DOM 容器（过程区 + 流式区）",
  "let turnState = null;        // 当前回合状态对象",
  "let userPinnedToBottom = true;",
  "",
  "function newTurnState() {",
  "  return { timeline: [], streamingText: \"\", streamingReasoning: \"\", content: \"\" };",
  "}",
  "",
  "// ── 工具函数 ──",
  "function setStatus(text, state) {",
  "  $status.textContent = text;",
  "  if (state) $status.setAttribute(\"data-state\", state);",
  "}",
  "",
  "function setTurn(num) {",
  "  if (typeof num === \"number\") {",
  "    $turnNum.textContent = String(num);",
  "    $turnBadge.hidden = false;",
  "  }",
  "}",
  "",
  "function scrollDown() { $story.scrollTop = $story.scrollHeight; }",
  "",
  "function maybeScrollDown() {",
  "  if (userPinnedToBottom) scrollDown();",
  "}",
  "",
  "$story.addEventListener(\"scroll\", function () {",
  "  const dist = $story.scrollHeight - $story.scrollTop - $story.clientHeight;",
  "  userPinnedToBottom = dist < 80;",
  "});",
  "",
  "// ── markdown 渲染（vendor marked）──",
  "function renderMarkdown(text) {",
  "  if (typeof window.marked !== \"undefined\") {",
  "    return window.marked.parse(text, { async: false });",
  "  }",
  "  // 降级：vendor 没加载时，至少 escape + 换行",
  "  return String(text).replace(/&/g, \"&amp;\").replace(/</g, \"&lt;\").replace(/>/g, \"&gt;\")",
  "    .replace(/\\n/g, \"<br>\");",
  "}",
  "",
  "// ── 消息渲染 ──",
  "function clearEmptyState() {",
  "  if ($emptyState && $emptyState.parentElement) $emptyState.remove();",
  "}",
  "",
  "// 渲染历史消息（from snapshot）",
  "function renderMessages(messages) {",
  "  clearEmptyState();",
  "  // 清掉流式回合残留，重建正文",
  "  $story.innerHTML = \"\";",
  "  const inner = document.createElement(\"div\");",
  "  inner.className = \"story-inner\";",
  "  if (!messages || messages.length === 0) {",
  "    const empty = document.createElement(\"div\");",
  "    empty.className = \"empty-state\";",
  "    empty.innerHTML = '<p class=\"empty-title\">故事尚未开始</p><p class=\"empty-hint\">在下方输入你的行动，开启冒险。</p>';",
  "    inner.appendChild(empty);",
  "  } else {",
  "    for (const m of messages) { inner.appendChild(renderMessageEl(m)); }",
  "  }",
  "  $story.appendChild(inner);",
  "  scrollDown();",
  "}",
  "",
  "// 单条消息 → DOM（剧情正文无气泡，用户消息左竖线）",
  "function renderMessageEl(m) {",
  "  if (m.role === \"user\") {",
  "    const div = document.createElement(\"div\");",
  "    div.className = \"user-msg\";",
  "    const role = document.createElement(\"div\"); role.className = \"msg-role\"; role.textContent = \"你\";",
  "    const body = document.createElement(\"div\"); body.className = \"msg-body\"; body.textContent = m.content;",
  "    div.appendChild(role); div.appendChild(body);",
  "    return div;",
  "  }",
  "  // assistant = 剧情正文",
  "  const div = document.createElement(\"div\");",
  "  div.className = \"narrative\";",
  "  const role = document.createElement(\"div\"); role.className = \"msg-role\"; role.textContent = m.role;",
  "  const body = document.createElement(\"div\"); body.className = \"msg-body prose\";",
  "  body.innerHTML = renderMarkdown(m.content || \"\");",
  "  div.appendChild(role); div.appendChild(body);",
  "  return div;",
  "}",
  "",
  "// ── 过程节点渲染 ──",
  "// 生成一个过程节点 DOM（thought/tool/interim），带 agentId 标签",
  "function createProcessNode(node) {",
  "  const div = document.createElement(\"div\");",
  "  div.className = \"process-node \" + node.type + (node.collapsed ? \" collapsed\" : \" expanded\");",
  "  if (node.type === \"tool\" && node.status === \"failed\") div.classList.add(\"failed\");",
  "  div.dataset.nodeId = node.id;",
  "",
  "  const head = document.createElement(\"div\"); head.className = \"process-head\";",
  "  // agentId 标签（agent 分流）",
  "  if (node.agentId) {",
  "    const tag = document.createElement(\"span\"); tag.className = \"agent-tag\"; tag.textContent = node.agentId;",
  "    head.appendChild(tag);",
  "    const dot = document.createElement(\"span\"); dot.className = \"glyph\"; dot.textContent = \"·\";",
  "    head.appendChild(dot);",
  "  }",
  "  // 折叠触发器（thought/tool 可折叠；interim 始终展开）",
  "  if (node.type === \"thought\" || node.type === \"tool\") {",
  "    const toggle = document.createElement(\"span\"); toggle.className = \"toggle\"; toggle.textContent = \"▶\";",
  "    head.appendChild(toggle);",
  "  }",
  "  const label = document.createElement(\"span\");",
  "  label.textContent = node.type === \"thought\" ? \"思考\" : node.type === \"tool\" ? (node.name || \"tool\") : \"\";",
  "  head.appendChild(label);",
  "  // tool 状态图标",
  "  if (node.type === \"tool\") {",
  "    const st = document.createElement(\"span\"); st.className = \"status-icon \" + node.status;",
  "    st.textContent = node.status === \"success\" ? \"✓\" : node.status === \"failed\" ? \"✗\" : \"▸\";",
  "    head.appendChild(st);",
  "  }",
  "  div.appendChild(head);",
  "",
  "  // body",
  "  const body = document.createElement(\"div\"); body.className = \"process-body\";",
  "  if (node.type === \"tool\" && node.output) { body.textContent = String(node.output).slice(0, 500); }",
  "  else if (node.text) { body.innerHTML = renderMarkdown(node.text); }",
  "  div.appendChild(body);",
  "",
  "  // 折叠交互",
  "  if (node.type === \"thought\" || node.type === \"tool\") {",
  "    head.addEventListener(\"click\", function () {",
  "      const collapsed = div.classList.toggle(\"collapsed\");",
  "      div.classList.toggle(\"expanded\", !collapsed);",
  "    });",
  "  }",
  "  return div;",
  "}",
  "",
  "// 按 callId 去重更新 tool 节点",
  "function upsertToolNode(timeline, payload) {",
  "  const existing = timeline.find(function (n) { return n.type === \"tool\" && n.id === payload.callId; });",
  "  if (existing) {",
  "    existing.status = payload.status;",
  "    if (payload.output !== undefined) existing.output = payload.output;",
  "    return existing;",
  "  }",
  "  const node = {",
  "    type: \"tool\", id: payload.callId, round: payload.round,",
  "    name: payload.name, status: payload.status, collapsed: false,",
  "    agentId: payload.agentId || null,",
  "  };",
  "  if (payload.output !== undefined) node.output = payload.output;",
  "  timeline.push(node);",
  "  return node;",
  "}",
  "",
  "// ── 回合 DOM 编排 ──",
  "// 开始一回合：创建过程区 + 流式正文区",
  "function beginTurn() {",
  "  clearEmptyState();",
  "  turnActive = true;",
  "  turnState = newTurnState();",
  "  // 确保有 story-inner 容器",
  "  let inner = $story.querySelector(\".story-inner\");",
  "  if (!inner) {",
  "    $story.innerHTML = \"\";",
  "    inner = document.createElement(\"div\"); inner.className = \"story-inner\";",
  "    $story.appendChild(inner);",
  "  }",
  "  // 过程区（过程节点按发生顺序追加）",
  "  const processZone = document.createElement(\"div\"); processZone.className = \"process-zone\";",
  "  inner.appendChild(processZone);",
  "  // 流式正文区",
  "  const streamEl = document.createElement(\"div\"); streamEl.className = \"narrative streaming-msg\";",
  "  const sbody = document.createElement(\"div\"); sbody.className = \"msg-body prose\";",
  "  streamEl.appendChild(sbody);",
  "  inner.appendChild(streamEl);",
  "  currentTurnEls = { processZone: processZone, streamEl: streamEl, streamBody: sbody };",
  "  maybeScrollDown();",
  "}",
  "",
  "// 渲染当前 timeline 的过程节点到过程区",
  "function renderProcessNodes() {",
  "  if (!currentTurnEls) return;",
  "  const zone = currentTurnEls.processZone;",
  "  zone.innerHTML = \"\";",
  "  for (const node of turnState.timeline) { zone.appendChild(createProcessNode(node)); }",
  "}",
  "",
  "// 流式正文更新",
  "function renderStreaming() {",
  "  if (!currentTurnEls || !turnState) return;",
  "  currentTurnEls.streamBody.innerHTML = renderMarkdown(turnState.streamingText);",
  "  maybeScrollDown();",
  "}",
  "",
  "// finalizeRound：镜像 useAssistantTimeline.onRoundEnd",
  "function finalizeRound(payload) {",
  "  const round = payload.round;",
  "  const kind = payload.kind;  // thought|final",
  "  const reasoning = turnState.streamingReasoning;",
  "  if (kind === \"thought\") {",
  "    // tool_calls 轮：过渡文本→interim，思维链→thought",
  "    const interimText = turnState.streamingText;",
  "    if (interimText.trim()) {",
  "      turnState.timeline.push({ type: \"interim\", id: \"interim-r\" + round, round: round, text: interimText, collapsed: false, agentId: payload.agentId || null });",
  "    }",
  "    if (reasoning.trim()) {",
  "      turnState.timeline.push({ type: \"thought\", id: \"thought-r\" + round, round: round, text: reasoning, collapsed: true, agentId: payload.agentId || null });",
  "    }",
  "  } else {",
  "    // 最终轮（stop）：思维链→thought，streamingText→content",
  "    if (reasoning.trim()) {",
  "      turnState.timeline.push({ type: \"thought\", id: \"thought-r\" + round, round: round, text: reasoning, collapsed: true, agentId: payload.agentId || null });",
  "    }",
  "    turnState.content = turnState.streamingText;",
  "  }",
  "  turnState.streamingReasoning = \"\";",
  "  turnState.streamingText = \"\";",
  "  renderProcessNodes();",
  "}",
  "",
  "// finalizeTurn：回合结束，折叠过程节点",
  "function finalizeTurn() {",
  "  if (turnState) {",
  "    for (const node of turnState.timeline) {",
  "      if (node.type === \"thought\" || node.type === \"tool\") node.collapsed = true;",
  "    }",
  "  }",
  "  renderProcessNodes();",
  "  turnActive = false;",
  "  // 流式区会在 onSnapshot 的 renderMessages 中被覆盖（§4 红线）",
  "}",
  "",
  "// ── 事件处理器（注册给协议层）──",
  "function handleEvent(event, payload) {",
  "  if (!turnActive || !turnState) return;  // 回合未开始忽略（兜底）",
  "  if (event === \"turn-delta\") {",
  "    if (payload.kind === \"reasoning\") {",
  "      turnState.streamingReasoning += payload.delta || \"\";",
  "    } else {",
  "      turnState.streamingText += payload.delta || \"\";",
  "      renderStreaming();",
  "    }",
  "    return;",
  "  }",
  "  if (event === \"turn-tool\") {",
  "    upsertToolNode(turnState.timeline, payload);",
  "    renderProcessNodes();",
  "    maybeScrollDown();",
  "    return;",
  "  }",
  "  if (event === \"turn-round-end\") {",
  "    finalizeRound(payload);",
  "    return;",
  "  }",
  "  // turn-completed 由 onSnapshot 处理（覆盖渲染）",
  "}",
  "",
  "// §4 红线：turn-completed.snapshot 到达时用 snapshot 覆盖渲染",
  "function handleSnapshot(snapshot) {",
  "  if (snapshot && snapshot.state) {",
  "    setTurn(snapshot.state.turn);",
  "    renderMessages(snapshot.state.messages || []);",
  "  }",
  "  finalizeTurn();",
  "  setSending(false);",
  "  setStatus(\"就绪\", \"ready\");",
  "}",
  "",
  "function handleReady(sid) {",
  "  setStatus(\"就绪\", \"ready\");",
  "  $send.disabled = false;",
  "  $input.disabled = false;",
  "  $input.focus();",
  "  // 初始拉取 snapshot",
  "  call(\"runtime.getRuntimeSnapshot\").then(function (snap) {",
  "    if (snap && snap.state) {",
  "      setTurn(snap.state.turn);",
  "      renderMessages(snap.state.messages || []);",
  "    }",
  "  }).catch(function () { setStatus(\"快照加载失败\", \"error\"); });",
  "}",
  "",
  "// ── 发送 ──",
  "function setSending(v) {",
  "  $send.disabled = v || !bridgeReady;",
  "  $input.disabled = v;",
  "  $stop.hidden = !v;",
  "  if (!v) $input.focus();",
  "}",
  "",
  "async function sendMessage() {",
  "  const content = $input.value.trim();",
  "  if (!content || !sessionId || turnActive) return;",
  "  $input.value = \"\";",
  "  $input.style.height = \"auto\";",
  "  setSending(true);",
  "  setStatus(\"回合进行中…\", \"busy\");",
  "  // 先把用户消息渲染出来",
  "  clearEmptyState();",
  "  let inner = $story.querySelector(\".story-inner\");",
  "  if (!inner) {",
  "    inner = document.createElement(\"div\"); inner.className = \"story-inner\";",
  "    $story.appendChild(inner);",
  "  }",
  "  inner.appendChild(renderMessageEl({ role: \"user\", content: content }));",
  "  scrollDown();",
  "  // 开始回合 DOM 编排",
  "  beginTurn();",
  "  try {",
  "    await call(\"interaction.sendMessage\", { content: content });",
  "    // turn-completed 事件会触发 handleSnapshot 覆盖渲染",
  "  } catch (e) {",
  "    finalizeTurn();",
  "    setSending(false);",
  "    const msg = (e && e.message) ? e.message : \"发送失败\";",
  "    setStatus(msg, \"error\");",
  "    // 错误时清掉空流式区",
  "    if (currentTurnEls && currentTurnEls.streamEl && !turnState.content) {",
  "      currentTurnEls.streamEl.remove();",
  "    }",
  "  }",
  "}",
  "",
  "// ── 输入交互 ──",
  "function autoGrow() {",
  "  $input.style.height = \"auto\";",
  "  const h = $input.scrollHeight;",
  "  $input.style.height = h <= 160 ? h + \"px\" : \"160px\";",
  "}",
  "",
  "$send.addEventListener(\"click\", sendMessage);",
  "$stop.addEventListener(\"click\", function () {",
  "  // 停止生成：本前端无直接 abort 桥方法，占位（后续接线）",
  "  // 当前依赖 turn-completed 自然结束",
  "});",
  "$input.addEventListener(\"keydown\", function (e) {",
  "  if (e.key === \"Enter\" && !e.shiftKey) { e.preventDefault(); sendMessage(); }",
  "});",
  "$input.addEventListener(\"input\", autoGrow);",
  "",
  "// ── 注册协议层回调 ──",
  "setEventHandlers({ onReady: handleReady, onEvent: handleEvent, onSnapshot: handleSnapshot });",
  "",
].join("\n")

/**
 * The default packaged frontend files, ready to inject into a game card's
 * `frontendFiles` via `putLocalGameCard`. Relative references in index.html
 * (`style.css`, `app.js`, `vendor/marked.umd.js`) resolve under the Service
 * Worker virtual prefix.
 */
export function defaultFrontendFiles(): PutLocalGameCardFrontendFileInput[] {
  return [
    { path: "frontend/index.html", data: FRONTEND_INDEX_HTML },
    { path: "frontend/style.css", data: FRONTEND_STYLE_CSS },
    { path: "frontend/app.js", data: FRONTEND_APP_JS },
    { path: "frontend/vendor/marked.umd.js", data: markedUmdSource },
  ]
}
