import type { GameCardFrontendBinding } from "@tsian/contracts"
import type { PutLocalGameCardFrontendFileInput } from "./game-cards"

/**
 * Packaged frontend binding for the default lightweight AIRP frontend.
 * Bound to template cards created via `createDefaultPlatformGameCard`.
 */
export const DEFAULT_FRONTEND_BINDING: GameCardFrontendBinding = {
  kind: "packaged",
  entry: "frontend/index.html",
  bridgeVersion: "tsian.play-bridge.v1",
}

const FRONTEND_INDEX_HTML = [
  "<!DOCTYPE html>",
  '<html lang="zh-CN">',
  "<head>",
  '  <meta charset="UTF-8" />',
  '  <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
  "  <title>Tsian 游戏前端</title>",
  '  <link rel="stylesheet" href="style.css" />',
  "</head>",
  "<body>",
  '  <div id="app" class="app">',
  '    <header class="app-header">',
  '      <span class="app-title">Tsian</span>',
  '      <span id="status" class="app-status">连接中…</span>',
  "    </header>",
  '    <main id="messages" class="messages" aria-live="polite"></main>',
  '    <div id="timeline" class="timeline" hidden></div>',
  '    <footer class="composer">',
  '      <textarea id="input" class="input" rows="2" placeholder="输入你的行动…（Enter 发送，Shift+Enter 换行）" disabled></textarea>',
  '      <button id="send" class="send" type="button" disabled>发送</button>',
  "    </footer>",
  "  </div>",
  '  <script src="app.js" defer></script>',
  "</body>",
  "</html>",
  "",
].join("\n")

const FRONTEND_STYLE_CSS = [
  "/* Tsian lightweight AIRP frontend — warm CRT brutalist, aligned with platform palette */",
  ":root {",
  "  --void: #203832;",
  "  --panel: #2c2a24;",
  "  --elevated: #3a352b;",
  "  --neon: #f3c56d;",
  "  --neon-deep: #9f7740;",
  "  --neon-muted: #8b8066;",
  "  --text-main: #f6ecd7;",
  "  --text-dim: #b9ad92;",
  "  --danger: #c84f5c;",
  "  --warning: #ffb454;",
  "}",
  "",
  "* { box-sizing: border-box; }",
  "html, body { margin: 0; padding: 0; height: 100%; }",
  "body {",
  "  background: var(--void);",
  "  color: var(--text-main);",
  '  font-family: \"JetBrains Mono\", \"Microsoft YaHei\", \"PingFang SC\", monospace;',
  "  font-size: 14px;",
  "  line-height: 1.6;",
  "}",
  "",
  ".app { display: flex; flex-direction: column; height: 100vh; min-height: 0; }",
  "",
  ".app-header {",
  "  display: flex; align-items: center; justify-content: space-between;",
  "  padding: 8px 14px; border-bottom: 1px solid var(--neon-deep);",
  "  background: var(--panel); flex: 0 0 auto;",
  "}",
  ".app-title { font-weight: 700; color: var(--neon); letter-spacing: 0.12em; }",
  ".app-status { font-size: 11px; color: var(--text-dim); text-transform: uppercase; letter-spacing: 0.18em; }",
  ".app-status.ok { color: var(--neon); }",
  ".app-status.busy { color: var(--warning); }",
  ".app-status.err { color: var(--danger); }",
  "",
  ".messages {",
  "  flex: 1 1 auto; min-height: 0; overflow-y: auto; padding: 16px 14px;",
  "  display: flex; flex-direction: column; gap: 12px;",
  "  scrollbar-width: thin; scrollbar-color: var(--neon-deep) var(--panel);",
  "}",
  ".messages::-webkit-scrollbar { width: 10px; }",
  ".messages::-webkit-scrollbar-track { background: var(--panel); }",
  ".messages::-webkit-scrollbar-thumb { background: var(--neon-deep); border: 2px solid var(--panel); }",
  "",
  ".msg { border: 1px solid var(--neon-deep); padding: 10px 12px; background: var(--panel); }",
  ".msg.user { border-color: var(--neon-muted); background: var(--elevated); align-self: flex-end; max-width: 80%; }",
  ".msg.assistant { align-self: stretch; }",
  ".msg-role { font-size: 10px; text-transform: uppercase; letter-spacing: 0.2em; color: var(--text-dim); margin-bottom: 6px; }",
  ".msg-content { white-space: pre-wrap; word-wrap: break-word; }",
  ".msg-content h1, .msg-content h2, .msg-content h3 { color: var(--neon); margin: 0.4em 0 0.2em; }",
  ".msg-content code { background: var(--void); padding: 1px 4px; color: var(--neon); }",
  ".msg-content pre { background: var(--void); padding: 8px; overflow-x: auto; border: 1px solid var(--neon-deep); }",
  ".msg-content strong { color: var(--neon); }",
  ".msg-content ul, .msg-content ol { margin: 0.3em 0; padding-left: 1.4em; }",
  "",
  ".streaming { color: var(--text-dim); }",
  ".streaming::after { content: '▋'; animation: blink 1s step-start infinite; color: var(--neon); }",
  "@keyframes blink { 50% { opacity: 0; } }",
  "",
  ".timeline { flex: 0 0 auto; padding: 6px 14px; border-top: 1px solid var(--neon-deep); background: var(--panel); display: flex; flex-direction: column; gap: 4px; max-height: 30vh; overflow-y: auto; }",
  ".tl-node { font-size: 11px; display: flex; align-items: center; gap: 6px; }",
  ".tl-node.thought { color: var(--text-dim); }",
  ".tl-node.tool { color: var(--neon-muted); }",
  ".tl-node .glyph { color: var(--neon); }",
  ".tl-node.failed .glyph { color: var(--danger); }",
  ".tl-node .detail { color: var(--text-dim); margin-left: auto; max-width: 60%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
  "",
  ".composer { flex: 0 0 auto; display: flex; gap: 8px; padding: 10px 14px; border-top: 1px solid var(--neon-deep); background: var(--panel); }",
  ".input {",
  "  flex: 1 1 auto; resize: none; min-height: 44px; max-height: 160px;",
  "  background: var(--elevated); color: var(--text-main); border: 1px solid var(--neon-deep);",
  "  padding: 8px 10px; font: inherit; outline: none;",
  "}",
  ".input:focus { border-color: var(--neon); }",
  ".input::placeholder { color: var(--text-dim); }",
  ".send {",
  "  flex: 0 0 auto; padding: 0 18px; background: var(--neon-deep); color: var(--text-main);",
  "  border: 1px solid var(--neon); cursor: pointer; font: inherit; font-weight: 700;",
  "}",
  ".send:hover:not(:disabled) { background: var(--neon); color: var(--void); }",
  ".send:disabled { opacity: 0.4; cursor: not-allowed; }",
  "",
  ".empty { text-align: center; color: var(--text-dim); padding: 40px 20px; }",
  ".error { border-color: var(--danger); color: var(--danger); }",
  "",
].join("\n")

const FRONTEND_APP_JS = [
  '"use strict";',
  'const CHANNEL = "tsian.play-bridge.v1";',
  "let sessionId = null;",
  "let nextReqId = 1;",
  "const pending = new Map();",
  "let streamingText = \"\";",
  "let streamingEl = null;",
  "let isSending = false;",
  "const timelineNodes = new Map();",
  "",
  "const $status = document.getElementById(\"status\");",
  "const $messages = document.getElementById(\"messages\");",
  "const $timeline = document.getElementById(\"timeline\");",
  "const $input = document.getElementById(\"input\");",
  "const $send = document.getElementById(\"send\");",
  "",
  "function setStatus(text, cls) {",
  "  $status.textContent = text;",
  "  $status.className = \"app-status\" + (cls ? \" \" + cls : \"\");",
  "}",
  "",
  "function escapeHtml(s) {",
  "  return s.replace(/&/g, \"&amp;\").replace(/</g, \"&lt;\").replace(/>/g, \"&gt;\").replace(/\"/g, \"&quot;\");",
  "}",
  "",
  "// Minimal markdown: headings, bold, italic, code, lists, paragraphs. Escape first.",
  "function renderMarkdown(text) {",
  "  let lines = text.split(\"\\n\");",
  "  let html = [];",
  "  let inList = false;",
  "  let inCode = false;",
  "  let codeBuf = [];",
  "  for (let i = 0; i < lines.length; i++) {",
  "    let line = lines[i];",
  "    if (line.trim().startsWith(\"```\")) {",
  "      if (inCode) { html.push(\"<pre>\" + escapeHtml(codeBuf.join(\"\\n\")) + \"</pre>\"); codeBuf = []; inCode = false; }",
  "      else { if (inList) { html.push(\"</ul>\"); inList = false; } inCode = true; }",
  "      continue;",
  "    }",
  "    if (inCode) { codeBuf.push(line); continue; }",
  "    let m = line.match(/^(#{1,3})\\s+(.*)$/);",
  "    if (m) { if (inList) { html.push(\"</ul>\"); inList = false; } html.push(\"<h\" + m[1].length + \">\" + inlineMd(m[2]) + \"</h\" + m[1].length + \">\"); continue; }",
  "    let lm = line.match(/^[-*]\\s+(.*)$/);",
  "    if (lm) { if (!inList) { html.push(\"<ul>\"); inList = true; } html.push(\"<li>\" + inlineMd(lm[1]) + \"</li>\"); continue; }",
  "    if (inList) { html.push(\"</ul>\"); inList = false; }",
  "    if (line.trim() === \"\") { continue; }",
  "    html.push(\"<p>\" + inlineMd(line) + \"</p>\");",
  "  }",
  "  if (inList) html.push(\"</ul>\");",
  "  if (inCode) html.push(\"<pre>\" + escapeHtml(codeBuf.join(\"\\n\")) + \"</pre>\");",
  "  return html.join(\"\");",
  "}",
  "",
  "function inlineMd(s) {",
  "  s = escapeHtml(s);",
  "  s = s.replace(/`([^`]+)`/g, \"<code>$1</code>\");",
  "  s = s.replace(/\\*\\*([^*]+)\\*\\*/g, \"<strong>$1</strong>\");",
  "  s = s.replace(/\\*([^*]+)\\*/g, \"<em>$1</em>\");",
  "  return s;",
  "}",
  "",
  "function scrollDown() {",
  "  $messages.scrollTop = $messages.scrollHeight;",
  "}",
  "",
  "function renderMessages(messages) {",
  "  $messages.innerHTML = \"\";",
  "  if (!messages || messages.length === 0) {",
  "    $messages.innerHTML = '<div class=\"empty\">游戏已就绪。输入你的行动开始冒险。</div>';",
  "    return;",
  "  }",
  "  for (const m of messages) {",
  "    const div = document.createElement(\"div\");",
  "    div.className = \"msg \" + (m.role === \"user\" ? \"user\" : \"assistant\");",
  "    const role = document.createElement(\"div\");",
  "    role.className = \"msg-role\";",
  "    role.textContent = m.role === \"user\" ? \"你\" : m.role;",
  "    const content = document.createElement(\"div\");",
  "    content.className = \"msg-content\";",
  "    content.innerHTML = m.role === \"user\" ? escapeHtml(m.content) : renderMarkdown(m.content);",
  "    div.appendChild(role);",
  "    div.appendChild(content);",
  "    $messages.appendChild(div);",
  "  }",
  "  scrollDown();",
  "}",
  "",
  "function startStreaming() {",
  "  streamingText = \"\";",
  "  const div = document.createElement(\"div\");",
  "  div.className = \"msg assistant streaming\";",
  "  const role = document.createElement(\"div\");",
  "  role.className = \"msg-role\";",
  "  role.textContent = \"assistant\";",
  "  const content = document.createElement(\"div\");",
  "  content.className = \"msg-content\";",
  "  div.appendChild(role);",
  "  div.appendChild(content);",
  "  $messages.appendChild(div);",
  "  streamingEl = content;",
  "  scrollDown();",
  "}",
  "",
  "function appendStreaming(delta) {",
  "  streamingText += delta;",
  "  if (streamingEl) { streamingEl.innerHTML = renderMarkdown(streamingText); scrollDown(); }",
  "}",
  "",
  "function endStreaming() {",
  "  if (streamingEl && streamingEl.parentElement) {",
  "    streamingEl.parentElement.classList.remove(\"streaming\");",
  "  }",
  "  streamingEl = null;",
  "  streamingText = \"\";",
  "}",
  "",
  "function addTimelineNode(kind, label, glyph, detail, failed) {",
  "  $timeline.hidden = false;",
  "  const node = document.createElement(\"div\");",
  "  node.className = \"tl-node \" + kind + (failed ? \" failed\" : \"\");",
  "  node.innerHTML = '<span class=\"glyph\">' + glyph + '</span><span class=\"label\">' + escapeHtml(label) + '</span>' + (detail ? '<span class=\"detail\">' + escapeHtml(detail) + '</span>' : '');",
  "  $timeline.appendChild(node);",
  "  $timeline.scrollTop = $timeline.scrollHeight;",
  "  return node;",
  "}",
  "",
  "function setSending(v) {",
  "  isSending = v;",
  "  $send.disabled = v || !sessionId;",
  "  $input.disabled = v;",
  "  if (!v) $input.focus();",
  "}",
  "",
  "function call(method, params) {",
  "  const id = String(nextReqId++);",
  "  return new Promise(function (resolve, reject) {",
  "    pending.set(id, { resolve: resolve, reject: reject });",
  "    window.parent.postMessage({ channel: CHANNEL, kind: \"request\", sessionId: sessionId, id: id, method: method, params: params }, \"*\");",
  "  });",
  "}",
  "",
  "async function loadSnapshot() {",
  "  try {",
  "    const snap = await call(\"runtime.getRuntimeSnapshot\");",
  "    if (snap && snap.state) { renderMessages(snap.state.messages || []); }",
  "  } catch (e) { setStatus(\"快照加载失败\", \"err\"); }",
  "}",
  "",
  "async function sendMessage() {",
  "  const content = $input.value.trim();",
  "  if (!content || !sessionId || isSending) return;",
  "  $input.value = \"\";",
  "  setSending(true);",
  "  setStatus(\"回合进行中…\", \"busy\");",
  "  $timeline.hidden = true;",
  "  $timeline.innerHTML = \"\";",
  "  timelineNodes.clear();",
  "  startStreaming();",
  "  try {",
  "    await call(\"interaction.sendMessage\", { content: content });",
  "    // turn-completed event will reload snapshot; endStreaming handled there.",
  "  } catch (e) {",
  "    endStreaming();",
  "    setStatus(e && e.message ? e.message : \"发送失败\", \"err\");",
  "    setSending(false);",
  "  }",
  "}",
  "",
  "function onEvent(event, payload) {",
  "  if (event === \"turn-delta\") {",
  "    if (payload && payload.kind === \"content\") appendStreaming(payload.delta || \"\");",
  "    // reasoning deltas: route to a collapsed thought node (keep simple: ignore for now)",
  "    return;",
  "  }",
  "  if (event === \"turn-tool\") {",
  "    if (!payload) return;",
  "    const key = payload.callId;",
  "    let node = timelineNodes.get(key);",
  "    const glyph = payload.status === \"success\" ? \"✓\" : payload.status === \"failed\" ? \"✗\" : payload.status === \"running\" ? \"▸\" : \"…\";",
  "    const detail = payload.output ? String(payload.output).slice(0, 120) : payload.status;",
  "    if (!node) {",
  "      node = addTimelineNode(\"tool\", payload.name || \"tool\", glyph, detail, payload.status === \"failed\");",
  "      timelineNodes.set(key, node);",
  "    } else {",
  "      node.innerHTML = '<span class=\"glyph\">' + glyph + '</span><span class=\"label\">' + escapeHtml(payload.name || \"tool\") + '</span><span class=\"detail\">' + escapeHtml(detail) + '</span>';",
  "      if (payload.status === \"failed\") node.classList.add(\"failed\");",
  "    }",
  "    return;",
  "  }",
  "  if (event === \"turn-round-end\") {",
  "    // round boundary; streaming continues or finalizes on turn-completed",
  "    return;",
  "  }",
  "  if (event === \"turn-completed\") {",
  "    endStreaming();",
  "    setSending(false);",
  "    setStatus(\"就绪\", \"ok\");",
  "    if (payload && payload.snapshot && payload.snapshot.state) {",
  "      renderMessages(payload.snapshot.state.messages || []);",
  "    } else {",
  "      loadSnapshot();",
  "    }",
  "    return;",
  "  }",
  "}",
  "",
  "window.addEventListener(\"message\", function (e) {",
  "  const msg = e.data;",
  "  if (!msg || msg.channel !== CHANNEL) return;",
  "  if (msg.kind === \"ready\") {",
  "    sessionId = msg.sessionId;",
  "    setStatus(\"就绪\", \"ok\");",
  "    $send.disabled = false;",
  "    $input.disabled = false;",
  "    $input.focus();",
  "    loadSnapshot();",
  "    return;",
  "  }",
  "  if (msg.kind === \"response\") {",
  "    const cb = pending.get(msg.id);",
  "    if (!cb) return;",
  "    pending.delete(msg.id);",
  "    if (msg.ok) cb.resolve(msg.result); else cb.reject(msg.error);",
  "    return;",
  "  }",
  "  if (msg.kind === \"event\") { onEvent(msg.event, msg.payload); return; }",
  "});",
  "",
  "$send.addEventListener(\"click\", sendMessage);",
  "$input.addEventListener(\"keydown\", function (e) {",
  "  if (e.key === \"Enter\" && !e.shiftKey) { e.preventDefault(); sendMessage(); }",
  "});",
  "",
  "// Boot: send hello to parent.",
  "window.parent.postMessage({ channel: CHANNEL, kind: \"hello\" }, \"*\");",
  "",
].join("\n")

/**
 * The three default packaged frontend files, ready to inject into a game card's
 * `frontendFiles` via `putLocalGameCard`. Relative references in index.html
 * (`style.css`, `app.js`) resolve under the Service Worker virtual prefix.
 */
export function defaultFrontendFiles(): PutLocalGameCardFrontendFileInput[] {
  return [
    { path: "frontend/index.html", data: FRONTEND_INDEX_HTML },
    { path: "frontend/style.css", data: FRONTEND_STYLE_CSS },
    { path: "frontend/app.js", data: FRONTEND_APP_JS },
  ]
}
