interface LocalAssistantKnowledgeFile {
  content: string
}

export interface LocalAssistantKnowledgeRefreshResult {
  updatedPaths: string[]
  removedPaths: string[]
}

type LocalAssistantKnowledgeFileMap = Record<string, LocalAssistantKnowledgeFile>

const FRAMEWORK_KNOWLEDGE_SKILL_MD = [
  "---",
  "name: framework-knowledge",
  "title: Framework Knowledge",
  "description: 读取 Tsian 平台通用概念、文档边界和工作区约定，帮助区分平台知识与当前游戏卡知识。",
  "triggers:",
  "  - 用户询问 Tsian、Game Card、Save Instance、Runtime Workspace、Agent、Skill、Bridge、checkpoint 或桌面助手如何工作",
  "  - 用户询问当前问题应该查平台文档、助手知识还是游戏卡 docs",
  "  - 助手准备解释或维护 workspace、Agent、Skill、游戏前端或卡内容边界",
  "  - 用户希望定位模型请求失败、重试、前端异常或一次操作的关联请求",
  "appliesTo:",
  "  - assistant",
  "---",
  "",
  "# Framework Knowledge",
  "",
  "当问题涉及 Tsian 平台通用概念、文档边界或 workspace 维护边界时，先使用本 Skill。",
  "",
  "## 使用原则",
  "",
  "1. 先判断问题属于平台通用知识、当前游戏卡知识，还是当前存档状态。",
  "2. 平台通用知识读本 Skill 的 reference 文件。",
  "3. 当前游戏卡的世界观、玩法 schema、前端约定和卡内 SOP，读取当前 Game Card 的 `docs/` 以及附近 README/schema/Agent/Skill 文件。",
  "4. 当前存档状态读取 `save/...` 下的运行时文件和平台提供的诊断资源。",
  "5. 不确定时先读文件，不要凭记忆猜测。",
  "",
  "## Reference 阅读顺序",
  "",
  "- `references/platform-concepts.md`：Tsian 核心概念和平台边界。",
  "- `references/documentation-boundaries.md`：人类文档、平台内置助手知识、游戏卡 `docs/` 的职责边界。",
  "- `references/workspace-and-authoring.md`：Runtime Workspace、Agent、Skill 与助手维护原则。",
  "- `references/diagnostics.md`：诊断资源的定位、关联分析与只读快照流程。",
  "- `references/frontend-and-bridge.md`：游戏前端、Bridge 和 `inspect_frontend` 的通用边界。",
  "",
  "读取 reference 时使用普通 workspace read/list/search 工具。本 Skill 不声明 action。",
  "",
].join("\n")

const PLATFORM_CONCEPTS_MD = [
  "# Tsian 平台通用概念",
  "",
  "本文是桌面助手的 Tsian 平台通用概念参考。它只描述平台边界和稳定心智模型，不描述具体游戏卡的世界观、玩法 schema 或前端 UI。",
  "",
  "## Tsian 是什么",
  "",
  "Tsian 是一个面向 AIRP（AI Role Play）的 Agent-Orchestrated Runtime 平台。",
  "",
  "平台负责：",
  "",
  "- 模型服务商配置与模型调用边界；",
  "- 本地存储、Game Card、Save Instance、checkpoint 和导入导出；",
  "- Runtime Workspace 的读写权限、工具执行和提交边界；",
  "- 游戏前端 iframe 沙箱与 Bridge；",
  "- 桌面助手的本地管理入口。",
  "",
  "平台不负责硬编码：",
  "",
  "- 某个游戏卡的世界观；",
  "- 某套固定玩法字段；",
  "- 某个前端如何渲染剧情、角色、状态或地图；",
  "- 某套固定记忆系统。",
  "",
  "这些都应该由 Game Card、Agent、Skill、随卡 `docs/`、Runtime Workspace 文件和游戏前端约定表达。",
  "",
  "## 核心对象",
  "",
  "| 概念 | 说明 |",
  "|---|---|",
  "| Game Card | 可复用的内容定义和可选前端绑定。它包含 Agent、Skill、docs、世界/玩法初始文件和前端资源。一张卡可以创建多个存档。 |",
  "| Save Instance | 一次游玩的运行时数据容器。它属于某张 Game Card，保存 `save/...` 下的历史、状态、记忆和运行时数据。 |",
  "| Runtime Workspace | 桌面助手、运行时 Agent 和游戏前端看到的有效虚拟文件系统，由 Game Card 内容 + 当前 Save Instance 的 `save/...` 组合而成。 |",
  "| Agent | AIRP 回合或管理任务的执行者。Agent 定义通常由 `agent.json`、`AGENT.md`、可选 `SOUL.md` 和 notes 组成。 |",
  "| Skill | 按需加载的能力/知识包。LLM 先通过 `use_skill` 读取 `SKILL.md`，再按需调用声明的 action。 |",
  "| Frontend Package | 游戏卡自带或绑定的游戏界面。它通过 Bridge 与平台通信，不直接访问平台内部对象。 |",
  "| checkpoint | Save Instance 内的回滚点。它用于恢复一次游玩的运行时数据，不是 Game Card 版本管理。 |",
  "| Desktop Assistant | 平台本地管理 Agent。默认文件位于 `.tsian/local/assistant/`，用于帮助玩家理解、检查和维护当前卡与存档。 |",
  "",
  "## Workspace scope 与权限",
  "",
  "Runtime Workspace 路径按前缀进入不同 scope。常见边界：",
  "",
  "| Scope | 路径 | 说明 |",
  "|---|---|---|",
  "| card-content | `agents/`、`skills/`、`docs/` 等根内容 | 随 Game Card 分发的内容。 |",
  "| card-frontend | `frontend/` | 游戏卡前端文件。 |",
  "| save-runtime | `save/` | 当前 Save Instance 的运行时数据。 |",
  "| platform-meta | `.tsian/` | 平台元数据和本地助手文件。 |",
  "",
  "运行时游戏 Agent 通常只能维护 `save/...`。桌面助手是玩家的本地管理助手，默认拥有更高权限，可维护可见 workspace 内容，包括自己的 `.tsian/local/assistant/` 文件。",
  "",
  "## 桌面助手不是卡内 Agent",
  "",
  "当前桌面助手是平台本地助手：",
  "",
  "- 默认文件在 `.tsian/local/assistant/`；",
  "- 平台内置知识库在 `.tsian/local/assistant/skills/framework-knowledge/`；",
  "- `knowledgeMount: \"docs/\"` 让助手能读取当前 Game Card 的 `docs/` 作为卡特定知识；",
  "- 助手 notes、会话上下文和 trace 是本地数据，不随 Game Card 分发。",
  "",
  "如果未来需要 Game Card 声明自己的助手入口，应另行设计 manifest 契约。当前不要把卡内助手入口当成已实现平台事实。",
  "",
  "## 回答问题时的判断顺序",
  "",
  "1. 问平台通用概念：读本 Skill reference。",
  "2. 问当前卡内容或玩法：读当前 Game Card 的 `docs/` 和 workspace 文件。",
  "3. 问当前存档发生了什么：读 `save/...` 和诊断资源。",
  "4. 问某个 Agent/Skill 怎么工作：读对应 `agent.json`、`AGENT.md`、`SOUL.md`、`SKILL.md`。",
  "5. 找不到证据时，说明当前文件没有覆盖，不要编造平台行为。",
  "",
].join("\n")

const DOCUMENTATION_BOUNDARIES_MD = [
  "# 文档与知识边界",
  "",
  "Tsian 有三层不同文档/知识来源。它们都重要，但权威范围不同。",
  "",
  "## 1. 仓库人类文档",
  "",
  "位置：`README.md`、`docs/`、`docs/active/`、`docs/sdk/`、`docs/reference/`。",
  "",
  "用途：",
  "",
  "- 给开发者、维护者、作者解释项目方向和当前实现。",
  "- 记录平台级架构、SDK、工作区方向和维护规则。",
  "- 作为长期维护入口，不一定会直接进入桌面助手运行时上下文。",
  "",
  "## 2. 平台内置助手知识",
  "",
  "位置：`.tsian/local/assistant/skills/framework-knowledge/`。",
  "",
  "用途：",
  "",
  "- 让桌面助手理解 Tsian 平台通用概念和边界。",
  "- 告诉助手遇到卡相关问题时要读取当前 Game Card 的 `docs/`，而不是把平台通用知识当成卡知识。",
  "- 提供稳定的概念入口，不承担完整开发手册或问题处理 SOP。",
  "",
  "维护规则：",
  "",
  "- 只写平台通用概念和边界。",
  "- 中文为主，保留必要英文术语、路径、字段名和 API 名。",
  "- 不写具体游戏卡世界观、具体前端 UI 手册或当前默认模板特定知识。",
  "- 不复制仓库 active docs 的长文；只保留助手回答前最需要的稳定知识。",
  "",
  "## 3. 游戏卡随卡 docs",
  "",
  "位置：当前 Game Card 的 `docs/`。",
  "",
  "用途：",
  "",
  "- 记录该卡自己的世界观、玩法 schema、前端约定和卡内 SOP。",
  "- 随 Game Card 分发给其它玩家。",
  "- 桌面助手回答该卡相关问题时应优先读取。",
  "",
  "维护规则：",
  "",
  "- 卡特定事实写在卡 `docs/`，不要写入平台内置助手知识。",
  "- 平台通用事实不要复制进每张卡；如需说明，保持简短并指向平台文档。",
  "- 卡 docs 与平台文档冲突时，先判断冲突属于当前卡自定义约定还是平台事实错误。平台事实以当前代码和 active docs 为准。",
  "",
  "## 冲突优先级",
  "",
  "1. 当前代码说明现在实现是什么。",
  "2. `docs/active/*` 说明当前方向和维护口径是什么。",
  "3. 当前 Game Card `docs/` 说明这张卡如何约定自己的玩法和前端。",
  "4. Trellis tasks 和 git history 说明过去为什么那样做。",
  "5. 旧入口、archive 和历史 reference 只作考古，不作为当前答案。",
  "",
  "## 当前默认卡模板",
  "",
  "当前内置 Game Card 模板的随卡 `docs/` 属于过渡内容。后续会将默认卡模板替换为更通用、适合创作的模板。",
  "",
  "因此，平台内置助手知识不应依赖当前默认卡模板 docs，也不应把它们当成平台通用事实。",
  "",
].join("\n")

const WORKSPACE_AND_AUTHORING_MD = [
  "# Runtime Workspace 与创作维护边界",
  "",
  "本文说明桌面助手维护 workspace、Agent 和 Skill 时的通用心智模型。具体游戏卡的字段、玩法和前端约定仍以当前 Game Card 的 `docs/` 与 workspace 文件为准。",
  "",
  "## Runtime Workspace 是文件系统心智",
  "",
  "Tsian 倾向把可被玩家或助手理解、编辑、维护的数据放到 workspace 文件里。",
  "",
  "常见路径：",
  "",
  "- `game-card.json`：Game Card manifest 的工作区视图。",
  "- `agents/<agent>/agent.json`：Agent 配置。",
  "- `agents/<agent>/AGENT.md`：Agent 的职责、流程和操作规范。",
  "- `agents/<agent>/SOUL.md`：Agent 的身份、语气和长期风格。",
  "- `agents/<agent>/skills/<skill>/SKILL.md`：Agent-local Skill。",
  "- `skills/<skill>/SKILL.md`：共享 Skill。",
  "- `docs/`：Game Card 作者维护的卡特定知识。",
  "- `save/...`：当前 Save Instance 的运行时数据。",
  "- `.tsian/local/assistant/`：桌面助手自己的本地文件、知识、notes、会话上下文和工具。",
  "",
  "## Agent 文件职责",
  "",
  "| 文件 | 职责 |",
  "|---|---|",
  "| `agent.json` | 机器可读配置：id、title、summary、contacts、contextPaths、skills、platformTools、workspaceAccess 等。 |",
  "| `AGENT.md` | 行动流程和职责说明：什么时候行动、读哪些文件、如何输出、何时委托。 |",
  "| `SOUL.md` | 可选的稳定身份和风格：人格、语气、偏好、长期表达习惯。 |",
  "| `save/agents/<agent>/notes.md` | 存档级运行时 notes，不随 Game Card 内容分发。 |",
  "",
  "修改 Agent 前，先读这些文件，不要只按通用知识猜测。",
  "",
  "## Skill 文件职责",
  "",
  "`SKILL.md` 是 Skill 入口。它通常包含：",
  "",
  "- frontmatter：name、title、description、triggers、appliesTo；",
  "- 使用说明：什么时候加载、读哪些资源、如何判断完成；",
  "- 可选 action 声明：通过 `json tsian-actions` fence 声明浏览器脚本 action。",
  "",
  "Skill 是按需加载的。不要把所有知识都常驻到 Agent prompt；把稳定、可复用的操作说明放进 Skill，让 Agent 需要时 `use_skill`。",
  "",
  "## 桌面助手维护原则",
  "",
  "1. 先读本地文件，再提出修改。",
  "2. 修改卡内容前，确认这是卡特定事实还是平台通用事实。",
  "3. 修改 `save/...` 前，确认这是当前存档运行时数据，不是应写回 Game Card 的模板内容。",
  "4. 修改 `.tsian/local/assistant/...` 前，确认这是玩家本地助手设置或知识，不会随 Game Card 分发。",
  "5. 对大文件优先用精确 edit；只有小文件或新文件才整文件 write。",
  "6. 不确定某个 schema 是否存在时，读当前卡 `docs/`、README 和 schema 文件。",
  "",
  "## 平台内置知识更新边界",
  "",
  "平台的“更新助手知识”只刷新 `.tsian/local/assistant/skills/framework-knowledge/` 下的官方知识文件。",
  "",
  "它不应该修改：",
  "",
  "- `.tsian/local/assistant/AGENT.md`；",
  "- `.tsian/local/assistant/SOUL.md`；",
  "- `.tsian/local/assistant/notes.md`；",
  "- `.tsian/local/assistant/agent.json`；",
  "- 模型、权限和 Skill config；",
  "- 用户自定义 Tool/Skill；",
  "- 当前 Game Card 的 `docs/`。",
  "",
  "这能让已有用户获得新的平台通用知识，同时保护玩家自己的助手设置和卡内容。",
  "",
].join("\n")

const FRONTEND_AND_BRIDGE_MD = [
  "# 游戏前端与 Bridge 通用边界",
  "",
  "本文说明游戏前端、Bridge 和桌面助手前端检查能力的通用边界。具体前端 UI 如何组织、哪些按钮代表什么、如何渲染状态，属于当前 Game Card 前端和随卡 `docs/` 的约定。",
  "",
  "## 游戏前端是可替换的",
  "",
  "Tsian 平台不提供通用玩法 UI DSL。Game Card 可以绑定自己的前端，前端负责体验呈现和交互方式。",
  "",
  "平台负责：",
  "",
  "- 加载远程或打包前端；",
  "- 提供 iframe 沙箱；",
  "- 提供 Bridge API；",
  "- 托管模型调用、存档、checkpoint 和 workspace 权限；",
  "- 在前端请求时运行正式 AIRP turn 或查询资源。",
  "",
  "前端负责：",
  "",
  "- 展示剧情、状态、角色、地图、选项等 UI；",
  "- 决定如何解释该卡 runtime 产出的数据；",
  "- 通过 Bridge 发送玩家输入、查询状态、触发平台允许的 action。",
  "",
  "## Remote 与 packaged frontend",
  "",
  "- Remote frontend：由 URL 加载，适合外部托管或开发中的前端。",
  "- Packaged frontend：作为 Game Card 的静态文件导入，平台通过本地虚拟资源 URL 和 Service Worker 加载。",
  "",
  "两者都应通过 Bridge 与平台通信。前端不应直接访问平台内部 Vue 状态、Dexie、模型 API key 或宿主文件系统。",
  "",
  "## Bridge 心智模型",
  "",
  "Bridge 是游戏前端和平台之间的领域 API / RPC 边界。",
  "",
  "常见能力包括：",
  "",
  "- 获取 runtime snapshot；",
  "- 发送玩家输入，触发正式 AIRP turn；",
  "- 订阅流式文本和工具过程事件；",
  "- 查询 history、checkpoint、workspace、Agent/Skill registry、诊断资源；",
  "- 在允许范围内执行平台 action。",
  "",
  "前端应该使用公开 Bridge / SDK，而不是依赖 platform-web 内部模块。",
  "",
  "## inspect_frontend 的定位",
  "",
  "`inspect_frontend` 是桌面助手用于检查玩家当前真实 `/play` 场景的能力。",
  "",
  "它的边界：",
  "",
  "- 检查的是玩家已经打开并准备好的 Play iframe。",
  "- 它不负责替玩家打开 Play、选择 Game Card 或跨启动器选择 Save Instance。",
  "- 它返回面向助手的过滤后页面快照、交互元素、Bridge 活动、诊断摘要和源码提示。",
  "- 它不默认返回 raw HTML、完整 computed style、完整 Bridge payload 或完整资源时序。",
  "- 玩家 turn 应通过前端自己的可见控件触发，不应由检查工具直接调用交互 API。",
  "",
  "当用户问某个具体前端为什么这样显示或某个按钮怎么用时，助手应读取当前 Game Card 的前端源码、随卡 `docs/` 和 `inspect_frontend` 结果，而不是把平台通用知识当成该前端说明书。",
  "",
  "## 编辑前端的边界",
  "",
  "桌面助手可以在权限允许时维护 `frontend/` 文件，但要区分：",
  "",
  "- 前端源码和构建产物的职责；",
  "- 当前 Game Card 的前端约定和平台通用 Bridge 约定；",
  "- UI 行为问题和 runtime 数据问题。",
  "",
  "修改前端前应先读当前卡的 `docs/`、`frontend/` 目录说明、源码入口和构建/诊断信息。",
  "",
].join("\n")

const DIAGNOSTICS_MD = [
  "# 诊断资源使用指南",
  "",
  "当用户需要定位模型请求失败、重试、前端异常，或核对一次操作是否在后续请求中恢复时，读取 `.tsian/local/diagnostics/`。",
  "",
  "## 目录",
  "",
  "- `index.jsonl`：按时间从新到旧列出当前诊断摘要。",
  "- `requests/<request-id>.json`：模型请求、响应、尝试记录和错误详情。",
  "- `frontend-errors/<error-id>.json`：前端异常详情。",
  "",
  "## 定位记录",
  "",
  "1. 已知大致时间、provider、model、状态或错误文字时，先读 `index.jsonl`；内容较多时按行继续读取。",
  "2. 已知请求 ID、错误 ID、operation ID 或关键文字时，可以直接搜索 `.tsian/local/diagnostics/`。",
  "3. 从摘要取得 ID 后，再读取对应的 request 或 frontend-error 文件。不要为了找一条记录而逐个读取全部正文。",
  "",
  "## 关联分析",
  "",
  "- 先看 `status`、`attempts` 和 `error`，区分请求失败、单次尝试失败后重试成功、主动中止与仍在运行。",
  "- 使用 `operationId` 汇总同一次操作中的请求；使用 `parentRequestId` 和 `previousRequestId` 继续查看父请求与前后请求。",
  "- 看到失败记录后，继续检查同一关联链中时间更晚的记录，确认是否已经重试成功或由后续请求完成。",
  "- 前端异常与模型请求时间接近时，分别读取双方正文，再根据时间、操作 ID 和错误内容判断是否相关。不要只凭一条摘要下结论。",
  "",
  "## 只读与快照",
  "",
  "诊断资源只读，并会随保留周期变化。需要批注、整理或长期保存时，把单个文件或整个目录复制到用户指定的普通可写路径，并明确说明副本是复制时刻的快照。后续分析和编辑在副本上进行。",
  "",
  "不要尝试向诊断目录写入内容，也不要移动或删除其中的记录。",
  "",
].join("\n")

const FRAMEWORK_KNOWLEDGE_SLUG = "framework-knowledge"

function frameworkKnowledgeDir(localAssistantDir: string): string {
  return `${localAssistantDir}/skills/${FRAMEWORK_KNOWLEDGE_SLUG}`
}

const OBSOLETE_REFERENCE_FILE_NAMES = ["platform-architecture.md", "frontend-development.md", "memory-system.md"]

export function obsoleteFrameworkKnowledgePaths(localAssistantDir: string): string[] {
  const dir = frameworkKnowledgeDir(localAssistantDir)
  return OBSOLETE_REFERENCE_FILE_NAMES.map((fileName) => `${dir}/references/${fileName}`)
}

export function defaultFrameworkKnowledgeFileMap(localAssistantDir: string): LocalAssistantKnowledgeFileMap {
  const dir = frameworkKnowledgeDir(localAssistantDir)
  return {
    [`${dir}/SKILL.md`]: {
      content: FRAMEWORK_KNOWLEDGE_SKILL_MD,
    },
    [`${dir}/references/platform-concepts.md`]: {
      content: PLATFORM_CONCEPTS_MD,
    },
    [`${dir}/references/documentation-boundaries.md`]: {
      content: DOCUMENTATION_BOUNDARIES_MD,
    },
    [`${dir}/references/workspace-and-authoring.md`]: {
      content: WORKSPACE_AND_AUTHORING_MD,
    },
    [`${dir}/references/diagnostics.md`]: {
      content: DIAGNOSTICS_MD,
    },
    [`${dir}/references/frontend-and-bridge.md`]: {
      content: FRONTEND_AND_BRIDGE_MD,
    },
  }
}
