import type { AgentConfig } from "@tsian/contracts"

export const DEFAULT_WORKSPACE_VERSION = 9
export const WORKSPACE_MANIFEST_PATH = ".tsian/manifest.json"

export const DEFAULT_SAVE_RUNTIME_UPGRADE_FILE_PATHS = new Set([
  "save/README.md",
  "save/agents/master/notes.md",
  "save/agents/retrieval/notes.md",
  "save/agents/post-processing/notes.md",
  "save/agents/world-architect/notes.md",
  "save/history/README.md",
  "save/history/turns/README.md",
  "save/memory/README.md",
  "save/source/README.md",
  "save/source/manifest.json",
  "save/schema/README.md",
  "save/schema/current.md",
  "save/schema/changelog.md",
  "save/schema/deprecated.md",
  "save/schema/patches/pending/README.md",
  "save/schema/patches/applied/README.md",
  "save/entities/README.md",
  "save/playthrough/README.md",
  "save/playthrough/runtime.json",
  "save/playthrough/player.json",
  "save/playthrough/mode.json",
  "save/playthrough/frontier.json",
  "save/playthrough/branch.json",
  "save/director/README.md",
  "save/director/current-brief.md",
  "save/director/current-brief.meta.json",
])

function text(lines: string[]): string {
  return `${lines.join("\n")}\n`
}

function json(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`
}

function agentConfigContent(config: AgentConfig): string {
  return json(config)
}

const MAINTENANCE_SCRIPT_COMMON = text([
  "function isRecord(value) {",
  "  return typeof value === 'object' && value !== null && !Array.isArray(value);",
  "}",
  "",
  "function fail(code, message, details) {",
  "  const error = new Error(message);",
  "  error.code = code;",
  "  if (details !== undefined) error.details = details;",
  "  throw error;",
  "}",
  "",
  "function normalizePath(value, codePrefix) {",
  "  if (typeof value !== 'string') fail(codePrefix + '_PATH_REQUIRED', 'Write path must be a string.');",
  "  const raw = value.trim();",
  "  const hadTrailingSlash = /[\\\\/]$/.test(raw);",
  "  const normalized = raw.replace(/\\\\/g, '/').replace(/^\\/+/, '').replace(/\\/+/g, '/').replace(/\\/+$/, '');",
  "  if (!normalized) fail(codePrefix + '_PATH_REQUIRED', 'Write path is required.');",
  "  if (hadTrailingSlash) fail(codePrefix + '_FILE_PATH_REQUIRED', 'Write path must not end with a slash.', { path: value });",
  "  const segments = normalized.split('/');",
  "  if (segments.some((segment) => segment === '.' || segment === '..' || segment === '')) {",
  "    fail(codePrefix + '_PATH_INVALID', 'Write path must not contain empty, current, or parent directory segments.', { path: value });",
  "  }",
  "  if (normalized === '.tsian' || normalized.startsWith('.tsian/')) {",
  "    fail(codePrefix + '_PLATFORM_METADATA_FORBIDDEN', 'Writes cannot target .tsian platform metadata.', { path: normalized });",
  "  }",
  "  return normalized;",
  "}",
  "",
  "function inferMediaType(path) {",
  "  if (path.endsWith('.json')) return 'application/json';",
  "  if (path.endsWith('.md')) return 'text/markdown';",
  "  return 'text/plain';",
  "}",
])

const MEMORY_MAINTENANCE_SKILL_MD = text([
  "---",
  "name: memory-maintenance",
  "title: Memory Maintenance",
  "description: Apply explicit workspace maintenance plans for Agent notes, timeline, and memory summaries.",
  "triggers:",
  "  - Agent notes need a durable update",
  "  - timeline or memory summaries should be refreshed",
  "appliesTo:",
  "  - master",
  "  - retrieval",
  "  - post-processing",
  "  - world-architect",
  "---",
  "",
  "# Memory Maintenance",
  "",
  "Use this Skill only when this turn has produced durable information that should be written to Agent notes, the timeline, or memory summaries. Do not run it automatically every turn.",
  "",
  "Before calling the action, read any file you intend to replace and prepare the full next content. The action only accepts explicit replacement writes.",
  "",
  "Allowed targets:",
  "",
  "- `save/agents/<agent>/notes.md`",
  "- `save/history/timeline.md`",
  "- `save/memory/summaries/current.md`",
  "- `save/memory/summaries/long-term.md`",
  "",
  "```json tsian-actions",
  "[",
  "  {",
  "    \"name\": \"apply_maintenance_plan\",",
  "    \"description\": \"Validate and apply an explicit memory maintenance plan through staged workspace writes.\",",
  "    \"inputSchema\": { \"type\": \"object\", \"required\": [\"schema\", \"writes\"], \"properties\": { \"schema\": { \"type\": \"string\" }, \"writes\": { \"type\": \"array\" } } },",
  "    \"outputSchema\": { \"type\": \"object\", \"required\": [\"schema\", \"status\", \"writes\"], \"properties\": { \"schema\": { \"type\": \"string\" }, \"status\": { \"type\": \"string\" }, \"writes\": { \"type\": \"array\" } } },",
  "    \"executor\": { \"type\": \"browser_script\", \"path\": \"scripts/apply-maintenance-plan.js\", \"timeoutMs\": 10000 }",
  "  }",
  "]",
  "```",
])

const MEMORY_MAINTENANCE_SCRIPT_JS = `${MAINTENANCE_SCRIPT_COMMON}${text([
  "const PLAN_SCHEMA = 'tsian.runtime.maintenance.plan.v1';",
  "const MAX_WRITES = 12;",
  "const MAX_CONTENT_LENGTH = 200000;",
  "",
  "function isAllowedTarget(path) {",
  "  return /^save\\/agents\\/[^/]+\\/notes\\.md$/.test(path)",
  "    || path === 'save/history/timeline.md'",
  "    || path === 'save/memory/summaries/current.md'",
  "    || path === 'save/memory/summaries/long-term.md';",
  "}",
  "",
  "function validateWrite(rawWrite, index) {",
  "  if (!isRecord(rawWrite)) fail('MAINTENANCE_WRITE_INVALID', 'Each maintenance write must be an object.', { index });",
  "  const path = normalizePath(rawWrite.path, 'MAINTENANCE');",
  "  if (!isAllowedTarget(path)) fail('MAINTENANCE_TARGET_NOT_ALLOWED', 'Maintenance write target is not allowed in this Skill.', { index, path });",
  "  if (rawWrite.mode !== 'replace') fail('MAINTENANCE_MODE_UNSUPPORTED', 'Maintenance write mode must be replace.', { index, path, mode: rawWrite.mode });",
  "  if (typeof rawWrite.content !== 'string') fail('MAINTENANCE_CONTENT_REQUIRED', 'Maintenance write content must be a string.', { index, path });",
  "  if (rawWrite.content.length > MAX_CONTENT_LENGTH) fail('MAINTENANCE_CONTENT_TOO_LARGE', 'Maintenance write content exceeds the allowed size.', { index, path, size: rawWrite.content.length, maxSize: MAX_CONTENT_LENGTH });",
  "  if (typeof rawWrite.reason !== 'string' || !rawWrite.reason.trim()) fail('MAINTENANCE_REASON_REQUIRED', 'Maintenance write reason must be a non-empty string.', { index, path });",
  "  return { path, mode: 'replace', content: rawWrite.content, reason: rawWrite.reason.trim() };",
  "}",
  "",
  "function validatePlan(plan) {",
  "  if (!isRecord(plan)) fail('MAINTENANCE_PLAN_INVALID', 'Maintenance plan must be an object.');",
  "  if (plan.schema !== PLAN_SCHEMA) fail('MAINTENANCE_SCHEMA_INVALID', 'Maintenance plan schema is invalid.', { expected: PLAN_SCHEMA, actual: plan.schema });",
  "  if (!Array.isArray(plan.writes)) fail('MAINTENANCE_WRITES_INVALID', 'Maintenance plan writes must be an array.');",
  "  if (plan.writes.length > MAX_WRITES) fail('MAINTENANCE_TOO_MANY_WRITES', 'Maintenance plan contains too many writes.', { count: plan.writes.length, maxWrites: MAX_WRITES });",
  "  return plan.writes.map(validateWrite);",
  "}",
  "",
  "async function applyMaintenancePlan(input, tsian, signal) {",
  "  try {",
  "    signal.throwIfAborted();",
  "    const writes = validatePlan(input);",
  "    tsian.trace('maintenance_started', { schema: PLAN_SCHEMA, writeCount: writes.length, paths: writes.map((write) => write.path) });",
  "    const applied = [];",
  "    for (const write of writes) {",
  "      signal.throwIfAborted();",
  "      const file = await tsian.workspace.write({ scope: 'save-runtime', path: write.path, content: write.content, mediaType: 'text/markdown' });",
  "      applied.push({ path: file.path, size: file.content.length, reason: write.reason });",
  "    }",
  "    tsian.trace('maintenance_completed', { status: applied.length ? 'applied' : 'noop', writeCount: applied.length, writes: applied });",
  "    return { schema: PLAN_SCHEMA, status: applied.length ? 'applied' : 'noop', writes: applied };",
  "  } catch (error) {",
  "    tsian.trace('maintenance_failed', { code: error && error.code || 'MAINTENANCE_FAILED', message: error && error.message || String(error), details: error && error.details });",
  "    throw error;",
  "  }",
  "}",
  "",
  "return applyMaintenancePlan(input, tsian, signal);",
])}`

const ENTITY_READER_SKILL_MD = text([
  "---",
  "name: entity-reader",
  "title: Entity Reader",
  "description: Read a novel AIRP entity from save/entities by typed id or direct path, returning the JSON object without changing it.",
  "triggers:",
  "  - Need to read a character, location, item, container, scene, or other entity by id",
  "appliesTo:",
  "  - retrieval",
  "  - master",
  "  - post-processing",
  "---",
  "",
  "# Entity Reader",
  "",
  "Use `read_entity` to read one entity JSON file from the novel AIRP entity store.",
  "",
  "Entity ids use `<type>:<localId>` and map to `save/entities/<type>/<localId>.json`.",
  "Natural-language prose is semantic context only. Do not parse prose for references. When data needs a resolvable reference, use explicit objects such as `{ \"ref\": \"character:萧玄\", \"name\": \"萧玄\" }`.",
  "",
  "Input may provide either `id` or `path`. Prefer `id` when you know the typed entity id.",
  "",
  "```json tsian-actions",
  "[",
  "  {",
  "    \"name\": \"read_entity\",",
  "    \"description\": \"Read one novel AIRP entity JSON file by typed id or path.\",",
  "    \"inputSchema\": { \"type\": \"object\", \"properties\": { \"id\": { \"type\": \"string\" }, \"path\": { \"type\": \"string\" } } },",
  "    \"outputSchema\": { \"type\": \"object\", \"required\": [\"path\", \"data\"], \"properties\": { \"path\": { \"type\": \"string\" }, \"id\": { \"type\": \"string\" }, \"data\": { \"type\": \"object\" } } },",
  "    \"executor\": { \"type\": \"browser_script\", \"path\": \"scripts/read-entity.js\", \"timeoutMs\": 10000 }",
  "  }",
  "]",
  "```",
])

const ENTITY_READER_SCRIPT_JS = text([
  "function isRecord(value) { return typeof value === 'object' && value !== null && !Array.isArray(value); }",
  "function fail(code, message, details) { const error = new Error(message); error.code = code; if (details !== undefined) error.details = details; throw error; }",
  "function normalizeSegment(value, label) {",
  "  if (typeof value !== 'string') fail('ENTITY_ID_INVALID', label + ' must be a string.');",
  "  const segment = value.trim();",
  "  if (!segment || segment === '.' || segment === '..' || /[\\\\/:\\0]/.test(segment)) fail('ENTITY_ID_INVALID', label + ' must not be empty or contain path separators, colon, NUL, . or ...', { value });",
  "  return segment;",
  "}",
  "function pathFromId(id) {",
  "  if (typeof id !== 'string') fail('ENTITY_ID_REQUIRED', 'Entity id must be a string.');",
  "  const parts = id.split(':');",
  "  if (parts.length !== 2) fail('ENTITY_ID_INVALID', 'Entity id must use <type>:<localId>.', { id });",
  "  return 'save/entities/' + normalizeSegment(parts[0], 'Entity type') + '/' + normalizeSegment(parts[1], 'Entity localId') + '.json';",
  "}",
  "function normalizeEntityPath(value) {",
  "  if (typeof value !== 'string') fail('ENTITY_PATH_REQUIRED', 'Entity path must be a string.');",
  "  const path = value.trim().replace(/\\\\/g, '/').replace(/^\\/+/, '').replace(/\\/+/g, '/');",
  "  if (!/^save\\/entities\\/[^/]+\\/[^/]+\\.json$/.test(path)) fail('ENTITY_PATH_INVALID', 'Entity path must look like save/entities/<type>/<localId>.json.', { path: value });",
  "  if (path.split('/').some((segment) => !segment || segment === '.' || segment === '..')) fail('ENTITY_PATH_INVALID', 'Entity path must not contain empty, current, or parent directory segments.', { path: value });",
  "  return path;",
  "}",
  "async function readEntity(input, tsian, signal) {",
  "  try {",
  "    signal.throwIfAborted();",
  "    if (!isRecord(input)) fail('ENTITY_INPUT_INVALID', 'read_entity input must be an object.');",
  "    const path = typeof input.id === 'string' && input.id.trim() ? pathFromId(input.id) : normalizeEntityPath(input.path);",
  "    tsian.trace('entity_read_started', { path, id: input.id });",
  "    const file = await tsian.workspace.read({ scope: 'effective', path });",
  "    let data;",
  "    try { data = JSON.parse(file.content); } catch (error) { fail('ENTITY_JSON_INVALID', 'Entity file is not valid JSON: ' + (error && error.message || error), { path }); }",
  "    if (!isRecord(data)) fail('ENTITY_JSON_OBJECT_REQUIRED', 'Entity JSON must be an object.', { path });",
  "    tsian.trace('entity_read_completed', { path, id: data.id });",
  "    return { path, id: typeof data.id === 'string' ? data.id : input.id, data };",
  "  } catch (error) {",
  "    tsian.trace('entity_read_failed', { code: error && error.code || 'ENTITY_READ_FAILED', message: error && error.message || String(error) });",
  "    throw error;",
  "  }",
  "}",
  "return readEntity(input, tsian, signal);",
])

const WORLD_STATE_MAINTENANCE_SKILL_MD = text([
  "---",
  "name: world-state-maintenance",
  "title: Novel State Maintenance",
  "description: Apply explicit novel AIRP workspace maintenance plans for entities, schema notes, runtime summaries, source metadata, and director brief files.",
  "triggers:",
  "  - Entity state needs updating after a turn",
  "  - Runtime summaries, source frontier, or director brief became stale",
  "  - A safe schema addition should be applied or a pending schema patch should be written",
  "appliesTo:",
  "  - post-processing",
  "  - world-architect",
  "---",
  "",
  "# Novel State Maintenance",
  "",
  "Use this Skill only when there is durable novel AIRP state to write. Do not run it automatically every turn when no state changed.",
  "",
  "Allowed targets:",
  "",
  "- `save/entities/**/*.json`",
  "- `save/schema/**/*.md`",
  "- `save/playthrough/*.json`",
  "- `save/source/manifest.json`",
  "- `save/source/**/*.md`",
  "- `save/source/**/*.txt`",
  "- `save/director/*.md`",
  "- `save/director/*.json`",
  "",
  "Schema policy: safe additive schema changes update `save/schema/current.md` and append `save/schema/changelog.md`. Decision, risk, or migration changes write Markdown files under `save/schema/patches/pending/`. Do not introduce JSON Patch or a migration engine for v0.",
  "",
  "```json tsian-actions",
  "[",
  "  {",
  "    \"name\": \"apply_world_state_plan\",",
  "    \"description\": \"Validate and apply an explicit novel AIRP state maintenance plan through staged workspace writes.\",",
  "    \"inputSchema\": { \"type\": \"object\", \"required\": [\"schema\", \"writes\"], \"properties\": { \"schema\": { \"type\": \"string\" }, \"writes\": { \"type\": \"array\" } } },",
  "    \"outputSchema\": { \"type\": \"object\", \"required\": [\"schema\", \"status\", \"writes\"], \"properties\": { \"schema\": { \"type\": \"string\" }, \"status\": { \"type\": \"string\" }, \"writes\": { \"type\": \"array\" } } },",
  "    \"executor\": { \"type\": \"browser_script\", \"path\": \"scripts/apply-world-state-plan.js\", \"timeoutMs\": 10000 }",
  "  }",
  "]",
  "```",
])

const WORLD_STATE_MAINTENANCE_SCRIPT_JS = `${MAINTENANCE_SCRIPT_COMMON}${text([
  "const PLAN_SCHEMA = 'tsian.runtime.novel-state.plan.v1';",
  "const MAX_WRITES = 30;",
  "const MAX_CONTENT_LENGTH = 300000;",
  "",
  "function isAllowedTarget(path) {",
  "  return /^save\\/entities\\/[^/]+\\/[^/]+\\.json$/.test(path)",
  "    || /^save\\/schema\\/.+\\.md$/.test(path)",
  "    || /^save\\/playthrough\\/[^/]+\\.json$/.test(path)",
  "    || path === 'save/source/manifest.json'",
  "    || /^save\\/source\\/.+\\.(md|txt)$/.test(path)",
  "    || /^save\\/director\\/[^/]+\\.(md|json)$/.test(path);",
  "}",
  "",
  "function validateWrite(rawWrite, index) {",
  "  if (!isRecord(rawWrite)) fail('NOVEL_STATE_WRITE_INVALID', 'Each novel state write must be an object.', { index });",
  "  const path = normalizePath(rawWrite.path, 'NOVEL_STATE');",
  "  if (!isAllowedTarget(path)) fail('NOVEL_STATE_TARGET_NOT_ALLOWED', 'Novel state write target is not allowed in this Skill.', { index, path });",
  "  if (rawWrite.mode !== 'replace') fail('NOVEL_STATE_MODE_UNSUPPORTED', 'Novel state write mode must be replace.', { index, path, mode: rawWrite.mode });",
  "  if (typeof rawWrite.content !== 'string') fail('NOVEL_STATE_CONTENT_REQUIRED', 'Novel state write content must be a string.', { index, path });",
  "  if (rawWrite.content.length > MAX_CONTENT_LENGTH) fail('NOVEL_STATE_CONTENT_TOO_LARGE', 'Novel state write content exceeds the allowed size.', { index, path, size: rawWrite.content.length, maxSize: MAX_CONTENT_LENGTH });",
  "  if (typeof rawWrite.reason !== 'string' || !rawWrite.reason.trim()) fail('NOVEL_STATE_REASON_REQUIRED', 'Novel state write reason must be a non-empty string.', { index, path });",
  "  return { path, mode: 'replace', content: rawWrite.content, reason: rawWrite.reason.trim() };",
  "}",
  "",
  "function validatePlan(plan) {",
  "  if (!isRecord(plan)) fail('NOVEL_STATE_PLAN_INVALID', 'Novel state plan must be an object.');",
  "  if (plan.schema !== PLAN_SCHEMA) fail('NOVEL_STATE_SCHEMA_INVALID', 'Novel state plan schema is invalid.', { expected: PLAN_SCHEMA, actual: plan.schema });",
  "  if (!Array.isArray(plan.writes)) fail('NOVEL_STATE_WRITES_INVALID', 'Novel state plan writes must be an array.');",
  "  if (plan.writes.length > MAX_WRITES) fail('NOVEL_STATE_TOO_MANY_WRITES', 'Novel state plan contains too many writes.', { count: plan.writes.length, maxWrites: MAX_WRITES });",
  "  return plan.writes.map(validateWrite);",
  "}",
  "",
  "async function applyWorldStatePlan(input, tsian, signal) {",
  "  try {",
  "    signal.throwIfAborted();",
  "    const writes = validatePlan(input);",
  "    tsian.trace('novel_state_started', { schema: PLAN_SCHEMA, writeCount: writes.length, paths: writes.map((write) => write.path) });",
  "    const applied = [];",
  "    for (const write of writes) {",
  "      signal.throwIfAborted();",
  "      const file = await tsian.workspace.write({ scope: 'save-runtime', path: write.path, content: write.content, mediaType: inferMediaType(write.path) });",
  "      applied.push({ path: file.path, size: file.content.length, reason: write.reason });",
  "    }",
  "    tsian.trace('novel_state_completed', { status: applied.length ? 'applied' : 'noop', writeCount: applied.length, writes: applied });",
  "    return { schema: PLAN_SCHEMA, status: applied.length ? 'applied' : 'noop', writes: applied };",
  "  } catch (error) {",
  "    tsian.trace('novel_state_failed', { code: error && error.code || 'NOVEL_STATE_FAILED', message: error && error.message || String(error), details: error && error.details });",
  "    throw error;",
  "  }",
  "}",
  "return applyWorldStatePlan(input, tsian, signal);",
])}`

const TSIAN_FRAMEWORK_KNOWLEDGE_MD = text([
  "# Tsian Framework Knowledge",
  "",
  "Tsian is an Agent-Orchestrated Runtime platform for AIRP. Platform code owns model configuration, local storage, checkpoints, bridge APIs, execution policy, and sandboxing. Gameplay-specific behavior belongs in workspace files, Agents, Skills, and frontend conventions.",
  "",
  "Runtime Workspace is an effective virtual file system composed from Game Card content plus the active save slot mounted at `save/`. Ordinary workspace paths are visible to Agents, Skills, and game frontends. `.tsian/` is platform-owned metadata and is hidden from ordinary workspace APIs.",
  "",
  "Default novel AIRP saves use `save/source/`, `save/schema/`, `save/entities/`, `save/playthrough/`, and `save/director/` for their main gameplay contract.",
])

const NOVEL_AIRP_SCHEMA_GUIDE_MD = text([
  "# Novel AIRP Schema Guide",
  "",
  "This default card supports a novel-reader AIRP flow: the player imports a novel, the source corpus lives in this save, and Agents gradually derive schema, entities, runtime state, and director brief as play progresses.",
  "",
  "## Main Paths",
  "",
  "```text",
  "save/source/       # imported source corpus, manifest, chapters, chunks",
  "save/schema/       # current schema, changelog, deprecated notes, Markdown patches",
  "save/entities/     # semantic entities as save/entities/<type>/<localId>.json",
  "save/playthrough/  # player setup, mode, branch, frontier, runtime summaries",
  "save/director/     # current master-safe director brief and metadata",
  "```",
  "",
  "Novel AIRP v0 does not use a separate `save/render/` layer, `save/world/<type>/<entity>/index.json`, generic `_ref` / `_dir` markers, or workspace-persisted pure frontend view state as its main path.",
  "",
  "## Entity Basics",
  "",
  "Entity ids use `<type>:<localId>` and map to `save/entities/<type>/<localId>.json`. Required fields are `id`, `name`, and `brief`.",
  "",
  "```json",
  "{",
  "  \"id\": \"character:萧玄\",",
  "  \"name\": \"萧玄\",",
  "  \"brief\": \"青玄门外门弟子，当前卷入山门冲突。\"",
  "}",
  "```",
  "",
  "Recommended fields when useful: `aliases`, `visibility`, `lifecycle`, `origin`, `sourceRefs`, `tags`, `status`, `fields`, `sections`, `updatedAtTurn`, `updatedBy`.",
  "",
  "Omit `visibility` for ordinary player-known data. Entity-level `visibility` defaults to `player-known`; nested `status`, `fields`, and `sections` inherit the parent unless explicitly overridden. Use explicit `hidden`, `future-spoiler`, or `director-only` only for exceptions.",
  "",
  "Use simple `sourceRefs` path strings by default, for example `save/source/chapters/chapter-0001.md`.",
  "",
  "## Frontend-readable Ordinary Fields",
  "",
  "The default frontend may read stable ordinary fields directly from entity/runtime files: `name`, `brief`, `tags`, `status`, `fields`, `sections`, and runtime summaries in `save/playthrough/runtime.json`.",
  "",
  "Avoid turning v0 into a universal card, meter, stat, or dashboard engine. If a special novel needs special UI later, customize the frontend then.",
  "",
  "## Structured References",
  "",
  "Natural-language prose is semantic search material only. Do not parse prose for references. Use explicit structured refs when a reference must be resolved: `{ \"ref\": \"character:萧玄\", \"name\": \"萧玄\" }`.",
  "",
  "## Schema Evolution",
  "",
  "`save/schema/current.md` is the human/Agent-readable authority. Do not create a second authoritative schema file by default.",
  "",
  "Safe additive changes can directly update `current.md` and append `changelog.md`. Use `save/schema/patches/pending/*.md` only when the change needs a decision or may surprise the player/author.",
  "",
  "Pending patches are Markdown files, not JSON Patch operations. When accepted, move the patch to `save/schema/patches/applied/`, update `current.md`, and append `changelog.md`.",
  "",
  "## Agent Responsibilities",
  "",
  "- `world-architect`: creates the initial schema draft, opening setup, and later schema patches.",
  "- `post-processing`: applies safe schema/entity/runtime updates, writes pending patches when confirmation is needed, and calls world-architect when schema design is needed.",
  "- `master`: consumes current brief, runtime summaries, and visible entity data; does not invent schema ad hoc.",
  "- `retrieval`: helps read source and entity details and returns concise findings.",
])

export const DEFAULT_WORKSPACE_FILES: Array<{
  path: string
  content: string
}> = [
  {
    path: "README.md",
    content: text([
      "# Runtime Workspace",
      "",
      "This effective workspace combines Game Card content with active save runtime data. Runtime play data lives under `save/`.",
      "The `.tsian/` directory is platform-owned metadata and is hidden from ordinary Agent, Skill, and frontend workspace APIs.",
      "",
      "This default card uses the novel AIRP workspace contract. Read `docs/novel-airp-schema-guide.md` before changing novel source, schema, entity, playthrough, or director files.",
    ]),
  },
  {
    path: "agents/README.md",
    content: text([
      "# Agents",
      "",
      "Agent configuration lives under `agents/<agent>/agent.json`. `AGENT.md` is the required SOP/instruction file for that Agent. Durable identity and work style can live under `SOUL.md`.",
    ]),
  },
  {
    path: "agents/master/agent.json",
    content: agentConfigContent({
      id: "master",
      title: "Master Agent",
      summary: "The player-facing AIRP narrator. Uses current brief, runtime summaries, and visible entity data; delegates source retrieval and schema maintenance.",
      contacts: ["retrieval", "post-processing", "world-architect"],
      contextPaths: ["README.md", "docs/novel-airp-schema-guide.md", "save/director/current-brief.md", "save/playthrough/runtime.json", "save/schema/current.md"],
      skills: { enabled: [], disabled: [] },
      platformTools: { enabled: ["agent_call", "workspace_read"], disabled: [] },
      workspaceAccess: { level: 1 },
      entryMode: "persistent",
      system: true,
    }),
  },
  {
    path: "agents/master/AGENT.md",
    content: text([
      "# Master Agent",
      "",
      "You are the player-facing AIRP narrator. You directly produce the reply to the player, including narrative prose.",
      "Read the current director brief, runtime summary, and visible entity data when continuity depends on established facts.",
      "Do not browse the full imported source by default. Ask retrieval for focused source/entity findings when you need background material.",
      "Do not invent schema ad hoc. If the current schema does not fit, ask post-processing or world-architect to maintain it.",
      "At the end of a turn, contact post-processing when durable entity, runtime, memory, or brief updates may be needed.",
    ]),
  },
  {
    path: "agents/master/SOUL.md",
    content: text(["# Master Agent Soul", "", "You narrate a novel-reader AIRP experience from the player's current perspective. Preserve immersion, avoid future spoilers in player-facing prose, and keep player agency open."]),
  },
  {
    path: "agents/retrieval/agent.json",
    content: agentConfigContent({
      id: "retrieval",
      title: "Retrieval Agent",
      summary: "A focused retrieval tool for source, entity, and canon-adjacent context. Returns concise findings to the caller.",
      contacts: ["master", "post-processing", "world-architect"],
      contextPaths: ["docs/novel-airp-schema-guide.md", "save/source/README.md", "save/entities/README.md"],
      skills: { enabled: ["entity-reader"], disabled: [] },
      platformTools: { enabled: ["workspace_read", "workspace_semantic_search"], disabled: [] },
      workspaceAccess: { level: 1 },
    }),
  },
  {
    path: "agents/retrieval/AGENT.md",
    content: text([
      "# Retrieval Agent",
      "",
      "You are a focused retrieval tool, not an independent character.",
      "Given a retrieval intent, search/read the smallest useful source, entity, schema, or brief files, then return refined conclusions.",
      "Use `read_entity` when you know a typed entity id or direct entity path.",
      "Respect `visibility`: omitted visibility means ordinary player-known data; `future-spoiler` and `director-only` must not leak into player-facing narration unless the caller explicitly needs non-player-facing planning context.",
      "Only return what the caller needs to know, not raw file dumps.",
    ]),
  },
  {
    path: "agents/retrieval/SOUL.md",
    content: text(["# Retrieval Agent Soul", "", "You save the caller's context window by finding the right material and compressing it into precise findings."]),
  },
  {
    path: "agents/post-processing/agent.json",
    content: agentConfigContent({
      id: "post-processing",
      title: "Post-Processing Agent",
      summary: "Maintains novel AIRP entities, runtime summaries, memory, schema freshness, and director brief staleness after turns.",
      contacts: ["master", "retrieval", "world-architect"],
      contextPaths: ["docs/novel-airp-schema-guide.md", "save/schema/current.md", "save/playthrough/runtime.json", "save/director/current-brief.md"],
      skills: { enabled: ["world-state-maintenance", "memory-maintenance"], disabled: [] },
      platformTools: { enabled: ["workspace_read", "workspace_write", "agent_call"], disabled: [] },
      workspaceAccess: { level: 1 },
    }),
  },
  {
    path: "agents/post-processing/AGENT.md",
    content: text([
      "# Post-Processing Agent",
      "",
      "You maintain durable state after AIRP turns.",
      "Update involved entity files under `save/entities/`, runtime summaries under `save/playthrough/`, and memory summaries when the turn produced durable changes.",
      "Check whether `save/schema/current.md` still fits new concepts introduced by source expansion or player branch changes.",
      "Apply safe additive schema updates directly by updating `current.md` and `changelog.md`.",
      "For decision, risk, or migration changes, write a Markdown patch under `save/schema/patches/pending/` instead of applying it silently.",
      "Call world-architect when schema design, opening setup, or director-brief redesign is needed.",
    ]),
  },
  {
    path: "agents/post-processing/SOUL.md",
    content: text(["# Post-Processing Agent Soul", "", "You keep the save coherent after each turn without over-engineering the schema. Prefer small, readable files and simple additive changes."]),
  },
  {
    path: "agents/world-architect/agent.json",
    content: agentConfigContent({
      id: "world-architect",
      title: "World Architect",
      summary: "Designs and evolves the save-local novel schema, opening setup, and director-safe brief when design judgment is needed.",
      contacts: ["master", "retrieval", "post-processing"],
      contextPaths: ["docs/novel-airp-schema-guide.md", "save/source/README.md", "save/schema/current.md", "save/schema/changelog.md", "save/playthrough/frontier.json"],
      skills: { enabled: ["world-state-maintenance"], disabled: [] },
      platformTools: { enabled: ["workspace_read", "workspace_write", "workspace_semantic_search", "agent_call"], disabled: [] },
      workspaceAccess: { level: 1 },
    }),
  },
  {
    path: "agents/world-architect/AGENT.md",
    content: text([
      "# World Architect",
      "",
      "You design and evolve the schema for the current imported novel and playthrough.",
      "Start from the minimum entity model and add only fields the current play actually needs.",
      "Use `save/schema/current.md` as the authoritative current schema. Append `save/schema/changelog.md` for applied changes and `save/schema/deprecated.md` for retired concepts.",
      "Write pending Markdown patches when a schema change needs player/author confirmation or may require migration.",
      "When preparing opening setup or director brief, keep player-facing material spoiler-safe and concise.",
    ]),
  },
  {
    path: "agents/world-architect/SOUL.md",
    content: text(["# World Architect Soul", "", "You are a pragmatic schema designer for one living novel save, not a universal ontology builder. Favor readable Markdown, small JSON files, and decisions that both humans and Agents can understand."]),
  },
  {
    path: "skills/README.md",
    content: text(["# Shared Skills", "", "Shared skills live under `skills/<skill>/SKILL.md`. Only summaries and triggers should be indexed eagerly; details load on demand."]),
  },
  { path: "skills/memory-maintenance/SKILL.md", content: MEMORY_MAINTENANCE_SKILL_MD },
  { path: "skills/memory-maintenance/scripts/apply-maintenance-plan.js", content: MEMORY_MAINTENANCE_SCRIPT_JS },
  { path: "skills/entity-reader/SKILL.md", content: ENTITY_READER_SKILL_MD },
  { path: "skills/entity-reader/scripts/read-entity.js", content: ENTITY_READER_SCRIPT_JS },
  { path: "skills/world-state-maintenance/SKILL.md", content: WORLD_STATE_MAINTENANCE_SKILL_MD },
  { path: "skills/world-state-maintenance/scripts/apply-world-state-plan.js", content: WORLD_STATE_MAINTENANCE_SCRIPT_JS },
  {
    path: "docs/README.md",
    content: text(["# Docs", "", "Official and game-card-authored documentation for Agents, Skills, frontends, and authors can live here. Read `docs/novel-airp-schema-guide.md` for this default card's novel workspace contract."]),
  },
  { path: "docs/tsian-framework-knowledge.md", content: TSIAN_FRAMEWORK_KNOWLEDGE_MD },
  { path: "docs/novel-airp-schema-guide.md", content: NOVEL_AIRP_SCHEMA_GUIDE_MD },
]

export const RUNTIME_DEFAULT_CARD_PATHS = new Set<string>([])

export const DEFAULT_SAVE_RUNTIME_FILES: Array<{
  path: string
  content: string
}> = [
  {
    path: "save/README.md",
    content: text(["# Save Runtime Data", "", "This directory contains runtime data for the active novel AIRP save slot.", "", "Main novel AIRP runtime paths: `source/`, `schema/`, `entities/`, `playthrough/`, and `director/`."]),
  },
  { path: "save/agents/master/notes.md", content: "# Master Notes\n\n" },
  { path: "save/agents/retrieval/notes.md", content: "# Retrieval Notes\n\n" },
  { path: "save/agents/post-processing/notes.md", content: "# Post-Processing Notes\n\n" },
  { path: "save/agents/world-architect/notes.md", content: "# World Architect Notes\n\n" },
  {
    path: "save/history/README.md",
    content: text(["# History", "", "Keep this playthrough's durable conversation records and timeline summaries here.", "Raw player-facing AIRP turns are stored under `save/history/turns/` as one JSON file per successful turn."]),
  },
  { path: "save/history/turns/README.md", content: text(["# Raw AIRP Turns", "", "Each successful AIRP turn is stored here as `turn-000001.json`, `turn-000002.json`, and so on.", "Turn files contain the player input and final assistant narrative only."]) },
  { path: "save/memory/README.md", content: text(["# Runtime Memory", "", "Store this playthrough's long-term summaries, durable facts, and retrieval-oriented notes here."]) },
  {
    path: "save/source/README.md",
    content: text(["# Source Corpus", "", "Imported novel text belongs here. The source corpus is the factual basis for derived schema, entities, and director briefs.", "", "Recommended layout:", "", "```text", "save/source/manifest.json", "save/source/normalized.md or save/source/novel.txt", "save/source/chapters/chapter-0001.md", "save/source/chunks/chapter-0001-003.md", "```", "", "Do not extract the whole book upfront by default. Track progress in `save/playthrough/frontier.json` and expand the source frontier as play needs it."]),
  },
  { path: "save/source/manifest.json", content: json({ title: "", importedAt: null, normalizedPath: null, chapterCount: 0, chunkCount: 0, notes: "Fill this when a novel is imported." }) },
  {
    path: "save/schema/README.md",
    content: text(["# Schema", "", "This directory holds the living schema for this novel AIRP save.", "", "- `current.md` is the authoritative human/Agent-readable schema.", "- `changelog.md` records applied changes and reasons.", "- `deprecated.md` records retired fields or concepts.", "- `patches/pending/*.md` records decision/risk/migration changes awaiting confirmation.", "- `patches/applied/*.md` records accepted patches after they are applied.", "", "Safe additive changes can update `current.md` and `changelog.md` directly. Use pending Markdown patches only when confirmation is needed."]),
  },
  {
    path: "save/schema/current.md",
    content: text(["# Current Novel AIRP Schema", "", "Status: draft", "", "## Entity Model", "", "Entity ids use `<type>:<localId>` and map to `save/entities/<type>/<localId>.json`.", "", "Required fields: `id`, `name`, `brief`.", "", "Recommended fields when useful: `aliases`, `visibility`, `lifecycle`, `origin`, `sourceRefs`, `tags`, `status`, `fields`, `sections`, `updatedAtTurn`, `updatedBy`.", "", "Omit `visibility` for ordinary player-known data. Use explicit `hidden`, `future-spoiler`, or `director-only` only for exceptions.", "", "## Frontend-readable Fields", "", "The default frontend may read `name`, `brief`, `tags`, `status`, `fields`, `sections`, and summaries in `save/playthrough/runtime.json`.", "", "## Schema Evolution", "", "Safe additive changes update this file and `changelog.md`. Decision/risk/migration changes use pending Markdown patches."]),
  },
  { path: "save/schema/changelog.md", content: "# Schema Changelog\n\n" },
  { path: "save/schema/deprecated.md", content: "# Deprecated Schema Concepts\n\n" },
  { path: "save/schema/patches/pending/README.md", content: "# Pending Schema Patches\n\nPut Markdown schema patches awaiting confirmation here.\n" },
  { path: "save/schema/patches/applied/README.md", content: "# Applied Schema Patches\n\nMove accepted schema patches here after applying them to current.md and changelog.md.\n" },
  {
    path: "save/entities/README.md",
    content: text(["# Entities", "", "Store semantic entities as JSON files at `save/entities/<type>/<localId>.json`.", "", "Minimum entity:", "", "```json", "{", "  \"id\": \"character:萧玄\",", "  \"name\": \"萧玄\",", "  \"brief\": \"青玄门外门弟子，当前卷入山门冲突。\"", "}", "```", "", "`localId` may be Chinese, but must not contain path separators, colon, NUL, empty path segments, `.`, or `..`.", "Entity files do not need duplicate `type` or per-file `schema` fields by default."]),
  },
  {
    path: "save/playthrough/README.md",
    content: text(["# Playthrough", "", "This directory stores save-level runtime variables, player setup, mode, source frontier, and branch summary.", "", "- `runtime.json`: frequently accessed player-facing or frontend-managed summaries.", "- `player.json`: player persona/viewpoint setup.", "- `mode.json`: play mode and preferences.", "- `frontier.json`: source extraction/reading progress.", "- `branch.json`: player-created branch summary, not a rewrite of the source corpus.", "", "Pure frontend view state such as active tabs, scroll positions, collapsed panels, transient filters, and hover state should not be stored here by default."]),
  },
  { path: "save/playthrough/runtime.json", content: json({ turn: 0, activeScene: null, player: { character: null, location: null }, inventory: null, status: [], updatedAtTurn: 0, updatedBy: null }) },
  { path: "save/playthrough/player.json", content: json({ viewpoint: null, character: null, preferences: {} }) },
  { path: "save/playthrough/mode.json", content: json({ mode: null, notes: "Examples: follow-canon, branch-from-node, free-fanfic." }) },
  { path: "save/playthrough/frontier.json", content: json({ sourceWindow: { start: null, end: null }, extractedThrough: null, notes: "Track how far the imported source has been normalized, chunked, and extracted." }) },
  { path: "save/playthrough/branch.json", content: json({ summary: "", divergenceLevel: "none", importantEvents: [] }) },
  {
    path: "save/director/README.md",
    content: text(["# Director Brief", "", "This directory stores the current master-safe creative direction brief and metadata.", "", "`current-brief.md` should help master use available material without leaking future spoilers or over-scripted plans.", "`current-brief.meta.json` records source/entity/turn basis and staleness hints."]),
  },
  { path: "save/director/current-brief.md", content: text(["# Current Director Brief", "", "No director brief has been prepared yet.", "", "Expected sections when available: stage goal, tone boundaries, available narrative entities, avoid/spoiler boundaries, and refresh triggers."]) },
  { path: "save/director/current-brief.meta.json", content: json({ basedOn: [], updatedAtTurn: 0, expiresAfterTurn: null, notes: "" }) },
  {
    path: WORKSPACE_MANIFEST_PATH,
    content: json({
      version: "0.0.0",
      workspaceVersion: DEFAULT_WORKSPACE_VERSION,
      contentModel: { fileContent: "text", binaryContent: false, cardContentRoot: "/", activeSaveRoot: "save/" },
      platformMetadata: { path: ".tsian/", ordinaryWorkspaceVisible: false },
    }),
  },
  { path: ".tsian/README.md", content: text(["# Tsian Platform Metadata", "", "Files under `.tsian/` are owned by the platform for this save slot. They are hidden from ordinary Agent, Skill, and frontend workspace APIs."]) },
  { path: ".tsian/save/traces/README.md", content: text(["# Traces", "", "Runtime trace files are platform-owned diagnostics input for this save."]) },
]
