import type { AgentConfig } from "@tsian/contracts"

export const DEFAULT_WORKSPACE_VERSION = 11
export const WORKSPACE_MANIFEST_PATH = ".tsian/manifest.json"

export const DEFAULT_SAVE_RUNTIME_UPGRADE_FILE_PATHS = new Set([
  "save/README.md",
  "save/agents/master/notes.md",
  "save/agents/retrieval/notes.md",
  "save/agents/post-processing/notes.md",
  "save/agents/world-architect/notes.md",
  "save/history/README.md",
  "save/history/turns/README.md",
  "save/memory/README.md",
  "save/source/README.md",
  "save/source/manifest.json",
  "save/schema/README.md",
  "save/schema/current.md",
  "save/schema/changelog.md",
  "save/schema/deprecated.md",
  "save/schema/patches/pending/README.md",
  "save/schema/patches/applied/README.md",
  "save/entities/README.md",
  "save/scenes/README.md",
  "save/relationships/README.md",
  "save/playthrough/README.md",
  "save/playthrough/runtime.json",
  "save/playthrough/player.json",
  "save/playthrough/mode.json",
  "save/playthrough/frontier.json",
  "save/playthrough/understanding-summary.json",
  "save/playthrough/branch.json",
  "save/director/README.md",
  "save/director/current-brief.md",
  "save/director/current-brief.meta.json",
])

function text(lines: string[]): string {
  return `${lines.join("\n")}\n`
}

function json(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`
}

function agentConfigContent(config: AgentConfig): string {
  return json(config)
}

const MAINTENANCE_SCRIPT_COMMON = text([
  "function isRecord(value) {",
  "  return typeof value === 'object' && value !== null && !Array.isArray(value);",
  "}",
  "",
  "function fail(code, message, details) {",
  "  const error = new Error(message);",
  "  error.code = code;",
  "  if (details !== undefined) error.details = details;",
  "  throw error;",
  "}",
  "",
  "function normalizePath(value, codePrefix) {",
  "  if (typeof value !== 'string') fail(codePrefix + '_PATH_REQUIRED', 'Write path must be a string.');",
  "  const raw = value.trim();",
  "  const hadTrailingSlash = /[\\\\/]$/.test(raw);",
  "  const normalized = raw.replace(/\\\\/g, '/').replace(/^\\/+/, '').replace(/\\/+/g, '/').replace(/\\/+$/, '');",
  "  if (!normalized) fail(codePrefix + '_PATH_REQUIRED', 'Write path is required.');",
  "  if (hadTrailingSlash) fail(codePrefix + '_FILE_PATH_REQUIRED', 'Write path must not end with a slash.', { path: value });",
  "  const segments = normalized.split('/');",
  "  if (segments.some((segment) => segment === '.' || segment === '..' || segment === '')) {",
  "    fail(codePrefix + '_PATH_INVALID', 'Write path must not contain empty, current, or parent directory segments.', { path: value });",
  "  }",
  "  if (normalized === '.tsian' || normalized.startsWith('.tsian/')) {",
  "    fail(codePrefix + '_PLATFORM_METADATA_FORBIDDEN', 'Writes cannot target .tsian platform metadata.', { path: normalized });",
  "  }",
  "  return normalized;",
  "}",
  "",
  "function inferMediaType(path) {",
  "  if (path.endsWith('.json')) return 'application/json';",
  "  if (path.endsWith('.md')) return 'text/markdown';",
  "  return 'text/plain';",
  "}",
])

const MEMORY_MAINTENANCE_SKILL_MD = text([
  "---",
  "name: memory-maintenance",
  "title: Memory Maintenance",
  "description: 对 Agent notes、timeline、memory summaries 执行显式的 workspace 维护写入。",
  "triggers:",
  "  - Agent notes 需要持久化更新",
  "  - timeline 或 memory summaries 需要刷新",
  "appliesTo:",
  "  - master",
  "  - retrieval",
  "  - post-processing",
  "  - world-architect",
  "---",
  "",
  "# 记忆维护",
  "",
  "仅在本回合产生了值得持久化的信息、需要写入 Agent notes、timeline 或 memory summaries 时使用本 Skill。不要每回合自动运行。",
  "",
  "这些目标是自由文本，没有 schema 结构约束。你也可以直接用平台 `workspace.write`/`workspace.edit` 工具更新它们。本 Skill 提供分阶段事务写入（staged transaction）、`reason` 审计与 trace 事件——当这些价值重要时再用，不是必须经过的关卡。",
  "",
  "action 每条写入接受两种 mode：`replace`（`content` = 完整新内容）或 `edit`（`oldString` + `newString`，可选 `replaceAll`）。省略 `mode` 时脚本按你提供的字段推断。对大摘要做小改动时优先用 `edit` 以省 token。",
  "",
  "调用前先读取要替换/编辑的文件，准备好完整的新内容或精确的 old/new 字符串。",
  "",
  "允许写入的目标：",
  "",
  "- `save/agents/<agent>/notes.md`",
  "- `save/history/timeline.md`",
  "- `save/memory/summaries/current.md`",
  "- `save/memory/summaries/long-term.md`",
  "",
  "```json tsian-actions",
  "[",
  "  {",
  "    \"name\": \"apply_maintenance_plan\",",
  "    \"description\": \"校验并应用一个显式的记忆维护计划，通过分阶段事务写入 workspace。\",",
  "    \"inputSchema\": { \"type\": \"object\", \"required\": [\"schema\", \"writes\"], \"properties\": { \"schema\": { \"type\": \"string\" }, \"writes\": { \"type\": \"array\" } } },",
  "    \"outputSchema\": { \"type\": \"object\", \"required\": [\"schema\", \"status\", \"writes\"], \"properties\": { \"schema\": { \"type\": \"string\" }, \"status\": { \"type\": \"string\" }, \"writes\": { \"type\": \"array\" } } },",
  "    \"executor\": { \"type\": \"browser_script\", \"path\": \"scripts/apply-maintenance-plan.js\", \"timeoutMs\": 10000 }",
  "  }",
  "]",
  "```",
])

const MEMORY_MAINTENANCE_SCRIPT_JS = `${MAINTENANCE_SCRIPT_COMMON}${text([
  "const PLAN_SCHEMA = 'tsian.runtime.maintenance.plan.v1';",
  "const MAX_WRITES = 12;",
  "const MAX_CONTENT_LENGTH = 200000;",
  "",
  "function isAllowedTarget(path) {",
  "  return /^save\\/agents\\/[^/]+\\/notes\\.md$/.test(path)",
  "    || path === 'save/history/timeline.md'",
  "    || path === 'save/memory/summaries/current.md'",
  "    || path === 'save/memory/summaries/long-term.md';",
  "}",
  "",
  "function requireReason(rawWrite, path, index) {",
  "  if (typeof rawWrite.reason !== 'string' || !rawWrite.reason.trim()) fail('MAINTENANCE_REASON_REQUIRED', 'Maintenance write reason must be a non-empty string.', { index, path });",
  "  return rawWrite.reason.trim();",
  "}",
  "async function resolveModeAndFields(rawWrite, path, index, tsian) {",
  "  const hasEditInput = typeof rawWrite.oldString === 'string' && rawWrite.oldString.length > 0 && typeof rawWrite.newString === 'string';",
  "  const hasReplaceInput = typeof rawWrite.content === 'string';",
  "  let mode = typeof rawWrite.mode === 'string' ? rawWrite.mode : null;",
  "  if (!mode) {",
  "    if (hasEditInput) mode = 'edit';",
  "    else if (hasReplaceInput) mode = 'replace';",
  "    else fail('MAINTENANCE_WRITE_FIELDS_REQUIRED', 'Maintenance write must provide content (replace) or oldString+newString (edit).', { index, path });",
  "  }",
  "  if (mode !== 'replace' && mode !== 'edit') fail('MAINTENANCE_MODE_UNSUPPORTED', 'Maintenance write mode must be replace or edit.', { index, path, mode });",
  "  if (mode === 'replace') {",
  "    if (!hasReplaceInput) fail('MAINTENANCE_CONTENT_REQUIRED', 'Maintenance write content must be a string.', { index, path });",
  "    if (rawWrite.content.length > MAX_CONTENT_LENGTH) fail('MAINTENANCE_CONTENT_TOO_LARGE', 'Maintenance write content exceeds the allowed size.', { index, path, size: rawWrite.content.length, maxSize: MAX_CONTENT_LENGTH });",
  "    return { mode, content: rawWrite.content };",
  "  }",
  "  if (!hasEditInput) fail('MAINTENANCE_EDIT_FIELDS_REQUIRED', 'Maintenance write edit requires non-empty oldString and newString.', { index, path });",
  "  if (rawWrite.oldString.length > MAX_CONTENT_LENGTH || rawWrite.newString.length > MAX_CONTENT_LENGTH) fail('MAINTENANCE_EDIT_TOO_LARGE', 'Maintenance write edit strings exceed the allowed size.', { index, path });",
  "  return { mode, oldString: rawWrite.oldString, newString: rawWrite.newString, replaceAll: rawWrite.replaceAll === true };",
  "}",
  "function validateWrite(rawWrite, index) {",
  "  if (!isRecord(rawWrite)) fail('MAINTENANCE_WRITE_INVALID', 'Each maintenance write must be an object.', { index });",
  "  const path = normalizePath(rawWrite.path, 'MAINTENANCE');",
  "  if (!isAllowedTarget(path)) fail('MAINTENANCE_TARGET_NOT_ALLOWED', 'Maintenance write target is not allowed in this Skill.', { index, path });",
  "  const reason = requireReason(rawWrite, path, index);",
  "  return { path, reason, rawWrite };",
  "}",
  "",
  "function validatePlan(plan) {",
  "  if (!isRecord(plan)) fail('MAINTENANCE_PLAN_INVALID', 'Maintenance plan must be an object.');",
  "  if (plan.schema !== PLAN_SCHEMA) fail('MAINTENANCE_SCHEMA_INVALID', 'Maintenance plan schema is invalid.', { expected: PLAN_SCHEMA, actual: plan.schema });",
  "  if (!Array.isArray(plan.writes)) fail('MAINTENANCE_WRITES_INVALID', 'Maintenance plan writes must be an array.');",
  "  if (plan.writes.length > MAX_WRITES) fail('MAINTENANCE_TOO_MANY_WRITES', 'Maintenance plan contains too many writes.', { count: plan.writes.length, maxWrites: MAX_WRITES });",
  "  return plan.writes.map(validateWrite);",
  "}",
  "",
  "async function applyMaintenancePlan(input, tsian, signal) {",
  "  try {",
  "    signal.throwIfAborted();",
  "    const validated = validatePlan(input);",
  "    tsian.trace('maintenance_started', { schema: PLAN_SCHEMA, writeCount: validated.length, paths: validated.map((w) => w.path) });",
  "    const applied = [];",
  "    for (const write of validated) {",
  "      signal.throwIfAborted();",
  "      const resolved = await resolveModeAndFields(write.rawWrite, write.path, applied.length, tsian);",
  "      let file;",
  "      if (resolved.mode === 'replace') {",
  "        file = await tsian.workspace.write({ scope: 'save-runtime', path: write.path, content: resolved.content, mediaType: 'text/markdown' });",
  "      } else {",
  "        file = await tsian.workspace.edit({ scope: 'save-runtime', path: write.path, oldString: resolved.oldString, newString: resolved.newString, replaceAll: resolved.replaceAll === true ? true : undefined });",
  "      }",
  "      applied.push({ path: file.path, size: file.content.length, mode: resolved.mode, reason: write.reason });",
  "    }",
  "    tsian.trace('maintenance_completed', { status: applied.length ? 'applied' : 'noop', writeCount: applied.length, writes: applied });",
  "    return { schema: PLAN_SCHEMA, status: applied.length ? 'applied' : 'noop', writes: applied };",
  "  } catch (error) {",
  "    tsian.trace('maintenance_failed', { code: error && error.code || 'MAINTENANCE_FAILED', message: error && error.message || String(error), details: error && error.details });",
  "    throw error;",
  "  }",
  "}",
  "",
  "return applyMaintenancePlan(input, tsian, signal);",
])}`

const ENTITY_READER_SKILL_MD = text([
  "---",
  "name: entity-reader",
  "title: Entity Reader",
  "description: Read a novel AIRP entity from save/entities by typed id or direct path, returning the JSON object without changing it.",
  "triggers:",
  "  - Need to read a character, location, item, container, scene, or other entity by id",
  "appliesTo:",
  "  - retrieval",
  "  - master",
  "  - post-processing",
  "---",
  "",
  "# Entity Reader",
  "",
  "Use `read_entity` to read one entity JSON file from the novel AIRP entity store.",
  "",
  "Entity ids use `<type>:<localId>` and map to `save/entities/<type>/<localId>.json`.",
  "Natural-language prose is semantic context only. Do not parse prose for references. When data needs a resolvable reference, use explicit objects such as `{ \"ref\": \"character:萧玄\", \"name\": \"萧玄\" }`.",
  "",
  "Input may provide either `id` or `path`. Prefer `id` when you know the typed entity id.",
  "",
  "```json tsian-actions",
  "[",
  "  {",
  "    \"name\": \"read_entity\",",
  "    \"description\": \"Read one novel AIRP entity JSON file by typed id or path.\",",
  "    \"inputSchema\": { \"type\": \"object\", \"properties\": { \"id\": { \"type\": \"string\" }, \"path\": { \"type\": \"string\" } } },",
  "    \"outputSchema\": { \"type\": \"object\", \"required\": [\"path\", \"data\"], \"properties\": { \"path\": { \"type\": \"string\" }, \"id\": { \"type\": \"string\" }, \"data\": { \"type\": \"object\" } } },",
  "    \"executor\": { \"type\": \"browser_script\", \"path\": \"scripts/read-entity.js\", \"timeoutMs\": 10000 }",
  "  }",
  "]",
  "```",
])

const ENTITY_READER_SCRIPT_JS = text([
  "function isRecord(value) { return typeof value === 'object' && value !== null && !Array.isArray(value); }",
  "function fail(code, message, details) { const error = new Error(message); error.code = code; if (details !== undefined) error.details = details; throw error; }",
  "function normalizeSegment(value, label) {",
  "  if (typeof value !== 'string') fail('ENTITY_ID_INVALID', label + ' must be a string.');",
  "  const segment = value.trim();",
  "  if (!segment || segment === '.' || segment === '..' || /[\\\\/:\\0]/.test(segment)) fail('ENTITY_ID_INVALID', label + ' must not be empty or contain path separators, colon, NUL, . or ...', { value });",
  "  return segment;",
  "}",
  "function pathFromId(id) {",
  "  if (typeof id !== 'string') fail('ENTITY_ID_REQUIRED', 'Entity id must be a string.');",
  "  const parts = id.split(':');",
  "  if (parts.length !== 2) fail('ENTITY_ID_INVALID', 'Entity id must use <type>:<localId>.', { id });",
  "  return 'save/entities/' + normalizeSegment(parts[0], 'Entity type') + '/' + normalizeSegment(parts[1], 'Entity localId') + '.json';",
  "}",
  "function normalizeEntityPath(value) {",
  "  if (typeof value !== 'string') fail('ENTITY_PATH_REQUIRED', 'Entity path must be a string.');",
  "  const path = value.trim().replace(/\\\\/g, '/').replace(/^\\/+/, '').replace(/\\/+/g, '/');",
  "  if (!/^save\\/entities\\/[^/]+\\/[^/]+\\.json$/.test(path)) fail('ENTITY_PATH_INVALID', 'Entity path must look like save/entities/<type>/<localId>.json.', { path: value });",
  "  if (path.split('/').some((segment) => !segment || segment === '.' || segment === '..')) fail('ENTITY_PATH_INVALID', 'Entity path must not contain empty, current, or parent directory segments.', { path: value });",
  "  return path;",
  "}",
  "async function readEntity(input, tsian, signal) {",
  "  try {",
  "    signal.throwIfAborted();",
  "    if (!isRecord(input)) fail('ENTITY_INPUT_INVALID', 'read_entity input must be an object.');",
  "    const path = typeof input.id === 'string' && input.id.trim() ? pathFromId(input.id) : normalizeEntityPath(input.path);",
  "    tsian.trace('entity_read_started', { path, id: input.id });",
  "    const file = await tsian.workspace.read({ scope: 'effective', path });",
  "    let data;",
  "    try { data = JSON.parse(file.content); } catch (error) { fail('ENTITY_JSON_INVALID', 'Entity file is not valid JSON: ' + (error && error.message || error), { path }); }",
  "    if (!isRecord(data)) fail('ENTITY_JSON_OBJECT_REQUIRED', 'Entity JSON must be an object.', { path });",
  "    tsian.trace('entity_read_completed', { path, id: data.id });",
  "    return { path, id: typeof data.id === 'string' ? data.id : input.id, data };",
  "  } catch (error) {",
  "    tsian.trace('entity_read_failed', { code: error && error.code || 'ENTITY_READ_FAILED', message: error && error.message || String(error) });",
  "    throw error;",
  "  }",
  "}",
  "return readEntity(input, tsian, signal);",
])

const WORLD_STATE_MAINTENANCE_SKILL_MD = text([
  "---",
  "name: world-state-maintenance",
  "title: Novel State Maintenance",
  "description: 对实体、schema 笔记、runtime 摘要、source 元数据、director brief 等执行显式的 novel AIRP workspace 维护写入。",
  "triggers:",
  "  - 回合后实体状态需要更新",
  "  - runtime 摘要、source frontier 或 director brief 变陈旧",
  "  - 应应用一个安全的 schema 增量，或写一个待确认的 schema patch",
  "appliesTo:",
  "  - post-processing",
  "  - world-architect",
  "---",
  "",
  "# 小说状态维护",
  "",
  "仅在有需要持久化的 novel AIRP 状态要写入时使用本 Skill。状态无变化时不要每回合自动运行。",
  "",
  "本 Skill 服务有 schema 结构约束的写入（entities、scene/relationship 分片、runtime、schema md、director、source）。无结构的自由文本（agent notes、timeline、memory summaries）可以直接用平台 `workspace.write`/`workspace.edit` 工具或 `memory-maintenance` Skill 写入——不必绕到这里。",
  "",
  "每条写入接受两种 mode：`replace`（`content` = 完整新内容）或 `edit`（`oldString` + `newString`，可选 `replaceAll`）。省略 `mode` 时脚本按你提供的字段推断。对大文件做小改动（如大关系分片里改一条 edge）时优先用 `edit` 以省 token、降低覆盖风险。",
  "",
  "允许写入的目标：",
  "",
  "- `save/entities/**/*.json`",
  "- `save/schema/**/*.md`",
  "- `save/playthrough/*.json`",
  "- `save/scenes/*.json`",
  "- `save/relationships/*.json`",
  "- `save/source/manifest.json`",
  "- `save/source/**/*.md`",
  "- `save/source/**/*.txt`",
  "- `save/director/*.md`",
  "- `save/director/*.json`",
  "",
  "Schema 策略：安全的增量变更直接更新 `save/schema/current.md` 并追加 `save/schema/changelog.md`。需要决策、有风险或涉及迁移的变更写成 `save/schema/patches/pending/` 下的 Markdown 文件。v0 不引入 JSON Patch 或迁移引擎。",
  "",
  "scene/relationship 分片是派生导航视图（entity 文件是权威）。场景/在场变化时维护 `save/scenes/<id>.json`；关系变化时维护 `save/relationships/<scope>.json`。scene.present 摘要从 entities 派生刷新，不要把它当作第二权威。双向关系两边各写一条 edge；单向关系（如隶属）只写从属方。",
  "",
  "```json tsian-actions",
  "[",
  "  {",
  "    \"name\": \"apply_world_state_plan\",",
  "    \"description\": \"校验并应用一个显式的 novel AIRP 状态维护计划，通过分阶段事务写入 workspace。\",",
  "    \"inputSchema\": { \"type\": \"object\", \"required\": [\"schema\", \"writes\"], \"properties\": { \"schema\": { \"type\": \"string\" }, \"writes\": { \"type\": \"array\" } } },",
  "    \"outputSchema\": { \"type\": \"object\", \"required\": [\"schema\", \"status\", \"writes\"], \"properties\": { \"schema\": { \"type\": \"string\" }, \"status\": { \"type\": \"string\" }, \"writes\": { \"type\": \"array\" } } },",
  "    \"executor\": { \"type\": \"browser_script\", \"path\": \"scripts/apply-world-state-plan.js\", \"timeoutMs\": 10000 }",
  "  }",
  "]",
  "```",
])

const WORLD_STATE_MAINTENANCE_SCRIPT_JS = `${MAINTENANCE_SCRIPT_COMMON}${text([
  "const PLAN_SCHEMA = 'tsian.runtime.novel-state.plan.v1';",
  "const MAX_WRITES = 30;",
  "const MAX_CONTENT_LENGTH = 300000;",
  "",
  "function isAllowedTarget(path) {",
  "  return /^save\\/entities\\/[^/]+\\/[^/]+\\.json$/.test(path)",
  "    || /^save\\/schema\\/.+\\.md$/.test(path)",
  "    || /^save\\/playthrough\\/[^/]+\\.json$/.test(path)",
  "    || path === 'save/source/manifest.json'",
  "    || /^save\\/source\\/.+\\.(md|txt)$/.test(path)",
  "    || /^save\\/director\\/[^/]+\\.(md|json)$/.test(path)",
  "    || /^save\\/scenes\\/[^/]+\\.json$/.test(path)",
  "    || /^save\\/relationships\\/[^/]+\\.json$/.test(path);",
  "}",
  "",
  "function requireReason(rawWrite, path, index) {",
  "  if (typeof rawWrite.reason !== 'string' || !rawWrite.reason.trim()) fail('NOVEL_STATE_REASON_REQUIRED', 'Novel state write reason must be a non-empty string.', { index, path });",
  "  return rawWrite.reason.trim();",
  "}",
  "async function resolveModeAndFields(rawWrite, path, index, tsian) {",
  "  const hasEditInput = typeof rawWrite.oldString === 'string' && rawWrite.oldString.length > 0 && typeof rawWrite.newString === 'string';",
  "  const hasReplaceInput = typeof rawWrite.content === 'string';",
  "  let mode = typeof rawWrite.mode === 'string' ? rawWrite.mode : null;",
  "  if (!mode) {",
  "    if (hasEditInput) mode = 'edit';",
  "    else if (hasReplaceInput) mode = 'replace';",
  "    else fail('NOVEL_STATE_WRITE_FIELDS_REQUIRED', 'Novel state write must provide content (replace) or oldString+newString (edit).', { index, path });",
  "  }",
  "  if (mode !== 'replace' && mode !== 'edit') fail('NOVEL_STATE_MODE_UNSUPPORTED', 'Novel state write mode must be replace or edit.', { index, path, mode });",
  "  if (mode === 'replace') {",
  "    if (!hasReplaceInput) fail('NOVEL_STATE_CONTENT_REQUIRED', 'Novel state write content must be a string.', { index, path });",
  "    if (rawWrite.content.length > MAX_CONTENT_LENGTH) fail('NOVEL_STATE_CONTENT_TOO_LARGE', 'Novel state write content exceeds the allowed size.', { index, path, size: rawWrite.content.length, maxSize: MAX_CONTENT_LENGTH });",
  "    return { mode, content: rawWrite.content };",
  "  }",
  "  if (!hasEditInput) fail('NOVEL_STATE_EDIT_FIELDS_REQUIRED', 'Novel state write edit requires non-empty oldString and newString.', { index, path });",
  "  if (rawWrite.oldString.length > MAX_CONTENT_LENGTH || rawWrite.newString.length > MAX_CONTENT_LENGTH) fail('NOVEL_STATE_EDIT_TOO_LARGE', 'Novel state write edit strings exceed the allowed size.', { index, path });",
  "  return { mode, oldString: rawWrite.oldString, newString: rawWrite.newString, replaceAll: rawWrite.replaceAll === true };",
  "}",
  "function validateWrite(rawWrite, index) {",
  "  if (!isRecord(rawWrite)) fail('NOVEL_STATE_WRITE_INVALID', 'Each novel state write must be an object.', { index });",
  "  const path = normalizePath(rawWrite.path, 'NOVEL_STATE');",
  "  if (!isAllowedTarget(path)) fail('NOVEL_STATE_TARGET_NOT_ALLOWED', 'Novel state write target is not allowed in this Skill.', { index, path });",
  "  const reason = requireReason(rawWrite, path, index);",
  "  return { path, reason, rawWrite };",
  "}",
  "",
  "function validatePlan(plan) {",
  "  if (!isRecord(plan)) fail('NOVEL_STATE_PLAN_INVALID', 'Novel state plan must be an object.');",
  "  if (plan.schema !== PLAN_SCHEMA) fail('NOVEL_STATE_SCHEMA_INVALID', 'Novel state plan schema is invalid.', { expected: PLAN_SCHEMA, actual: plan.schema });",
  "  if (!Array.isArray(plan.writes)) fail('NOVEL_STATE_WRITES_INVALID', 'Novel state plan writes must be an array.');",
  "  if (plan.writes.length > MAX_WRITES) fail('NOVEL_STATE_TOO_MANY_WRITES', 'Novel state plan contains too many writes.', { count: plan.writes.length, maxWrites: MAX_WRITES });",
  "  return plan.writes.map(validateWrite);",
  "}",
  "",
  "async function applyWorldStatePlan(input, tsian, signal) {",
  "  try {",
  "    signal.throwIfAborted();",
  "    const validated = validatePlan(input);",
  "    tsian.trace('novel_state_started', { schema: PLAN_SCHEMA, writeCount: validated.length, paths: validated.map((w) => w.path) });",
  "    const applied = [];",
  "    for (const write of validated) {",
  "      signal.throwIfAborted();",
  "      const resolved = await resolveModeAndFields(write.rawWrite, write.path, applied.length, tsian);",
  "      let file;",
  "      if (resolved.mode === 'replace') {",
  "        file = await tsian.workspace.write({ scope: 'save-runtime', path: write.path, content: resolved.content, mediaType: inferMediaType(write.path) });",
  "      } else if (resolved.mode === 'edit') {",
  "        file = await tsian.workspace.edit({ scope: 'save-runtime', path: write.path, oldString: resolved.oldString, newString: resolved.newString, replaceAll: resolved.replaceAll === true ? true : undefined });",
  "      } else {",
  "        fail('NOVEL_STATE_MODE_UNSUPPORTED', 'Unsupported write mode.', { path: write.path, mode: resolved.mode });",
  "      }",
  "      applied.push({ path: file.path, size: file.content.length, mode: resolved.mode, reason: write.reason });",
  "    }",
  "    tsian.trace('novel_state_completed', { status: applied.length ? 'applied' : 'noop', writeCount: applied.length, writes: applied });",
  "    return { schema: PLAN_SCHEMA, status: applied.length ? 'applied' : 'noop', writes: applied };",
  "  } catch (error) {",
  "    tsian.trace('novel_state_failed', { code: error && error.code || 'NOVEL_STATE_FAILED', message: error && error.message || String(error), details: error && error.details });",
  "    throw error;",
  "  }",
  "}",
  "return applyWorldStatePlan(input, tsian, signal);",
])}`

const RESOLVE_ENTITIES_SKILL_MD = text([
  "---",
  "name: entity-resolver",
  "title: Entity Resolver",
  "description: 批量按 id 取实体数据，按有界 depth 展开容器/列表的嵌套，可选附带关系/场景在场——一次工具调用代替多次 read 往返。",
  "triggers:",
  "  - 需要一次按 typed id 读取多个实体",
  "  - 需要展开容器的 contents（或容器里的容器）到有限几层",
  "  - 需要实体详情加上它们的关系边或当前场景在场，一次拿到",
  "appliesTo:",
  "  - retrieval",
  "  - post-processing",
  "  - world-architect",
  "---",
  "",
  "# 实体解析器",
  "",
  "调用 `resolve_entities` 一次取回多个实体，可选按有界 `depth` 展开嵌套 `ref` 链（容器装容器/物品），省掉普通 `workspace.read` 对嵌套结构要做多次往返的麻烦。",
  "",
  "实体 id 用 `<type>:<localId>`，映射到 `save/entities/<type>/<localId>.json`。容器的 `contents` 用 `{ ref, name, quantity }`；嵌套靠 ref 链表达，不是靠存储结构。",
  "",
  "本 Skill 不做的事：",
  "",
  "- 不做语义搜索——*找* 实体用平台 `workspace.search`。",
  "- 不替代单文件直读——只需要一个文件时用平台 `workspace.read`。",
  "",
  "当普通 read 会意味着多次往返时用它：一批实体、嵌套容器、或实体详情加上关系/场景。",
  "",
  "## 输入",
  "",
  "- `refs`（必填）：要解析的实体 id 数组。",
  "- `depth`（可选，默认 1）：展开多少层容器 `contents` 的 ref。`0` 表示实体原样返回，ref 保留为标记不展开；`1` 展开一层；更大值展开更深。深度由调用方控制，不由 skill 决定。",
  "- `withRelations`（可选，默认 false）：顺带读取每个已解析 subject 的 `save/relationships/<scope>.json` 并合并 edges。",
  "- `withScene`（可选，默认 false）：顺带读取 `save/playthrough/runtime.json` 的 `activeSceneIds`，再读场景文件，返回 `present` 含已有解析 ref 的场景。",
  "",
  "缺失的实体报告为 `{ id, path, missing: true }`，不抛错——一个 id 缺失不会让整次调用失败。循环引用用 visited 集合兜底；见过的 ref 返回为标记，不再展开。",
  "",
  "```json tsian-actions",
  "[",
  "  {",
  "    \"name\": \"resolve_entities\",",
  "    \"description\": \"批量按 id 取实体数据，展开容器嵌套到有界 depth，可选附带关系/场景在场。\",",
  "    \"inputSchema\": { \"type\": \"object\", \"required\": [\"refs\"], \"properties\": { \"refs\": { \"type\": \"array\", \"items\": { \"type\": \"string\" } }, \"depth\": { \"type\": \"number\" }, \"withRelations\": { \"type\": \"boolean\" }, \"withScene\": { \"type\": \"boolean\" } } },",
  "    \"outputSchema\": { \"type\": \"object\", \"required\": [\"entities\"], \"properties\": { \"entities\": { \"type\": \"array\" }, \"expanded\": { \"type\": \"array\" }, \"relationships\": { \"type\": \"array\" }, \"scenes\": { \"type\": \"array\" } } },",
  "    \"executor\": { \"type\": \"browser_script\", \"path\": \"scripts/resolve-entities.js\", \"timeoutMs\": 10000 }",
  "  }",
  "]",
  "```",
])

const RESOLVE_ENTITIES_SCRIPT_JS = text([
  "function isRecord(value) { return typeof value === 'object' && value !== null && !Array.isArray(value); }",
  "function fail(code, message, details) { const error = new Error(message); error.code = code; if (details !== undefined) error.details = details; throw error; }",
  "function parseEntityId(id) {",
  "  if (typeof id !== 'string' || !id.trim()) fail('ENTITY_ID_REQUIRED', 'Each ref must be a non-empty string.', { id });",
  "  const trimmed = id.trim();",
  "  const parts = trimmed.split(':');",
  "  if (parts.length !== 2 || !parts[0] || !parts[1]) fail('ENTITY_ID_INVALID', 'Entity id must use <type>:<localId>.', { id: trimmed });",
  "  if (/[\\\\/:\\0]/.test(parts[1]) || parts[1] === '.' || parts[1] === '..') fail('ENTITY_ID_INVALID', 'Entity localId must not contain path separators, colon, NUL, . or ..', { id: trimmed });",
  "  return { id: trimmed, type: parts[0], localId: parts[1] };",
  "}",
  "function entityPathFromId(id) { const p = parseEntityId(id); return 'save/entities/' + p.type + '/' + p.localId + '.json'; }",
  "function relationshipScopeFromId(id) { const p = parseEntityId(id); return p.type + '-' + p.localId; }",
  "function normalizeDepth(value) { const n = Number(value); if (!Number.isFinite(n)) return 1; return Math.max(0, Math.min(5, Math.floor(n))); }",
  "async function readJsonSafe(tsian, path) {",
  "  try { const file = await tsian.workspace.read({ scope: 'effective', path }); if (!file || typeof file.content !== 'string') return null; try { return JSON.parse(file.content); } catch (e) { return null; } } catch (e) { return null; }",
  "}",
  "async function readEntityFile(tsian, id) {",
  "  const path = entityPathFromId(id);",
  "  try { const file = await tsian.workspace.read({ scope: 'effective', path }); if (!file || typeof file.content !== 'string') return { id, path, missing: true }; let data; try { data = JSON.parse(file.content); } catch (e) { return { id, path, missing: true, parseError: true }; } return { id, path, data: isRecord(data) ? data : null, missing: !isRecord(data) }; } catch (e) { return { id, path, missing: true }; }",
  "}",
  "function collectContentRefs(data) {",
  "  if (!isRecord(data) || !Array.isArray(data.contents)) return [];",
  "  return data.contents.filter((c) => isRecord(c) && typeof c.ref === 'string' && c.ref.trim()).map((c) => ({ ref: c.ref.trim(), name: typeof c.name === 'string' ? c.name : undefined, quantity: c.quantity }));",
  "}",
  "async function resolveEntities(input, tsian, signal) {",
  "  try {",
  "    signal.throwIfAborted();",
  "    if (!isRecord(input)) fail('RESOLVE_INPUT_INVALID', 'resolve_entities input must be an object.');",
  "    if (!Array.isArray(input.refs) || input.refs.length === 0) fail('RESOLVE_REFS_REQUIRED', 'refs must be a non-empty array of entity ids.');",
  "    if (input.refs.length > 60) fail('RESOLVE_REFS_TOO_MANY', 'refs must contain at most 60 ids.', { count: input.refs.length });",
  "    const refs = input.refs.map((r) => parseEntityId(r).id);",
  "    const depth = normalizeDepth(input.depth);",
  "    const withRelations = input.withRelations === true;",
  "    const withScene = input.withScene === true;",
  "    const visited = new Set();",
  "    const entities = [];",
  "    const expanded = [];",
  "    async function expand(id, remainingDepth) {",
  "      if (visited.has(id)) { expanded.push({ ref: id, cycle: true }); return; }",
  "      visited.add(id);",
  "      const entry = await readEntityFile(tsian, id);",
  "      entities.push(entry);",
  "      if (entry.missing || !entry.data || remainingDepth <= 0) { if (entry.data) { const refs = collectContentRefs(entry.data); if (refs.length) expanded.push({ ref: id, contents: refs, depth: 0 }); } return; }",
  "      const contentRefs = collectContentRefs(entry.data);",
  "      if (contentRefs.length === 0) return;",
  "      expanded.push({ ref: id, contents: contentRefs, depth: remainingDepth });",
  "      for (const c of contentRefs) { signal.throwIfAborted(); await expand(c.ref, remainingDepth - 1); }",
  "    }",
  "    for (const id of refs) { signal.throwIfAborted(); await expand(id, depth); }",
  "    let relationships = undefined;",
  "    if (withRelations) {",
  "      relationships = [];",
  "      for (const id of refs) { signal.throwIfAborted(); const scope = relationshipScopeFromId(id); const path = 'save/relationships/' + scope + '.json'; const data = await readJsonSafe(tsian, path); if (data && isRecord(data) && Array.isArray(data.edges)) relationships.push({ subject: id, path, edges: data.edges }); }",
  "    }",
  "    let scenes = undefined;",
  "    if (withScene) {",
  "      scenes = [];",
  "      const runtime = await readJsonSafe(tsian, 'save/playthrough/runtime.json');",
  "      const activeSceneIds = isRecord(runtime) && Array.isArray(runtime.activeSceneIds) ? runtime.activeSceneIds.filter((s) => typeof s === 'string' && s.trim()).map((s) => s.trim()) : [];",
  "      const resolvedIds = new Set(refs);",
  "      for (const sceneId of activeSceneIds) { signal.throwIfAborted(); const localId = sceneId.startsWith('scene:') ? sceneId.slice(6) : sceneId; const data = await readJsonSafe(tsian, 'save/scenes/' + localId + '.json'); if (!data || !isRecord(data) || !Array.isArray(data.present)) continue; const presentRefs = data.present.filter((p) => isRecord(p) && typeof p.ref === 'string').map((p) => p.ref); if (presentRefs.some((r) => resolvedIds.has(r))) scenes.push({ id: sceneId, name: typeof data.name === 'string' ? data.name : undefined, present: data.present }); }",
  "    }",
  "    tsian.trace('entities_resolved', { refCount: refs.length, depth, expandedCount: expanded.length, withRelations, withScene, sceneCount: scenes ? scenes.length : 0 });",
  "    return { entities, expanded, relationships, scenes };",
  "  } catch (error) {",
  "    tsian.trace('entities_resolve_failed', { code: error && error.code || 'RESOLVE_FAILED', message: error && error.message || String(error), details: error && error.details });",
  "    throw error;",
  "  }",
  "}",
  "return resolveEntities(input, tsian, signal);",
])


const OPENING_INITIALIZATION_SKILL_MD = text([
  "---",
  "name: 小说开局初始化",
  "description: 为刚导入的小说建立开局资料：阅读足够的开头剧情，整理初始人物、地点、势力、设定与开局场景，写入第一版 director brief、实体、关系、场景和阅读进度。",
  "---",
  "",
  "# 小说开局初始化",
  "",
  "当玩家确认小说导入和章节切分后，使用本 Skill 建立第一版开局资料。这是开局一次性建档，不是推进期维护。目标不是理解整本书，而是读到一段足够支撑开局的连续剧情，并把成果落到后续游玩能读到的正式路径。",
  "",
  "## 产出落点",
  "",
  "commit 一次性写入以下正式契约路径（不写 `save/understanding/`）:",
  "",
  "- `save/entities/<type>/<localId>.json` — 开局实体（人物/地点/势力/设定/物品/容器）。",
  "- `save/scenes/<localId>.json` — 开局场景（当前局面有谁、在哪）。",
  "- `save/relationships/<scope>.json` — 开局涉及人物的关系（一 subject 一文件）。",
  "- `save/director/current-brief.md` + `.meta.json` — 开局 brief（master 游玩时直接读）。",
  "- `save/playthrough/frontier.json` — 阅读进度。",
  "- `save/playthrough/understanding-summary.json` — 完成摘要（前端读以判断完成态）。",
  "- `save/playthrough/runtime.json` — 更新 activeSceneIds 指向开局场景。",
  "",
  "开局成果直接进入游玩回路: master 的 contextPaths 已含 director brief 与 runtime，开局后即可读到，无需额外桥接。",
  "",
  "## 工作步骤",
  "",
  "### 1. inspect_source_opening — 观察导入 source",
  "",
  "调用 `inspect_source_opening` 观察书名、章节数和前部章节预览。判断小说类型与可能的实体类别（修仙/悬疑/科幻/都市...各有高频实体类别）。",
  "",
  "### 2. read_opening_slice — 连续阅读开头剧情",
  "",
  "调用 `read_opening_slice` 连续阅读开头章节。**是否继续读由剧情充分性决定**，不按固定章节数机械停止。读够的判据:",
  "",
  "- 主要角色已登场且有可辨识的身份/动机。",
  "- 至少一个冲突或张力已经建立（开局的 inciting situation）。",
  "- 开局场景可定（玩家能介入的起点位置/情境）。",
  "- 第一幕可以起（有可推进的近期目标）。",
  "",
  "护栏（不是停止主因）: 默认在累计约 60k 字或读够后停止；超长篇可少读几章，短篇可一次读完。记录每个读到的章节（脚本返回值含 path/index/title）。",
  "",
  "### 3. commit_opening_understanding — 一次性提交理解包",
  "",
  "调用 `commit_opening_understanding` 提交完整开局资料。提交工具会在写入时校验结构和 source 引用；返回错误时按错误修正后重试，不放弃。",
  "",
  "## 实体抽取指引",
  "",
  "### 类型清单（用这些前缀，不自创）",
  "",
  "- `character:` — 人物。",
  "- `location:` — 地点。",
  "- `faction:` — 势力/组织/门派。",
  "- `setting:` — 设定/规则/体系（修炼体系、世界规则、时代背景等）。",
  "- `item:` — 开局关键物品（按需，非每本都抽）。",
  "- `container:` — 开局就有且重要的容器（按需）。",
  "",
  "id 用 `<type>:<localId>`，中文 localId 允许，不含 `/ \\ : NUL . ..`。例: `character:萧玄`、`location:青玄门山门`、`faction:青玄门`、`setting:修炼体系`。",
  "",
  "### 粒度",
  "",
  "只抽开局窗口内登场/提及且对开局有用的实体。背景提及但不开局介入的不抽（推进期 post 再补）。宁少勿滥: 开局用不上的角色不建实体。",
  "",
  "### 字段",
  "",
  "每实体至少 `id` / `name` / `brief`。按需加:",
  "- `sourceRefs` — 指向读到的章节路径（必须真实存在，脚本会校验）。",
  "- `tags` — 轻量标签。",
  "- `aliases` — 别名/称号。",
  "- `origin` — 开局实体都是 `canon`。",
  "",
  "完整字段手册见 `docs/novel-airp-schema-reference.md`（需要时 workspace.read 查阅）。",
  "",
  "## brief 段落结构（写进 director）",
  "",
  "`brief` 是面向后续 master/post 的开局方向，简洁可执行，包含:",
  "",
  "- **开局氛围** — 一两句定调。",
  "- **可用素材** — 开局已登场的关键人物/地点/势力/冲突。",
  "- **第一幕场景** — 玩家可介入的起点。",
  "- **spoiler 边界** — 只写开局窗口内事实，不提未来剧情。",
  "",
  "## candidateCharacters 选取",
  "",
  "开局窗口内登场、有足够信息可供玩家选择扮演的原著角色，最多 8 个，每人 `name` + `brief`（一句话定位）。若无合适原著角色（主角已固定或信息不足），给空数组（后续走原创角色流程）。",
  "",
  "## scene 组装",
  "",
  "从读到的开局确定一个开局场景，提交时填 `scene`:",
  "",
  "- `id` — `scene:<localId>`，如 `scene:山门冲突`。",
  "- `name` — 场景名。",
  "- `location` — `{ ref, name }` 指向地点实体（必须在本次 entities 或已存在）。",
  "- `present` — 开局在场人物数组，每项 `{ ref, name, brief, status? }`，ref 指向本次/已有实体。present 是导航摘要非实体副本。",
  "",
  "## relationships 组装",
  "",
  "开局窗口内已明确的人物间关系（隶属/敌对/师徒/亲属等）。提交时填 `relationships`，按 subject 分组（一人物一 subject）:",
  "",
  "- `subject` — 主体实体 id。",
  "- `edges` — 数组，每项 `{ to, type, since?, note? }`，`to` 指向目标实体。",
  "- **双向关系两边都给 edges**（萧玄有指向赵长老的敌对 edge，赵长老也要有指向萧玄的对称 edge）。",
  "- 单向关系（如隶属）只写从属方。",
  "",
  "## frontier.notes 写法",
  "",
  "写为什么这个窗口足够开局: 哪些 inciting situation / protagonist context / conflict / setting cues 让你判断读够了。这也是 commit `window.reason` 的内容。",
  "",
  "## window.chapters 组装",
  "",
  "从 `read_opening_slice` 返回值的 `window.chapters` 直接取（含 path/index/title/charactersRead），commit 的 `window.chapters` 复用这些字段，`reason` 写上面的判断依据。",
  "",
  "## 重试策略",
  "",
  "commit 返回校验错误时按错误 code/message 修正后重试，不放弃。常见错误:",
  "",
  "- `OPENING_SOURCE_REF_UNKNOWN` — sourceRefs/window chapter path 指向不存在章节 → 检查 path 是否来自 read 结果。",
  "- `OPENING_ENTITY_ID_INVALID` — id 格式错 → 改成 `<type>:<localId>`。",
  "- `OPENING_REF_UNKNOWN` / `OPENING_RELATIONSHIP_SUBJECT_UNKNOWN` / `OPENING_RELATIONSHIP_TO_UNKNOWN` — scene/relationship 的 ref 指向不存在的实体 → 确认该实体在本次 entities 或已存在。",
  "- `OPENING_SCENE_PRESENT_REQUIRED` — 场景 present 不能为空。",
  "- 缺必填 → 补齐。",
  "",
  "## spoiler-safe",
  "",
  "只使用开头窗口中读到的内容。不推断、不剧透未来剧情。brief 和实体都只反映开局已知事实。",
  "",
  "```json tsian-actions",
  "[",
  "  {",
  "    \"name\": \"inspect_source_opening\",",
  "    \"description\": \"Inspect imported source metadata and early chapter previews before choosing an opening reading window.\",",
  "    \"inputSchema\": { \"type\": \"object\", \"properties\": { \"previewCount\": { \"type\": \"number\" }, \"previewCharacters\": { \"type\": \"number\" } } },",
  "    \"outputSchema\": { \"type\": \"object\" },",
  "    \"executor\": { \"type\": \"browser_script\", \"path\": \"scripts/inspect-source-opening.js\", \"timeoutMs\": 10000 }",
  "  },",
  "  {",
  "    \"name\": \"read_opening_slice\",",
  "    \"description\": \"Read a continuous opening slice from the imported source for plot-based initialization judgment.\",",
  "    \"inputSchema\": { \"type\": \"object\", \"properties\": { \"startIndex\": { \"type\": \"number\" }, \"endIndex\": { \"type\": \"number\" }, \"maxCharacters\": { \"type\": \"number\" } } },",
  "    \"outputSchema\": { \"type\": \"object\" },",
  "    \"executor\": { \"type\": \"browser_script\", \"path\": \"scripts/read-opening-slice.js\", \"timeoutMs\": 10000 }",
  "  },",
  "  {",
  "    \"name\": \"commit_opening_understanding\",",
  "    \"description\": \"Validate and write the initial opening understanding package: entities, scene, relationships, director brief, frontier, understanding summary, and runtime scene pointer.\",",
  "    \"inputSchema\": { \"type\": \"object\", \"required\": [\"schema\", \"window\", \"brief\", \"entities\", \"frontier\", \"scene\"], \"properties\": { \"schema\": { \"type\": \"string\" }, \"window\": { \"type\": \"object\" }, \"brief\": { \"type\": \"string\" }, \"entities\": { \"type\": \"array\" }, \"candidateCharacters\": { \"type\": \"array\" }, \"frontier\": { \"type\": \"object\" }, \"summary\": { \"type\": \"string\" }, \"scene\": { \"type\": \"object\" }, \"relationships\": { \"type\": \"array\" }, \"activeSceneId\": { \"type\": \"string\" } } },",
  "    \"outputSchema\": { \"type\": \"object\" },",
  "    \"executor\": { \"type\": \"browser_script\", \"path\": \"scripts/commit-opening-understanding.js\", \"timeoutMs\": 10000 }",
  "  }",
  "]",
  "```",
])

const OPENING_SCRIPT_COMMON = text([
  "const OPENING_SCHEMA = 'tsian.opening.initial-understanding.v1';",
  "const MANIFEST_PATH = 'save/source/manifest.json';",
  "const CHAPTER_INDEX_PATH = 'save/source/chapters.index.json';",
  "function isRecord(value) { return typeof value === 'object' && value !== null && !Array.isArray(value); }",
  "function fail(code, message, details) { const error = new Error(message); error.code = code; if (details !== undefined) error.details = details; throw error; }",
  "function parseJson(content, path) { try { return JSON.parse(content); } catch (error) { fail('OPENING_JSON_INVALID', path + ' is not valid JSON: ' + (error && error.message || error), { path }); } }",
  "async function readJson(tsian, path) { const file = await tsian.workspace.read({ scope: 'effective', path }); if (!file || typeof file.content !== 'string') fail('OPENING_FILE_MISSING', 'Required file is missing.', { path }); return parseJson(file.content, path); }",
  "async function readText(tsian, path) { try { const file = await tsian.workspace.read({ scope: 'effective', path }); return file && typeof file.content === 'string' ? file.content : ''; } catch (error) { return ''; } }",
  "function cleanText(text) { return String(text || '').replace(/^#\\s+.*\\n+/, '').replace(/\\n{3,}/g, '\\n\\n').trim(); }",
  "function clipText(text, limit) { const cleaned = cleanText(text); return cleaned.length <= limit ? cleaned : cleaned.slice(0, limit).trimEnd() + '……'; }",
  "function normalizePositiveInt(value, fallback, min, max) { const number = Number(value); if (!Number.isFinite(number)) return fallback; return Math.max(min, Math.min(max, Math.floor(number))); }",
  "async function loadSource(tsian) {",
  "  const manifest = await readJson(tsian, MANIFEST_PATH);",
  "  const index = await readJson(tsian, CHAPTER_INDEX_PATH);",
  "  if (!isRecord(manifest) || manifest.status !== 'ready') fail('OPENING_SOURCE_NOT_READY', 'Imported source manifest is not ready.', { path: MANIFEST_PATH });",
  "  if (!isRecord(index) || !Array.isArray(index.chapters)) fail('OPENING_CHAPTER_INDEX_INVALID', 'Chapter index must contain chapters array.', { path: CHAPTER_INDEX_PATH });",
  "  const chapters = index.chapters.map((chapter, index) => {",
  "    if (!isRecord(chapter) || typeof chapter.path !== 'string') fail('OPENING_CHAPTER_INVALID', 'Each chapter must include a path.', { index });",
  "    return { index: index + 1, title: typeof chapter.title === 'string' && chapter.title.trim() ? chapter.title.trim() : '第 ' + (index + 1) + ' 章', path: chapter.path, characters: typeof chapter.characters === 'number' ? chapter.characters : null };",
  "  });",
  "  return { manifest, chapters };",
  "}",
])

const OPENING_INSPECT_SOURCE_SCRIPT_JS = `${OPENING_SCRIPT_COMMON}${text([
  "async function inspectSourceOpening(input, tsian, signal) {",
  "  try {",
  "    signal.throwIfAborted();",
  "    const previewCount = normalizePositiveInt(input && input.previewCount, 8, 1, 20);",
  "    const previewCharacters = normalizePositiveInt(input && input.previewCharacters, 700, 120, 2000);",
  "    const source = await loadSource(tsian);",
  "    const earlyChapters = [];",
  "    for (const chapter of source.chapters.slice(0, previewCount)) {",
  "      signal.throwIfAborted();",
  "      const content = await readText(tsian, chapter.path);",
  "      earlyChapters.push({ ...chapter, preview: clipText(content, previewCharacters) });",
  "    }",
  "    const result = { schema: OPENING_SCHEMA, title: source.manifest.title || '导入小说', totalCharacters: source.manifest.totalCharacters || 0, chapterCount: source.chapters.length, earlyChapters };",
  "    tsian.trace('opening_source_inspected', { title: result.title, chapterCount: result.chapterCount, previewCount: earlyChapters.length });",
  "    return result;",
  "  } catch (error) {",
  "    tsian.trace('opening_source_inspect_failed', { code: error && error.code || 'OPENING_INSPECT_FAILED', message: error && error.message || String(error), details: error && error.details });",
  "    throw error;",
  "  }",
  "}",
  "return inspectSourceOpening(input, tsian, signal);",
])}`

const OPENING_READ_SLICE_SCRIPT_JS = `${OPENING_SCRIPT_COMMON}${text([
  "async function readOpeningSlice(input, tsian, signal) {",
  "  try {",
  "    signal.throwIfAborted();",
  "    const source = await loadSource(tsian);",
  "    const startIndex = normalizePositiveInt(input && input.startIndex, 1, 1, Math.max(1, source.chapters.length));",
  "    const defaultEnd = Math.min(source.chapters.length, startIndex + 2);",
  "    const endIndex = normalizePositiveInt(input && input.endIndex, defaultEnd, startIndex, source.chapters.length);",
  "    const maxCharacters = normalizePositiveInt(input && input.maxCharacters, 60000, 4000, 120000);",
  "    let totalCharacters = 0;",
  "    const selectedChapters = [];",
  "    const parts = [];",
  "    for (const chapter of source.chapters.slice(startIndex - 1, endIndex)) {",
  "      signal.throwIfAborted();",
  "      const content = await readText(tsian, chapter.path);",
  "      const cleaned = cleanText(content);",
  "      const remaining = maxCharacters - totalCharacters;",
  "      if (remaining <= 0) break;",
  "      const used = cleaned.length > remaining ? cleaned.slice(0, remaining) : cleaned;",
  "      totalCharacters += used.length;",
  "      selectedChapters.push({ ...chapter, charactersRead: used.length, truncated: used.length < cleaned.length });",
  "      parts.push('# ' + chapter.title + '\\n\\n' + used);",
  "      if (totalCharacters >= maxCharacters) break;",
  "    }",
  "    const result = { schema: OPENING_SCHEMA, window: { startIndex, endIndex: selectedChapters.length ? selectedChapters[selectedChapters.length - 1].index : startIndex, maxCharacters, totalCharacters, chapters: selectedChapters }, text: parts.join('\\n\\n') };",
  "    tsian.trace('opening_slice_read', { startIndex: result.window.startIndex, endIndex: result.window.endIndex, totalCharacters, chapterCount: selectedChapters.length });",
  "    return result;",
  "  } catch (error) {",
  "    tsian.trace('opening_slice_read_failed', { code: error && error.code || 'OPENING_SLICE_FAILED', message: error && error.message || String(error), details: error && error.details });",
  "    throw error;",
  "  }",
  "}",
  "return readOpeningSlice(input, tsian, signal);",
])}`

const OPENING_COMMIT_UNDERSTANDING_SCRIPT_JS = `${OPENING_SCRIPT_COMMON}${text([
  "function normalizeString(value, code, label, maxLength) {",
  "  if (typeof value !== 'string' || !value.trim()) fail(code, label + ' must be a non-empty string.');",
  "  const normalized = value.trim();",
  "  if (maxLength && normalized.length > maxLength) fail(code + '_TOO_LONG', label + ' is too long.', { maxLength, length: normalized.length });",
  "  return normalized;",
  "}",
  "function normalizeSegment(value, label) {",
  "  const segment = normalizeString(value, 'OPENING_ENTITY_ID_INVALID', label, 80);",
  "  if (segment === '.' || segment === '..' || /[\\/:\\0]/.test(segment)) fail('OPENING_ENTITY_ID_INVALID', label + ' must not contain path separators, colon, NUL, . or ...', { value });",
  "  return segment;",
  "}",
  "function normalizeEntityId(rawId, label) {",
  "  const id = normalizeString(rawId, 'OPENING_ENTITY_ID_REQUIRED', label, 120);",
  "  const parts = id.split(':');",
  "  if (parts.length !== 2) fail('OPENING_ENTITY_ID_INVALID', label + ' must use <type>:<localId>.', { id });",
  "  const type = normalizeSegment(parts[0], 'Entity type');",
  "  const localId = normalizeSegment(parts[1], 'Entity localId');",
  "  return { id: type + ':' + localId, type, localId };",
  "}",
  "function normalizeEntity(rawEntity, index) {",
  "  if (!isRecord(rawEntity)) fail('OPENING_ENTITY_INVALID', 'Each entity must be an object.', { index });",
  "  const parsed = normalizeEntityId(rawEntity.id, 'Entity id');",
  "  const entity = { ...rawEntity, id: parsed.id, name: normalizeString(rawEntity.name, 'OPENING_ENTITY_NAME_REQUIRED', 'Entity name', 120), brief: normalizeString(rawEntity.brief, 'OPENING_ENTITY_BRIEF_REQUIRED', 'Entity brief', 1000) };",
  "  const sourceRefs = Array.isArray(rawEntity.sourceRefs) ? rawEntity.sourceRefs.filter((ref) => typeof ref === 'string' && ref.trim()).map((ref) => ref.trim()) : [];",
  "  entity.sourceRefs = sourceRefs;",
  "  return { path: 'save/entities/' + parsed.type + '/' + parsed.localId + '.json', entity };",
  "}",
  "function normalizeCandidate(rawCandidate, index) {",
  "  if (!isRecord(rawCandidate)) fail('OPENING_CANDIDATE_INVALID', 'Each candidate character must be an object.', { index });",
  "  return { id: typeof rawCandidate.id === 'string' ? rawCandidate.id.trim() : '', name: normalizeString(rawCandidate.name, 'OPENING_CANDIDATE_NAME_REQUIRED', 'Candidate name', 120), brief: normalizeString(rawCandidate.brief, 'OPENING_CANDIDATE_BRIEF_REQUIRED', 'Candidate brief', 500) };",
  "}",
  "function normalizeWindow(rawWindow, knownPaths) {",
  "  if (!isRecord(rawWindow)) fail('OPENING_WINDOW_INVALID', 'Window must be an object.');",
  "  const startIndex = normalizePositiveInt(rawWindow.startIndex, 1, 1, 999999);",
  "  const endIndex = normalizePositiveInt(rawWindow.endIndex, startIndex, startIndex, 999999);",
  "  const reason = normalizeString(rawWindow.reason, 'OPENING_WINDOW_REASON_REQUIRED', 'Window reason', 1000);",
  "  const chapters = Array.isArray(rawWindow.chapters) ? rawWindow.chapters : [];",
  "  const normalizedChapters = chapters.map((chapter, index) => {",
  "    if (!isRecord(chapter)) fail('OPENING_WINDOW_CHAPTER_INVALID', 'Window chapters must be objects.', { index });",
  "    const path = normalizeString(chapter.path, 'OPENING_WINDOW_CHAPTER_PATH_REQUIRED', 'Window chapter path', 240);",
  "    if (!knownPaths.has(path)) fail('OPENING_SOURCE_REF_UNKNOWN', 'Window chapter path is not in imported chapter index.', { path });",
  "    return { index: normalizePositiveInt(chapter.index, index + 1, 1, 999999), title: typeof chapter.title === 'string' ? chapter.title.trim() : '', path };",
  "  });",
  "  return { startIndex, endIndex, reason, chapters: normalizedChapters };",
  "}",
  "function ensureSourceRefsKnown(items, knownPaths) {",
  "  for (const item of items) {",
  "    for (const ref of item.entity.sourceRefs || []) {",
  "      if (!knownPaths.has(ref)) fail('OPENING_SOURCE_REF_UNKNOWN', 'Entity sourceRefs must point to imported chapter files.', { entity: item.entity.id, ref });",
  "    }",
  "  }",
  "}",
  "function normalizeRef(rawRef, label, knownEntityIds, context) {",
  "  if (!isRecord(rawRef)) fail('OPENING_REF_INVALID', label + ' must be an object { ref, name }.', context);",
  "  const parsed = normalizeEntityId(rawRef.ref, label + ' ref');",
  "  if (knownEntityIds && !knownEntityIds.has(parsed.id)) fail('OPENING_REF_UNKNOWN', label + ' ref must point to an entity in this commit or an existing entity.', { ...context, ref: parsed.id });",
  "  return { ref: parsed.id, name: normalizeString(rawRef.name, 'OPENING_REF_NAME_REQUIRED', label + ' name', 120) };",
  "}",
  "function normalizeScene(rawScene, knownEntityIds) {",
  "  if (!isRecord(rawScene)) fail('OPENING_SCENE_INVALID', 'Opening scene must be an object.');",
  "  const parsed = normalizeEntityId(rawScene.id, 'Scene id');",
  "  if (parsed.type !== 'scene') fail('OPENING_SCENE_TYPE_INVALID', 'Scene id must use scene:<localId>.', { id: parsed.id });",
  "  const name = normalizeString(rawScene.name, 'OPENING_SCENE_NAME_REQUIRED', 'Scene name', 120);",
  "  const location = normalizeRef(rawScene.location, 'Scene location', knownEntityIds, { scene: parsed.id });",
  "  const presentRaw = Array.isArray(rawScene.present) ? rawScene.present : [];",
  "  if (presentRaw.length === 0) fail('OPENING_SCENE_PRESENT_REQUIRED', 'Scene present must list at least one entity.', { scene: parsed.id });",
  "  const present = presentRaw.map((item, index) => {",
  "    const ref = normalizeRef(item, 'Scene present[' + index + ']', knownEntityIds, { scene: parsed.id, index });",
  "    return { ref: ref.ref, name: ref.name, brief: normalizeString(item && item.brief, 'OPENING_SCENE_PRESENT_BRIEF_REQUIRED', 'Scene present brief', 1000), status: typeof item && item.status === 'string' && item.status.trim() ? item.status.trim() : undefined };",
  "  });",
  "  return { id: parsed.id, name, location, present };",
  "}",
  "function scopeFromSubject(subjectId) {",
  "  const parsed = normalizeEntityId(subjectId, 'Relationship subject');",
  "  return parsed.type + '-' + parsed.localId;",
  "}",
  "function normalizeRelationships(rawRelationships, knownEntityIds) {",
  "  if (!Array.isArray(rawRelationships)) return [];",
  "  const seen = new Set();",
  "  const result = [];",
  "  for (const raw of rawRelationships) {",
  "    if (!isRecord(raw)) fail('OPENING_RELATIONSHIP_INVALID', 'Each relationship must be an object { subject, edges }.');",
  "    const subjectParsed = normalizeEntityId(raw.subject, 'Relationship subject');",
  "    if (knownEntityIds && !knownEntityIds.has(subjectParsed.id)) fail('OPENING_RELATIONSHIP_SUBJECT_UNKNOWN', 'Relationship subject must point to an entity in this commit or an existing entity.', { subject: subjectParsed.id });",
  "    const scope = scopeFromSubject(raw.subject);",
  "    if (seen.has(scope)) fail('OPENING_RELATIONSHIP_DUPLICATE_SUBJECT', 'Duplicate relationship subject in this commit.', { subject: subjectParsed.id });",
  "    seen.add(scope);",
  "    const edgesRaw = Array.isArray(raw.edges) ? raw.edges : [];",
  "    if (edgesRaw.length === 0) fail('OPENING_RELATIONSHIP_EDGES_REQUIRED', 'Relationship must have at least one edge.', { subject: subjectParsed.id });",
  "    const edges = edgesRaw.map((edge, index) => {",
  "      if (!isRecord(edge)) fail('OPENING_RELATIONSHIP_EDGE_INVALID', 'Each edge must be an object.', { subject: subjectParsed.id, index });",
  "      const toParsed = normalizeEntityId(edge.to, 'Edge to');",
  "      if (knownEntityIds && !knownEntityIds.has(toParsed.id)) fail('OPENING_RELATIONSHIP_TO_UNKNOWN', 'Edge to must point to an entity in this commit or an existing entity.', { subject: subjectParsed.id, to: toParsed.id });",
  "      return { to: toParsed.id, type: normalizeString(edge.type, 'OPENING_RELATIONSHIP_TYPE_REQUIRED', 'Edge type', 60), since: typeof edge.since === 'number' ? edge.since : 0, until: typeof edge.until === 'number' ? edge.until : undefined, note: typeof edge.note === 'string' && edge.note.trim() ? edge.note.trim() : undefined };",
  "    });",
  "    result.push({ subject: subjectParsed.id, edges, scope });",
  "  }",
  "  return result;",
  "}",
  "async function loadExistingEntityIds(tsian) {",
  "  try { const list = await tsian.workspace.list({ scope: 'effective', path: 'save/entities' }); return new Set((list || []).map((f) => f.path).filter((p) => /^save\\/entities\\/[^/]+\\/[^/]+\\.json$/.test(p)).map((p) => { const seg = p.slice('save/entities/'.length).replace(/\\.json$/, '').split('/'); return seg[0] + ':' + seg[1]; })); } catch (error) { return new Set(); }",
  "}",
  "async function commitOpeningUnderstanding(input, tsian, signal) {",
  "  try {",
  "    signal.throwIfAborted();",
  "    if (!isRecord(input)) fail('OPENING_COMMIT_INVALID', 'Commit input must be an object.');",
  "    if (input.schema !== OPENING_SCHEMA) fail('OPENING_SCHEMA_INVALID', 'Commit schema is invalid.', { expected: OPENING_SCHEMA, actual: input.schema });",
  "    const source = await loadSource(tsian);",
  "    const knownPaths = new Set(source.chapters.map((chapter) => chapter.path));",
  "    const window = normalizeWindow(input.window, knownPaths);",
  "    const brief = normalizeString(input.brief, 'OPENING_BRIEF_REQUIRED', 'Opening brief', 12000);",
  "    const summary = typeof input.summary === 'string' && input.summary.trim() ? input.summary.trim() : brief.slice(0, 240);",
  "    if (!Array.isArray(input.entities) || input.entities.length === 0) fail('OPENING_ENTITIES_REQUIRED', 'At least one opening entity is required.');",
  "    const entities = input.entities.map(normalizeEntity);",
  "    ensureSourceRefsKnown(entities, knownPaths);",
  "    const knownEntityIds = await loadExistingEntityIds(tsian);",
  "    for (const item of entities) knownEntityIds.add(item.entity.id);",
  "    const candidateCharacters = Array.isArray(input.candidateCharacters) ? input.candidateCharacters.map(normalizeCandidate) : entities.filter((item) => item.entity.id.startsWith('character:')).slice(0, 8).map((item) => ({ id: item.entity.id, name: item.entity.name, brief: item.entity.brief }));",
  "    if (!isRecord(input.frontier)) fail('OPENING_FRONTIER_INVALID', 'Frontier must be an object.');",
  "    const extractedThrough = typeof input.frontier.extractedThrough === 'string' && input.frontier.extractedThrough.trim() ? input.frontier.extractedThrough.trim() : (window.chapters[window.chapters.length - 1] && window.chapters[window.chapters.length - 1].path) || null;",
  "    if (extractedThrough && !knownPaths.has(extractedThrough)) fail('OPENING_SOURCE_REF_UNKNOWN', 'frontier.extractedThrough must point to an imported chapter file.', { extractedThrough });",
  "    const scene = normalizeScene(input.scene, knownEntityIds);",
  "    const relationships = normalizeRelationships(input.relationships, knownEntityIds);",
  "    const activeSceneId = typeof input.activeSceneId === 'string' && input.activeSceneId.trim() ? input.activeSceneId.trim() : scene.id;",
  "    if (activeSceneId !== scene.id) fail('OPENING_ACTIVE_SCENE_MISMATCH', 'activeSceneId must match the opening scene id for initialization.', { activeSceneId, sceneId: scene.id });",
  "    const committedAt = new Date().toISOString();",
  "    const sceneFile = { id: scene.id, name: scene.name, location: scene.location, present: scene.present, status: 'active', updatedTurn: 0, updatedBy: 'world-architect' };",
  "    const frontier = { sourceWindow: { start: window.startIndex, end: window.endIndex, chapters: window.chapters }, extractedThrough, notes: normalizeString(input.frontier.notes || window.reason, 'OPENING_FRONTIER_NOTES_REQUIRED', 'Frontier notes', 1000), updatedAt: committedAt, updatedBy: 'world-architect' };",
  "    const briefMeta = { basedOn: ['opening-extraction'], updatedAtTurn: 0, scene: { ref: scene.id, name: scene.name }, sourceWindow: frontier.sourceWindow, expiresAfterTurn: null, notes: '' };",
  "    const understandingSummary = { schema: OPENING_SCHEMA, status: 'ready', title: source.manifest.title || '导入小说', summary, entityCount: entities.length, candidateCharacters, sourceWindow: { start: window.startIndex, end: window.endIndex }, extractedThrough, committedAt };",
  "    const runtimeUpdate = { turn: 0, activeSceneIds: [scene.id], activeScene: { ref: scene.id, name: scene.name }, player: { character: null, location: null }, inventory: null, status: [], updatedAtTurn: 0, updatedBy: 'world-architect' };",
  "    const sceneLocalId = scene.id.split(':')[1];",
  "    const writes = [",
  "      { path: 'save/director/current-brief.md', content: brief + '\\n', mediaType: 'text/markdown' },",
  "      { path: 'save/director/current-brief.meta.json', content: JSON.stringify(briefMeta, null, 2) + '\\n', mediaType: 'application/json' },",
  "      { path: 'save/scenes/' + sceneLocalId + '.json', content: JSON.stringify(sceneFile, null, 2) + '\\n', mediaType: 'application/json' },",
  "      ...relationships.map((rel) => ({ path: 'save/relationships/' + rel.scope + '.json', content: JSON.stringify({ subject: rel.subject, edges: rel.edges, updatedTurn: 0, updatedBy: 'world-architect' }, null, 2) + '\\n', mediaType: 'application/json' })),",
  "      { path: 'save/playthrough/frontier.json', content: JSON.stringify(frontier, null, 2) + '\\n', mediaType: 'application/json' },",
  "      { path: 'save/playthrough/understanding-summary.json', content: JSON.stringify(understandingSummary, null, 2) + '\\n', mediaType: 'application/json' },",
  "      { path: 'save/playthrough/runtime.json', content: JSON.stringify(runtimeUpdate, null, 2) + '\\n', mediaType: 'application/json' },",
  "      ...entities.map((item) => ({ path: item.path, content: JSON.stringify({ ...item.entity, updatedBy: 'world-architect', updatedAt: committedAt }, null, 2) + '\\n', mediaType: 'application/json' }))",
  "    ];",
  "    const applied = [];",
  "    for (const write of writes) {",
  "      signal.throwIfAborted();",
  "      const file = await tsian.workspace.write({ scope: 'save-runtime', path: write.path, content: write.content, mediaType: write.mediaType });",
  "      applied.push({ path: file.path, size: file.content.length });",
  "    }",
  "    tsian.trace('opening_understanding_committed', { entityCount: entities.length, candidateCount: candidateCharacters.length, sceneId: scene.id, relationshipCount: relationships.length, writes: applied.map((write) => write.path) });",
  "    return { schema: OPENING_SCHEMA, status: 'ready', writes: applied, entityCount: entities.length, candidateCharacters, sceneId: scene.id, relationshipCount: relationships.length, summaryPath: 'save/playthrough/understanding-summary.json' };",
  "  } catch (error) {",
  "    tsian.trace('opening_understanding_commit_failed', { code: error && error.code || 'OPENING_COMMIT_FAILED', message: error && error.message || String(error), details: error && error.details });",
  "    throw error;",
  "  }",
  "}",
  "return commitOpeningUnderstanding(input, tsian, signal);",
])}`

const TSIAN_FRAMEWORK_KNOWLEDGE_MD = text([
  "# Tsian Framework Knowledge",
  "",
  "Tsian is an Agent-Orchestrated Runtime platform for AIRP. Platform code owns model configuration, local storage, checkpoints, bridge APIs, execution policy, and sandboxing. Gameplay-specific behavior belongs in workspace files, Agents, Skills, and frontend conventions.",
  "",
  "Runtime Workspace is an effective virtual file system composed from Game Card content plus the active save slot mounted at `save/`. Ordinary workspace paths are visible to Agents, Skills, and game frontends. `.tsian/` is platform-owned metadata and is hidden from ordinary workspace APIs.",
  "",
  "Default novel AIRP saves use `save/source/`, `save/schema/`, `save/entities/`, `save/playthrough/`, and `save/director/` for their main gameplay contract.",
])

const SCENES_README_MD = text([
  "# Scenes",
  "",
  "一场景一文件，存于 `save/scenes/<localId>.json`。场景是派生导航视图，记录\"当前局面有谁、在哪\"，不是实体副本。entity 文件是实体权威；scene 的 `present` 摘要从实体派生，丢了可重建，不要反向当作第二权威。",
  "",
  "## 字段",
  "",
  "- `id`：场景 id，`scene:<localId>`。",
  "- `name`：场景名。",
  "- `location`：`{ ref, name }`，指向地点实体。",
  "- `present`：在场实体数组，每项 `{ ref, name, brief, status? }`，只放导航索引需要的摘要，不放实体全量。",
  "- `status`：`active`（当前焦点）/ `background`（仍在发生但非焦点）/ `resolved`（已结束，不删——剧情可回溯）。",
  "- `updatedTurn` / `updatedBy`：维护锚点。",
  "",
  "## 多场景",
  "",
  "原创角色扮演天然双线（主角线 + 原著线），原著本身也常多线。每个场景独立文件，互不干扰。新场景开新文件；旧场景改 `status` 保留。`save/playthrough/runtime.json` 的 `activeSceneIds` 指向当前活跃场景，是导航入口指针，不是场景内容权威。",
  "",
  "## 维护",
  "",
  "post-processing 在场景变动时重写涉及的场景文件。present 摘要从对应 entity 派生刷新。resolved 场景不删（剧情可回溯）；远了再考虑归档到 `save/scenes/archive/`。",
])

const RELATIONSHIPS_README_MD = text([
  "# Relationships",
  "",
  "一 subject 一文件，存于 `save/relationships/<scope>.json`。`<scope>` = subject 实体的 localId（去 `type:` 前缀，如 `character-萧玄`）。吸收长篇小说关系爆炸：一个角色的关系通常几条到几十条，文件小，检索 O(1)——查\"萧玄的全部关系\"直接读该文件。",
  "",
  "## 字段",
  "",
  "- `subject`：主体实体 id，`<type>:<localId>`。",
  "- `edges`：关系条目数组，每项 `{ to, type, since?, until?, note? }`。",
  "  - `to`：目标实体 id。",
  "  - `type`：关系类型自由文本（敌对/师徒/隶属/亲属/...）。",
  "  - `since` / `until`：回合号锚点，表达关系演化（先师徒后决裂可两条 edge 或用 until 标注）。",
  "  - `note`：自然语言说明。",
  "- `updatedTurn` / `updatedBy`：维护锚点。",
  "",
  "## 双向 vs 单向",
  "",
  "双向关系（敌对、师徒、亲属等）**两边各写一条**——萧玄的文件有指向赵长老的 edge，赵长老的文件也有指向萧玄的对称 edge。反向查询靠对称条目命中，不扫全局。单向关系（如隶属）**只写从属方**。",
  "",
  "## 维护",
  "",
  "post-processing 在关系变动时只重写涉及的 subject 文件，不动其它。比单文件全量替换安全。若 post 漏写对称条目，反向查询会退化——这是 post 维护规范必须守的点。",
])

const NOVEL_AIRP_SCHEMA_GUIDE_MD = text([
  "# Novel AIRP Schema 速查指南",
  "",
  "本默认卡支持小说阅读器 AIRP 流程：玩家导入一本小说，源文本存在当前存档，Agent 在游玩中渐进地推导 schema、entities、runtime 状态与 director brief。",
  "",
  "速查层：每回合写数据文件前查本文件。完整字段手册（lifecycle/origin 受控词、status 协议、容器模型、evidence、patch 模板、scene/relationship 完整格式）见 `docs/novel-airp-schema-reference.md`，按需 `workspace.read` 查阅，不常驻。",
  "",
  "## 主路径",
  "",
  "```text",
  "save/source/         # 导入的源文本：manifest、chapters、chunks",
  "save/schema/         # 当前 schema、changelog、deprecated 笔记、Markdown patches",
  "save/entities/       # 语义实体，存为 save/entities/<type>/<localId>.json",
  "save/scenes/         # 场景分片，存为 save/scenes/<localId>.json（一场景一文件）",
  "save/relationships/  # 关系分片，存为 save/relationships/<scope>.json（一 subject 一文件）",
  "save/playthrough/    # player 设置、mode、branch、frontier、runtime 摘要、understanding 摘要",
  "save/director/       # 当前 master-safe 的 director brief 和元数据",
  "```",
  "",
  "Novel AIRP v0 不使用独立的 `save/render/` 层、`save/world/<type>/<entity>/index.json` 一实体一目录、通用的 `_ref` / `_dir` 标记，也不把纯前端 view state 持久化到 workspace 作为主路径。",
  "",
  "## Three-Layer Responsibility",
  "",
  "- **存储层** `save/entities/`：实体本体权威，一实体一文件，扁平。post 整体替换写入。",
  "- **引用层**：实体内 `{ ref, name }` 指向别处，只提一句关联，不承担导航。容器 `contents` 用 ref 链表达嵌套。",
  "- **聚合层** `save/scenes/` + `save/relationships/`：派生导航视图，记录\"当前局面\"与\"实体间关系\"。丢了可重建，不是第二权威。",
  "",
  "判据：这个文件回答\"某实体本体\"还是\"实体间关系/当前局面\"？前者存储层，后者聚合层。",
  "",
  "## 权威归属",
  "",
  "- entity json 是实体权威。",
  "- scene / relationship json 是派生快照（present 摘要从 entity 派生；edges 引用 entity id），丢了可重建。",
  "- `save/playthrough/runtime.json` 的 `activeSceneIds` 是当前活跃场景的指针，不是场景内容权威。",
  "",
  "出现两份相同数据时，必须明确哪处权威、哪处派生、派生如何刷新，避免双 authority。",
  "",
  "## 实体基础",
  "",
  "实体 id 用 `<type>:<localId>`，映射到 `save/entities/<type>/<localId>.json`。必填字段：`id`、`name`、`brief`。",
  "",
  "```json",
  "{",
  "  \"id\": \"character:萧玄\",",
  "  \"name\": \"萧玄\",",
  "  \"brief\": \"青玄门外门弟子，当前卷入山门冲突。\"",
  "}",
  "```",
  "",
  "按需使用推荐字段：`aliases`、`visibility`、`lifecycle`、`origin`、`sourceRefs`、`tags`、`status`、`fields`、`sections`、`updatedAtTurn`、`updatedBy`。",
  "",
  "普通玩家可见数据省略 `visibility`。实体级 `visibility` 默认 `player-known`；嵌套的 `status`、`fields`、`sections` 继承父级，除非显式覆盖。只在例外时用显式的 `hidden`、`future-spoiler` 或 `director-only`。",
  "",
  "`sourceRefs` 默认用简单的路径字符串，例如 `save/source/chapters/chapter-0001.md`。",
  "",
  "## fields vs sections",
  "",
  "- `fields`：稳定 label/value 键值对，前端状态栏/卡片行式渲染。例：境界、当前位置、气血。判据：需要前端按固定行结构渲染。",
  "- `sections`：title/body 段落块，前端详情面板或 Agent 上下文用。例：当前目标、背景故事。判据：段落式描述。",
  "",
  "一个实体可两者都有。`fields` 和 `sections` 都是普通 entity 数据，不是独立 render 层。",
  "",
  "## 前端可读的普通字段",
  "",
  "默认前端可直接从 entity/runtime 文件读取稳定的普通字段：`name`、`brief`、`tags`、`status`、`fields`、`sections`，以及 `save/playthrough/runtime.json` 里的 runtime 摘要。",
  "",
  "不要把 v0 做成万能卡片/仪表/数值/看板引擎。某本特殊小说需要特殊 UI 时，以后再定制前端。",
  "",
  "## 结构化引用",
  "",
  "自然语言散文只是语义搜索原料。不要从散文里解析引用。当某个引用必须可解析时，用显式的结构化 ref：`{ \"ref\": \"character:萧玄\", \"name\": \"萧玄\" }`。",
  "",
  "## Schema 演进",
  "",
  "`save/schema/current.md` 是人类/Agent 可读的权威。默认不要建第二个权威 schema 文件。",
  "",
  "安全的增量变更可直接更新 `current.md` 并追加 `changelog.md`。只有当变更需要决策或可能让玩家/作者意外时，才用 `save/schema/patches/pending/*.md` 写待确认方案。",
  "",
  "待确认 patch 是 Markdown 文件，不是 JSON Patch 操作。被采纳后移到 `save/schema/patches/applied/`，更新 `current.md`，追加 `changelog.md`。",
  "",
  "## Agent 职责",
  "",
  "- `world-architect`：创建初始 schema 草案、开局资料（entities + scene + relationships + director brief），以及后续 schema patches。",
  "- `post-processing`：应用安全的 schema/entity/runtime 更新，回合后维护 scene/relationship 聚合分片，需要确认时写待确认 patch，需要 schema 设计时调用 world-architect。",
  "- `master`：消费当前 brief、runtime 摘要与可见实体数据；不擅自发明 schema。",
  "- `retrieval`：阅读 source、entity、scene、relationship 详情并返回精炼结论。",
])

const NOVEL_AIRP_SCHEMA_REFERENCE_MD = text([
  "# Novel AIRP Schema 详尽参考",
  "",
  "详尽字段手册，按需查阅，不常驻上下文。速查见 `docs/novel-airp-schema-guide.md`。",
  "",
  "## 实体推荐元数据",
  "",
  "```json",
  "{",
  "  \"id\": \"character:萧玄\",",
  "  \"name\": \"萧玄\",",
  "  \"brief\": \"青玄门外门弟子，当前卷入山门冲突。\",",
  "  \"aliases\": [\"萧师弟\"],",
  "  \"origin\": \"canon\",",
  "  \"sourceRefs\": [\"save/source/chapters/chapter-0001.md\"],",
  "  \"tags\": [\"青玄门\", \"外门弟子\"],",
  "  \"status\": [",
  "    { \"id\": \"injury:右臂轻伤\", \"level\": \"minor\", \"description\": \"挥剑时略有迟滞。\" }",
  "  ],",
  "  \"fields\": [",
  "    { \"label\": \"当前位置\", \"value\": \"青玄门山门\" },",
  "    { \"label\": \"境界\", \"value\": \"炼气后期\" }",
  "  ],",
  "  \"sections\": [",
  "    { \"title\": \"当前目标\", \"body\": \"查清山门冲突的起因。\" }",
  "  ],",
  "  \"updatedAtTurn\": 6,",
  "  \"updatedBy\": \"post-processing\"",
  "}",
  "```",
  "",
  "## 受控词表",
  "",
  "### visibility",
  "",
  "```text",
  "player-known      # 玩家面向的叙述/前端安全；省略时默认",
  "hidden            # 玩家当前看不见，但背景 Agent 可用",
  "future-spoiler    # 未来的原著信息；不要泄露进玩家面向的叙述",
  "director-only     # 策划/原著风险材料；master 默认不应使用",
  "```",
  "",
  "普通玩家可见数据省略 `visibility`。实体级默认 `player-known`；嵌套的 `status`/`fields`/`sections` 继承父级，除非显式覆盖。只在例外时加 `visibility`。",
  "",
  "### lifecycle",
  "",
  "```text",
  "candidate    # 已抽取但尚未确认重要",
  "active       # 当前可在游玩中使用",
  "background   # 作为背景存在但非当前焦点",
  "retired      # 已退出当前游玩，除非刻意重新引入",
  "```",
  "",
  "### origin",
  "",
  "```text",
  "canon        # 来自导入的原著小说",
  "branch       # 玩家分支创建或改变",
  "player       # 玩家创建的 persona/偏好/输入",
  "generated    # Agent 创建的运行时材料",
  "```",
  "",
  "如果一个字段表达不清细节，用一段短注释替代，不要引入新的层级结构。",
  "",
  "## Status",
  "",
  "Status v0 是轻量、描述性的。唯一必填字段是 `id`：",
  "",
  "```json",
  "{ \"id\": \"talent:木灵根\" }",
  "```",
  "",
  "Optional fields:",
  "",
  "```json",
  "{",
  "  \"id\": \"debuff:内息紊乱\",",
  "  \"level\": \"medium\",",
  "  \"until\": \"调息恢复或离开战斗\",",
  "  \"description\": \"短时间内不宜强行催动高阶功法。\",",
  "  \"source\": \"technique:青木诀\"",
  "}",
  "```",
  "",
  "- `:` 前的前缀是大类（`buff`/`debuff`/`injury`/`talent`/`constraint`/`condition`/`mode`...）。",
  "- `:` 后的后缀默认是展示/本地名。",
  "- 除非存档显式开启工具/前端管理的数值机制，否则避免对持续时间、叠加、伤害、容量、冷却或数值效果做精确算术。",
  "- post-processing 可以整体替换 `status` 数组，或按 status id 增删/替换。",
  "",
  "## 容器与库存",
  "",
  "背包、储物袋、宝箱、仓库、房间、载具货舱、装备槽可以被建模为容器。容器只是一个 entity，其 `contents` 用 ref 链。",
  "",
  "```json",
  "{",
  "  \"id\": \"container:玩家储物袋\",",
  "  \"name\": \"我的储物袋\",",
  "  \"brief\": \"下品储物法器，空间有限。\",",
  "  \"contents\": [",
  "    { \"ref\": \"item:下品灵石\", \"name\": \"下品灵石\", \"quantity\": 12 },",
  "    { \"ref\": \"container:青玉匣\", \"name\": \"青玉匣\", \"quantity\": 1 }",
  "  ],",
  "  \"capacityNote\": \"接近满载\",",
  "  \"status\": [",
  "    { \"id\": \"constraint:接近满载\", \"description\": \"不宜继续收纳大件物品。\" }",
  "  ],",
  "  \"updatedAtTurn\": 6",
  "}",
  "```",
  "",
  "`container:青玉匣` 自己也是一个 entity 文件，内部再 `contents` 指向丹药。嵌套深度无限，靠 ref 链表达；读取靠批量 skill 按 depth 展开（见兄弟任务 `resolve_entities`），不靠存储结构递归。",
  "",
  "默认容量策略：描述性（`capacityNote`/`near-full`/`full`）为默认；严格数值容量只 opt-in，且应通过 toolkit action 处理。",
  "",
  "## 源引用",
  "",
  "默认用简单的路径字符串：",
  "",
  "```json",
  "\"sourceRefs\": [",
  "  \"save/source/chapters/chapter-0001.md\",",
  "  \"save/source/chunks/chapter-0001-003.md\"",
  "]",
  "```",
  "",
  "If precision is needed later, add a small `evidence` array instead of replacing `sourceRefs`:",
  "",
  "```json",
  "\"evidence\": [",
  "  { \"ref\": \"save/source/chunks/chapter-0001-003.md\", \"note\": \"首次提到青玄门外门弟子身份。\" }",
  "]",
  "```",
  "",
  "## 结构化引用",
  "",
  "只有显式的结构化 id 是可解析的引用：",
  "",
  "```json",
  "{",
  "  \"owner\": { \"ref\": \"character:萧玄\", \"name\": \"萧玄\" },",
  "  \"contents\": [",
  "    { \"ref\": \"item:云纹剑\", \"name\": \"云纹剑\", \"quantity\": 1 }",
  "  ]",
  "}",
  "```",
  "",
  "内联的 `name` 是为了可读性和前端容错而做的去规范化展示快照，不是权威来源。",
  "",
  "## Runtime 变量",
  "",
  "`save/playthrough/runtime.json` 存放高频访问、玩家面向或前端管理的摘要。",
  "",
  "```json",
  "{",
  "  \"turn\": 6,",
  "  \"activeSceneIds\": [\"scene:山门冲突\"],",
  "  \"activeScene\": { \"ref\": \"scene:山门冲突\", \"name\": \"山门冲突\" },",
  "  \"player\": {",
  "    \"character\": { \"ref\": \"character:萧玄\", \"name\": \"萧玄\" },",
  "    \"location\": { \"ref\": \"location:青玄门山门\", \"name\": \"青玄门山门\" }",
  "  },",
  "  \"inventory\": {",
  "    \"primaryContainer\": { \"ref\": \"container:玩家储物袋\", \"name\": \"我的储物袋\" },",
  "    \"state\": \"near-full\"",
  "  },",
  "  \"status\": [",
  "    { \"id\": \"constraint:储物袋接近满载\", \"description\": \"不宜继续收纳大件物品。\" }",
  "  ],",
  "  \"updatedAtTurn\": 6,",
  "  \"updatedBy\": \"post-processing\"",
  "}",
  "```",
  "",
  "`activeSceneIds` 是当前活跃场景的指针数组（导航入口），多场景时以数组为准；`activeScene` 是单场景兼容字段。场景内容权威在 `save/scenes/<id>.json`，runtime 只存指针。",
  "",
  "纯前端 view state（活跃标签、滚动位置、折叠面板、瞬时过滤、悬停状态）默认不应存入 workspace。",
  "",
  "## 场景分片格式",
  "",
  "```json",
  "{",
  "  \"id\": \"scene:山门冲突\",",
  "  \"name\": \"山门冲突\",",
  "  \"location\": { \"ref\": \"location:青玄门山门\", \"name\": \"青玄门山门\" },",
  "  \"present\": [",
  "    { \"ref\": \"character:萧玄\", \"name\": \"萧玄\", \"brief\": \"青玄门外门弟子，当前卷入山门冲突。\", \"status\": \"右臂轻伤\" },",
  "    { \"ref\": \"character:赵长老\", \"name\": \"赵长老\", \"brief\": \"内门执法长老。\" }",
  "  ],",
  "  \"status\": \"active\",",
  "  \"updatedTurn\": 0,",
  "  \"updatedBy\": \"world-architect\"",
  "}",
  "```",
  "",
  "`present` 只放 ref + name + brief + 关键状态摘要，是导航索引非实体副本。`status`: `active`/`background`/`resolved`（resolved 不删，剧情可回溯）。",
  "",
  "## 关系分片格式",
  "",
  "```json",
  "{",
  "  \"subject\": \"character:萧玄\",",
  "  \"edges\": [",
  "    { \"to\": \"character:赵长老\", \"type\": \"敌对\", \"since\": 0, \"note\": \"因山门冲突结怨。\" },",
  "    { \"to\": \"faction:青玄门\", \"type\": \"隶属\", \"since\": 0 }",
  "  ],",
  "  \"updatedTurn\": 0,",
  "  \"updatedBy\": \"world-architect\"",
  "}",
  "```",
  "",
  "`<scope>` 文件名 = subject 的 localId（去 `type:` 前缀，如 `character-萧玄`）。双向关系两边各写一条；单向关系（如隶属）只写从属方。",
  "",
  "## Schema Patch Markdown 模板",
  "",
  "待确认 patch 是 `save/schema/patches/pending/*.md` 下的 Markdown 文件：",
  "",
  "```md",
  "# Schema Patch: 增加宗门贡献点",
  "",
  "Status: pending",
  "Decision: player-required",
  "Proposed by: world-architect",
  "Reason: 新章节出现\"宗门贡献点\"，看起来会持续影响角色行动和资源兑换。",
  "",
  "## 拟议变更",
  "",
  "- 为 `character` entity 增加可选字段：`progression.contributionPoints`。",
  "- 含义：角色当前可用的宗门贡献点。",
  "- 默认不存在；不存在表示未知或不追踪。",
  "",
  "## 受影响文件",
  "",
  "- `save/entities/character/*.json`",
  "- `save/schema/current.md`",
  "",
  "## 迁移",
  "",
  "无需迁移。已有角色不需要补字段。只有剧情明确出现贡献点时才写入。",
  "",
  "## 需要确认",
  "",
  "需要玩家确认，因为这会把\"贡献点\"从背景设定提升为可追踪玩法状态。",
  "",
  "## 回滚",
  "",
  "如果不采用，删除本 patch 即可；不要修改现有 entity。",
  "```",
  "",
  "被采纳后，移到 `save/schema/patches/applied/`，更新 `current.md`，追加 `changelog.md`。",
])

export const DEFAULT_WORKSPACE_FILES: Array<{
  path: string
  content: string
}> = [
  {
    path: "README.md",
    content: text([
      "# Runtime Workspace",
      "",
      "This effective workspace combines Game Card content with active save runtime data. Runtime play data lives under `save/`.",
      "The `.tsian/` directory is platform-owned metadata and is hidden from ordinary Agent, Skill, and frontend workspace APIs.",
      "",
      "This default card uses the novel AIRP workspace contract. Read `docs/novel-airp-schema-guide.md` before changing novel source, schema, entity, playthrough, or director files.",
    ]),
  },
  {
    path: "agents/README.md",
    content: text([
      "# Agents",
      "",
      "Agent 配置放在 `agents/<agent>/agent.json`。`AGENT.md` 是该 Agent 的岗位说明（SOP）——以一个职业身份（而非工具）定义这位同事的职责；人格化的偏好与工作风格放在 `SOUL.md`。",
    ]),
  },
  {
    path: "agents/master/agent.json",
    content: agentConfigContent({
      id: "master",
      title: "Master Agent",
      summary: "The player-facing AIRP narrator. Uses current brief, runtime summaries, and visible entity data; delegates source retrieval and schema maintenance.",
      contacts: ["retrieval", "post-processing", "world-architect"],
      contextPaths: ["README.md", "docs/novel-airp-schema-guide.md", "save/director/current-brief.md", "save/playthrough/runtime.json", "save/schema/current.md"],
      skills: { enabled: [], disabled: [] },
      platformTools: { enabled: ["agent_call", "workspace_read"], disabled: [] },
      workspaceAccess: { level: 1 },
      entryMode: "persistent",
      system: true,
    }),
  },
  {
    path: "agents/master/AGENT.md",
    content: text([
      "# 主述者",
      "",
      "你是这次 AIRP 游玩的主述者——站在玩家面前、直接讲述故事的那一位。",
      "你的职责是把当前 director brief、runtime 摘要与可见的实体资料，编织成玩家当回合读到的叙述，包括正文散文。",
      "当连贯性依赖既成事实时，先读 brief、runtime 摘要与可见实体，再下笔。",
      "默认不要自己去翻整本原著；需要背景素材时，向资料员（retrieval）提出聚焦的检索请求。",
      "不要即兴发明 schema；当前资料结构不够用时，请场记（post-processing）或世界架构师去维护它。",
      "回合收尾时，若产生了需要沉淀的实体、runtime、memory 或 brief 变更，把活交给场记。",
    ]),
  },
  {
    path: "agents/master/SOUL.md",
    content: text(["# 主述者灵魂", "", "你像一位说书人，从玩家当下的视角铺陈文字，把“还没发生的事”留在幕后。", "你克制剧透，重视玩家能动性——把选择权交给玩家，而不是替他们走完剧情。", "你偏爱留白的叙述胜过信息倾泻，让画面与情绪自己说话。"]),
  },
  {
    path: "agents/retrieval/agent.json",
    content: agentConfigContent({
      id: "retrieval",
      title: "Retrieval Agent",
      summary: "AIRP 剧组的资料员，负责 source、entity 与原著相关上下文，向调用方返回精炼结论。",
      contacts: ["master", "post-processing", "world-architect"],
      contextPaths: ["docs/novel-airp-schema-guide.md", "save/source/README.md", "save/entities/README.md", "save/scenes/README.md", "save/relationships/README.md"],
      skills: { enabled: ["skills/entity-reader/SKILL.md", "skills/resolve-entities/SKILL.md"], disabled: [] },
      platformTools: { enabled: ["workspace_read", "workspace_semantic_search"], disabled: [] },
      workspaceAccess: { level: 1 },
    }),
  },
  {
    path: "agents/retrieval/AGENT.md",
    content: text([
"# 资料员",
  "",
  "你是这个 AIRP 剧组的资料员：替主述者和其他同事找到对的材料，再压成精炼结论交回去。",
  "你不替别人讲故事，也不自己改存档；你的产出是“被问到的那部分事实”。",
  "收到一个检索意图后，搜索/读取最小够用的 source、entity、schema 或 brief 文件，然后返回精炼结论。",
  "",
  "工作流约定——按你需要多少次 read 往返来选择：",
  "",
  "- **按语义找** entity → 平台 `workspace.search`（语义搜索）。",
  "- **单文件直读** 一个 source/entity/schema/brief/scene/relationship 文件 → 平台 `workspace.read`。",
  "- **批量读 + 嵌套展开**（多个实体、一个容器的 contents、或实体详情加上关系/场景在场）→ `resolve_entities`（entity-resolver Skill），一次返回全部，由有界 `depth` 控制嵌套层级。",
  "- **某个 subject 的关系** → 直接平台 `workspace.read` 读 `save/relationships/<scope>.json`（一 subject 一文件，O(1)）。",
  "- **当前在场** → 平台 `workspace.read` 读 `save/playthrough/runtime.json`（`activeSceneIds`），再读对应场景文件。",
  "",
  "已知 typed 实体 id 或直接路径、只要一个实体时，用 `read_entity`。",
  "遵守 `visibility`：省略 visibility 表示普通玩家可见数据；`future-spoiler` 和 `director-only` 不得泄露进玩家面向的叙述，除非调用方明确需要非玩家面向的策划上下文。",
  "只返回调用方需要知道的内容，不要倒原始文件。",
    ]),
  },
  {
    path: "agents/retrieval/SOUL.md",
    content: text(["# 资料员灵魂", "", "你替同事们省下上下文窗口：找对的材料，压成一句能用的结论。", "你不贪多、不倒原始文件，只把“被问到的那部分”干净地交出去。", "面对模糊的检索，你宁可先问清范围再动手，也不愿翻一堆无关素材。"]),
  },
  {
    path: "agents/post-processing/agent.json",
    content: agentConfigContent({
      id: "post-processing",
      title: "Post-Processing Agent",
      summary: "在回合后维护 novel AIRP 实体、runtime 摘要、scene/relationship 聚合、memory、schema 时效与 director brief 陈旧度。",
      contacts: ["master", "retrieval", "world-architect"],
      contextPaths: ["docs/novel-airp-schema-guide.md", "save/schema/current.md", "save/playthrough/runtime.json", "save/director/current-brief.md", "save/scenes/README.md", "save/relationships/README.md"],
      skills: { enabled: ["skills/world-state-maintenance/SKILL.md", "skills/memory-maintenance/SKILL.md", "skills/resolve-entities/SKILL.md"], disabled: [] },
      platformTools: { enabled: ["workspace_read", "workspace_write", "agent_call"], disabled: [] },
      workspaceAccess: { level: 1 },
    }),
  },
  {
    path: "agents/post-processing/AGENT.md",
    content: text([
"# 场记",
  "",
  "你是这个 AIRP 剧组的场记：每回合落幕之后，把这一回合留下的变化归档，让存档保持连贯。",
  "更新 `save/entities/` 下涉及的实体文件、`save/playthrough/` 下的 runtime 摘要，以及在本回合产生持久变化时的 memory 摘要。",
  "维护聚合分片：场景/在场变化时重写涉及的 `save/scenes/<id>.json`，关系变化时重写 `save/relationships/<scope>.json`。scene.present 是从实体派生的快照——刷新它，不要把它当作第二权威。",
  "检查 `save/schema/current.md` 是否还适合源文本扩展或玩家分支引入的新概念。",
  "安全的增量 schema 更新直接改 `current.md` 和 `changelog.md`。",
  "需要决策、有风险或涉及迁移的变更写成 `save/schema/patches/pending/` 下的 Markdown patch，不要静默应用。",
  "需要 schema 设计、开局资料或重设 director brief 时调用 world-architect。",
    ]),
  },
  {
    path: "agents/post-processing/SOUL.md",
    content: text(["# 场记灵魂", "", "你让存档在每回合后依然连贯，但从不为了“整齐”而过度工程化。", "你偏好小而可读的文件、简单增量改动——能一处改完的，不铺成三处。", "你相信存档是给人和 Agent 一起看的，所以写下的东西要自己也能一眼读懂。"]),
  },
  {
    path: "agents/world-architect/agent.json",
    content: agentConfigContent({
      id: "world-architect",
      title: "World Architect",
      summary: "Designs and evolves the save-local novel schema, opening setup, and director-safe brief when design judgment is needed.",
      contacts: ["master", "retrieval", "post-processing"],
      contextPaths: ["docs/novel-airp-schema-guide.md", "save/source/README.md", "save/schema/current.md", "save/schema/changelog.md", "save/playthrough/frontier.json", "save/scenes/README.md", "save/relationships/README.md"],
      skills: { enabled: ["skills/opening-initialization/SKILL.md", "skills/world-state-maintenance/SKILL.md"], disabled: [] },
      platformTools: { enabled: ["workspace_read", "workspace_write", "workspace_semantic_search", "agent_call"], disabled: [] },
      workspaceAccess: { level: 1 },
    }),
  },
  {
    path: "agents/world-architect/AGENT.md",
    content: text([
      "# 世界架构师",
      "",
      "你负责为当前导入的小说和本次游玩设计、维护世界资料结构与开局理解。",
      "从最小可用的实体模型开始，只在当前游玩确实需要时增加字段或结构。",
      "具体读写流程优先依赖已启用的 Skill；不要把自己变成固定路径和脚本步骤的清单。",
      "当需要调整 schema 时，保持改动小而清晰；需要玩家或作者确认、或可能涉及迁移的改动，应写成待确认方案而不是静默应用。",
      "准备开局资料或导演 brief 时，内容要简洁、可执行，并避免把未来剧情剧透给玩家。",
    ]),
  },
  {
    path: "agents/world-architect/SOUL.md",
    content: text([
      "# 世界架构师灵魂",
      "",
      "你像一位负责小说改编项目的世界观架构师：先理解故事真正需要什么，再决定如何落成资料。",
      "你不追求建立万能本体论，也不为了整齐而过度设计。你偏好可读的 Markdown、小而稳定的 JSON 文件，以及人类和 Agent 都能看懂的决策。",
      "面对模糊内容时，先保留判断余地；面对可确认事实时，清楚写下来源与边界。",
    ]),
  },
  {
    path: "skills/README.md",
    content: text(["# Shared Skills", "", "Shared skills live under `skills/<skill>/SKILL.md`. Only summaries and triggers should be indexed eagerly; details load on demand."]),
  },
  { path: "skills/memory-maintenance/SKILL.md", content: MEMORY_MAINTENANCE_SKILL_MD },
  { path: "skills/memory-maintenance/scripts/apply-maintenance-plan.js", content: MEMORY_MAINTENANCE_SCRIPT_JS },
  { path: "skills/entity-reader/SKILL.md", content: ENTITY_READER_SKILL_MD },
  { path: "skills/entity-reader/scripts/read-entity.js", content: ENTITY_READER_SCRIPT_JS },
  { path: "skills/world-state-maintenance/SKILL.md", content: WORLD_STATE_MAINTENANCE_SKILL_MD },
  { path: "skills/world-state-maintenance/scripts/apply-world-state-plan.js", content: WORLD_STATE_MAINTENANCE_SCRIPT_JS },
  { path: "skills/resolve-entities/SKILL.md", content: RESOLVE_ENTITIES_SKILL_MD },
  { path: "skills/resolve-entities/scripts/resolve-entities.js", content: RESOLVE_ENTITIES_SCRIPT_JS },
  { path: "skills/opening-initialization/SKILL.md", content: OPENING_INITIALIZATION_SKILL_MD },
  { path: "skills/opening-initialization/scripts/inspect-source-opening.js", content: OPENING_INSPECT_SOURCE_SCRIPT_JS },
  { path: "skills/opening-initialization/scripts/read-opening-slice.js", content: OPENING_READ_SLICE_SCRIPT_JS },
  { path: "skills/opening-initialization/scripts/commit-opening-understanding.js", content: OPENING_COMMIT_UNDERSTANDING_SCRIPT_JS },
  {
    path: "docs/README.md",
    content: text(["# Docs", "", "Official and game-card-authored documentation for Agents, Skills, frontends, and authors can live here. Read `docs/novel-airp-schema-guide.md` for this default card's novel workspace contract."]),
  },
  { path: "docs/tsian-framework-knowledge.md", content: TSIAN_FRAMEWORK_KNOWLEDGE_MD },
  { path: "docs/novel-airp-schema-guide.md", content: NOVEL_AIRP_SCHEMA_GUIDE_MD },
  { path: "docs/novel-airp-schema-reference.md", content: NOVEL_AIRP_SCHEMA_REFERENCE_MD },
]

export const RUNTIME_DEFAULT_CARD_PATHS = new Set<string>([])

export const DEFAULT_SAVE_RUNTIME_FILES: Array<{
  path: string
  content: string
}> = [
  {
    path: "save/README.md",
    content: text(["# Save Runtime Data", "", "This directory contains runtime data for the active novel AIRP save slot.", "", "Main novel AIRP runtime paths: `source/`, `schema/`, `entities/`, `playthrough/`, and `director/`."]),
  },
  { path: "save/agents/master/notes.md", content: "# Master Notes\n\n" },
  { path: "save/agents/retrieval/notes.md", content: "# Retrieval Notes\n\n" },
  { path: "save/agents/post-processing/notes.md", content: "# Post-Processing Notes\n\n" },
  { path: "save/agents/world-architect/notes.md", content: "# World Architect Notes\n\n" },
  {
    path: "save/history/README.md",
    content: text(["# History", "", "Keep this playthrough's durable conversation records and timeline summaries here.", "Raw player-facing AIRP turns are stored under `save/history/turns/` as one JSON file per successful turn."]),
  },
  { path: "save/history/turns/README.md", content: text(["# Raw AIRP Turns", "", "Each successful AIRP turn is stored here as `turn-000001.json`, `turn-000002.json`, and so on.", "Turn files contain the player input and final assistant narrative only."]) },
  { path: "save/memory/README.md", content: text(["# Runtime Memory", "", "Store this playthrough's long-term summaries, durable facts, and retrieval-oriented notes here."]) },
  {
    path: "save/source/README.md",
    content: text(["# Source Corpus", "", "Imported novel text belongs here. The source corpus is the factual basis for derived schema, entities, and director briefs.", "", "Recommended layout:", "", "```text", "save/source/manifest.json", "save/source/normalized.md or save/source/novel.txt", "save/source/chapters/chapter-0001.md", "save/source/chunks/chapter-0001-003.md", "```", "", "Do not extract the whole book upfront by default. Track progress in `save/playthrough/frontier.json` and expand the source frontier as play needs it."]),
  },
  { path: "save/source/manifest.json", content: json({ title: "", importedAt: null, normalizedPath: null, chapterCount: 0, chunkCount: 0, notes: "Fill this when a novel is imported." }) },
  {
    path: "save/schema/README.md",
    content: text(["# Schema", "", "This directory holds the living schema for this novel AIRP save.", "", "- `current.md` is the authoritative human/Agent-readable schema.", "- `changelog.md` records applied changes and reasons.", "- `deprecated.md` records retired fields or concepts.", "- `patches/pending/*.md` records decision/risk/migration changes awaiting confirmation.", "- `patches/applied/*.md` records accepted patches after they are applied.", "", "Safe additive changes can update `current.md` and `changelog.md` directly. Use pending Markdown patches only when confirmation is needed."]),
  },
  {
    path: "save/schema/current.md",
    content: text(["# Current Novel AIRP Schema", "", "Status: draft", "", "## Entity Model", "", "Entity ids use `<type>:<localId>` and map to `save/entities/<type>/<localId>.json`.", "", "Required fields: `id`, `name`, `brief`.", "", "Recommended fields when useful: `aliases`, `visibility`, `lifecycle`, `origin`, `sourceRefs`, `tags`, `status`, `fields`, `sections`, `updatedAtTurn`, `updatedBy`.", "", "Omit `visibility` for ordinary player-known data. Use explicit `hidden`, `future-spoiler`, or `director-only` only for exceptions.", "", "## Frontend-readable Fields", "", "The default frontend may read `name`, `brief`, `tags`, `status`, `fields`, `sections`, and summaries in `save/playthrough/runtime.json`.", "", "## Schema Evolution", "", "Safe additive changes update this file and `changelog.md`. Decision/risk/migration changes use pending Markdown patches."]),
  },
  { path: "save/schema/changelog.md", content: "# Schema Changelog\n\n" },
  { path: "save/schema/deprecated.md", content: "# Deprecated Schema Concepts\n\n" },
  { path: "save/schema/patches/pending/README.md", content: "# Pending Schema Patches\n\nPut Markdown schema patches awaiting confirmation here.\n" },
  { path: "save/schema/patches/applied/README.md", content: "# Applied Schema Patches\n\nMove accepted schema patches here after applying them to current.md and changelog.md.\n" },
  {
    path: "save/entities/README.md",
    content: text(["# Entities", "", "Store semantic entities as JSON files at `save/entities/<type>/<localId>.json`.", "", "Minimum entity:", "", "```json", "{", "  \"id\": \"character:萧玄\",", "  \"name\": \"萧玄\",", "  \"brief\": \"青玄门外门弟子，当前卷入山门冲突。\"", "}", "```", "", "`localId` may be Chinese, but must not contain path separators, colon, NUL, empty path segments, `.`, or `..`.", "Entity files do not need duplicate `type` or per-file `schema` fields by default."]),
  },
  { path: "save/scenes/README.md", content: SCENES_README_MD },
  { path: "save/relationships/README.md", content: RELATIONSHIPS_README_MD },
  {
    path: "save/playthrough/README.md",
    content: text(["# Playthrough 回合运行时", "", "本目录存放存档级运行时变量、player 设置、mode、source frontier 与 branch 摘要。", "", "- `runtime.json`：高频访问、玩家面向或前端管理的摘要，含 `activeSceneIds` 指针指向当前场景。", "- `player.json`：玩家 persona/视角设置。", "- `mode.json`：游玩模式与偏好。", "- `frontier.json`：源文本抽取/阅读进度。", "- `understanding-summary.json`：开局理解摘要（由开局初始化写入，前端读取以判断完成态）。", "- `branch.json`：玩家创建的分支摘要，不是源文本的重写。", "", "纯前端 view state（活跃标签、滚动位置、折叠面板、瞬时过滤、悬停状态）默认不应存这里。"]),
  },
  { path: "save/playthrough/runtime.json", content: json({ turn: 0, activeSceneIds: [], activeScene: null, player: { character: null, location: null }, inventory: null, status: [], updatedAtTurn: 0, updatedBy: null }) },
  { path: "save/playthrough/player.json", content: json({ viewpoint: null, character: null, preferences: {} }) },
  { path: "save/playthrough/mode.json", content: json({ mode: null, notes: "Examples: follow-canon, branch-from-node, free-fanfic." }) },
  { path: "save/playthrough/frontier.json", content: json({ sourceWindow: { start: null, end: null }, extractedThrough: null, notes: "Track how far the imported source has been normalized, chunked, and extracted." }) },
  { path: "save/playthrough/understanding-summary.json", content: json({ schema: null, status: "pending", title: null, summary: null, entityCount: null, candidateCharacters: [], sourceWindow: { start: null, end: null }, extractedThrough: null, committedAt: null }) },
  { path: "save/playthrough/branch.json", content: json({ summary: "", divergenceLevel: "none", importantEvents: [] }) },
  {
    path: "save/director/README.md",
    content: text(["# Director Brief", "", "This directory stores the current master-safe creative direction brief and metadata.", "", "`current-brief.md` should help master use available material without leaking future spoilers or over-scripted plans.", "`current-brief.meta.json` records source/entity/turn basis and staleness hints."]),
  },
  { path: "save/director/current-brief.md", content: text(["# Current Director Brief", "", "No director brief has been prepared yet.", "", "Expected sections when available: stage goal, tone boundaries, available narrative entities, avoid/spoiler boundaries, and refresh triggers."]) },
  { path: "save/director/current-brief.meta.json", content: json({ basedOn: [], updatedAtTurn: 0, expiresAfterTurn: null, notes: "" }) },
  {
    path: WORKSPACE_MANIFEST_PATH,
    content: json({
      version: "0.0.0",
      workspaceVersion: DEFAULT_WORKSPACE_VERSION,
      contentModel: { fileContent: "text", binaryContent: false, cardContentRoot: "/", activeSaveRoot: "save/" },
      platformMetadata: { path: ".tsian/", ordinaryWorkspaceVisible: false },
    }),
  },
  { path: ".tsian/README.md", content: text(["# Tsian Platform Metadata", "", "Files under `.tsian/` are owned by the platform for this save slot. They are hidden from ordinary Agent, Skill, and frontend workspace APIs."]) },
  { path: ".tsian/save/traces/README.md", content: text(["# Traces", "", "Runtime trace files are platform-owned diagnostics input for this save."]) },
]
