import type { AgentConfig } from "@tsian/contracts"

export const DEFAULT_WORKSPACE_VERSION = 12
export const WORKSPACE_MANIFEST_PATH = ".tsian/manifest.json"

export const DEFAULT_SAVE_RUNTIME_UPGRADE_FILE_PATHS = new Set([
  "save/README.md",
  "save/agents/storyteller/notes.md",
  "save/agents/researcher/notes.md",
  "save/agents/stage-manager/notes.md",
  "save/agents/world-architect/notes.md",
  "save/agents/director/notes.md",
  "save/history/README.md",
  "save/history/turns/README.md",
  "save/memory/README.md",
  "save/source/README.md",
  "save/source/manifest.json",
  "save/schema/README.md",
  "save/schema/current.md",
  "save/schema/changelog.md",
  "save/schema/deprecated.md",
  "save/schema/patches/pending/README.md",
  "save/schema/patches/applied/README.md",
  "save/entities/README.md",
  "save/scenes/README.md",
  "save/relationships/README.md",
  "save/playthrough/README.md",
  "save/playthrough/runtime.json",
  "save/playthrough/mode.json",
  "save/playthrough/player.json",
  "save/playthrough/frontier.json",
  "save/playthrough/understanding-summary.json",
  "save/playthrough/setup-summary.json",
  "save/playthrough/opening-narrative.json",
  "save/playthrough/branch.json",
  "save/director/README.md",
  "save/director/current-brief.md",
  "save/director/current-brief.meta.json",
])

function text(lines: string[]): string {
  return `${lines.join("\n")}\n`
}

function json(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`
}

function agentConfigContent(config: AgentConfig): string {
  return json(config)
}

const STORYTELLER_ACTION_RESOLUTION_SKILL_MD = text([
  "---",
  "name: 行动裁定",
  "title: 行动裁定（说书人视角）",
  "description: 当行动裁定玩法已启用时，帮助说书人把裁定意图、结果和叙事反馈融合进正文；当前模板不声明执行脚本。",
  "triggers:",
  "  - 玩家行动存在明显成败不确定性，且行动裁定已启用",
  "  - 已获得行动裁定结果，需要写成沉浸式正文",
  "---",
  "",
  "# 行动裁定（说书人视角）",
  "",
  "本 Skill 只定义说书人的叙事边界，不提供骰点、数值对抗或随机表脚本。完整执行器由后续玩法任务落地。",
  "",
  "使用原则：",
  "",
  "- 只有当本次存档明确启用“行动裁定”时才按玩法处理；默认 `mode.json` 中该玩法为 `deferred`。",
  "- 没有可用执行器或后台给出的裁定结果时，不要假装已经完成随机/数值计算。",
  "- 把已知裁定结果写成玩家能感受到的后果：成败、代价、机会、局势变化。",
  "- 不维护 runtime、entity、status bar 或资源变化；这些由场记在回合后维护。",
])

const RESEARCHER_ENTITY_READ_SKILL_MD = text([
  "---",
  "name: 实体读取",
  "title: 实体读取",
  "description: 资料员按实体、场景、关系或直接路径读取事实，并压缩成调用方需要的精炼结论。",
  "triggers:",
  "  - 调用方给出 entity id、scene id、relationship scope 或文件路径",
  "  - 需要确认一个角色、地点、物品、容器或关系事实",
  "---",
  "",
  "# 实体读取",
  "",
  "你负责读事实，不负责改写事实。",
  "",
  "- 已知实体 id `<type>:<localId>` 时，读取 `save/entities/<type>/<localId>.json`。",
  "- 当前场景从 `save/playthrough/runtime.json` 的 `activeSceneIds` 找到，再读 `save/scenes/<localId>.json`。",
  "- 某 subject 的关系读 `save/relationships/<scope>.json`。",
  "- 返回调用方问题需要的摘要；不要倒整份 JSON。",
  "- 遵守 `visibility`，不要把 `future-spoiler` 或 `director-only` 内容泄露给玩家面向叙事。",
])

const RESEARCHER_RETRIEVAL_SKILL_MD = text([
  "---",
  "name: 资料检索",
  "title: 资料检索",
  "description: 资料员在 source、schema、entity、scene、relationship、brief 中按问题查找材料并给出可用结论。",
  "triggers:",
  "  - 调用方缺少源文本或世界事实",
  "  - 需要在较大 source/实体资料中定位相关段落",
  "---",
  "",
  "# 资料检索",
  "",
  "检索目标是“让调用方少读上下文也能行动”，不是展示你翻了多少资料。",
  "",
  "工作方式：",
  "",
  "- 先确认调用方真正问的事实范围。",
  "- 可用 `semantic_search` 找候选 source/notes，再用 `read` 读取关键文件。",
  "- 若是结构化路径明确的问题，直接读文件，不做语义搜索。",
  "- 输出精炼事实、来源路径和不确定性；不讲故事、不写存档、不判断玩法启用。",
])

const STAGE_MANAGER_STATUS_SKILL_MD = text([
  "---",
  "name: 状态栏维护",
  "title: 状态栏维护",
  "description: 场记在回合后维护 runtime/entity 中可被前端投影到状态栏、人物卡、场景面板的玩家可见状态。",
  "triggers:",
  "  - 回合后玩家状态、场景状态或实体可见状态发生变化",
  "  - 需要更新 runtime/entity 的 fields、sections 或 extensions",
  "---",
  "",
  "# 状态栏维护",
  "",
  "状态栏、人物卡、容器/背包、物品详情和场景面板是前端默认渲染结构，不是 `mode.json` 里的玩法开关。",
  "",
  "维护时：",
  "",
  "- `save/playthrough/runtime.json` 存高频摘要和当前指针，例如 activeSceneIds、player、inventory、status、extensions。",
  "- entity 文件仍是实体权威；人物/物品/容器的稳定状态优先写回对应 entity。",
  "- scene/relationship 是派生导航视图，刷新摘要，不把它当第二权威。",
  "- `extensions` 的 key 可用中文；值内 `render` preset、tone 等机器字段用英文。",
])

const STAGE_MANAGER_SCHEMA_SKILL_MD = text([
  "---",
  "name: schema演进检查",
  "title: Schema 演进检查",
  "description: 场记在回合后发现新长期概念、结构空缺或过期临时字段，并决定直接维护或提交待确认方案。",
  "triggers:",
  "  - 回合产生了现有 schema 难以表达的新长期概念",
  "  - 某个临时 extensions 字段反复出现，可能需要正式化",
  "---",
  "",
  "# Schema 演进检查",
  "",
  "原则：小改直接维护，大改写待确认方案。",
  "",
  "- 安全的增量（可选字段、轻量 tag/status 约定、README 澄清）可更新 `save/schema/current.md` 并追加 `changelog.md`。",
  "- 删除、改名、严格数值机制、数据迁移或可能让玩家/作者意外的变更，写到 `save/schema/patches/pending/*.md`。",
  "- 需要 schema 设计判断时 call 世界架构师；需要事实材料时 call 资料员。",
  "- 不把 schema 维护工作写进玩家可见正文。",
])

const STAGE_MANAGER_ACTION_RESOLUTION_SKILL_MD = text([
  "---",
  "name: 行动裁定",
  "title: 行动裁定（场记视角）",
  "description: 当行动裁定玩法已启用时，场记根据已发生的裁定后果维护 runtime/entity/status；当前模板不声明执行脚本。",
  "triggers:",
  "  - 已启用行动裁定，且本回合出现裁定结果",
  "  - 裁定后需要更新伤势、资源、位置、关系或局势",
  "---",
  "",
  "# 行动裁定（场记视角）",
  "",
  "本 Skill 不执行随机/数值计算；它只处理已知裁定后果的落盘维护。",
  "",
  "- `save/playthrough/mode.json` 中 `\"行动裁定\": \"enabled\"` 时，按本 Skill 维护结果。",
  "- `deferred` 时，不前台打断玩家；若剧情明显需要，可在后台 notes 或 pending patch 中提出轻量启用建议。",
  "- 维护落点优先是相关 entity、runtime 摘要、scene/relationship 派生视图。",
  "- 不把 UI 模块开关写入 `mode.json`。",
])

const WORLD_ARCHITECT_OPENING_SKILL_MD = text([
  "---",
  "name: 开局建模",
  "title: 开局建模",
  "description: 世界架构师为刚导入的小说建立初始 schema、entities、scenes、relationships、runtime 与 mode 骨架；当前模板不声明执行脚本。",
  "triggers:",
  "  - 小说导入后需要建立开局世界资料",
  "  - 需要根据玩家设定补齐开局实体、场景或 runtime 指针",
  "---",
  "",
  "# 开局建模",
  "",
  "目标是建立后续常态流程能读到的正式路径，而不是建立一次性中间目录。",
  "",
  "产物落点：",
  "",
  "- `save/schema/current.md` 与 `save/schema/changelog.md`：当前 schema 草案与变更理由。",
  "- `save/entities/<type>/<localId>.json`：人物、地点、势力、设定、物品、容器等实体。",
  "- `save/scenes/<localId>.json` 与 `save/relationships/<scope>.json`：派生导航视图。",
  "- `save/playthrough/runtime.json`：当前 activeSceneIds、player、status、extensions 等摘要。",
  "- `save/playthrough/mode.json`：只记录真正玩法系统的三态，例如“行动裁定”。",
  "",
  "不写开局正文；不把导演 brief 写成世界建模报告。导演负责剧情指导文档。",
])

const WORLD_ARCHITECT_GAMEPLAY_ENABLEMENT_SKILL_MD = text([
  "---",
  "name: 玩法启用",
  "title: 玩法启用",
  "description: 世界架构师根据玩家或后台决策维护真正玩法系统的 enabled/disabled/deferred 状态。",
  "triggers:",
  "  - 玩家选择启用、不启用或暂缓某个玩法系统",
  "  - 场记提出一个 deferred 玩法值得启用的后台建议",
  "---",
  "",
  "# 玩法启用",
  "",
  "`save/playthrough/mode.json` 是玩法启用状态表，不是规则书，也不是前端 UI 模块表。",
  "",
  "约定：",
  "",
  "- key 是真正会改变剧情裁定逻辑的玩法名，例如 `行动裁定`。",
  "- value 只能是 `enabled`、`disabled`、`deferred`。",
  "- 不写人物卡、背包、物品详情、状态栏、场景面板等渲染结构。",
  "- 启用玩法时，再初始化相应 schema/rules/runtime 骨架；本模板不提供自动初始化脚本。",
])

const WORLD_ARCHITECT_ACTION_RESOLUTION_SKILL_MD = text([
  "---",
  "name: 行动裁定",
  "title: 行动裁定（世界架构师视角）",
  "description: 世界架构师在行动裁定玩法被启用时设计基础规则、schema 示例和状态落点；当前模板不声明执行脚本。",
  "triggers:",
  "  - 玩家选择启用行动裁定",
  "  - 需要为行动裁定补齐 schema、规则说明或示例状态",
  "---",
  "",
  "# 行动裁定（世界架构师视角）",
  "",
  "本 Skill 负责设计，不负责临场投骰。完整随机/数值/对抗脚本由后续行动裁定玩法任务实现。",
  "",
  "启用时可设计：",
  "",
  "- 哪些 entity/runtime 字段承载难度、属性、资源或伤势。",
  "- 哪些裁定结果由场记落盘维护。",
  "- 哪些规则需要写入 `save/schema/current.md` 或 pending patch。",
  "",
  "不要让 Agent 手写复杂数值运算；确定性计算应交给后续脚本。",
])

const DIRECTOR_BRIEF_SKILL_MD = text([
  "---",
  "name: 剧情指导维护",
  "title: 剧情指导维护",
  "description: 导演维护当前剧情方向 brief、节奏、伏笔、原著/分支平衡和刷新元数据。",
  "triggers:",
  "  - 开局建模后需要写初始剧情方向",
  "  - 场记标记 brief 过期，或阶段性剧情需要重新校准",
  "---",
  "",
  "# 剧情指导维护",
  "",
  "维护 `save/director/current-brief.md` 与 `save/director/current-brief.meta.json`。",
  "",
  "Brief 应包含：",
  "",
  "- 当前阶段目标与张力。",
  "- 可用人物、场景、冲突和伏笔。",
  "- 叙事边界：哪些未来信息不能泄露给玩家。",
  "- 何时需要刷新 brief。",
  "",
  "导演不直接面向玩家，不整理 runtime/entity；需要事实时 call 资料员。",
])

const TSIAN_FRAMEWORK_KNOWLEDGE_MD = text([
  "# Tsian Framework Knowledge",
  "",
  "Tsian is an Agent-Orchestrated Runtime platform for AIRP. Platform code owns model configuration, local storage, checkpoints, bridge APIs, execution policy, and sandboxing. Gameplay-specific behavior belongs in workspace files, Agents, Skills, docs, and game frontends.",
  "",
  "Runtime Workspace is an effective virtual file system composed from Game Card content plus the active save slot mounted at `save/`. Ordinary workspace paths are visible to Agents, Skills, and game frontends. `.tsian/` is platform-owned metadata and is hidden from ordinary Agent, Skill, and frontend workspace APIs.",
  "",
  "The default novel AIRP card uses `storyteller` as the formal player-turn entry Agent. Background specialists are `researcher`, `stage-manager`, `world-architect`, and `director`.",
])

const SCENES_README_MD = text([
  "# Scenes",
  "",
  "一场景一文件，存于 `save/scenes/<localId>.json`。场景是派生导航视图，记录“当前局面有谁、在哪”，不是实体副本。entity 文件是实体权威；scene 的 `present` 摘要从实体派生，丢了可重建，不要反向当作第二权威。",
  "",
  "字段：",
  "",
  "- `id`：场景 id，`scene:<localId>`。",
  "- `name`：场景名。",
  "- `location`：`{ ref, name }`，指向地点实体。",
  "- `present`：在场实体摘要，每项 `{ ref, name, brief, status? }`。",
  "- `status`：`active` / `background` / `resolved`。",
  "- `updatedTurn` / `updatedBy`：维护锚点。",
  "",
  "场记在场景变动时刷新涉及的场景文件。resolved 场景不删，剧情可回溯。",
])

const RELATIONSHIPS_README_MD = text([
  "# Relationships",
  "",
  "一 subject 一文件，存于 `save/relationships/<scope>.json`。`<scope>` = subject 实体的 localId（去 `type:` 前缀，如 `character-萧玄`）。",
  "",
  "字段：",
  "",
  "- `subject`：主体实体 id。",
  "- `edges`：关系条目数组，每项 `{ to, type, since?, until?, note? }`。",
  "- `updatedTurn` / `updatedBy`：维护锚点。",
  "",
  "双向关系两边各写一条；单向关系（如隶属）只写从属方。关系分片是导航视图，不是实体权威。",
])

const NOVEL_AIRP_SCHEMA_GUIDE_MD = text([
  "# Novel AIRP Schema 速查指南",
  "",
  "本默认卡支持小说 AIRP 流程：玩家导入小说，后台 Agent 团队渐进维护 schema、entities、runtime、mode 与 director brief。完整字段手册见 `docs/novel-airp-schema-reference.md`。",
  "",
  "## 主路径",
  "",
  "```text",
  "save/source/         # 导入的源文本：manifest、chapters、chunks",
  "save/schema/         # 当前 schema、changelog、deprecated 笔记、Markdown patches",
  "save/entities/       # 语义实体，存为 save/entities/<type>/<localId>.json",
  "save/scenes/         # 场景分片，存为 save/scenes/<localId>.json（一场景一文件）",
  "save/relationships/  # 关系分片，存为 save/relationships/<scope>.json（一 subject 一文件）",
  "save/playthrough/    # player、mode、frontier、runtime、opening/setup 摘要",
  "save/director/       # 当前剧情指导 brief 和元数据",
  "```",
  "",
  "## 语言边界",
  "",
  "- 英文：JSON 字段、机器枚举、render preset、tone、visibility、lifecycle、entity type、mode 状态值。",
  "- 中文：Agent/Skill 显示名、玩法名、entity `name`/`brief`、字段 label、section title/body、extension key、玩家可见描述。",
  "",
  "## 权威归属",
  "",
  "- entity json 是实体权威。",
  "- scene / relationship json 是派生快照；丢了可重建。",
  "- `runtime.activeSceneIds` 是当前活跃场景指针，不是场景内容权威。",
  "- `mode.json` 是玩法启用状态表，不是规则书，也不是 UI 模块表。",
  "",
  "## mode.json",
  "",
  "默认：",
  "",
  "```json",
  "{",
  "  \"行动裁定\": \"deferred\"",
  "}",
  "```",
  "",
  "value 只能是 `enabled` / `disabled` / `deferred`。只记录真正会改变剧情裁定逻辑的玩法系统；不要记录人物卡、容器/背包、物品详情、状态栏或场景面板。",
  "",
  "## 实体基础",
  "",
  "实体 id 用 `<type>:<localId>`，映射到 `save/entities/<type>/<localId>.json`。必填字段：`id`、`name`、`brief`。",
  "",
  "```json",
  "{",
  "  \"id\": \"character:萧玄\",",
  "  \"name\": \"萧玄\",",
  "  \"brief\": \"青玄门外门弟子，当前卷入山门冲突。\",",
  "  \"gender\": \"男\"",
  "}",
  "```",
  "",
  "按需使用：`gender`、`aliases`、`visibility`、`lifecycle`、`origin`、`sourceRefs`、`tags`、`status`、`fields`、`sections`、`extensions`、`updatedAtTurn`、`updatedBy`。",
  "",
  "## fields / sections / extensions",
  "",
  "- `fields`：稳定 label/value 键值对，前端状态栏/卡片行式渲染。",
  "- `sections`：title/body 段落块。",
  "- `extensions`：动态玩家可见字段，子 key 可用中文，值内用有限 `render` preset（text/number/progress/tag/tags/list/section/ref/cards）。",
  "",
  "固定基础 schema 由前端做专门 UI；`extensions` 只是这些 UI 内的新字段扩展槽，不是万能 renderer。",
  "",
  "## Agent 职责",
  "",
  "- `storyteller` / 说书人：玩家正式回合入口，写沉浸式正文和选项；信息不足时 call 资料员。",
  "- `researcher` / 资料员：只读 source/entity/scene/relationship/schema/brief，返回精炼事实。",
  "- `stage-manager` / 场记：回合后维护 runtime、entities、scenes、relationships、memory 与可渲染状态；必要时 call 世界架构师。",
  "- `world-architect` / 世界架构师：开局建模、schema 设计、玩法启用方案和 pending patch。",
  "- `director` / 导演：维护剧情方向 brief、节奏、伏笔与原著/分支平衡。",
])

const NOVEL_AIRP_SCHEMA_REFERENCE_MD = text([
  "# Novel AIRP Schema 详尽参考",
  "",
  "详尽字段手册，按需查阅，不常驻上下文。速查见 `docs/novel-airp-schema-guide.md`。",
  "",
  "## 实体推荐元数据",
  "",
  "```json",
  "{",
  "  \"id\": \"character:萧玄\",",
  "  \"name\": \"萧玄\",",
  "  \"brief\": \"青玄门外门弟子，当前卷入山门冲突。\",",
  "  \"gender\": \"男\",",
  "  \"origin\": \"canon\",",
  "  \"sourceRefs\": [\"save/source/chapters/chapter-0001.md\"],",
  "  \"tags\": [\"青玄门\", \"外门弟子\"],",
  "  \"status\": [",
  "    { \"id\": \"injury:右臂轻伤\", \"level\": \"minor\", \"description\": \"挥剑时略有迟滞。\" }",
  "  ],",
  "  \"fields\": [",
  "    { \"label\": \"当前位置\", \"value\": \"青玄门山门\" }",
  "  ],",
  "  \"extensions\": {",
  "    \"腐化值\": { \"render\": \"progress\", \"value\": 37, \"max\": 100, \"tone\": \"danger\" }",
  "  },",
  "  \"updatedAtTurn\": 6,",
  "  \"updatedBy\": \"stage-manager\"",
  "}",
  "```",
  "",
  "## 受控词表",
  "",
  "### visibility",
  "",
  "```text",
  "player-known      # 玩家面向的叙述/前端安全；省略时默认",
  "hidden            # 玩家当前看不见，但背景 Agent 可用",
  "future-spoiler    # 未来的原著信息；不要泄露进玩家面向的叙述",
  "director-only     # 策划/原著风险材料；说书人默认不应使用",
  "```",
  "",
  "### lifecycle",
  "",
  "```text",
  "candidate    # 已抽取但尚未确认重要",
  "active       # 当前可在游玩中使用",
  "background   # 作为背景存在但非当前焦点",
  "retired      # 已退出当前游玩，除非刻意重新引入",
  "```",
  "",
  "### origin",
  "",
  "```text",
  "canon        # 来自导入的原著小说",
  "branch       # 玩家分支创建或改变",
  "player       # 玩家创建的 persona/偏好/输入",
  "generated    # Agent 创建的运行时材料",
  "```",
  "",
  "## Runtime 变量",
  "",
  "`save/playthrough/runtime.json` 存放高频访问、玩家面向或前端管理的摘要。",
  "",
  "```json",
  "{",
  "  \"turn\": 6,",
  "  \"activeSceneIds\": [\"scene:山门冲突\"],",
  "  \"activeScene\": { \"ref\": \"scene:山门冲突\", \"name\": \"山门冲突\" },",
  "  \"player\": {",
  "    \"character\": { \"ref\": \"character:萧玄\", \"name\": \"萧玄\" },",
  "    \"location\": { \"ref\": \"location:青玄门山门\", \"name\": \"青玄门山门\" }",
  "  },",
  "  \"inventory\": {",
  "    \"primaryContainer\": { \"ref\": \"container:玩家储物袋\", \"name\": \"我的储物袋\" },",
  "    \"state\": \"near-full\"",
  "  },",
  "  \"status\": [",
  "    { \"id\": \"constraint:储物袋接近满载\", \"description\": \"不宜继续收纳大件物品。\" }",
  "  ],",
  "  \"extensions\": {",
  "    \"当前时间\": { \"render\": \"text\", \"value\": \"赤明纪十二年三月初七，黄昏\" }",
  "  },",
  "  \"updatedAtTurn\": 6,",
  "  \"updatedBy\": \"stage-manager\"",
  "}",
  "```",
  "",
  "`activeSceneIds` 是当前活跃场景的指针数组。场景内容权威在 `save/scenes/<id>.json`，runtime 只存指针。纯前端 view state 默认不写入 workspace。",
  "",
  "## mode.json",
  "",
  "`save/playthrough/mode.json` 只存真正玩法系统的三态：",
  "",
  "```json",
  "{",
  "  \"行动裁定\": \"deferred\"",
  "}",
  "```",
  "",
  "不要把状态栏、人物卡、容器/背包、物品详情或场景面板写成 mode 项。它们是前端默认渲染结构，有数据就渲染，没有就不渲染。",
  "",
  "## 场景分片格式",
  "",
  "```json",
  "{",
  "  \"id\": \"scene:山门冲突\",",
  "  \"name\": \"山门冲突\",",
  "  \"location\": { \"ref\": \"location:青玄门山门\", \"name\": \"青玄门山门\" },",
  "  \"present\": [",
  "    { \"ref\": \"character:萧玄\", \"name\": \"萧玄\", \"brief\": \"青玄门外门弟子，当前卷入山门冲突。\" }",
  "  ],",
  "  \"status\": \"active\",",
  "  \"updatedTurn\": 0,",
  "  \"updatedBy\": \"world-architect\"",
  "}",
  "```",
  "",
  "## Schema Patch Markdown 模板",
  "",
  "```md",
  "# Schema Patch: 增加宗门贡献点",
  "",
  "Status: pending",
  "Decision: player-required",
  "Proposed by: stage-manager",
  "Reason: 新章节出现“宗门贡献点”，看起来会持续影响角色行动和资源兑换。",
  "",
  "## 拟议变更",
  "",
  "- 为 `character` entity 增加可选字段：`progression.contributionPoints`。",
  "- 默认不存在；不存在表示未知或不追踪。",
  "```",
])

export const DEFAULT_WORKSPACE_FILES: Array<{
  path: string
  content: string
}> = [
  {
    path: "README.md",
    content: text([
      "# Runtime Workspace",
      "",
      "This effective workspace combines Game Card content with active save runtime data. Runtime play data lives under `save/`.",
      "The `.tsian/` directory is platform-owned metadata and is hidden from ordinary Agent, Skill, and frontend workspace APIs.",
      "",
      "This default card uses the novel AIRP backstage crew: `storyteller`, `researcher`, `stage-manager`, `world-architect`, and `director`. Read `docs/novel-airp-schema-guide.md` before changing novel source, schema, entity, playthrough, mode, or director files.",
    ]),
  },
  {
    path: "agents/README.md",
    content: text([
      "# Agents",
      "",
      "Agent 配置放在 `agents/<agent>/agent.json`。`AGENT.md` 是岗位说明（SOP），`SOUL.md` 是工作风格。",
      "",
      "默认阵容：",
      "",
      "- `storyteller` / 说书人：玩家正式回合入口。",
      "- `researcher` / 资料员：只读资料检索。",
      "- `stage-manager` / 场记：回合后维护。",
      "- `world-architect` / 世界架构师：开局建模、schema 与玩法启用设计。",
      "- `director` / 导演：剧情指导 brief。",
      "",
      "Agent-local Skills 放在 `agents/<agent>/skills/<skill>/SKILL.md`，默认优先按岗位定制。",
    ]),
  },
  {
    path: "agents/storyteller/agent.json",
    content: agentConfigContent({
      id: "storyteller",
      title: "说书人",
      summary: "玩家正式回合入口。读取 brief、runtime、schema 与可见实体资料，写沉浸式正文和选项；信息不足时 call 资料员。",
      contacts: ["researcher"],
      contextPaths: ["README.md", "docs/novel-airp-schema-guide.md", "save/director/current-brief.md", "save/playthrough/runtime.json", "save/schema/current.md"],
      skills: { enabled: ["agents/storyteller/skills/行动裁定/SKILL.md"], disabled: [] },
      platformTools: { enabled: ["agent_call", "workspace_read"], disabled: [] },
      workspaceAccess: { level: 1 },
      entryMode: "persistent",
      system: true,
    }),
  },
  {
    path: "agents/storyteller/AGENT.md",
    content: text([
      "# 说书人",
      "",
      "你是玩家正式回合入口，负责把当前 brief、runtime 摘要、schema 约定与可见实体资料写成玩家读到的正文和选项。",
      "",
      "常驻原则：",
      "",
      "- 先理解当前局面，再写正文；不要为了补设定而打断叙事。",
      "- 信息不足时，向资料员提出聚焦问题，拿到结论后再继续写。",
      "- 只使用已启用玩法；暂缓玩法不由你在前台启用。",
      "- 不维护 runtime、entity、schema、status bar 或 director brief。",
      "- 输出应保持沉浸、克制剧透，并保留玩家能动性。",
    ]),
  },
  {
    path: "agents/storyteller/SOUL.md",
    content: text(["# 说书人灵魂", "", "你像一位临场说书人，从玩家当下视角铺陈文字，把未来仍留在幕后。", "你重视选择权：给玩家可行动的机会，而不是替玩家走完剧情。"]),
  },
  {
    path: "agents/researcher/agent.json",
    content: agentConfigContent({
      id: "researcher",
      title: "资料员",
      summary: "只读检索 source、entity、scene、relationship、schema 与 brief，按调用方问题返回精炼事实。",
      contacts: ["storyteller", "stage-manager", "world-architect", "director"],
      contextPaths: ["docs/novel-airp-schema-guide.md", "save/source/README.md", "save/entities/README.md", "save/scenes/README.md", "save/relationships/README.md", "save/schema/current.md"],
      skills: { enabled: ["agents/researcher/skills/实体读取/SKILL.md", "agents/researcher/skills/资料检索/SKILL.md"], disabled: [] },
      platformTools: { enabled: ["workspace_read", "workspace_semantic_search"], disabled: [] },
      workspaceAccess: { level: 1 },
    }),
  },
  {
    path: "agents/researcher/AGENT.md",
    content: text([
      "# 资料员",
      "",
      "你是后台剧组的资料员：替同事找到对的事实，再压缩成调用方能直接使用的结论。",
      "",
      "常驻原则：",
      "",
      "- 只读资料，不讲故事，不写存档，不判断玩法启用。",
      "- 先明确问题范围，再读取 source、entity、scene、relationship、schema 或 brief。",
      "- 返回精炼结论、关键来源路径和必要的不确定性。",
      "- 遵守 visibility；未来剧透只给明确需要后台策划事实的调用方。",
    ]),
  },
  {
    path: "agents/researcher/SOUL.md",
    content: text(["# 资料员灵魂", "", "你替同事们省下上下文窗口：找对材料，压成一句能用的结论。", "你不贪多，不倒原文，只交付被问到的那部分事实。"]),
  },
  {
    path: "agents/stage-manager/agent.json",
    content: agentConfigContent({
      id: "stage-manager",
      title: "场记",
      summary: "回合后维护 runtime、entities、scenes、relationships、memory 和可渲染 extensions；对 deferred 玩法提出后台建议。",
      contacts: ["researcher", "world-architect", "director"],
      contextPaths: ["docs/novel-airp-schema-guide.md", "save/schema/current.md", "save/playthrough/runtime.json", "save/playthrough/mode.json", "save/director/current-brief.md", "save/scenes/README.md", "save/relationships/README.md"],
      skills: { enabled: ["agents/stage-manager/skills/状态栏维护/SKILL.md", "agents/stage-manager/skills/schema演进检查/SKILL.md", "agents/stage-manager/skills/行动裁定/SKILL.md"], disabled: [] },
      platformTools: { enabled: ["workspace_read", "workspace_write", "agent_call"], disabled: [] },
      workspaceAccess: { level: 1 },
    }),
  },
  {
    path: "agents/stage-manager/AGENT.md",
    content: text([
      "# 场记",
      "",
      "你是后台剧组的场记：在一个玩家回合落幕后，把已经发生的变化维护到存档，使下一轮上下文和前端投影保持连贯。",
      "",
      "常驻原则：",
      "",
      "- 维护 runtime、entities、scenes、relationships、memory 与可渲染 extensions。",
      "- entity 是权威；scene/relationship 是派生导航视图；runtime 存当前高频摘要和指针。",
      "- 已启用玩法按本地 Skill 维护状态；`deferred` 玩法只做后台建议，不前台打断玩家。",
      "- 需要事实时 call 资料员；需要 schema/玩法设计时 call 世界架构师。",
      "- 写入要小而清晰，避免把同一事实变成多个权威。",
    ]),
  },
  {
    path: "agents/stage-manager/SOUL.md",
    content: text(["# 场记灵魂", "", "你让存档在每回合后依然连贯，但不为了整齐而过度工程化。", "你偏好小而可读的文件、明确的权威归属和可恢复的派生视图。"]),
  },
  {
    path: "agents/world-architect/agent.json",
    content: agentConfigContent({
      id: "world-architect",
      title: "世界架构师",
      summary: "开局建模、schema/world model 设计、玩法启用方案与 pending patch；不写开局正文，不维护每回合 runtime。",
      contacts: ["researcher", "stage-manager", "director"],
      contextPaths: ["docs/novel-airp-schema-guide.md", "save/source/README.md", "save/source/manifest.json", "save/schema/current.md", "save/schema/changelog.md", "save/playthrough/frontier.json", "save/playthrough/mode.json", "save/scenes/README.md", "save/relationships/README.md"],
      skills: { enabled: ["agents/world-architect/skills/开局建模/SKILL.md", "agents/world-architect/skills/玩法启用/SKILL.md", "agents/world-architect/skills/行动裁定/SKILL.md"], disabled: [] },
      platformTools: { enabled: ["workspace_read", "workspace_write", "workspace_semantic_search", "agent_call"], disabled: [] },
      workspaceAccess: { level: 1 },
    }),
  },
  {
    path: "agents/world-architect/AGENT.md",
    content: text([
      "# 世界架构师",
      "",
      "你负责为当前小说和本次游玩设计世界资料结构：开局 schema、实体、场景、关系、runtime 指针、mode 状态，以及后续 schema/pending patch。",
      "",
      "常驻原则：",
      "",
      "- 从最小可用模型开始，只在当前游玩确实需要时增加字段或结构。",
      "- 玩法启用只处理真正改变剧情裁定逻辑的系统，不处理前端渲染模块。",
      "- 安全小改可直接维护；有风险或需要决策的变更写 pending patch。",
      "- 需要源文本或实体事实时 call 资料员。",
      "- 不写开局正文，不维护每回合 runtime。",
    ]),
  },
  {
    path: "agents/world-architect/SOUL.md",
    content: text(["# 世界架构师灵魂", "", "你像一位负责小说改编项目的世界观架构师：先理解故事真正需要什么，再决定如何落成资料。", "你不追求万能本体论；你偏好小而稳定、可读、可演进的结构。"]),
  },
  {
    path: "agents/director/agent.json",
    content: agentConfigContent({
      id: "director",
      title: "导演",
      summary: "低频维护剧情方向 brief、节奏、伏笔、原著主线与玩家分支平衡；不直接面向玩家。",
      contacts: ["researcher", "stage-manager", "world-architect"],
      contextPaths: ["docs/novel-airp-schema-guide.md", "save/director/current-brief.md", "save/director/current-brief.meta.json", "save/playthrough/runtime.json", "save/schema/current.md", "save/source/README.md"],
      skills: { enabled: ["agents/director/skills/剧情指导维护/SKILL.md"], disabled: [] },
      platformTools: { enabled: ["workspace_read", "workspace_write", "agent_call"], disabled: [] },
      workspaceAccess: { level: 1 },
    }),
  },
  {
    path: "agents/director/AGENT.md",
    content: text([
      "# 导演",
      "",
      "你负责剧情指导层：维护当前阶段目标、节奏、伏笔、原著主线与玩家分支之间的平衡。",
      "",
      "常驻原则：",
      "",
      "- 维护 `save/director/current-brief.md` 与 `.meta.json`。",
      "- brief 要帮助说书人使用可用素材，而不是替说书人写正文。",
      "- 不整理 runtime/entity，不直接面向玩家。",
      "- 需要事实时 call 资料员；需要 schema 或玩法设计时 call 世界架构师。",
    ]),
  },
  {
    path: "agents/director/SOUL.md",
    content: text(["# 导演灵魂", "", "你像一位克制的剧集导演：看见节奏、伏笔和主题，但不抢演员和玩家的戏。", "你写方向，不写结局；你保护悬念，也保护玩家的选择。"]),
  },
  { path: "agents/storyteller/skills/行动裁定/SKILL.md", content: STORYTELLER_ACTION_RESOLUTION_SKILL_MD },
  { path: "agents/researcher/skills/实体读取/SKILL.md", content: RESEARCHER_ENTITY_READ_SKILL_MD },
  { path: "agents/researcher/skills/资料检索/SKILL.md", content: RESEARCHER_RETRIEVAL_SKILL_MD },
  { path: "agents/stage-manager/skills/状态栏维护/SKILL.md", content: STAGE_MANAGER_STATUS_SKILL_MD },
  { path: "agents/stage-manager/skills/schema演进检查/SKILL.md", content: STAGE_MANAGER_SCHEMA_SKILL_MD },
  { path: "agents/stage-manager/skills/行动裁定/SKILL.md", content: STAGE_MANAGER_ACTION_RESOLUTION_SKILL_MD },
  { path: "agents/world-architect/skills/开局建模/SKILL.md", content: WORLD_ARCHITECT_OPENING_SKILL_MD },
  { path: "agents/world-architect/skills/玩法启用/SKILL.md", content: WORLD_ARCHITECT_GAMEPLAY_ENABLEMENT_SKILL_MD },
  { path: "agents/world-architect/skills/行动裁定/SKILL.md", content: WORLD_ARCHITECT_ACTION_RESOLUTION_SKILL_MD },
  { path: "agents/director/skills/剧情指导维护/SKILL.md", content: DIRECTOR_BRIEF_SKILL_MD },
  {
    path: "skills/README.md",
    content: text([
      "# Shared Skills",
      "",
      "默认卡的核心 Skill 都是 Agent-local，路径为 `agents/<agent>/skills/<skill>/SKILL.md`。",
      "",
      "卡级共享 `skills/` 只用于多个 Agent 完全一致的底层能力。当前默认模板不放共享玩法 Skill。",
    ]),
  },
  {
    path: "docs/README.md",
    content: text(["# Docs", "", "Official and game-card-authored documentation for Agents, Skills, frontends, and authors can live here. Read `docs/novel-airp-schema-guide.md` for this default card's novel workspace contract."]),
  },
  { path: "docs/tsian-framework-knowledge.md", content: TSIAN_FRAMEWORK_KNOWLEDGE_MD },
  { path: "docs/novel-airp-schema-guide.md", content: NOVEL_AIRP_SCHEMA_GUIDE_MD },
  { path: "docs/novel-airp-schema-reference.md", content: NOVEL_AIRP_SCHEMA_REFERENCE_MD },
]

export const RUNTIME_DEFAULT_CARD_PATHS = new Set<string>([])

export const DEFAULT_SAVE_RUNTIME_FILES: Array<{
  path: string
  content: string
}> = [
  {
    path: "save/README.md",
    content: text(["# Save Runtime Data", "", "This directory contains runtime data for the active novel AIRP save slot.", "", "Main novel AIRP runtime paths: `source/`, `schema/`, `entities/`, `scenes/`, `relationships/`, `playthrough/`, `director/`, `memory/`, and `agents/`."]),
  },
  { path: "save/agents/storyteller/notes.md", content: "# 说书人 Notes\n\n" },
  { path: "save/agents/researcher/notes.md", content: "# 资料员 Notes\n\n" },
  { path: "save/agents/stage-manager/notes.md", content: "# 场记 Notes\n\n" },
  { path: "save/agents/world-architect/notes.md", content: "# 世界架构师 Notes\n\n" },
  { path: "save/agents/director/notes.md", content: "# 导演 Notes\n\n" },
  {
    path: "save/history/README.md",
    content: text(["# History", "", "Keep this playthrough's durable conversation records and timeline summaries here.", "Raw player-facing AIRP turns are stored under `save/history/turns/` as one JSON file per successful turn."]),
  },
  { path: "save/history/turns/README.md", content: text(["# Raw AIRP Turns", "", "Each successful AIRP turn is stored here as `turn-000001.json`, `turn-000002.json`, and so on.", "Turn files contain the player input and final assistant narrative only."]) },
  { path: "save/memory/README.md", content: text(["# Runtime Memory", "", "Store this playthrough's long-term summaries, durable facts, and retrieval-oriented notes here."]) },
  {
    path: "save/source/README.md",
    content: text(["# Source Corpus", "", "Imported novel text belongs here. The source corpus is the factual basis for derived schema, entities, scenes, relationships, and director briefs.", "", "Recommended layout:", "", "```text", "save/source/manifest.json", "save/source/normalized.md or save/source/novel.txt", "save/source/chapters/chapter-0001.md", "save/source/chunks/chapter-0001-003.md", "```", "", "Track progress in `save/playthrough/frontier.json` and expand the source frontier as play needs it."]),
  },
  { path: "save/source/manifest.json", content: json({ title: "", importedAt: null, normalizedPath: null, chapterCount: 0, chunkCount: 0, notes: "Fill this when a novel is imported." }) },
  {
    path: "save/schema/README.md",
    content: text(["# Schema", "", "This directory holds the living schema for this novel AIRP save.", "", "- `current.md` is the authoritative human/Agent-readable schema.", "- `changelog.md` records applied changes and reasons.", "- `deprecated.md` records retired fields or concepts.", "- `patches/pending/*.md` records decision/risk/migration changes awaiting confirmation.", "- `patches/applied/*.md` records accepted patches after they are applied.", "", "Safe additive changes can update `current.md` and `changelog.md` directly. Use pending Markdown patches only when confirmation is needed."]),
  },
  {
    path: "save/schema/current.md",
    content: text(["# Current Novel AIRP Schema", "", "Status: draft", "", "## Entity Model", "", "Entity ids use `<type>:<localId>` and map to `save/entities/<type>/<localId>.json`.", "", "Required fields: `id`, `name`, `brief`.", "", "Recommended fields when useful: `gender`, `aliases`, `visibility`, `lifecycle`, `origin`, `sourceRefs`, `tags`, `status`, `fields`, `sections`, `extensions`, `updatedAtTurn`, `updatedBy`.", "", "Omit `visibility` for ordinary player-known data. Use explicit `hidden`, `future-spoiler`, or `director-only` only for exceptions.", "", "## Frontend-readable Fields", "", "The default frontend may read `name`, `brief`, `gender`, `tags`, `status`, `fields`, `sections`, `extensions`, and summaries in `save/playthrough/runtime.json`.", "", "Fixed schemas (character/scene/container/item/runtime) can have bespoke frontend UI. Use `extensions` only for new or temporary player-visible fields that should enter those UI extension slots. Extension values choose finite `render` presets such as `text`, `number`, `progress`, `tag`, `tags`, `list`, `section`, `ref`, or `cards`.", "", "## Gameplay Modes", "", "`save/playthrough/mode.json` stores gameplay mode states. It is not a UI module list. The default first gameplay mode is `行动裁定: deferred`.", "", "## Schema Evolution", "", "Safe additive changes update this file and `changelog.md`. Decision/risk/migration changes use pending Markdown patches."]),
  },
  { path: "save/schema/changelog.md", content: "# Schema Changelog\n\n" },
  { path: "save/schema/deprecated.md", content: "# Deprecated Schema Concepts\n\n" },
  { path: "save/schema/patches/pending/README.md", content: "# Pending Schema Patches\n\nPut Markdown schema patches awaiting confirmation here.\n" },
  { path: "save/schema/patches/applied/README.md", content: "# Applied Schema Patches\n\nMove accepted schema patches here after applying them to current.md and changelog.md.\n" },
  {
    path: "save/entities/README.md",
    content: text(["# Entities", "", "Store semantic entities as JSON files at `save/entities/<type>/<localId>.json`.", "", "Minimum entity:", "", "```json", "{", "  \"id\": \"character:萧玄\",", "  \"name\": \"萧玄\",", "  \"brief\": \"青玄门外门弟子，当前卷入山门冲突。\",", "  \"gender\": \"男\"", "}", "```", "", "`localId` may be Chinese, but must not contain path separators, colon, NUL, empty path segments, `.`, or `..`."]),
  },
  { path: "save/scenes/README.md", content: SCENES_README_MD },
  { path: "save/relationships/README.md", content: RELATIONSHIPS_README_MD },
  {
    path: "save/playthrough/README.md",
    content: text(["# Playthrough 回合运行时", "", "本目录存放存档级运行时变量、player 设置、source frontier、玩法 mode、setup 摘要与 branch 摘要。", "", "- `runtime.json`：高频访问、玩家面向或前端管理的摘要，含 `activeSceneIds` 指针指向当前场景；也可通过 `extensions` 承载新增/临时的玩家可见运行时字段。", "- `mode.json`：真正玩法系统的启用状态表。value 只能是 `enabled` / `disabled` / `deferred`。默认仅包含 `行动裁定: deferred`。", "- `player.json`：玩家 persona/视角设置。", "- `frontier.json`：源文本抽取/阅读进度。", "- `understanding-summary.json`：开局理解摘要。", "- `setup-summary.json`：游玩设定对话完成信号。", "- `opening-narrative.json`：开局叙事文本。", "- `branch.json`：玩家创建的分支摘要，不是源文本的重写。", "", "不要把人物卡、容器/背包、物品详情、状态栏或场景面板写入 `mode.json`。这些是前端默认渲染结构，有数据就渲染，没有就不渲染。", "", "纯前端 view state（活跃标签、滚动位置、折叠面板、瞬时过滤、悬停状态）默认不应存这里。"]),
  },
  { path: "save/playthrough/runtime.json", content: json({ turn: 0, activeSceneIds: [], activeScene: null, player: { character: null, location: null }, inventory: null, status: [], extensions: {}, updatedAtTurn: 0, updatedBy: null }) },
  { path: "save/playthrough/mode.json", content: json({ "行动裁定": "deferred" }) },
  { path: "save/playthrough/player.json", content: json({ viewpoint: null, character: null, preferences: {} }) },
  { path: "save/playthrough/frontier.json", content: json({ sourceWindow: { start: null, end: null }, extractedThrough: null, notes: "Track how far the imported source has been normalized, chunked, and extracted." }) },
  { path: "save/playthrough/understanding-summary.json", content: json({ schema: null, status: "pending", title: null, summary: null, entityCount: null, candidateCharacters: [], sourceWindow: { start: null, end: null }, extractedThrough: null, committedAt: null }) },
  { path: "save/playthrough/setup-summary.json", content: json({ status: "pending", summary: null }) },
  { path: "save/playthrough/opening-narrative.json", content: json({ narrative: null, createdAt: null }) },
  { path: "save/playthrough/branch.json", content: json({ summary: "", divergenceLevel: "none", importantEvents: [] }) },
  {
    path: "save/director/README.md",
    content: text(["# Director Brief", "", "This directory stores the current creative direction brief and metadata.", "", "`current-brief.md` should help the storyteller use available material without leaking future spoilers or over-scripted plans.", "`current-brief.meta.json` records source/entity/turn basis and staleness hints."]),
  },
  { path: "save/director/current-brief.md", content: text(["# Current Director Brief", "", "No director brief has been prepared yet.", "", "Expected sections when available: stage goal, tone boundaries, available narrative entities, avoid/spoiler boundaries, and refresh triggers."]) },
  { path: "save/director/current-brief.meta.json", content: json({ basedOn: [], updatedAtTurn: 0, expiresAfterTurn: null, notes: "" }) },
  {
    path: WORKSPACE_MANIFEST_PATH,
    content: json({
      version: "0.0.0",
      workspaceVersion: DEFAULT_WORKSPACE_VERSION,
      contentModel: { fileContent: "text", binaryContent: false, cardContentRoot: "/", activeSaveRoot: "save/" },
      platformMetadata: { path: ".tsian/", ordinaryWorkspaceVisible: false },
    }),
  },
  { path: ".tsian/README.md", content: text(["# Tsian Platform Metadata", "", "Files under `.tsian/` are owned by the platform for this save slot. They are hidden from ordinary Agent, Skill, and frontend workspace APIs."]) },
  { path: ".tsian/save/traces/README.md", content: text(["# Traces", "", "Runtime trace files are platform-owned diagnostics input for this save."]) },
]
