import { text } from "../utils"

export const SCENES_README_MD = text([
  "# Scenes",
  "",
  "一场景一文件，存于 `save/scenes/<localId>.json`。场景是派生导航视图，记录“当前局面有谁、在哪”，不是实体副本。entity 文件是实体权威；scene 的 `present` 摘要从实体派生，丢了可重建，不要反向当作第二权威。",
  "",
  "字段：",
  "",
  "- `id`：场景 id，`scene:<localId>`。",
  "- `name`：场景名。",
  "- `location`：`{ ref, name }`，指向地点实体。",
  "- `present`：在场实体指针数组，每项仅 `{ ref }`（指向 `save/entities/<type>/<localId>.json`）。名称、简介、状态等展示信息一律回读实体权威，不在 scene 里冗余。",
  "- `status`：`active` / `background` / `resolved`。",
  "- `updatedTurn` / `updatedBy`：维护锚点。",
  "",
  "场记在场景变动时刷新涉及的场景文件。resolved 场景不删，剧情可回溯。",
])

export const RELATIONSHIPS_README_MD = text([
  "# Relationships",
  "",
  "一角色 subject 一文件，存于 `save/relationships/<scope>.json`。`<scope>` = subject 的 character scope，如 `character-萧玄`。",
  "",
  "本目录只承载人物/社交/阵营关系，不是泛实体图谱。`subject` 与 `edges[].to` 当前均必须使用 `character:<localId>`。地点、组织、物品、场景、事件、尸体/线索、概念等非角色关联不要写入 relationships；放到对应固定字段、已有 ref 结构或 `extensions.render=\"ref\"`，直到统一引用体系被正式设计。",
  "",
  "字段：",
  "",
  "- `subject`：主体角色实体 id，`character:<localId>`。",
  "- `edges`：角色关系条目数组，每项 `{ to, type, since?, until?, note? }`；`to` 也必须是 `character:<localId>`。",
  "- `updatedTurn` / `updatedBy`：维护锚点。",
  "",
  "双向角色关系两边各写一条；刻意单向的认知/隐瞒/单方面态度可只写主体侧。关系分片是导航视图，不是实体权威。",
])

export const NOVEL_AIRP_SCHEMA_GUIDE_MD = text([
  "# Novel AIRP Schema 速查指南",
  "",
  "本默认卡支持小说 AIRP 流程：玩家导入小说，后台 Agent 团队渐进维护 schema、entities、runtime 与 frontier.timeline。完整字段手册见 `docs/novel-airp-schema-reference.md`。",
  "",
  "## 主路径",
  "",
  "```text",
  "save/source/         # 导入的源文本：manifest、章节索引、source reader 可读的源正文",
  "save/schema/         # 当前 schema、changelog、deprecated 笔记、Markdown patches",
  "save/entities/       # 语义实体，存为 save/entities/<type>/<localId>.json",
  "save/scenes/         # 场景分片，存为 save/scenes/<localId>.json（一场景一文件）",
  "save/relationships/  # 人物关系分片，存为 save/relationships/<scope>.json（一角色 subject 一文件）",
"save/playthrough/    # player、frontier、runtime、opening/setup 摘要",
"```",
  "",
  "## 语言边界",
  "",
  "- 英文：JSON 字段、机器枚举、render preset、tone、visibility、lifecycle、entity type。",
  "- 中文：Agent/Skill 显示名、entity `name`/`brief`、字段 label、section title/body、extension key、玩家可见描述。",
  "",
  "## 权威归属",
  "",
  "- entity json 是实体权威。",
  "- scene / relationship json 是派生快照；丢了可重建。relationship 只承载人物/社交/阵营关系，不是泛实体图谱。",
  "- `runtime.activeSceneRefs` 是当前活跃场景指针（每项 `{ ref, name }`），不是场景内容权威。",
  "- `runtime.protagonistRef` 是当前主角指针 `{ ref, name }`；主角实体权威仍在 `save/entities/character/<localId>.json`。",
  "- `runtime.location` 是当前地点指针 `{ ref, name } | null`。",
  "- `runtime.worldTime` 是当前世界/剧情时间的固定字符串字段；它不是平台时间，也不等同于 turn。未知或尚未建立时写空字符串。",
  "- `runtime.plotOrder` 是数字字段，单调递增，表示玩家当前走到哪个 source order；场记每回合维护，前端用于判断是否触发 frontier 推进。",
  "- `runtime.weather` 是当前天气字符串；未知时写空字符串。",
  "",
  "## runtime.json",
  "",
  "当前世界/剧情时间写固定字段 `worldTime`，天气写 `weather`。`plotOrder` 是数字，单调递增，表示玩家当前走到哪个 source order；场记每回合维护，前端用于判断是否触发 frontier 推进。月相、倒计时、诅咒周期等新增/临时时间机制仍可放在 `extensions`。旧字段 `activeSceneIds`/`activeScene`/`player`/`inventory`/`status` 已废弃，不再写入 runtime。",
  "",
  "```json",
  "{",
  "  \"turn\": 6,",
  "  \"worldTime\": \"赤明纪十二年三月初七，黄昏\",",
  "  \"plotOrder\": 3,",
  "  \"weather\": \"阴云聚拢\",",
  "  \"location\": { \"ref\": \"location:青玄门山门\", \"name\": \"青玄门山门\" },",
  "  \"activeSceneRefs\": [{ \"ref\": \"scene:山门冲突\", \"name\": \"山门冲突\" }],",
  "  \"protagonistRef\": { \"ref\": \"character:萧玄\", \"name\": \"萧玄\" },",
  "  \"extensions\": {",
  "    \"月相\": { \"render\": \"text\", \"value\": \"上弦\" }",
  "  },",
  "  \"updatedAtTurn\": 6,",
  "  \"updatedBy\": \"stage-manager\"",
  "}",
  "```",
  "",
  "## frontier.json",
  "",
  "`save/playthrough/frontier.json` 记录源文本抽取进度与时间标记锚点。",
  "",
  "```json",
  "{",
  "  \"sourceWindow\": { \"start\": 1, \"end\": 8, \"chapters\": [...] },",
  "  \"extractedThrough\": \"source:chapter-0008\",",
  "  \"timeline\": [",
  "    { \"kind\": \"source\", \"order\": 1, \"chapter\": 1, \"time\": \"元年\", \"label\": \"开局\" },",
  "    { \"kind\": \"player\", \"order\": 2, \"turn\": 8, \"time\": \"二年春\", \"label\": \"离开山门\", \"alignment\": \"diverged\", \"sourceRef\": 2 }",
  "  ],",
  "  \"notes\": \"...\",",
  "  \"updatedAt\": \"...\",",
  "  \"updatedBy\": \"world-architect\"",
  "}",
  "```",
  "",
  "- `sourceWindow`：已读章节窗口（`start`/`end` 为章节号，`chapters` 为窗口章节元信息）。推进 frontier 时移动。",
  "- `extractedThrough`：已抽取到的最远源章节引用。",
  "- `timeline`：时间标记锚点数组，用 `kind` 区分 source/player：",
  "  - source 锚点 `{ kind: \"source\", order, chapter, time, label }`：world-architect 推进时建立，标记原著剧情节点。",
  "  - player 锚点 `{ kind: \"player\", order, turn, time, label, alignment, sourceRef }`：stage-manager 维护时追加，标记玩家视角显著事件。",
  "  - `order`：单调递增整数，是我们建立的线性轴，表示剧情事件先后顺序，与原著精确时间标记无关（即使原著写“回到过去”，order 也只向前）。",
  "  - `alignment`（仅 player）：`diverged`（偏离原著，sourceRef=分叉自的 source order 或 null）、`rejoined`（从分支并回主干，sourceRef=并回的 source order）、`aligned`（经历 source 事件且结果相近，sourceRef=该 source order；可选，完美跟随时不建）。",
  "- `timeline` 与 `sourceWindow` 独立：`sourceWindow` 记录已读窗口，`timeline` 记录锚点；推进时 `sourceWindow` 移动、`timeline` 追加 source 锚点。",
  "",
  "## 实体基础",
  "",
  "实体 id 用 `<type>:<localId>`，映射到 `save/entities/<type>/<localId>.json`。必填字段：`id`、`name`、`brief`。",
  "",
  "```json",
  "{",
  "  \"id\": \"character:萧玄\",",
  "  \"name\": \"萧玄\",",
  "  \"brief\": \"青玄门外门弟子，当前卷入山门冲突。\",",
  "  \"gender\": \"男\"",
  "}",
  "```",
  "",
  "按需使用：`gender`、`aliases`、`visibility`、`lifecycle`、`tags`、`identity`、`appearance`、`attributes`、`gauges`、`status`、`traits`、`goals`、`background`、`containers`、`portrait`、`extensions`。旧字段 `fields`、`sections`、`origin`、`sourceRefs`、`updatedAtTurn`、`updatedBy` 已废弃，不再新增。",
  "",
  "## character identity / appearance / attributes / gauges / status / traits / goals / background / containers",
  "",
  "- `identity`：稳定身份键值对，键为 `age`/`gender`/`role`/`affiliation`/`realm`（如 年龄/性别/身份/所属/境界）。旧键 `race`/`class`/`title` 已废弃。",
  "- `appearance`：当前形象叙事字符串（单段），描述角色当下外貌。旧 label/value 键值对形态已废弃。",
  "- `attributes`：固定6维基础属性，键名由世界架构师按世界观定义（默认`体魄`/`悟性`/`气运`/`根骨`/`法力`/`魅力`），值为正整数，基线 5。维度分两类：**修炼型**（`法力`，随境界暴涨）和**天赋型**（`悟性`/`气运`/`根骨`/`魅力`，先天素质，与境界关系小）；`体魄`介于两者之间（天生体质＋修炼强化）。填值时按角色境界估算法力量级，天赋维度按角色资质给，不要把所有维度压在同一小区间。",
  "",
  "  以下是示例刻度尺（仅供参照——不同小说的战力差距天差地别，有的境界间差百倍，有的几乎没有差距，按实际世界观调整）：",
  "",
  "  | 境界 | 法力（修炼型） | 体魄（半修炼） | 天赋型（悟性/气运/根骨/魅力） |",
  "  |---|---|---|---|",
  "  | 凡人 | 1-2 | 3-8 | 1-15 |",
  "  | 开识 | 2-5 | 5-10 | 1-18 |",
  "  | 观心 | 5-15 | 8-15 | 1-20 |",
  "  | 生灵 | 15-50 | 12-25 | 1-22 |",
  "  | 金丹 | 50-150 | 20-40 | 1-25 |",
  "  | 元婴 | 150-500 | 30-60 | 1-25 |",
  "  | 化神 | 500-1500 | 50-100 | 1-25 |",
  "  | 神通 | 1500-5000 | 80-150 | 1-25 |",
  "  | 大乘 | 5000+ | 100+ | 1-25 |",
  "",
  "  天赋型四维语义不同，按角色资质独立给值：`悟性`（学习领悟速度）、`气运`（运势机缘）、`根骨`（修炼资质与身体契合度）、`魅力`（人际感染力与气质）。不要四维都压在同一数字——一个悟性绝顶但魅力平庸的角色，悟性给 22、魅力给 8 是正常的。",
  "",
  "  天赋型与境界是否相关取决于世界观设定，以实际设定为准。表格里天赋区间随境界微升，只是因为能修到高境界的人往往资质更好，不代表境界本身会提升天赋。若世界观设定天赋纯先天、修炼不改变天赋，所有境界用同一区间，不随境界递增。",
  "",
  "  上述区间是当前世界观下该境界的普通标准范围，不是硬上限。如剧情有超常表现佐证（绝顶资质、特殊体质、跨界压制等），可突破上限；突破需有剧情依据，不是无脑拉满。",
  "",
  "  没有剧情佐证时也要按境界大致估算，不要留空或全填基线——空值或全 5 比不合理估值更糟，因为掷骰对抗会直接用这些数值做差值。跨境界法力差距应大到低境界方几乎不可能正面赢，这靠数值刻度本身保证，不靠掷骰时事后主观找补。",
  "- `gauges`：自由命名量表数组，每项 `{ id, name, value, max?, min?, unit?, tone? }`。`id`/`name`/`value` 必填；`tone` 取值 `neutral`/`accent`/`success`/`warning`/`danger`/`muted`。旧固定 5 key `hp`/`mp`/`sp`/`hunger`/`stamina` 已废弃。",
  "- `status`：状态项数组，每项 `{ id, name?, description?, polarity? }`。`polarity` 取值 `positive`/`negative`/`neutral`；旧 `status[].level` 已废弃。`status[]` 表示当前临时状态（受伤、中毒、灵力亏空、buff）。",
  "- `traits`：永久性稳定特质数组，每项 `{ id, name?, description?, effects? }`。`id` 必填（`trait:<localId>` 格式）；`name` 主展示；`description` 表达特质本身的设定说明；`effects` 为字符串数组，表达具体可用效果/限制/叙事影响（如「能够堪破虚妄」「心神不受外力影响」）。表示特殊体质、天赋、系统、血脉、命格等稳定能力来源。区别于 `status[]`（当前临时状态）：`traits[]` 是永久性的，不随单回合状态变化消失。旧存档无此字段仍可解析。",
  "- `goals`：意图与目标 `{ current?, shortTerm?, longTerm? }`，每项字符串。缺省项不写入。",
  "- `background`：背景摘记，单段叙事字符串。",
  "- `containers`：当前持有的容器指针数组，每项 `{ ref, count? }`，ref 指向 container entity；`count` 缺省视为 1。角色不持有容器时省略该字段或写空数组。物品数量不落在这里，落在 container.contents[*].count。",
  "- `portrait`：玩家上传头像的 UI/媒体引用元数据 `{ path, mimeType?, updatedAt?, updatedBy? }`，`path` 指向 `save/assets/portraits/characters/<localId>.webp`。仅前端 UI 使用，不进入 AIRP injection；agent 重写 character entity 时应保留该字段，不要删除。",
  "- `relationships` 不内嵌于 character entity；继续走 `save/relationships/character-<localId>.json` 分片。该分片只记录人物关系：subject/to 当前均必须是 `character:<localId>`；地点、组织、物品、场景、事件、尸体/线索、概念等非角色关联不要写入 relationships。",
  "",
  "## container / item entity",
  "",
  "容器与物品是独立实体，不内嵌于 character。",
  "",
  "- `container` entity 存于 `save/entities/container/<localId>.json`。字段：`id`、`name`、`brief`、`type=\"container\"`、`contents: Array<{ ref, count? }>`（ref 指向 item 或嵌套 container 实体；count 缺省 1）、`status?`（可选，沿用 character status 数组形态）、`extensions?`。不设容量字段；不冗余存储子物品的 name/brief。",
  "- `item` entity 存于 `save/entities/item/<localId>.json`。字段：`id`、`name`、`brief`、`type`（取值 `equipment`/`material`/`consumable`/`special`/`other`）、`tags?: string[]`、`extensions?`。物品不设 `status`（品相变化直接改 name/brief 或走 extensions）；数量由持有者 container.contents[*].count 表达，item entity 自身不存 `quantity`。",
  "",
  "```json",
  "{",
  "  \"id\": \"container:萧玄行囊\",",
  "  \"name\": \"外门弟子行囊\",",
  "  \"brief\": \"入门时统一发放的青灰色布囊，绳口有磨损。\",",
  "  \"type\": \"container\",",
  "  \"contents\": [",
  "    { \"ref\": \"item:清心丹\", \"count\": 3 },",
  "    { \"ref\": \"item:粗铁短剑\" }",
  "  ]",
  "}",
  "```",
  "",
  "```json",
  "{",
  "  \"id\": \"item:粗铁短剑\",",
  "  \"name\": \"粗铁短剑\",",
  "  \"brief\": \"制式短剑，刃口有小豁，仍堪一用。\",",
  "  \"type\": \"equipment\",",
  "  \"tags\": [\"制式\", \"近战\"]",
  "}",
  "```",
  "",
  "## extensions",
  "",
  "- `extensions`：动态玩家可见字段，子 key 可用中文，值内用有限 `render` preset（text/number/progress/tag/tags/list/section/ref/cards）。`render` 可省略，省略时前端按朴素文本展示 value；写了 `render` 但值不在 preset 里时前端 fail loud（warn + 隐藏该字段），不静默降级。需要新 render 类型时通过脚本/工具在写入时校验，不要在数据里发明任意 UI 组件名。",
  "",
  "固定基础 schema 由前端做专门 UI；`extensions` 只是这些 UI 内的新字段扩展槽，不是万能 renderer。",
  "",
  "## Agent 职责",
  "",
  "- `storyteller` / 三人写手：玩家正式回合入口，写沉浸式正文和选项；信息不足时 call 资料员。",
"- `researcher` / 资料员：只读 source/entity/scene/relationship/schema，返回精炼事实。",
"- `stage-manager` / 场记：回合后维护 runtime、entities、scenes、relationships、memory 与可渲染状态；必要时 call 世界架构师。",
"- `world-architect` / 世界架构师：开局建模、schema 设计与 pending patch。",
])

export const NOVEL_AIRP_SCHEMA_REFERENCE_MD = text([
  "# Novel AIRP Schema 详尽参考",
  "",
  "详尽字段手册，按需查阅，不常驻上下文。速查见 `docs/novel-airp-schema-guide.md`。",
  "",
  "## 实体推荐元数据",
  "",
  "```json",
  "{",
  "  \"id\": \"character:萧玄\",",
  "  \"name\": \"萧玄\",",
  "  \"brief\": \"青玄门外门弟子，当前卷入山门冲突。\",",
  "  \"gender\": \"男\",",
  "  \"tags\": [\"青玄门\", \"外门弟子\"],",
  "  \"identity\": { \"age\": 17, \"gender\": \"男\", \"role\": \"外门弟子\", \"affiliation\": \"青玄门\", \"realm\": \"炼气后期\" },",
  "  \"appearance\": \"身着青玄门外门弟子袍，衣袖被剑气割裂，右臂缠着临时止血布。脸色略白，但目光仍然清醒。\",",
  "  \"attributes\": { \"体魄\": 5, \"悟性\": 6, \"气运\": 4, \"根骨\": 5, \"法力\": 5, \"魅力\": 5 },",
  "  \"gauges\": [",
  "    { \"id\": \"cultivation-progress\", \"name\": \"修炼进度\", \"value\": 24, \"max\": 100, \"tone\": \"accent\" },",
  "    { \"id\": \"corruption\", \"name\": \"腐化值\", \"value\": 37, \"max\": 100, \"tone\": \"danger\" },",
  "    { \"id\": \"mana-deficit\", \"name\": \"法力亏空\", \"value\": 10, \"max\": 100, \"tone\": \"warning\" }",
  "  ],",
  "  \"status\": [",
  "    { \"id\": \"injury:右臂轻伤\", \"name\": \"右臂轻伤\", \"description\": \"挥剑时略有迟滞。\", \"polarity\": \"negative\" }",
  "  ],",
  "  \"traits\": [",
  "    { \"id\": \"trait:明镜心\", \"name\": \"明镜心\", \"description\": \"一种天生澄澈、难染外邪的心性天赋。\", \"effects\": [\"能够堪破虚妄\", \"心神不受外力影响\"] }",
  "  ],",
  "  \"goals\": {",
  "    \"current\": \"证明自己没有私通外敌，并从山门冲突中脱身。\",",
  "    \"shortTerm\": \"查清禁地异动与玄衣少女出现之间的关联。\",",
  "    \"longTerm\": \"在青玄门站稳脚跟，找出山门内暗藏的叛徒线索。\"",
  "  },",
  "  \"background\": \"萧玄入门时间不长，但剑法基础稳。本轮前，他被卷入山门冲突，目标是证明自己没有私通外敌。\",",
  "  \"containers\": [",
  "    { \"ref\": \"container:萧玄行囊\" }",
  "  ],",
  "  \"extensions\": {",
  "    \"腐化值\": { \"render\": \"progress\", \"value\": 37, \"max\": 100, \"tone\": \"danger\" }",
  "  }",
  "}",
  "```",
  "",
  "`identity`/`appearance`/`attributes`/`gauges`/`status`/`traits`/`goals`/`background` 为 character 权威结构。旧字段 `fields`、`sections`、`status[].level` 已废弃，不再新增。`identity` 键为 `age`/`gender`/`role`/`affiliation`/`realm`（旧键 `race`/`class`/`title` 已废弃）。`attributes` 固定6维，键名由世界架构师按世界观定义，基线为 5。`gauges` 是自由命名数组，每项 `{ id, name, value, max?, min?, unit?, tone? }`（旧固定 5 key `hp`/`mp`/`sp`/`hunger`/`stamina` 已废弃）。`appearance` 是单段叙事字符串（旧 label/value 键值对已废弃）。`goals` 是 `{ current?, shortTerm?, longTerm? }`，每项字符串。`background` 是单段字符串。`status[].polarity` 取值 `positive`/`negative`/`neutral`。`traits` 是永久性稳定特质数组，每项 `{ id, name?, description?, effects? }`，`id` 必填（`trait:<localId>` 格式），表示特殊体质、天赋、系统、血脉、命格等稳定能力来源；区别于 `status[]`（当前临时状态），`traits[]` 是永久性的，不随单回合状态变化消失。`relationships` 不内嵌于 character entity；走 `save/relationships/character-<localId>.json` 分片。",
  "",
  "character 可选 `containers?: Array<{ ref, count? }>`：当前持有的容器指针数组，ref 指向 `save/entities/container/<localId>.json`，`count` 缺省视为 1。角色不持有容器时省略该字段或写空数组。物品数量不写在 character 层，落在 container.contents[*].count。",
  "",
  "## container / item entity",
  "",
  "容器与物品是独立实体，与 character 平级，通过 ref 从 character.containers 与 container.contents 引用。前端做专门 UI（背包网格 / 物品详情弹窗）；不需要用 extensions 承载它们。",
  "",
  "```json",
  "{",
  "  \"id\": \"container:萧玄行囊\",",
  "  \"name\": \"外门弟子行囊\",",
  "  \"brief\": \"入门时统一发放的青灰色布囊，绳口有磨损。\",",
  "  \"type\": \"container\",",
  "  \"contents\": [",
  "    { \"ref\": \"item:清心丹\", \"count\": 3 },",
  "    { \"ref\": \"container:内胆锦囊\" }",
  "  ],",
  "  \"status\": [",
  "    { \"id\": \"container:潮湿\", \"name\": \"轻微受潮\", \"polarity\": \"negative\" }",
  "  ]",
  "}",
  "```",
  "",
  "container 字段：`id`（必填，`container:<localId>`）、`name`、`brief`、`type`（固定字符串 `\"container\"`）、`contents: Array<{ ref, count? }>`（ref 指向 item 或嵌套 container 实体；count 缺省 1，负数或 0 视为无效）、`status?`（可选，与 character status 数组形态一致）、`extensions?`。不设容量字段；contents 只存 ref+count，不冗余子物品 name/brief（前端按 ref 回读实体权威）。嵌套 container 允许（书箱内套锦囊）但不做无限展开，UI 逐层进入。",
  "",
  "```json",
  "{",
  "  \"id\": \"item:清心丹\",",
  "  \"name\": \"清心丹\",",
  "  \"brief\": \"外门发放的低阶疗伤丹，回气去乱。\",",
  "  \"type\": \"consumable\",",
  "  \"tags\": [\"丹药\", \"疗伤\"],",
  "  \"extensions\": {",
  "    \"药力\": { \"render\": \"progress\", \"value\": 30, \"max\": 100, \"tone\": \"success\" }",
  "  }",
  "}",
  "```",
  "",
  "item 字段：`id`（必填，`item:<localId>`）、`name`、`brief`、`type`（取值 `equipment`/`material`/`consumable`/`special`/`other` 五类之一；未知或不便归类写 `other`）、`tags?: string[]`（自由标签，用于列表分组或详情 chip）、`extensions?`（承载新增/临时可见字段，如药力进度、耐久、附魔层数；沿用 extensions render preset）。物品自身不存 `quantity`：数量由持有者 container.contents[*].count 表达。物品也不存 `status`：品相变化直接改 name/brief 或用 extensions（如 `{ 破损度: { render: 'progress' } }`），不再区分 status/extensions 两条路径。",
  "",
  "type 五类的语义指引：`equipment` 装备武器护甲等可佩戴/持握；`material` 材料矿石药材等制作/交易素材；`consumable` 消耗品丹药符箓一次性道具；`special` 剧情关键物任务物证；`other` 上述都不合适的杂项。归类不清时写 `other`，不发明第六类。",
  "",
  "## 受控词表",
  "",
  "### visibility",
  "",
  "```text",
"player-known      # 玩家面向的叙述/前端安全；省略时默认",
"hidden            # 玩家当前看不见，但背景 Agent 可用",
"future-spoiler    # 未来的原著信息；不要泄露进玩家面向的叙述",
"```",
  "",
  "### lifecycle",
  "",
  "```text",
  "candidate    # 已抽取但尚未确认重要",
  "active       # 当前可在游玩中使用",
  "background   # 作为背景存在但非当前焦点",
  "retired      # 已退出当前游玩，除非刻意重新引入",
  "```",
  "",
  "## Runtime 变量",
  "",
  "`save/playthrough/runtime.json` 存放高频访问、玩家面向或前端管理的摘要。`worldTime` 是当前世界/剧情时间的固定字符串字段；它不是平台墙钟时间，也不用于日历运算。`plotOrder` 是数字字段，单调递增，表示玩家当前走到哪个 source order；场记每回合用维护工具返回的 `timeline.sourceAnchors` 映射维护，前端用于判断是否触发 frontier 推进（`plotOrder > 最后 source 锚点 order` 时触发）。未知或尚未建立时写空字符串/0。",
  "",
  "```json",
  "{",
  "  \"turn\": 6,",
  "  \"worldTime\": \"赤明纪十二年三月初七，黄昏\",",
  "  \"plotOrder\": 3,",
  "  \"weather\": \"阴云聚拢\",",
  "  \"location\": { \"ref\": \"location:青玄门山门\", \"name\": \"青玄门山门\" },",
  "  \"activeSceneRefs\": [{ \"ref\": \"scene:山门冲突\", \"name\": \"山门冲突\" }],",
  "  \"protagonistRef\": { \"ref\": \"character:萧玄\", \"name\": \"萧玄\" },",
  "  \"extensions\": {",
  "    \"月相\": { \"render\": \"text\", \"value\": \"上弦\" },",
  "    \"护山阵倒计时\": { \"render\": \"number\", \"value\": 3, \"unit\": \"刻\" }",
  "  },",
  "  \"updatedAtTurn\": 6,",
  "  \"updatedBy\": \"stage-manager\"",
  "}",
  "```",
  "",
  "`activeSceneRefs` 是当前活跃场景指针数组（每项 `{ ref, name }`）；场景内容权威在 `save/scenes/<id>.json`，runtime 只存指针。`protagonistRef` 是当前主角指针（`{ ref, name }`），主角实体权威仍在 `save/entities/character/<localId>.json`。`location` 是当前地点指针 `{ ref, name } | null`。`weather` 是当前天气字符串。`plotOrder` 是数字，单调递增，表示玩家当前走到哪个 source order；场记每回合用维护工具返回的 `timeline.sourceAnchors` 映射维护，前端用于判断是否触发 frontier 推进。旧字段 `activeSceneIds`/`activeScene`/`player`/`inventory`/`status` 已废弃。`extensions` 仍用于月相、倒计时、诅咒周期、节气规则等新增/临时时间机制；当前世界/剧情时间本身写 `worldTime`，剧情进度坐标写 `plotOrder`。纯前端 view state 默认不写入 workspace。",
  "",
  "## frontier.json",
  "",
  "`save/playthrough/frontier.json` 记录源文本抽取进度与时间标记锚点，供资料员映射 `runtime.worldTime` → `timeline` 锚点 → `sourceWindow` 位置找素材。",
  "",
  "```json",
  "{",
  "  \"sourceWindow\": { \"start\": 1, \"end\": 8, \"chapters\": [{ \"index\": 1, \"title\": \"第 1 章\", \"ref\": \"source:chapter-0001\" }] },",
  "  \"extractedThrough\": \"source:chapter-0008\",",
  "  \"timeline\": [",
  "    { \"kind\": \"source\", \"order\": 1, \"chapter\": 1, \"time\": \"元年\", \"label\": \"开局\" },",
  "    { \"kind\": \"source\", \"order\": 2, \"chapter\": 4, \"time\": \"二年春\", \"label\": \"离山历练\" },",
  "    { \"kind\": \"player\", \"order\": 2, \"turn\": 8, \"time\": \"二年春\", \"label\": \"提前离山\", \"alignment\": \"diverged\", \"sourceRef\": 2 }",
  "  ],",
  "  \"notes\": \"Track how far the imported source has been normalized, chunked, and extracted.\",",
  "  \"updatedAt\": \"2026-07-07T00:00:00.000Z\",",
  "  \"updatedBy\": \"world-architect\"",
  "}",
  "```",
  "",
  "字段：",
  "",
  "- `sourceWindow`：已读章节窗口。`start`/`end` 为章节号（闭区间），`chapters` 为窗口章节元信息数组（每项 `{ index, title, ref }`；旧存档可能仍是等价的 legacy 引用）。推进 frontier 时移动。",
  "- `extractedThrough`：已抽取到的最远源章节引用；缺省取窗口末章引用。",
  "- `timeline`：时间标记锚点数组，用 `kind` 字段区分两类锚点：",
  "  - source 锚点：`{ kind: \"source\", order, chapter, time, label }`。world-architect 推进时建立，标记原著剧情节点。",
  "    - `order`：单调递增整数，是我们建立的线性坐标轴，表示剧情事件先后顺序，与原著精确时间标记无关。即使原著写“回到过去”，`order` 也严格递增——`time` 字段可能变化，但 `order` 只向前。source 锚点 order 由 world-architect 推进时递增赋值。",
  "    - `chapter`：原著章节号，与 `sourceWindow` 同一坐标。",
  "    - `time`：游戏时间字符串，自由粒度（默认年+季/月）。原文无明确时间词时从剧情推断估计；开局第一个锚点 `time` 固定 `\"元年\"`。",
  "    - `label`：一句话客观标签，不是剧情摘要。",
  "  - player 锚点：`{ kind: \"player\", order, turn, time, label, alignment, sourceRef }`。stage-manager 维护时追加，标记玩家视角显著事件。",
  "    - `order`：等于玩家当前所在 source 区间的起始 source 锚点 order。同一 source 区间内的多个 player 锚点共享相同 order，前端按 turn 排序展开。",
  "    - `turn`：游戏回合号，分支内排序与后续精确找 turn 正文用。",
  "    - `time`：游戏时间字符串（显示用）。",
  "    - `label`：一句话客观描述。",
  "    - `alignment`：标记与原著关系，取值 `diverged` / `rejoined` / `aligned`。",
  "    - `sourceRef`：关联的 source order（number 或 null）。语义见下表。",
  "",
  "  `alignment` 三值语义：",
  "",
  "  | 值 | 含义 | sourceRef | 建立时机 |",
  "  |---|---|---|---|",
  "  | `diverged` | 玩家偏离原著 | 分叉自的 source order，或 null（原创区间） | 玩家从 source 事件分叉，或在原创区间发生显著事件 |",
  "  | `rejoined` | 从分支并回主干 | 并回的 source order | 玩家重新遇到 source 事件且结果相近 |",
  "  | `aligned` | 经历 source 事件且结果相近 | 该 source order | 可选——完美跟随时不需要建，source 锚点本身代表那段故事 |",
  "",
  "  stage-manager 只在有意义的时刻建 player 锚点：偏离、并回、或经历 source 事件但结果不同（此时用 `diverged` + sourceRef，表示遇到了同一事件但走了不同方向）。",
  "- `notes`：抽取进度备注。",
  "- `updatedAt` / `updatedBy`：维护锚点。",
  "",
  "`timeline` 与 `sourceWindow` 独立：`sourceWindow` 记录已读窗口，`timeline` 记录锚点。推进时 `sourceWindow` 移动、`timeline` 追加新 source 锚点。两者通过 `chapter` 字段关联。`runtime.plotOrder` 是前端做触发判断的剧情进度坐标，等于玩家当前走到的 source 锚点 order。",
  "",
  "## 场景分片格式",
  "",
  "```json",
  "{",
  "  \"id\": \"scene:山门冲突\",",
  "  \"name\": \"山门冲突\",",
  "  \"location\": { \"ref\": \"location:青玄门山门\", \"name\": \"青玄门山门\" },",
  "  \"present\": [",
  "    { \"ref\": \"character:萧玄\" }",
  "  ],",
  "  \"status\": \"active\",",
  "  \"updatedTurn\": 0,",
  "  \"updatedBy\": \"world-architect\"",
  "}",
  "```",
  "",
  "## Schema Patch Markdown 模板",
  "",
  "```md",
  "# Schema Patch: 增加宗门贡献点",
  "",
  "Status: pending",
  "Decision: player-required",
  "Proposed by: stage-manager",
  "Reason: 新章节出现“宗门贡献点”，看起来会持续影响角色行动和资源兑换。",
  "",
  "## 拟议变更",
  "",
  "- 为 `character` entity 增加可选字段：`progression.contributionPoints`。",
  "- 默认不存在；不存在表示未知或不追踪。",
  "```",
])
